chatwoot/chatwoot

app/javascript/packs/application.js, app/javascript/src/components/ChatList.vue, app/javascript/src/components/ui/Wizard.vue, app/javascript/src/components/widgets/conversation/ConversationBox.vue, app/javascript/src/helper/pusher.js
**why?**
- The app instance initiation is a race condition
=> Resurrection of the broken pusher

app/javascript/src/assets/scss/_foundation-settings.scss, app/javascript/src/assets/scss/_variables.scss
=> Change #FFFFFF to #FFF

app/javascript/src/assets/scss/views/_signup.scss, app/javascript/src/assets/scss/widgets/_login.scss
=> Remove redundant variables, use shorthand

bin/webpack-dev-server
Fixing Rubocop issues in `bin/webpack-dev-server` #74 and #75
=> Fix Rubocop issues in webpack-dev-server

app/javascript/src/assets/scss/views/settings/inbox.scss
Issue: https://github.com/chatwoot/chatwoot/issues/63
=> Fixed ZeroUnit issue

app/models/conversation.rb
=> Refactor create_activity method on Conversation model

app/models/plan.rb
=> Fix code climate issues on Plan model

app/models/attachment.rb
Fixes https://github.com/chatwoot/chatwoot/issues/53
=> Refactor Attachment#push_event_data

app/controllers/api/v1/inbox_members_controller.rb
=> Reduce line code to please Rubocop

app/javascript/src/assets/scss/views/_signup.scss, app/javascript/src/routes/auth/Signup.vue
Fixing issue #80 but also other "SelectorFormat" warnings according to [this link](https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/src/assets/scss/views/_signup.scss#issue_5d87481187cf1900010005ca).
Only for views/_signup.scss
Other files like _login.scss seems to have the same warnings.
=> Fix multiple SelectorFormat issues in views/_signup.scss

app/javascript/src/routes/index.js
fixes #73 
I don't see javascript tests in this project, however, I did run testing over the old and new functions to validate behavior. See attached.
[chatwoot-validate-auth-tests.zip](https://github.com/chatwoot/chatwoot/files/3679744/chatwoot-validate-auth-tests.zip)
=> Reduce complexity of validateAuthenticateRoutePermission function

app/models/conversation.rb
=> Refactor for notify_status_change

app/builders/messages/message_builder.rb
=> Refactor for attachment_params method

.gitignore
For ignoring Jetbrains IDE (webstorm) config files
=> Add .idea folder to the gitignore 

app/javascript/src/assets/scss/widgets/_billing.scss
Fix #65 issue codeclimate in app/javascript/src/assets/scss/widgets/_billing.scss
=> Fix #65 issue codeclimate in _billing.scss

app/javascript/src/helper/APIHelper.js
=> Refactor parseErrorCode and try to decrease method complexity

docs/development/environment-setup/mac-os.md
=> Add mac os installation guide

config/locales/en.yml
=> [bug-fix] Fix missing username in assignment message

.editorconfig
.editorconfig will allow maintaining consistent coding style across
various text editors and IDEs
[EditorConfig](https://editorconfig.org)
=> Introduce .editorconfig

app/builders/account_builder.rb, app/controllers/application_controller.rb, app/controllers/confirmations_controller.rb, lib/constants/report.rb, lib/custom_exceptions/account.rb, lib/custom_exceptions/base.rb, lib/custom_exceptions/report.rb, lib/events/types.rb, lib/integrations/facebook/delivery_status.rb, lib/integrations/facebook/message_creator.rb, lib/integrations/facebook/message_parser.rb, lib/integrations/widget/incoming_message_builder.rb, lib/integrations/widget/outgoing_message_builder.rb, lib/local_resource.rb, lib/reports/update_account_identity.rb, lib/reports/update_agent_identity.rb, lib/reports/update_identity.rb, lib/webhooks/chargebee.rb
+ This PR adds the frozen string literal true magic comments for some files.
+ It also corrects indentation in some files
If this PR feels too cosmetic, please do close this.
=> Sprinkle frozen string literal & Indentation Fix

Gemfile, Gemfile.lock, app/javascript/dashboard/api/auth.js, app/javascript/dashboard/helper/pusher.js, app/listeners/pusher_listener.rb, app/models/contact.rb, app/models/user.rb, config/application.rb, db/migrate/20191016211109_rename_channel_attribute_name_in_models.rb, db/schema.rb, spec/factories/contacts.rb, spec/factories/users.rb, spec/models/contact_spec.rb
We were using the attribute name 'channel' to store pubsub tokens, which was confusing.
Also
- switched to faker from ffaker
- spec for `contact.rb`
=> Refactoring the code for pub sub

lib/constants/redis_keys.rb, lib/constants/report.rb
Freeze ruby constants to make it actual constant.
=> Freeze Ruby Constant

Gemfile, Gemfile.lock, app/models/inbox.rb, config/initializers/carrierwave.rb
- carrierwave local config 
- upgrade facebook messenger gem
=> upgrade facebook messenger gem

Gemfile, app/assets/javascripts/api/base.coffee, app/assets/javascripts/api/v1/agents.coffee, app/assets/javascripts/api/v1/canned_responses.coffee, app/assets/javascripts/api/v1/conversations.coffee, app/assets/javascripts/api/v1/reports.coffee, app/assets/javascripts/api/v1/subscriptions.coffee, app/assets/javascripts/api/v1/webhooks.coffee, app/assets/javascripts/api/v1/widget/messages.coffee, app/assets/javascripts/home.coffee, config/application.rb
deleted coffee files & coffee-rails gem. disable js generation on application.rb
=> Disable coffeescript generation.

app/assets/stylesheets/api/base.scss, app/assets/stylesheets/api/v1/agents.scss, app/assets/stylesheets/api/v1/canned_responses.scss, app/assets/stylesheets/api/v1/conversations.scss, app/assets/stylesheets/api/v1/reports.scss, app/assets/stylesheets/api/v1/subscriptions.scss, app/assets/stylesheets/api/v1/webhooks.scss, app/assets/stylesheets/api/v1/widget/messages.scss, app/assets/stylesheets/home.scss, config/application.rb
This is related to issue #176 
Sorry for similar 2 PRs. I just think that disabling stylesheet generation makes less files and keep organized.
=> removed app/stylesheets & set stylesheet generator to false

app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue, app/javascript/dashboard/i18n/locale/en/agentMgmt.json, app/javascript/widget/App.vue
=> [Bug] Update copy in search agent select dropdown

Gemfile, Gemfile.lock, app/controllers/api/v1/widget/messages_controller.rb, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, db/migrate/20191116073924_add_additional_attributes_to_conversation.rb, db/schema.rb
=> [Feature] Detect browser on conversation initiation

app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/components/widgets/conversation/EmptyState.vue, app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
=> [Enhancement] Create EmptyState component

app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
=> [Bug] Fix selected label alignment in MultiSelect

app/javascript/widget/assets/scss/sdk.js
=> [Bug] Fix widget mobile layout design

app/controllers/widgets_controller.rb, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/mixins/time.js
=> [Enhancement] Format time to time ago, fix sorting in conversation list

package.json
=> Remove docs script 

.circleci/config.yml, Gemfile, Gemfile.lock
I think it may be a good idea to check vulnerable gems :-)
=> Add bundle audit to CI

README.md
=> [Docs] Update Readme

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/shared/helpers/MessageFormatter.js, app/javascript/shared/helpers/specs/MessageFormatter.spec.js, app/javascript/shared/mixins/messageFormatterMixin.js, app/javascript/widget/components/AgentMessageBubble.vue, app/javascript/widget/components/UserMessageBubble.vue
=> [Enhancement] Format messages in widget

docs/development/project-setup/environment-variables.md, docs/development/project-setup/errors.md
=> [Docs] Fix links in documentation

docs/contributing.md, docs/development/project-setup/quick-setup.md
=> [Docs] Update links in contributing.md

docs/README.md, docs/development/environment-setup/mac-os.md, docs/development/environment-setup/ubuntu.md, docs/development/environment-setup/windows.md, docs/development/project-setup/environment-variables.md
=> [Docs] Add documentation for SMTP settings

.dependabot/config.yml
Add a [validated](https://dependabot.com/docs/config-file/validator/) Dependabot config so we can keep our Ruby and JavaScript dependencies fresh.
=> Add Dependabot

.circleci/config.yml, Gemfile, Gemfile.lock, app/models/message.rb, config/environments/development.rb, spec/rails_helper.rb
- upgrade gems
- fix the warning in console
- fix the depreciation message for where not
=> [Chore] Add bullet gem  #249 

README.md
=> [Chore] Add docker build status to repo #287

app/models/user.rb, db/migrate/20191126185833_update_user_invite_foreign_key.rb, db/schema.rb
=> [BugFix] Fix Users not deletable because of foreign key reference (#297)

.github/PULL_REQUEST_TEMPLATE.md
Add a pull request template to the repo
=> [Chore] Add a pull request template to the repo

app/controllers/api/v1/inbox_members_controller.rb
=> [Bugfix] Fixes agent cannot be removed from inbox #18

.github/ISSUE_TEMPLATE/enhancement_request.md
=> [Chore] Enhancement request template

app/javascript/widget/components/ChatMessage.vue, app/listeners/action_cable_listener.rb, app/views/api/v1/widget/messages/index.json.jbuilder, config/database.yml
=> [Bug] Fix private note shown to the user in live chat widget

app/javascript/widget/assets/scss/woot.scss, app/javascript/widget/components/AgentMessage.vue, app/javascript/widget/components/UserMessage.vue
Fixes # #197 
The spacing between bubbles were not proper. Also the max width was not set on bubbles.
=> Adjust space between message bubbles in widget

Procfile.dev, docker/Procfile.docker.dev
Fix rails port getting toggled from 3000 to 5000 when using foreman
=> Fix rails port getting toggled from 3000 to 5000

README.md, docs/development/project-setup/environment-variables.md, docs/development/project-setup/quick-setup.md
=> Updated docs for docker configuration

app/javascript/widget/components/ChatMessage.vue, app/javascript/widget/components/UserMessage.vue, app/javascript/widget/components/UserMessageBubble.vue, app/javascript/widget/helpers/uuid.js, app/javascript/widget/store/modules/conversation.js, app/javascript/widget/store/modules/specs/conversation.spec.js, jest.config.js
Fixes #250 
https://www.loom.com/share/4b54645ecac046f89cd6ceac2af6ea7d
=> Add an intermediate pending state for widget messages

.rubocop.yml, app/controllers/api/v1/widget/inboxes_controller.rb, app/javascript/dashboard/assets/scss/widgets/_states.scss, app/javascript/dashboard/components/Code.vue, app/javascript/dashboard/components/index.js, app/javascript/dashboard/helper/scriptGenerator.js, app/javascript/dashboard/i18n/en.js, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Website.vue, app/javascript/dashboard/store/modules/sidebar.js, app/policies/inbox_policy.rb, app/views/api/v1/widget/inboxes/create.json.jbuilder, package.json, spec/controllers/api/v1/widget/inboxes_controller_spec.rb, yarn.lock
=> [Enhancement] Add CopyToClipboard action in code component

app/controllers/api/v1/conversations_controller.rb, app/finders/conversation_finder.rb, app/javascript/dashboard/api/inbox/conversation.js, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/widgets/ChatTypeTabs.vue, app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue, app/javascript/dashboard/i18n/locale/en/chatlist.json, app/javascript/dashboard/store/modules/conversations/getters.js, app/javascript/dashboard/store/modules/conversations/index.js, app/views/api/v1/conversations/index.json.jbuilder, spec/factories/conversations.rb, spec/factories/inbox_members.rb, spec/finders/conversation_finder_spec.rb
This PR handles #248 and #247 . We already have filtering support for assignee type. Added specs for the same.
Fixes #247 
Partially completes #248
=> [#247] Filters conversation by status and paginate conversations

.circleci/config.yml
cache gem files in circle builds 
Fixes #338 
=> Chore: Cache gemfiles in circle builds [#338]

.gitignore, Gemfile.lock
=> Fix security advisory warning CVE-2019-16770

app/javascript/dashboard/assets/scss/_foundation-settings.scss, app/javascript/dashboard/assets/scss/views/settings/inbox.scss, app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/SidemenuIcon.vue, app/javascript/dashboard/components/index.js, app/javascript/dashboard/components/specs/SidemenuIcon.spec.js, app/javascript/dashboard/components/specs/__snapshots__/SidemenuIcon.spec.js.snap, app/javascript/dashboard/routes/dashboard/Dashboard.vue, app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue, app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue
https://recordit.co/HubR9Q96Zw
=> [Enhancement] Hide sidebar on tablets

app/javascript/dashboard/assets/scss/_layout.scss, app/javascript/dashboard/assets/scss/widgets/_buttons.scss, app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue, app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue, app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
=> [Bug] Fix icon alignment in buttons

app/javascript/shared/components/DateSeparator.vue, app/javascript/shared/components/specs/DateSeparator.spec.js, app/javascript/shared/components/specs/__snapshots__/DateSeparator.spec.js.snap, app/javascript/shared/helpers/DateHelper.js, app/javascript/shared/helpers/specs/DateHelper.sepc.js, app/javascript/widget/components/ConversationWrap.vue, app/javascript/widget/store/modules/conversation.js, app/javascript/widget/store/modules/specs/conversation/getters.spec.js, app/javascript/widget/views/Home.vue, package.json, yarn.lock
=> [Enhancement] Group widget messages by date

.gitignore, app/finders/conversation_finder.rb, app/finders/message_finder.rb, app/views/api/v1/conversations/index.json.jbuilder, spec/finders/message_finder_spec.rb
=> [Performance] Optimize queries in conversation/message finders

app/javascript/dashboard/components/layout/Sidebar.vue
Made it to use `Array.includes()` instead of `indexOf` to check for existence.
N/A
N/A
=> refactor: minor code refactoring

app/javascript/dashboard/App.vue, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/Modal.vue, app/javascript/dashboard/components/SidemenuIcon.vue, app/javascript/dashboard/components/SnackbarContainer.vue, app/javascript/dashboard/components/buttons/FormSubmitButton.vue, app/javascript/dashboard/components/buttons/ResolveButton.vue, app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/widgets/EmptyState.vue, app/javascript/dashboard/components/widgets/SearchBox.vue, app/javascript/dashboard/components/widgets/Thumbnail.vue, app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Adopt `Vue.js` best practices.
- Made components self-closing.
- Use `Array.includes()` instead of `indexOf()`
- Use directive shorthands to be consistent with the rest of the codebase.
N/A
=> refactor: minor code refactoring in accordance with Vue.js best practices

app/javascript/widget/store/modules/conversation.js, app/javascript/widget/store/modules/specs/conversation/actions.spec.js
=> [Bug] Fix timestamp in temporary message

README.md, docs/development/environment-setup/docker.md
=> Refactoring the docker documentation

app/views/assignment_mailer/conversation_assigned.html.erb, config/routes.rb
=> [Bug] Fix conversation assignment mailer url

.rubocop.yml, app/actions/contact_merge_action.rb, app/controllers/api/v1/actions/contact_merges_controller.rb, config/routes.rb, spec/actions/contact_merge_action_spec.rb, spec/controllers/api/v1/actions/contact_merges_controller_spec.rb, spec/controllers/api/v1/profiles_controller_spec.rb, spec/factories/contact_inbox.rb, spec/factories/conversations.rb, spec/finders/conversation_finder_spec.rb, spec/finders/message_finder_spec.rb, spec/models/conversation_spec.rb, spec/presenters/conversations/event_data_presenter_spec.rb
New service to merge two contacts. Also, an API endpoint to execute this action
Addresses #258
=> Feature: Contact Merge Action [#258]

app/controllers/api/v1/conversations/labels_controller.rb, app/views/api/v1/conversations/labels/create.json.jbuilder, spec/controllers/api/v1/conversations/labels_controller_spec.rb, spec/controllers/api/v1/labels_controller_spec.rb
Verifying the code that existed to add labels work. Also, add specs to ensure the same
Addresses #245 
=> Chore: Add labels to Conversations [#245]

app/builders/account_builder.rb, app/controllers/api/v1/accounts_controller.rb, app/controllers/concerns/auth_helper.rb, app/controllers/passwords_controller.rb, spec/controllers/api/v1/accounts_controller_spec.rb
=> Code-climate duplicate code fixes

README.md
Fixed broken link to docker setup guide in Readme
=> Update Docker Setup guide link in the Readme

app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue
=> Bug: Fix short_code param in update canned response API

app/javascript/dashboard/components/widgets/conversation/EmptyState.vue, app/javascript/dashboard/i18n/locale/en/conversation.json
Fixes copy shown when no inbox is added.
=> Bug: Fix copy shown when no inbox is added.

app/controllers/api/v1/accounts_controller.rb
=> Bug: Fix signup 500 error

spec/factories/users.rb, spec/policies/contact_policy_spec.rb, spec/policies/inbox_policy_spec.rb, spec/policies/user_policy_spec.rb, spec/rails_helper.rb
I have added specs for the Policies
=> Add specs for Policies

app/services/facebook/send_reply_service.rb, spec/factories/facebook_page.rb, spec/factories/messages.rb, spec/services/facebook/send_reply_service_spec.rb
=> Specs: Add specs for Facebook::SendReplyService

LICENSE, README.md
=> Docs: Update year in license file

.env.example, config/cable.yml, config/routes.rb, docker-compose.production.yaml, docker-compose.yaml, docs/development/environment-setup/docker.md
- action cable works from sidekiq in development environments
- documentation updates for docker
=> Chore: Sidekiq ActionCable fix for Development

app/jobs/action_cable_broadcast_job.rb, app/jobs/pusher_call_job.rb, app/listeners/action_cable_listener.rb
I have moved  action cable broadcasts to background job
Fixes #154
=> Move Pusher Calls to sidekiq #154

app/controllers/api/v1/widget/messages_controller.rb, spec/controllers/api/v1/widget/messages_controller_spec.rb
=> Bug Fix: Ignore case from input email

app/listeners/reporting_listener.rb, app/models/message.rb, spec/listeners/reporting_listener_spec.rb
Include only incoming/outgoing messages in reporting
Fixes #428 
Unit tested
=> Include only incoming/outgoing messages in reporting

app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss, app/javascript/packs/sdk.js, app/javascript/widget/App.vue, app/javascript/widget/assets/scss/_mixins.scss, app/javascript/widget/assets/scss/_variables.scss, app/javascript/widget/assets/scss/sdk.js, app/javascript/widget/components/AgentMessage.vue, app/javascript/widget/components/Branding.vue, app/javascript/widget/components/ChatFooter.vue, app/javascript/widget/components/ChatHeader.vue, app/javascript/widget/components/ChatHeaderExpanded.vue, app/javascript/widget/components/UserMessage.vue, app/javascript/widget/components/UserMessageBubble.vue, app/javascript/widget/components/template/EmailInput.vue, app/javascript/widget/helpers/utils.js, app/javascript/widget/views/Home.vue, app/views/widget_tests/index.html.erb, package.json
=> Enhancements to widget

app/javascript/widget/views/Home.vue
=> Fix the last message style issue

docs/contributing.md
=> Docs: Update contributing.md

docs/development/project-setup/configuring-cloud-storage.md, docs/development/project-setup/environment-variables.md
=> Chore: Documentation for configuring cloud storage

app/controllers/api/v1/labels_controller.rb, app/finders/conversation_finder.rb, app/views/api/v1/labels/most_used.json.jbuilder, config/routes.rb, spec/controllers/api/v1/labels_controller_spec.rb, spec/finders/conversation_finder_spec.rb
=> Feature: API to get most used labels

.codeclimate.yml
=> Chore: Remove brakeman from codeclimate

app/controllers/devise_overrides/confirmations_controller.rb, app/controllers/devise_overrides/passwords_controller.rb, app/controllers/devise_overrides/sessions_controller.rb, app/controllers/devise_overrides/token_validations_controller.rb, config/routes.rb
=> Bugfix: Fix password reset

app/javascript/dashboard/i18n/locale/en/signup.json, app/javascript/dashboard/routes/auth/Signup.vue
=> Chore: Update copy in signup page

app/javascript/dashboard/components/widgets/Thumbnail.vue, app/javascript/widget/App.vue, app/javascript/widget/api/agent.js, app/javascript/widget/api/endPoints.js, app/javascript/widget/assets/scss/_mixins.scss, app/javascript/widget/components/AvailableAgents.vue, app/javascript/widget/components/ChatHeader.vue, app/javascript/widget/components/ChatHeaderExpanded.vue, app/javascript/widget/components/GroupedAvatars.vue, app/javascript/widget/helpers/specs/utils.spec.js, app/javascript/widget/helpers/utils.js, app/javascript/widget/store/index.js, app/javascript/widget/store/modules/agent.js, app/javascript/widget/store/modules/specs/agent/actions.spec.js, app/javascript/widget/store/modules/specs/agent/data.js, app/javascript/widget/store/modules/specs/agent/getters.spec.js, app/javascript/widget/store/modules/specs/agent/mutations.spec.js, app/javascript/widget/views/Home.vue, app/views/api/v1/widget/inbox_members/index.json.jbuilder, app/views/widgets/show.html.erb
=> As an end-user, I should be able to see the list of agents in the widget.

app/javascript/widget/helpers/specs/utils.spec.js, app/javascript/widget/helpers/utils.js, config/initializers/twitter.rb
=> Bugfix: Fix copy in agent availability status

.env.example, app/services/twitter/direct_message_parser_service.rb, app/services/twitter/webhooks_base_service.rb, lib/webhooks/twitter.rb
=> BugFix: Filter duplicate DMs in Twitter Integration

spec/controllers/api/v1/widget/messages_controller_spec.rb
Hey,
this is my first pull request here :) I looked at your issues and saw that you are missing some tests for your controllers. This PR fixes the api/v1/widget/messages_controller.rb
I will add more tests for controllers over time.
Improves #37 
=> Chore: Increase test coverage for widget messages

docs/contributing.md
Update to documentation regarding contribution guidelines.
Fixes #471 
=> Chore: Update contribution guidelines (#471)

app/controllers/widgets_controller.rb, spec/controllers/widgets_controller_spec.rb
This PR fixes the widgets_controller.rb. It also changes the index function to be in compliance with other "just render" functions inside other controllers in this project.
Improves #37 
=> Chore: Increase test coverage for widgets controller

spec/controllers/api/v1/accounts_controller_spec.rb
This PR fixes the accounts_controller.rb
Improves #37 
=> Chore: Increase test coverage for accounts controller

spec/controllers/api/v1/contacts/conversations_controller_spec.rb
This PR fixes the contacts/conversation_controller.rb
Improves #37 
=> Chore: Increase test coverage for conversations controller

spec/controllers/api/v1/canned_responses_controller_spec.rb, spec/factories/canned_responses.rb
This PR adds tests for the canned_responses_controller.rb
Improves #37 
=> Chore: Added tests for canned_responses

app/controllers/api/v1/inbox_members_controller.rb
This is a small followup for #478 
It removes the unnessecary check if the inbox exists.
=> Chore: Remove unnessecary check if object exists

spec/controllers/api/v1/agents_controller_spec.rb
This adds tests for agents_controller.rb
Issue #37
=> Chore: Added tests for agents_controller

spec/controllers/api/v1/conversations/assignments_controller_spec.rb
This adds tests for assignments_controller.rb
Issue #37
=> Chore: Added tests for assignments_controller

.rubocop.yml, app/builders/messages/message_builder.rb, app/builders/messages/outgoing/normal_builder.rb, app/controllers/api/v1/webhooks_controller.rb, app/javascript/dashboard/components/widgets/Thumbnail.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/store/modules/specs/contactConversations/fixtures.js, app/models/channel/twitter_profile.rb, app/models/contact.rb, app/models/message.rb, app/services/facebook/send_reply_service.rb, app/services/twitter/send_reply_service.rb, app/services/twitter/tweet_parser_service.rb, app/services/twitter/webhooks_base_service.rb, app/views/api/v1/contacts/index.json.jbuilder, app/views/api/v1/contacts/show.json.jbuilder, app/views/api/v1/contacts/update.json.jbuilder, app/views/api/v1/conversations/get_messages.json.jbuilder, app/views/api/v1/conversations/show.json.jbuilder, config/initializers/twitter.rb, db/migrate/20200206180408_add_contact_to_message.rb, db/migrate/20200206180927_rename_fb_id_to_source_id.rb, db/migrate/20200206182948_add_additional_attributes_to_contact.rb, db/schema.rb, lib/webhooks/twitter.rb, spec/factories/twitter/tweet_create_event.rb, spec/lib/webhooks/twitter_spec.rb, spec/services/facebook/send_reply_service_spec.rb, spec/services/twitter/send_reply_service_spec.rb
=> Feature: Create conversations from Tweets

Gemfile.lock, app/controllers/twitter/authorizations_controller.rb, app/controllers/twitter/base_controller.rb, app/controllers/twitter/callbacks_controller.rb, app/javascript/dashboard/components/widgets/ChannelItem.vue, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/channel-factory.js, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Twitter.vue, app/models/account.rb, app/models/channel/twitter_profile.rb, app/services/twitter/webhook_subscribe_service.rb, config/routes.rb, spec/controllers/twitter/callbacks_controller_spec.rb, spec/services/twitter/webhook_subscribe_service_spec.rb
=> Feature: SignIn with Twitter

.circleci/config.yml, app/controllers/devise_overrides/sessions_controller.rb, app/views/devise/auth.json.jbuilder, spec/controllers/devise/session_controller_spec.rb
- include avatar url in sign_in response
- fix circle ci builds
Fixes #500 
=> Chore: Include avatar url in sign_in response

.circleci/config.yml, __mocks__/fileMock.js, app/controllers/api/v1/profiles_controller.rb, app/javascript/dashboard/App.vue, app/javascript/dashboard/api/auth.js, app/javascript/dashboard/api/endPoints.js, app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/i18n/default-sidebar.js, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/i18n/locale/en/index.js, app/javascript/dashboard/i18n/locale/en/settings.json, app/javascript/dashboard/routes/auth/PasswordEdit.vue, app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue, app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue, app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue, app/javascript/dashboard/routes/dashboard/settings/profile/profile.routes.js, app/javascript/dashboard/routes/dashboard/settings/settings.routes.js, app/javascript/dashboard/store/modules/auth.js, app/javascript/dashboard/store/modules/specs/auth/actions.spec.js, app/javascript/dashboard/store/modules/specs/auth/getters.spec.js, app/javascript/dashboard/store/utils/api.js, app/views/api/v1/profiles/update.json.jbuilder, jest.config.js, package.json, yarn.lock
=> Feature: Agent Profile Update with avatar

app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
=> Bug: Fix imports in ProfileSettings

app/controllers/api/base_controller.rb, app/controllers/api/v1/subscriptions_controller.rb, app/controllers/api/v1/webhooks_controller.rb, app/controllers/application_controller.rb, config/routes.rb, spec/controllers/api/v1/subscriptions_controller_spec.rb, spec/spec_helper.rb
This adds tests for the subscriptions_controller
Issue #37 
I wasn't able to tests the "Status" function of this controller. Is it still used? @sojan-official  @pranavrajs thoughts?
Also I needed to change the Inheritance of this controller because it didn't really check for user authentication before.
=> Chore: Added tests for subscriptions_controller

spec/controllers/api/v1/inboxes_controller_spec.rb
This adds tests for inboxes_controller.rb
Issue #37
=> Chore: Added tests for inboxes_controller

app/views/api/v1/contacts/index.json.jbuilder, app/views/api/v1/contacts/update.json.jbuilder, spec/controllers/api/v1/contacts_controller_spec.rb, spec/factories/contacts.rb, spec/rails_helper.rb
This adds tests for contacts_controller.rb
I also had to remove two different thumbnail functions from the views because rails didn't know them. Please tell me if that was wrong @sojan-official @pranavrajs 😅 
Issue #37
=> Chore: Added tests for contacts_controller

docs/development/environment-setup/docker.md
- refactor docker manual
- removed debugging instructions from docker setup
Fixes #503 
=> Chore: Update docker setup manual

.scss-lint.yml, app/javascript/dashboard/assets/scss/_variables.scss, app/javascript/dashboard/assets/scss/plugins/_multiselect.scss, app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss, app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss, app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/SidebarItem.vue, app/javascript/dashboard/components/widgets/conversation/Message.vue
=> 510 -Visual enhancements for dashboard 

app/controllers/api/v1/inboxes_controller.rb, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/store/modules/inboxes.js, app/javascript/dashboard/store/modules/specs/inboxes/actions.spec.js, app/javascript/dashboard/store/modules/specs/inboxes/fixtures.js, app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js, app/models/conversation.rb, app/models/inbox.rb, app/views/api/v1/inboxes/index.json.jbuilder, config/routes.rb, db/migrate/20200217192734_add_enable_auto_assignment_to_inboxes.rb, db/schema.rb, spec/controllers/api/v1/inboxes_controller_spec.rb, spec/models/conversation_spec.rb
This adds the ability for admins to enable or disable the round robin of conversations. I wanted to add a feature instead of just writing tests. I hope that's okay 😅 But will continue to write tests of course 😀
Do I also need to add this to a documentation?
For #489 
Added new tests for it.
=> Feature: Added ability to toggle auto assignment of conversations

spec/controllers/api/v1/contacts_controller_spec.rb, spec/controllers/api/v1/facebook_indicators_controller_spec.rb
This adds test for the facebook_indicators_controller
For #37
=> Chore: Added tests for facebook_indicators_controller

Gemfile, Gemfile.lock, app/listeners/webhook_listener.rb, spec/listeners/webhook_listener_spec.rb
=> Enhancement: Add event name in webhook payload

app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
=> Bug: Hide contact panel when user switches the inboxes

spec/controllers/dashboard_controller_spec.rb
This adds tests for the dashboard controller
For #37
=> Chore: Added tests for dashboard_controller

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, app/javascript/dashboard/helper/URLHelper.js, app/javascript/dashboard/helper/spec/URLHelper.spec.js, app/javascript/dashboard/i18n/default-sidebar.js, app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue, app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js
=> Bug : Inbox Filter indicator is removed when a conversation is selected #495

app/javascript/widget/components/UserMessageBubble.vue
=> URL text going out of bubble 

.eslintrc.js, app/javascript/dashboard/mixins/conversations.js, app/javascript/dashboard/store/modules/conversations/getters.js, app/javascript/dashboard/store/modules/inboxes.js, app/javascript/dashboard/store/modules/specs/inboxes/actions.spec.js, package.json, yarn.lock
=> Enhancement: Upgrade @babel/preset-env

app/javascript/widget/views/Home.vue
=> Hide who's available section for widget after first interaction #547

app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
=> Add close button for right sidebar panel #550

yarn.lock
=> Bug: Fix yarn.lock discrepancies

docker-compose.production.yaml
* Sidekiq service was missing from the production docker-compose file. Added it.
Fixes #555
=> Bug: Added Sidekiq to production docker compose (#555)

Gemfile, Gemfile.lock, app/controllers/api/v1/callbacks_controller.rb, app/controllers/api/v1/user/notification_settings_controller.rb, app/models/account.rb, app/models/notification_setting.rb, app/models/user.rb, app/views/api/v1/user/notification_settings/show.json.jbuilder, config/routes.rb, db/migrate/20200226194012_add_notification_settings.rb, db/schema.rb, spec/controllers/api/v1/user/notification_settings_controller_spec.rb, spec/models/account_spec.rb, spec/models/notification_setting_spec.rb, spec/models/user_spec.rb
This closes #570
* Added a new model - notification settings - scoped to account and user
* Added two new email related flags, one for receiving emails when a conversation is assigned, another for getting an email on a new conversation when auto assignment is disabled
* Added two api endpoints, one for showing all the selected flags and another for updating it
* Added tests for model and controller
In silence.
=> Feature: Add new notification settings for user

spec/controllers/api/v1/conversations/messages_controller_spec.rb
This adds tests for the conversations/messages_controller.rb
For #37
=> Chore: Added tests for conversations messages controller

app/javascript/dashboard/components/Modal.vue
=> Bug: Fix close button action on webhook settings modal

app/javascript/dashboard/routes/dashboard/settings/profile/EmailNotifications.vue, app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
=> Improves UI on user preferences page

Gemfile.lock
=> Security: Upgrade puma to 4.3.3

.scss-lint.yml, app/javascript/packs/sdk.js, app/javascript/widget/App.vue, app/javascript/widget/assets/scss/woot.scss, app/javascript/widget/components/AgentMessage.vue, app/javascript/widget/components/ChatHeader.vue, app/javascript/widget/components/ChatHeaderExpanded.vue, app/javascript/widget/views/Home.vue
=> Bug: Fix missing close button on mobile chat window

swagger/definitions/index.yml, swagger/definitions/request/conversation/create_message.yml, swagger/definitions/resource/contact.yml, swagger/definitions/resource/conversation.yml, swagger/definitions/resource/extension/contact/conversation.yml, swagger/definitions/resource/extension/contact/show.yml, swagger/definitions/resource/extension/conversation/labels.yml, swagger/definitions/resource/extension/conversation/show.yml, swagger/definitions/resource/inbox.yml, swagger/definitions/resource/message.yml, swagger/index.yml, swagger/paths/conversation/assignments.yml, swagger/paths/conversation/labels.yml, swagger/paths/conversation/list.yml, swagger/paths/conversation/messages.yml, swagger/paths/conversation/messages/index_create.yml, swagger/paths/conversation/toggle_status.yml, swagger/paths/inboxes/index.yml, swagger/paths/inboxes/update.yml, swagger/paths/index.yml, swagger/paths/widget/inboxes/create.yml, swagger/paths/widget/inboxes/update.yml, swagger/swagger.json
=> Chore: Update Swagger API docs

app/javascript/shared/components/CardButton.vue, app/javascript/shared/components/ChatCard.vue
=> Feature: Support card options in widget and dashboard #594

app/javascript/shared/components/CardButton.vue, app/javascript/shared/components/ChatCard.vue, app/javascript/shared/components/ChatOption.vue, app/javascript/shared/components/ChatOptions.vue, app/javascript/widget/components/ConversationWrap.vue
=> Feature: Support options message type on widget and dashboard

app/controllers/api/v1/accounts/inboxes_controller.rb, app/javascript/dashboard/helper/scriptGenerator.js, app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/packs/sdk.js, app/models/channel/web_widget.rb, app/views/api/v1/accounts/inboxes/index.json.jbuilder, app/views/api/v1/accounts/widget/inboxes/create.json.jbuilder, app/views/api/v1/accounts/widget/inboxes/update.json.jbuilder, swagger/definitions/resource/inbox.yml, swagger/swagger.json
=> Chore: Add web_widget_script in the Inboxes API

app/actions/contact_merge_action.rb, app/models/contact.rb, spec/actions/contact_merge_action_spec.rb
=> Bug: Migrate messages while merging contact

app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assigned.html.erb, app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_created.html.erb, config/routes.rb
Fixes #627 
* Update the conversation URLs in email templates.
=> Bug: Update conversation urls in email

app/dispatchers/async_dispatcher.rb, app/jobs/event_dispatcher_job.rb, config/sidekiq.yml, spec/builders/v2/report_builder_spec.rb, spec/dispatchers/async_dispatcher_spec.rb, spec/jobs/event_dispatcher_job_spec.rb
=> Non blocking  event dispatch

app/javascript/widget/api/conversation.js, app/javascript/widget/api/endPoints.js, app/javascript/widget/assets/images/paperclip.svg, app/javascript/widget/components/AgentMessage.vue, app/javascript/widget/components/ChatAttachment.vue, app/javascript/widget/components/ChatFooter.vue, app/javascript/widget/components/ChatInputWrap.vue, app/javascript/widget/components/ChatMessage.vue, app/javascript/widget/components/ImageBubble.vue, app/javascript/widget/components/UserMessage.vue, app/javascript/widget/components/UserMessageBubble.vue, app/javascript/widget/store/modules/conversation.js, app/javascript/widget/store/modules/specs/conversation/actions.spec.js, app/javascript/widget/store/modules/specs/conversation/mutations.spec.js, app/javascript/widget/store/modules/specs/conversation/utils.spec.js, app/javascript/widget/views/Home.vue
=> As a user, I would like to send files/images to the agent #643

app/builders/messages/outgoing/normal_builder.rb, app/controllers/api/v1/widget/messages_controller.rb, app/helpers/file_type_helper.rb, app/javascript/dashboard/api/inbox/message.js, app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/components/widgets/conversation/bubble/File.vue, app/javascript/dashboard/i18n/en.js, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/packs/widget.js, app/javascript/shared/helpers/MessageFormatter.js, app/javascript/shared/helpers/specs/MessageFormatter.spec.js, app/javascript/widget/components/AgentMessage.vue, app/javascript/widget/components/ChatAttachment.vue, app/javascript/widget/components/ChatInputWrap.vue, app/javascript/widget/components/FileBubble.vue, app/javascript/widget/components/ImageBubble.vue, app/javascript/widget/components/UserMessage.vue, app/javascript/widget/components/UserMessageBubble.vue, app/javascript/widget/i18n/en.js, app/javascript/widget/i18n/index.js, app/javascript/widget/store/modules/conversation.js, app/javascript/widget/store/modules/specs/conversation/actions.spec.js, app/javascript/widget/store/modules/specs/conversation/mutations.spec.js, app/views/api/v1/widget/messages/create.json.jbuilder, app/views/api/v1/widget/messages/index.json.jbuilder, spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb, spec/controllers/api/v1/widget/messages_controller_spec.rb
=> Feature: Support file type messages on widget and dashboard

.rubocop.yml, app/actions/contact_merge_action.rb, app/controllers/api/base_controller.rb, app/controllers/api/v1/accounts/inboxes_controller.rb, app/controllers/concerns/access_token_auth_helper.rb, app/models/account.rb, app/models/inbox.rb, spec/controllers/api/v1/accounts/inboxes_controller_spec.rb, swagger/paths/inboxes/update.yml, swagger/paths/index.yml, swagger/swagger.json
API to add a business logo to webwidget
addresses : #237
=> Feature: Business logo API for web widget

app/controllers/api/v1/accounts/inboxes_controller.rb, app/controllers/api/v1/agent_bots_controller.rb, app/models/inbox.rb, app/policies/inbox_policy.rb, config/routes.rb, spec/controllers/api/v1/accounts/inboxes_controller_spec.rb, spec/controllers/api/v1/agent_bots_controller_spec.rb, spec/policies/inbox_policy_spec.rb, swagger/definitions/index.yml, swagger/definitions/resource/agent_bot.yml, swagger/paths/agent_bots/index.yml, swagger/paths/inboxes/set_agent_bot.yml, swagger/paths/index.yml, swagger/swagger.json
APIs for agent bots
Addresses: #675
=> Chore: APIs for agent bots

app/javascript/widget/components/Branding.vue, app/javascript/widget/components/ChatSendButton.vue
=> Bug: Fix IE issues in Widget

docs/development/environment-setup/mac-os.md, docs/development/environment-setup/ubuntu.md, docs/development/environment-setup/windows.md
Bump ruby version in documentation to match current project version.
`2.6.5 --> 2.7.0`
Fixes #743 
=> docs: [#743] Bump ruby version to 2.7.0 in docs

app/javascript/widget/components/ChatHeader.vue, app/javascript/widget/components/ChatHeaderExpanded.vue, app/javascript/widget/views/Home.vue, app/views/api/v1/accounts/inboxes/create.json.jbuilder, app/views/api/v1/accounts/inboxes/update.json.jbuilder, app/views/widgets/show.html.erb, swagger/definitions/resource/inbox.yml, swagger/paths/inboxes/create.yml, swagger/paths/inboxes/update.yml, swagger/paths/index.yml, swagger/swagger.json
=> Chore: Update swagger API documentation

app/builders/v2/report_builder.rb
=> Bug:  Force scoping message metrics to account_id

app/javascript/sdk/IFrameHelper.js, app/javascript/sdk/bubbleHelpers.js
=> Bug: Fix `webwidget.triggered` event

app/javascript/dashboard/components/widgets/conversation/EmptyState.vue, app/javascript/dashboard/mixins/account.js, app/javascript/dashboard/mixins/specs/account.spec.js, app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
Fixes #753 
- Added a mixin to provide account_id
- Update URL to use account_id scoping
=> Bug: Add account scoping in CTA

app/javascript/packs/sdk.js, app/javascript/sdk/IFrameHelper.js, app/javascript/sdk/bubbleHelpers.js, app/javascript/widget/assets/scss/sdk.js, app/views/widget_tests/index.html.erb, docs/channels/facebook-channel.md, docs/channels/website-sdk.md, docs/development/project-setup/environment-variables.md
Fixes #235 
Supported positions are `left` and `right`. Default is right.
=> Feature: Customise the position of messenger

app/javascript/dashboard/routes/auth/Confirmation.vue
=> Bug: Redirect user to set new password screen

app/javascript/dashboard/assets/scss/_woot.scss, app/javascript/dashboard/assets/scss/widgets/_emojiinput.scss, app/javascript/dashboard/components/widgets/emoji/EmojiInput.vue, app/javascript/widget/components/ChatAttachment.vue, app/javascript/widget/components/ChatInputWrap.vue, app/javascript/widget/components/ChatSendButton.vue
=> Feature: Support an Emoji selector in the chat widget

db/seeds.rb
=> Fixes broken seeds issue

app/views/api/v1/accounts/conversations/messages/index.json.jbuilder, spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
Add additional information to conversation meta
Fixes # 785
=> Chore: Add additional information to conversation meta

db/migrate/20200422130153_create_notifications.rb
=> Bug: Fix data migration in notification settings

app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Fix missing contact_id in conversation list
=> Bug: Fix missing contact_id in conversation list

app/javascript/dashboard/components/widgets/chart/BarChart.js
=> Bug: Use beginAtZero option for reports

.env.example, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, docs/development/project-setup/conversation-continuity.md
This fixes #777 
* Moved the email ingress method in the config to an environment variable
* Updated documentation to reflect this
Tested locally and verified that the application is picking up new values from the `.env` file and working as expected.
=> Chore: Moved the email ingress method to an env variable (#777)

app/controllers/api/v1/accounts/conversations_controller.rb, app/views/api/v1/accounts/conversations/meta.json.jbuilder, config/routes.rb, spec/controllers/api/v1/accounts/conversations_controller_spec.rb
API to get conversations count
Addresses: #497
=> Chore: API to get conversations count

.env.example, app/controllers/apple_app_controller.rb, app/controllers/home_controller.rb, app/views/apple_app/site_association.html.erb, config/routes.rb, spec/controllers/apple_app_spec.rb
Sets up apple app association file for universal deep linking
Fixes #786
=> Chore: Apple site association file

app/controllers/api/v1/accounts/conversations_controller.rb, app/listeners/action_cable_listener.rb, app/models/agent_bot.rb, app/models/contact.rb, app/models/user.rb, config/routes.rb, lib/events/types.rb, spec/controllers/api/v1/accounts/conversations_controller_spec.rb, spec/listeners/action_cable_listener_spec.rb
- api to toggle typing status on a conversation
- clients receive webhook events on the same
Addresses: #718 , #719 , #775
=> Feature: Api to toggle typing status on a conversation

app/javascript/widget/components/template/EmailInput.vue
This is already available
This will conflict with the existing input box, so we cannot do this.
Done
Fixes #664
=> Chore: Add enter key listener for email input box

app/javascript/widget/components/Branding.vue, app/javascript/widget/i18n/en.js
Fixes #673 
@nithindavid We already have a translation file set up in the widget.
=> Chore: Fix missing translation text in web widget

app/javascript/shared/components/ChatForm.vue, app/javascript/shared/helpers/constants.js, app/models/concerns/content_attribute_validator.rb
=> Feature: Add default value to ChatForm

config/environments/production.rb, deployment/chatwoot-web.1.service, deployment/chatwoot-worker.1.service, deployment/chatwoot.target, deployment/setup.sh
Improve production deployment.
- Installation script
Fixes #282 and #361  
Over and over on Ubuntu 18.04LTS Digital Ocean servers.
=> Feature: Add installation script

app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
Addresses: #681 
| - | - |
|<img width="572" alt="Screenshot 2020-05-06 at 12 33 38 PM" src="https://user-images.githubusercontent.com/2246121/81146396-d1bdd700-8f95-11ea-9cdc-6434568dbea6.png"> | <img width="569" alt="Screenshot 2020-05-06 at 12 33 15 PM" src="https://user-images.githubusercontent.com/2246121/81146371-c36fbb00-8f95-11ea-8a19-32d4441af94f.png"> |
=> Chore: Fix broken conversation mailer layout

.rubocop.yml, app/models/account.rb, app/models/concerns/featurable.rb, app/models/installation_config.rb, config/installation_config.yml, db/migrate/20200510112339_create_installation_config.rb, db/schema.rb, db/seeds.rb, lib/config_loader.rb, spec/lib/config_loader_spec.rb, spec/models/installation_config_spec.rb
Closes #839 
* Added new model installation config with corresponding migrations and specs
* Created an installation config YML (key-value store model)
* Created a config loader module to load the installation configs
* Added this to the config loader seeder
* Changed the account `before_create` hook for default feature enabling to use the feature values from installation config
* Renamed the feature concern to Featurable to follow the naming pattern for concerns
* Added comments and specs for modules and places that deemed necessary
Tested locally. Wrote unit tests for new modules which pass along with existing tests.
Tired to even write a funny story on how this was tested. The irony of life at max.
=> Feature: Installation global config (#839)

app/javascript/dashboard/api/ApiClient.js, app/javascript/dashboard/api/reports.js, app/javascript/dashboard/api/specs/reports.spec.js
=> Bug: Use v2 reports instead of v1 reports

app/controllers/dashboard_controller.rb, app/controllers/widgets_controller.rb, app/views/layouts/vueapp.html.erb, app/views/widgets/show.html.erb, config/installation_config.yml
=> Chore: Add an option to toggle web manifest

app/javascript/dashboard/i18n/locale/de/cannedMgmt.json, app/javascript/dashboard/i18n/locale/de/chatlist.json, app/javascript/dashboard/i18n/locale/de/conversation.json, app/javascript/dashboard/i18n/locale/de/settings.json
"canned responses" are no food: "Eingemachte Antwort" -> "Vorgefertigte Antwort"
"open", "closed" status are no verbs, so "Öffnen" -> "Offen", ...
"mine" has nothing to do with mining :) "Bergwerk" -> "Meine"
"home" isn't your home, but the main page "Hauptseite"
"resolve action" is about solutions not determination, so
"Entschlossenheit" -> "Fall schließen"
"settings" are simply "Einstellungen"
- [ X ] Bug fix (non-breaking change which fixes an issue)
Switch to german in settings, take a look :)
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- …
=> Fixed some German translation strings

app/javascript/widget/components/ChatAttachment.vue
=> Bug: fix widget icon alignment

Gemfile, Gemfile.lock, app/builders/contact_builder.rb, app/controllers/api/v1/accounts/callbacks_controller.rb, app/controllers/twitter/callbacks_controller.rb, app/models/channel/twitter_profile.rb, app/models/channel/web_widget.rb, app/services/twitter/send_reply_service.rb, app/services/twitter/webhook_subscribe_service.rb, spec/controllers/twitter/callbacks_controller_spec.rb, spec/services/twitter/webhook_subscribe_service_spec.rb
- identify and fix some of the issues in existing twitter integration
=> Chore: Twitter Integration house cleaning

app/controllers/super_admin/account_users_controller.rb, app/controllers/super_admin/devise/sessions_controller.rb, app/dashboards/account_user_dashboard.rb, app/javascript/dashboard/assets/scss/super_admin/index.scss, app/views/super_admin/application/_navigation.html.erb, app/views/super_admin/devise/sessions/new.html.erb, config/routes.rb, spec/controllers/super_admin/account_users_controller_spec.rb, spec/controllers/super_admin/users_controller_spec.rb
- Show errors on login page
- Dashboard for admin panel
=> Chore: Add Account Users to Admin Panel

app/controllers/application_controller.rb, app/javascript/packs/sdk.js, app/javascript/sdk/IFrameHelper.js, app/javascript/widget/App.vue, app/javascript/widget/api/endPoints.js, app/javascript/widget/api/specs/endPoints.spec.js, app/javascript/widget/i18n/index.js, app/views/widget_tests/index.html.erb, app/views/widgets/show.html.erb, docs/channels/website-sdk.md
Fixes #870 
- Expose setLocale function which accepts a language code
- Send locale in messages API
=> Feature: Introduce locale in web-widget SDK

.env.example, config/environments/development.rb
Configure Letter opener with environment variable
=> Chore: Configure Letter opener with environment variable

app/javascript/dashboard/components/index.js, app/javascript/dashboard/components/widgets/Thumbnail.vue, app/javascript/dashboard/components/widgets/forms/AvatarUploader.vue, app/javascript/dashboard/components/widgets/forms/Input.vue, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Website.vue, app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue, app/javascript/dashboard/store/modules/inboxes.js, app/javascript/widget/components/ChatHeader.vue
=> Chore: Add an option to upload business logo

lib/config_loader.rb
Fix undefined method `compare_and_save`
run `bundle exec rake db:migrate` successfully.
run `bundle exec rake assets:precompile` successfully.
=> Fix undefined method `compare_and_save`

Procfile, app.json
Use db:prepare instead of db:migrate
Fixes #922 
=> Chore: Fix heroku post deploy issue

app/builders/notification_subscription_builder.rb
=> Bugfix: FCM push subscription builder fix

app/controllers/api/v1/accounts/labels_controller.rb, app/models/account.rb, app/models/label.rb, app/policies/label_policy.rb, app/views/api/v1/accounts/labels/create.json.jbuilder, app/views/api/v1/accounts/labels/index.json.jbuilder, app/views/api/v1/accounts/labels/most_used.json.jbuilder, app/views/api/v1/accounts/labels/show.json.jbuilder, app/views/api/v1/accounts/labels/update.json.jbuilder, config/routes.rb, db/migrate/20200606132552_create_labels.rb, db/schema.rb, spec/controllers/api/v1/accounts/labels_controller_spec.rb, spec/factories/labels.rb, spec/models/label_spec.rb
=> Feature: Label APIs

app/javascript/widget/helpers/actionCable.js
=> Bug: Fix socket reconnect if the pubsub token is same

app/javascript/dashboard/api/inbox/conversation.js, app/javascript/dashboard/api/specs/inbox/conversation.spec.js, app/javascript/dashboard/api/specs/inboxes.spec.js, app/javascript/dashboard/assets/scss/widgets/_conv-header.scss, app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/helper/actionCable.js, app/javascript/dashboard/store/modules/conversations/actions.js, app/javascript/dashboard/store/modules/conversations/specs/actions.spec.js, app/views/api/v1/accounts/conversations/meta.json.jbuilder, spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Fixes #497 
- Fetch metadata on conversation created, status change, assignee change
=> Bug: Update conversation counters in realtime

app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
Fix greeting_message set as null
=> Use empty string as fallback greeting_message if null

app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
Fix missing tagline in inbox settings
=> Bug: Fix missing tagline in inbox settings

app/controllers/api/v1/widget/events_controller.rb, app/javascript/widget/api/endPoints.js, app/javascript/widget/api/events.js, app/javascript/widget/helpers/specs/urlParamsHelper.spec.js, app/javascript/widget/helpers/urlParamsHelper.js, app/listeners/agent_bot_listener.rb, app/listeners/webhook_listener.rb, app/models/conversation.rb, db/schema.rb, spec/controllers/api/v1/widget/events_controller_spec.rb
- update conversation webhook payload 
- web widget triggered event comes with browser language payload
=> Chore: Send browser language in webwidget events

app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Twilio.vue
=> Bug: Replace non-numeric characters in Twilio phonenumber

app/javascript/widget/components/ChatInputArea.vue
Fixes #959 
**BEFORE**
**AFTER**
=> Add min height to widget input box

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Addresses #961 
- Remove HTML rendering in ConversationCard
=> Chore: Fix HTML rendering in ConversationCard

app/javascript/widget/components/FileBubble.vue, app/javascript/widget/components/UserMessage.vue, app/javascript/widget/components/UserMessageBubble.vue
=> Fix: Set widget bg color for file-bubble

app/controllers/api/v1/accounts/notifications_controller.rb, app/models/notification.rb, app/services/notification/push_notification_service.rb, app/views/api/v1/accounts/notifications/index.json.jbuilder, spec/controllers/api/v1/accounts/notifications_controller_spec.rb, spec/models/notification_spec.rb
* notification default sort to desc
* endpoint to mark notifications read_at for primary_actor
* notification primary_actor_type in payload
* group key for fcm notifications
=> Chore: FCM Notification Improvements

.rubocop.yml, app/models/contact.rb, app/services/notification/push_notification_service.rb, config/initializers/00_init.rb, config/initializers/custom_error_codes.rb, config/routes.rb, spec/services/notification/push_notification_service_spec.rb
- Fix failing sidekiq events for contact create
=> Chore: Fix failing sidekiq events for contact create

docs/development/project-setup/slack-integration-setup.md
- Fix typo in slack-integration-setup.md
=> Chore: Fix typo in Slack documentation

app/models/label.rb, db/migrate/20200625154254_add_default_value_to_color.rb, db/schema.rb
- Set a default color for labels if nothing is available
=> Chore: Add default value for label color

app/javascript/dashboard/assets/scss/_foundation-settings.scss, app/javascript/widget/assets/scss/_variables.scss
This change proposes the addition of Tahoma font to give the Arabic characters better looks.
Fixes #990 
=> Font proposals

docs/development/project-setup/environment-variables.md
Add information about how to integrate with Sendgrid.
Addresses #296 
I used these configs to integrate with Sendgrid with my chatwoot instance.
=> Update documentation with Sendgrid instructions

app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss, app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
=> Add icon show last reply is from agent on conversation list

.scss-lint.yml, app/javascript/dashboard/assets/scss/_helper-classes.scss, app/javascript/dashboard/assets/scss/_mixins.scss, app/javascript/dashboard/assets/scss/widgets/_reply-box.scss, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Fixes - #998 
Adds a subtle shadow change when input box is active
=> Enhancement - Add a visual feedback to show reply box is focused on dashboard #998

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/store/modules/contacts.js, app/javascript/dashboard/store/modules/conversations/actions.js, app/javascript/dashboard/store/modules/conversations/index.js, app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js, app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js, app/models/notification.rb, app/presenters/conversations/event_data_presenter.rb, app/views/api/v1/conversations/partials/_conversation.json.jbuilder, spec/models/conversation_spec.rb, spec/presenters/conversations/event_data_presenter_spec.rb
- Removed channel from the sender, add a separate attribute outside of the sender 
- Updated UPDATE_CONVERSATION mutation
- Added specs for the conversation actions.
=> Chore: Fix issues with conversation data models

docs/channels/facebook-channel.md, docs/channels/twitter-channel.md, docs/channels/website-channel.md, docs/channels/whatsapp-sms-twilio.md, docs/deployment/production/architecture.md, docs/deployment/production/caprover.md, docs/deployment/production/docker.md, docs/deployment/production/heroku.md, docs/deployment/production/linux-vm.md, docs/development/environment-setup/windows.md, docs/development/project-setup/slack-integration-setup.md
Fix spellings mistakes in docs
=> Chore: Fix spelling mistakes in docs

app/javascript/dashboard/components/widgets/ChannelItem.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue, app/models/user.rb, app/views/api/v1/accounts/show.json.jbuilder, config/features.yml, db/migrate/20200704173104_add_twitter_feature_flag.rb, db/schema.rb
Ability to limit channel using feature flag
=> Chore: Feature Flags for Channels

docs/development/project-setup/environment-variables.md
=> Add documentation for Mailgun & Mailchimp

app/javascript/widget/components/template/EmailInput.vue
Fixes #923 
https://recordit.co/xWh2uzXU5T
=> Bug: Set auto width to email input

.rubocop.yml, .rubocop_todo.yml, app/models/conversation.rb, app/models/inbox.rb, app/models/inbox_member.rb, app/models/message.rb, app/services/round_robin/assignment_service.rb, app/services/round_robin/manage_service.rb, app/workers/conversation_reply_email_worker.rb, config/initializers/redis.rb, config/puma.rb, db/migrate/20170525104650_round_robin.rb, lib/constants/redis_keys.rb, lib/online_status_tracker.rb, lib/redis/alfred.rb, lib/redis/redis_keys.rb, spec/models/conversation_spec.rb, spec/services/round_robin/manage_service_spec.rb
=> Chore: Refactor round robin logic

app/javascript/dashboard/components/widgets/ChannelItem.vue, app/javascript/dashboard/routes/auth/Signup.vue, semantic.yml
- Update the copy on Signup page
- Use correct feature flag on inbox page
- Introduce semantic.yml
=> Chore: Update copy on Signup page

config/app.yml, db/migrate/20200709145000_remove_multiple_feature_flags.rb, db/schema.rb, lib/config_loader.rb
=> Chore: Migration fix for feature flags

app.json
=> Update Heroku deploy

docs/channels/supported-features.md
- Add docs on supported features
=> Chore: Add docs on supported features per channel

app.json, docker-compose.production.yaml, docker-compose.yaml
=> Chore: Update PostgreSQL version to 12

app/javascript/dashboard/i18n/locale/el/settings.json, app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
=> Bug: Fix translated keys for availability statuses in Greek

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/store/modules/conversations/index.js, app/javascript/shared/helpers/KeyboardHelpers.js, app/javascript/shared/helpers/MessageFormatter.js, app/javascript/shared/helpers/MessageTypeHelper.js, app/javascript/shared/helpers/specs/KeyboardHelpers.spec.js, app/jobs/send_reply_job.rb, app/models/message.rb, app/services/facebook/send_on_facebook_service.rb, docs/channels/supported-features.md, spec/factories/messages.rb, spec/services/facebook/send_on_facebook_service_spec.rb, spec/services/twilio/send_on_twilio_service_spec.rb, spec/services/twitter/send_on_twitter_service_spec.rb
Chore: Fix fb file uploads
Fixes  #1047
=> Chore: Cleanup attachment handling for Facebook & Whatsapp

docs/development/environment-setup/windows.md
=> Make minor grammatical changes

app/javascript/dashboard/constants.js, app/javascript/dashboard/i18n/locale/en/chatlist.json
Enable status Bot to be visible in conversation status dropdown
=> Chore: Enable bot conversations in status dropdown

app/controllers/api/v1/accounts_controller.rb, app/javascript/dashboard/i18n/locale/en/generalSettings.json, app/javascript/dashboard/routes/dashboard/settings/account/Index.vue, app/mailers/conversation_reply_mailer.rb, app/models/account.rb, app/models/concerns/featurable.rb, app/views/api/v1/accounts/show.json.jbuilder, app/views/api/v1/accounts/update.json.jbuilder, app/views/mailers/conversation_reply_mailer/reply_without_summary.html.erb, db/migrate/20200709145000_remove_multiple_feature_flags.rb, spec/controllers/api/v1/accounts_controller_spec.rb, spec/factories/accounts.rb, spec/mailers/conversation_reply_mailer_spec.rb
The email settings under account settings needed to be
feature locked in a way different from the current way for it
to be enabled for accounts in a self-hosted scenario.
Some refactorings were also done along with this change.
1. There was a feature flag defined in code in account-model called
domain_emails_enabled was used to check if the inbound emails were
enabled for the account. But there was already a feature flag called
"inbound_emails" defined in features.yml. So changed to use this to
check if inbound emails are enabled for an account.
2. Renamed and re-purposed existing `domain_emails_enabled` to
`custom_email_domain_enabled` to use for feature toggling the UI
for email settings.
3. To enable & disable multiple features using the feature concern
we were passing an array of …
=> Chore: Feature lock email settings in UI

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
- Remove automatic removal of whitespace while editing
=> Enhancement: Remove v-model.trim from reply box

docs/development/environment-setup/ubuntu.md
Minor changes to remove typos and create a coherent structure throughout the docs.
Thanks
=> Fix grammatical issues in Ubuntu Environment Setup

app/controllers/api/v1/widget/base_controller.rb, app/controllers/api/v1/widget/events_controller.rb, app/controllers/api/v1/widget/messages_controller.rb, app/dashboards/user_dashboard.rb, app/models/user.rb, app/views/api/v1/models/_user.json.jbuilder, db/migrate/20200719171437_rename_nick_name_to_display_name.rb, db/schema.rb, docs/deployment/production/linux-vm.md, spec/controllers/api/v1/widget/events_controller_spec.rb, spec/factories/users.rb, swagger/definitions/resource/user.yml, swagger/swagger.json
- Adding browser info to web widget triggered event
fixes: #970, #1057
=> Chore: Minor Fixes and Improvements

config/installation_config.yml, lib/tasks/db_enhancements.rake
We have been duplicating the config loader migration. Hence let's hook it to rake db:migrate
=> Chore: Run ConfigLoader on migrate

.gitignore, Gemfile, Gemfile.lock, Procfile.test, app/javascript/dashboard/components/buttons/FormSubmitButton.vue, app/javascript/dashboard/routes/login/Login.vue, config/initializers/cypress_on_rails.rb, docs/README.md, docs/development/project-setup/quick-setup.md, package.json, spec/cypress.json, spec/cypress/app_commands/activerecord_fixtures.rb, spec/cypress/app_commands/clean.rb, spec/cypress/app_commands/eval.rb, spec/cypress/app_commands/factory_bot.rb, spec/cypress/app_commands/load_seed.rb, spec/cypress/app_commands/log_fail.rb, spec/cypress/app_commands/scenarios/default.rb, spec/cypress/cypress_helper.rb, spec/cypress/fixtures/example.json, spec/cypress/integration/happy_paths/admin_dashboard_authentication.js, spec/cypress/plugins/index.js, spec/cypress/support/commands.js, spec/cypress/support/index.js, spec/cypress/support/on-rails.js, yarn.lock
=> Chore: Cypress Tests

docs/channels/facebook-channel.md, docs/channels/twitter-channel.md, docs/channels/website-channel.md
Minor grammatical changes.
Going through all doc files sequentially.
=> Fix Docs for FB Twitter Website Channel

app/javascript/dashboard/components/ui/Tabs/Tabs.js, app/javascript/dashboard/components/ui/Tabs/TabsItem.vue
- Add a prop to hide badge in tabs
=> chore: Add showBadge prop to tabs-item component

app/controllers/widgets_controller.rb, app/javascript/shared/store/globalConfig.js, app/javascript/widget/components/Branding.vue, app/mailers/application_mailer.rb, app/views/layouts/mailer.html.erb, config/installation_config.yml
- Remove hardcoded Twitter link
=> chore: Update mailer to remove hardcoded Twitter links

app/mailers/conversation_reply_mailer.rb, spec/mailers/conversation_reply_mailer_spec.rb
=> bug: Fix emails if assignee is nil

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
- Fix scroll behaviour in messages view
=> chore: Fix scroll in message view

app/controllers/api/v1/accounts/inboxes_controller.rb, app/javascript/dashboard/assets/scss/_layout.scss, app/javascript/dashboard/assets/scss/views/settings/inbox.scss, app/javascript/dashboard/components/ModalHeader.vue, app/javascript/dashboard/components/layout/SidebarItem.vue, app/javascript/dashboard/components/widgets/ChannelItem.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/store/modules/inboxes.js, app/javascript/shared/mixins/inboxMixin.js, app/javascript/shared/mixins/specs/inboxMixin.spec.js, app/javascript/widget/components/ChatInputWrap.vue, app/javascript/widget/mixins/configMixin.js, app/javascript/widget/mixins/specs/configMixin.spec.js, app/models/channel/web_widget.rb, app/models/inbox.rb, app/views/api/v1/models/_inbox.json.jbuilder, app/views/widgets/show.html.erb, db/migrate/20200730080242_add_feature_setting_to_website_inbox.rb, db/schema.rb
- Add feature flags for attachments/emoji_picker
- Update UI to accept these values
- Move inbox methods to a mixin
Fixes #971
=> feat: Disable attachments and emoji picker in the web widget

app/javascript/dashboard/store/utils/api.js, config/initializers/session_store.rb
Signed-off-by: Pranav Raj Sreepuram <pranavrajs@gmail.com>
Fixes #919
=> chore: Use 'Lax' instead of 'None'

docs/customizations/email-notifications.md
- Add documentation around email template content customization
=> chore: Add docs on customizing email template content

app/drops/user_drop.rb, app/mailers/application_mailer.rb, app/mailers/conversation_reply_mailer.rb, app/views/layouts/mailer/base.liquid
=> Chore: Enable additional attributes in liquid

docs/development/project-setup/environment-variables.md
Add documentation for DATABASE_URL environment variable
Fixes #1145
=> chore: Add documentation for DATABASE_URL environment variable

README.md
=> chore: Update Readme with feature details

swagger/definitions/request/contact/create.yml, swagger/definitions/request/conversation/create_message.yml, swagger/paths/contact/list_create.yml, swagger/swagger.json
Remove unneeded parameters and add missing/undocumented parameters from the definitions
Bug fix (non-breaking change which fixes an issue)
Developed a complete API integration between https://studio.csml.dev and Chatwoot. These are some of my finds along the way.
=> chore: update swagger definitions

swagger/definitions/index.yml, swagger/definitions/resource/account.yml, swagger/definitions/resource/contact.yml, swagger/definitions/resource/contact_inboxes.yml, swagger/definitions/resource/inbox.yml, swagger/definitions/resource/user.yml, swagger/paths/contact/search.yml, swagger/paths/contact_inboxes/create.yml, swagger/paths/index.yml, swagger/paths/profile/index.yml, swagger/swagger.json
- Add Contact APIs
- Update parameters
=> chore: Update API docs

app/javascript/packs/sdk.js, app/javascript/sdk/IFrameHelper.js, docs/channels/website-sdk.md
- Allow user to custom 'launcherText'
@sojan-official Do we need to limit the number of characters?
=> feat: Allow user to change the bubble title using SDK

app/views/api/v1/accounts/contacts/create.json.jbuilder, app/views/api/v1/accounts/contacts/index.json.jbuilder, app/views/api/v1/accounts/contacts/search.json.jbuilder, app/views/api/v1/accounts/contacts/show.json.jbuilder, app/views/api/v1/accounts/contacts/update.json.jbuilder, app/views/api/v1/models/_contact.json.jbuilder
Remove rendering contact inboxes in unnecessary places.
=> chore: Control rendering contact inbox

app/javascript/packs/sdk.js, app/javascript/sdk/IFrameHelper.js, app/javascript/widget/App.vue, app/javascript/widget/assets/scss/_buttons.scss, app/javascript/widget/assets/scss/woot.scss, app/javascript/widget/components/ChatHeader.vue, app/javascript/widget/components/ChatHeaderExpanded.vue, app/javascript/widget/components/HeaderActions.vue, app/javascript/widget/helpers/constants.js, app/javascript/widget/helpers/specs/urlParamsHelper.spec.js, app/javascript/widget/helpers/specs/utils.spec.js, app/javascript/widget/helpers/urlParamsHelper.js, app/javascript/widget/helpers/utils.js, app/javascript/widget/views/Home.vue, app/javascript/widget/views/Router.vue, app/views/widget_tests/index.html.erb, docs/channels/website-sdk.md
=> feat: Add a popout option on webwidget

app/models/message.rb, app/services/base/send_on_channel_service.rb, db/migrate/20200828175931_add_external_source_ids_to_messages.rb, db/schema.rb, lib/integrations/slack/incoming_message_builder.rb, lib/integrations/slack/send_on_slack_service.rb
- Enable slack integration in all channels
=> feat: Enable Slack Integration in all channels

lib/integrations/facebook/delivery_status.rb
- Fix nil class error at bot endpoint
=> chore: Fix nil class error at bot endpoint

.env.example, app/javascript/shared/assets/fonts/widget_fonts.scss, app/javascript/widget/assets/scss/woot.scss, config/environments/production.rb
- Use CDN for widget/dashboard assets
- Remove unused font weights
=> chore: Improve widget loading performance

app/javascript/sdk/bubbleHelpers.js
- Add alt text for bubble icon
=> chore: Add alt text for bubble icon

package.json, yarn.lock
=> chore: Upgrade yargs-parser to fix GHSA-p9pc-299p-vxgp

docs/channels/website-sdk.md
Fixes #1210 
- Update documentation
=> fix: Update documentation to use `launcherTitle`

app/controllers/api/v1/accounts/integrations/slack_controller.rb, lib/integrations/slack/send_on_slack_service.rb
Fix the issue when destroying integration hooks. 
=> chore: Fix integration hooks destroy

app/models/agent_bot.rb
Fixes #1236 
- Add available_name method for agent_bot
=> fix: Add available_name method to agent_bot

yarn.lock
=> chore: Upgrade selfsigned to fix CVE-2020-7720

app/controllers/api/v1/widget/labels_controller.rb, app/jobs/contact_avatar_job.rb, lib/webhooks/trigger.rb
- external url exception handling for webhooks
- external url exception handling for contact avatars
- fix for add, remove labels  when conversation is nil
=> chore: sentry error fixes

.github/ISSUE_TEMPLATE/bug_report.md
Add sections for browser and server logs
=> chore: Add browser logs and server logs to the template

app/controllers/api/v1/widget/labels_controller.rb, spec/controllers/api/v1/widget/labels_controller_spec.rb
- Fixes adding undefined labels to the conversation
=> chore: Add a check for defined labels in SDK API

docs/channels/website-sdk.md
Update the `website-sdk` documentation to reflect the feedback on setUser method from a customer
=> chore: Update website-sdk documentation

app/controllers/api/v1/accounts/conversations_controller.rb, app/finders/conversation_finder.rb, app/views/api/v1/accounts/conversations/search.json.jbuilder, config/routes.rb, spec/controllers/api/v1/accounts/conversations_controller_spec.rb, swagger/paths/conversation/index_or_create.yml, swagger/swagger.json
- API end point which takes message content as search parameter
- end point supports additional filtering with labels and inbox ids
- swagger doc
fixes: #243
=> feat: Ability to search conversation with message content

docs/channels/website-sdk.md
- Fix wrong documentation
Addresses #1268
=> chore: Fix wrong documentation to set a label

app/javascript/widget/i18n/locale/de.json
The widget is now fully translated into German. 
=> DE Widget - 100% Translation

app/javascript/packs/sdk.js, app/javascript/specs/packs/sdk.spec.js, package.json, yarn.lock
Fixes #856 
Compare data in setUser call before making the API call.
=> chore: Add a check for data diff in setUser call

app/controllers/api/v1/accounts/callbacks_controller.rb, app/javascript/dashboard/api/channel/fbChannel.js, app/javascript/dashboard/assets/scss/widgets/_forms.scss, app/javascript/dashboard/components/SettingsSection.vue, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/facebook/Reauthorize.vue, app/javascript/dashboard/store/modules/inboxes.js, app/models/channel/facebook_page.rb, app/models/concerns/reauthorizable.rb, app/services/facebook/send_on_facebook_service.rb, app/views/api/v1/accounts/callbacks/reauthorize_page.json.jbuilder, app/views/api/v1/models/_inbox.json.jbuilder, lib/redis/alfred.rb, lib/redis/redis_keys.rb, spec/controllers/api/v1/accounts/callbacks_controller_spec.rb, spec/models/channel/facebook_page_spec.rb, spec/models/concerns/reauthorizable_spec.rb, spec/services/facebook/send_on_facebook_service_spec.rb
enables reauthorization of third party connections like facebook pages, integrations etc
changes:
- reauthorizable concern for models
- Introduces new patterns for adding specs for model concerns
=> feat: Enables reauthorization of Third Party tokens 

.env.example, config/initializers/redis.rb
Added support for redis-sentinel
Fixes #925 
- Tested manually against docker redis-sentinel https://github.com/bitnami/bitnami-docker-redis-sentinel
=> add: support for redis sentinel

app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/SidebarItem.vue
=> resolve #1303 Replace Whatsapp inbox icon

app/javascript/dashboard/components/widgets/conversation/bubble/File.vue
Long file name appears to be broken in the UI in the agent conversation dashboard.
Fixes # (issue) #1273 
=> Fixed word break in file with long name in agent conversation view.

config/initializers/redis.rb, config/initializers/sidekiq.rb, lib/redis/config.rb, spec/lib/redis/config_spec.rb
This is extension of https://github.com/chatwoot/chatwoot/pull/1301
I missed to add sentinel configuration to Sidekiq. I have refactored redis configuration for application and sidekiq.
- Manually tested with Sidekiq and Rails
- Added RSpec to check return values for Redis::Config
=> refactor: redis config

config/initializers/languages.rb
Enable Vietnamese in available languages
=> chore: Enable Vietnamese in languages

app/controllers/api/v1/accounts/contacts_controller.rb, app/policies/contact_policy.rb, app/views/api/v1/accounts/contacts/active.json.jbuilder, config/routes.rb, lib/online_status_tracker.rb, spec/controllers/api/v1/accounts/contacts_controller_spec.rb
- endpoint: `account/{account_id}/contacts/active`
- Specs
=> feat: API to get the active contacts

lib/redis/config.rb, spec/lib/redis/config_spec.rb
Refactored the Redis config module which had Redis sentinel related configs. Also changed the specs accordingly.
This is related to #1310 
Local. Unit tests.
=> chore: refactored redis config (sentinel related)

public/robots.txt
Search bots trying to render the widget ends up throwing errors.
=> chore: Block Search bots from rendering widget

app/builders/messages/facebook/message_builder.rb, app/controllers/api/v1/accounts/callbacks_controller.rb, app/jobs/contact_avatar_job.rb, app/services/twilio/incoming_message_service.rb, lib/exception_list.rb, lib/webhooks/trigger.rb
Exception handling for common errors when calling external URLs.
=> chore: Handle exceptions on external URL calls

app/mailers/conversation_reply_mailer.rb, app/models/inbox.rb, db/migrate/20201011152227_add_email_address_to_inbox.rb, db/schema.rb, spec/mailers/conversation_reply_mailer_spec.rb
- Set email_address for inboxes. Use the email address while sending the email.
=> feat: Allow custom email address for inbox

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/models/conversation.rb, spec/models/conversation_spec.rb
=> Use full name in activity messages, fix specs

app/javascript/dashboard/i18n/locale/es/agentMgmt.json, app/javascript/dashboard/i18n/locale/es/cannedMgmt.json, app/javascript/dashboard/i18n/locale/es/chatlist.json, app/javascript/dashboard/i18n/locale/es/contact.json, app/javascript/dashboard/i18n/locale/es/conversation.json, app/javascript/dashboard/i18n/locale/es/generalSettings.json, app/javascript/dashboard/i18n/locale/es/inboxMgmt.json, app/javascript/dashboard/i18n/locale/es/integrations.json, app/javascript/dashboard/i18n/locale/es/labelsMgmt.json, app/javascript/dashboard/i18n/locale/es/login.json, app/javascript/dashboard/i18n/locale/es/report.json, app/javascript/dashboard/i18n/locale/es/resetPassword.json, app/javascript/dashboard/i18n/locale/es/setNewPassword.json, app/javascript/dashboard/i18n/locale/es/settings.json, app/javascript/dashboard/i18n/locale/es/signup.json
=> Update Spanish translation

.env.example
Update documentation for inbound email service
=> chore: Update documentation for inbound email service

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
=> feat: Enable File Upload for API Inbox in the UI

app/javascript/dashboard/assets/scss/widgets/_buttons.scss, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
=> fix: Add compact type, fix spacing in contact panel

app/javascript/widget/i18n/locale/pl.json
The widget is now fully translated into Polish. Crowdin is also updated
Fixes #307 
- New feature (non-breaking change which adds functionality)
n/a
=> PL Widget - 100% Translation

deployment/setup_18.04.sh, deployment/setup_20.04.sh, docs/README.md, docs/deployment/production/linux-vm.md
=> fix: Update production installation setup script for Ubuntu 20.04

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/components/Modal.vue, app/javascript/dashboard/components/widgets/conversation/bubble/Image.vue
Fixes the display of image files
=> fix: Add a full width image view to fix resolution issues

.rubocop.yml, config/initializers/azure_storage_service_patch.rb, lib/azure/storage.rb, lib/azure/storage/core/auth/shared_access_signature.rb
Monkey patch azure storage service until the changes come into rails stable versions
=> chore: Monkey patch Azure storage service 

lib/integrations/facebook/message_parser.rb, lib/tasks/swagger.rake
I found the typos and fixed them.
=> Fixed typo with misspell

app/javascript/dashboard/i18n/locale/es/contact.json, app/javascript/dashboard/i18n/locale/es/inboxMgmt.json, app/javascript/dashboard/i18n/locale/es/settings.json
Comparing the en locale with the es locale there are missing keywords.
=> Added missing keywords to Spanish translation

app/javascript/dashboard/components/layout/AvailabilityStatus.vue
=> Enhancement: Add status color for items in availability status menu

app/javascript/widget/components/FileBubble.vue
=> Fix-1403 Ui Chore fix

app/models/concerns/avatarable.rb, app/models/user.rb
Gravatar URLs for contacts
Fixes #1240 
=> feat: Gravatar urls for contacts

app/services/twitter/tweet_parser_service.rb, spec/factories/twitter/tweet_create_event.rb, spec/lib/webhooks/twitter_spec.rb
- Ignore blocked_users
Fixes #1154
=> feat: Ignore tweets from blocked users

app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
Ignore submit if the search term is empty
=> fix: Fire query only if search term is available

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
- Remove duplicate call for conversation id
=> fix: Remove duplicate API calls for conversation

README.md, docs/contributing.md, docs/contributing/translating-chatwoot-to-your-language.md
- Add documentation on the translation process
=> [skip ci] chore: Add documentation on translation process

app/javascript/dashboard/store/modules/auth.js, app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
- Update agent presence when the current user changes their presence.
Fixes #1402
=> fix: Update agent list when the user changes their presence

app/controllers/api/v1/accounts/contacts_controller.rb
I have added another filter of phone number in the search query in contacts_controller so that it can also search for phone number
Fixes #1438 
Database query update.
=> feat: Search contacts using phone number

deployment/setup_18.04.sh, deployment/setup_20.04.sh
Simple if check for variable.
Documentation at https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm should be changed to
`./setup.sh develop`
Either that or change the wget links you provide
https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_18.04.sh
https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_20.04.sh
to
https://raw.githubusercontent.com/chatwoot/chatwoot/master/deployment/setup_18.04.sh
https://raw.githubusercontent.com/chatwoot/chatwoot/master/deployment/setup_20.04.sh
=> Add branch variable

app/javascript/widget/i18n/locale/nl.json
Add translation string for widget in locale NL
Fixes # n/a
Tested in self-hosted version of Chatwoot.
=> Add translation strings to locale NL for widget

deployment/setup_18.04.sh, deployment/setup_20.04.sh
=> fix: Check if the branch argument is an empty string

app/javascript/dashboard/components/Code.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue, app/javascript/packs/application.js, app/models/channel/web_widget.rb, package.json, yarn.lock
- Upgrade highlight.js to 10.4.1
- Remove vue-highlight.js
=> chore: Upgrade highlight.js to 10.4.1

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/widget/components/ChatAttachment.vue
- image/*
- application/pdf
- audio/mpeg
- video/mp4
- audio/ogg
- text/csv
Allow only the above mentioned file-types on uploader
=> feat: Allow only image, pdf, audio, video,csv on file uploader

app/javascript/dashboard/i18n/locale/de/conversation.json, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/i18n/locale/en/integrations.json, app/javascript/dashboard/i18n/locale/fa/conversation.json, app/javascript/dashboard/i18n/locale/fi/conversation.json, app/javascript/dashboard/i18n/locale/hi/conversation.json, app/javascript/dashboard/i18n/locale/hu/conversation.json, app/javascript/dashboard/i18n/locale/it/conversation.json, app/javascript/dashboard/i18n/locale/ko/conversation.json, app/javascript/dashboard/i18n/locale/nl/conversation.json, app/javascript/dashboard/i18n/locale/pl/conversation.json, app/javascript/dashboard/i18n/locale/pt/conversation.json, app/javascript/dashboard/i18n/locale/ro/conversation.json, app/javascript/dashboard/i18n/locale/sk/conversation.json, app/javascript/dashboard/i18n/locale/sv/conversation.json, app/javascript/dashboard/i18n/locale/ta/conversation.json, app/javascript/dashboard/i18n/locale/uk/conversation.json, app/javascript/dashboard/i18n/locale/zh/conversation.json, app/javascript/dashboard/i18n/locale/zh_CN/conversation.json, app/javascript/dashboard/i18n/locale/zh_TW/conversation.json
- `Send the transcript of the assigned agent` -> `Send the transcript to the assigned agent`
- Remove `INTEGRATION_TXT` and `DESC`
=> chore: Fix translation issues

app/views/api/v1/conversations/partials/_conversation.json.jbuilder
=> fix: Display assignee only if the assignee has access to the account

app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue, app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/i18n/locale/en/generalSettings.json, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/i18n/locale/en/signup.json, app/javascript/dashboard/routes/auth/Signup.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue, app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
- Add text to translation files.
=> fix: Move untranslated text to translation files

docs/deployment/production/linux-vm.md
Context: https://github.com/chatwoot/chatwoot/discussions/1358
=> chore: Add steps for copying targets in linux VM

app/controllers/api/v1/accounts/contacts_controller.rb, app/controllers/widgets_controller.rb, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue, app/jobs/contact_ip_lookup_job.rb, app/models/channel/web_widget.rb, app/models/contact.rb, package.json, yarn.lock
- Log country code
- Display country name, city and country flag.
=> chore: Improve location display in sidebar

docs/development/environment-setup/mac-os.md, docs/development/project-setup/errors.md, docs/development/project-setup/quick-setup.md
- Remove outdated command, added an error section
=> chore: Update Mac OS setup guide

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/i18n/locale/en/conversation.json
=> chore: Add missing label to locale file

config/integration/apps.yml
=> chore: Fix i18n_key for webhooks

app/javascript/dashboard/api/reports.js, app/javascript/dashboard/api/specs/reports.spec.js, app/javascript/dashboard/i18n/locale/en/report.json, app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue, app/javascript/dashboard/store/modules/reports.js, app/javascript/dashboard/store/modules/specs/reports/actions.spec.js, app/views/api/v2/accounts/reports/agents.csv.erb, config/locales/en.yml
- Added a download button in reports
- Added report from, to in the CSV download
=> feat: Download Agent wise report

app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, docs/self-hosted/enable-ip-logging.md
- Add a doc on how to setup Maxmind DB with Chatwoot
=> chore: Add documentation for Maxmind geocoder setup

app/javascript/dashboard/routes/dashboard/conversation/ContactDetailsItem.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
=> Add href to "initiated from" url #1522

README.md
- Fixed translation link in docs
=> Chore: Fix translation link in docs

app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue
=> chore: fix add agent select placeholder translation

.env.example, app/views/layouts/vueapp.html.erb
If the app is already installed on a mobile device, the banner intelligently changes its action, and tapping the banner will simply open the app. If the user doesn’t have your app on their device, tapping on the banner will take them to the app’s entry in the App Store. 
Smart App Banners automatically determine whether the app is supported on the user’s device. If the device loading the banner does not support your app, or if your app is not available in the user's location, the banner will not display.
=> feature: smart app banner in website(iOS)

app/javascript/dashboard/assets/scss/app.scss, app/javascript/dashboard/assets/scss/super_admin/pages.scss, app/javascript/shared/assets/stylesheets/ionicons.scss, app/javascript/widget/assets/scss/woot.scss
- Use woff as src for Ionicons
=> chore: Remove Ionicons TTF references

docs/deployment/production/heroku.md
- Added a "Known limitations" section
=> chore: Add limitations section to Heroku

LICENSE, README.md
- Update license year and company name
=> chore: Update license year and update company name

app/javascript/dashboard/components/widgets/conversation/Message.vue
- Add a link on the sender name
Fixes #1594
=> feat: Add link to the Twitter profile of the sender

app/models/conversation.rb, db/migrate/20210105185632_enable_pg_stats_extention.rb, db/schema.rb
Fix the inconsistencies in schema and migrations
=> chore: Sync the schema and migrations

docs/development/project-setup/conversation-continuity.md
Add documentation to enable inbound_emails in the account.
=> chore: Add steps to enable inbound_emails in the account

app/javascript/dashboard/assets/scss/app.scss, app/javascript/shared/assets/stylesheets/shadows.scss
**Why?**
First step towards making shadows consistent.
=> Chore: UI: Add shadow utility variables

app/controllers/api/v1/accounts/conversations_controller.rb, app/controllers/api/v1/widget/messages_controller.rb, app/models/conversation.rb, spec/controllers/api/v1/accounts/conversations_controller_spec.rb, swagger/paths/conversation/index_or_create.yml, swagger/swagger.json
Enable updating additional attributes via conversation API
Fixes: #1357
=> chore: Enable updating conversation additional attributes

app/controllers/dashboard_controller.rb, spec/controllers/dashboard_controller_spec.rb
- Add switch_locale for Dashboard Controller
=> fix: Add missing switch_locale on DashboardController

app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactDetailsItem.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue, app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue, app/javascript/shared/components/EmojiOrIcon.vue, app/javascript/shared/helpers/emoji.js
Fixes #1604 
**Before**
**After**
=> Improve sidebar UI

swagger/paths/contact_inboxes/create.yml, swagger/swagger.json
Update Contact Inbox create API
Fixes #1627 
=> chore: Update Contact Inbox create API

config/installation_config.yml
remove un-necessary lock attribute in config
Pakka local.
=> feat: remove un-necessary lock attribute in config

docs/development/environment-setup/mac-os.md
- Update homebrew installation step
=> chore: Update homebrew installation command

app/javascript/widget/assets/scss/woot.scss
Fix ol, ul rendering in widget.
=> fix: Avoid list-style none in message-content

Procfile, app.json, lib/tasks/db_enhancements.rake
Introducing custom rake task `db:chatwoot_prepare`
ref: #1667
=> chore: Fix db:prepare error in deployments

app/controllers/api/v1/accounts/contacts_controller.rb
=> Contact.find_by should be Current.account.contacts.find_by

docs/channels/website-sdk.md
=> chore: update identity verification docs

app/views/widget_tests/index.html.erb, db/seeds.rb, lib/woot_message_seeder.rb
=> chore: Seeder for Bot Messages

app/javascript/dashboard/assets/scss/widgets/_reply-box.scss, app/javascript/dashboard/components/widgets/conversation/CannedResponse.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
- Move canned responses list to mention component
- Remove canned fetching logic from reply box component
=> chore: Move Canned Responses list to a separate component

Gemfile, app/controllers/api/v1/widget/contacts_controller.rb, app/javascript/dashboard/routes/login/Login.vue, app/mailers/application_mailer.rb, app/models/concerns/reauthorizable.rb, spec/actions/contact_identify_action_spec.rb, spec/controllers/api/v1/accounts/contacts_controller_spec.rb
=> docs: fixed typos

clevercloud/ruby.json, lib/tasks/db_enhancements.rake
- Add clever cloud deployment config
- Change the table setup check to use ar_internal_metadata
=> feat: Add support for Clever cloud deployments

app/controllers/api/v1/accounts/conversations/assignments_controller.rb, app/finders/conversation_finder.rb, spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb, spec/finders/conversation_finder_spec.rb
=> feat: Team Assignment & Filter APIs

app/javascript/shared/helpers/MessageFormatter.js, app/listeners/notification_listener.rb, spec/listeners/notification_listener_spec.rb
- Update mention regex to match all characters except \n
- Test the mentions with non-english characters
=> fix: Update flaky notification tests

Gemfile, Gemfile.lock, app/views/mailers/conversation_reply_mailer/conversation_transcript.html.erb, app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb, app/views/mailers/conversation_reply_mailer/reply_without_summary.html.erb
Use `commonmarker` for `commonmark` support.
=> fix: Use commonmarker instead of redcarpet

app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss, app/javascript/dashboard/components/layout/SidebarItem.vue, app/javascript/dashboard/components/widgets/TableFooter.vue, app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
- Fixes contact footer button
- Sidebar inbox name overflow
=> chore: UI fixes

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/mixins/specs/uiSettings.spec.js, app/javascript/dashboard/mixins/uiSettings.js, app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
Fixes #1697
- Save the rich content editor state to user UISettings
=> feat: Save rich content editor state to user.uiSettings

app/presenters/conversations/event_data_presenter.rb, lib/woot_message_seeder.rb, spec/models/conversation_spec.rb, spec/presenters/conversations/event_data_presenter_spec.rb
- send contact inbox data in webhook payload
- fix the example bot messages
=> chore: Minor Changes to Bot Message APIs

app/javascript/shared/components/ChatOption.vue, app/javascript/shared/components/ChatOptions.vue
=> feat: Update bot option select button styles

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/helpers/botMessageContentHelper.js, app/javascript/dashboard/components/widgets/conversation/helpers/specs/botMessageContentHelper.spec.js, app/javascript/dashboard/i18n/locale/en/conversation.json
Fix input_email, input_select, form message rendering in dashboard.
=> fix: Fix bot message rendering in dashboard

app/controllers/api/v1/accounts/inbox_members_controller.rb, app/controllers/api/v1/accounts/team_members_controller.rb, app/models/team.rb, app/policies/team_member_policy.rb, config/routes.rb, spec/controllers/api/v1/accounts/team_members_controller_spec.rb
=> chore: Update method for team members

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/mixins/specs/time.spec.js, app/javascript/dashboard/mixins/time.js, jest.config.js, jest.setup.js
This will be a temporary fix until #1556 is merged.
=> feat: Show date along with time in messages

app/models/account_user.rb, app/services/agents/destroy_service.rb, spec/models/account_user_spec.rb, spec/services/agents/destroy_service_spec.rb
- Remove user from teams on removing from accounts.
=> fix: Remove teams on account user destroy

app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
Fixes #1773 
**Describe the Fix**
Fixes url overflow issue on Webhook settings page.
=> Fixes link address overflow in webhook.

app/models/notification.rb, app/services/notification/push_notification_service.rb
=> chore: Fix push message tag error

app/controllers/api/v1/accounts/inboxes_controller.rb, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/store/modules/inboxes.js, app/javascript/widget/components/PreChat/Form.vue, app/javascript/widget/views/Home.vue, app/views/api/v1/models/_inbox.json.jbuilder, app/views/widget_tests/index.html.erb
=> feat: Add pre_chat_form_settings in inbox settings page

app/controllers/api/v1/widget/conversations_controller.rb, app/javascript/widget/components/PreChat/Form.vue
- Add validations based on conditions
- Update contact only if email present.
=> fix: Add validations dynamically

db/migrate/20210217154129_remove_orphan_inbox_members_from_inboxes.rb, db/schema.rb
Part of #1766, this PR is to clean up the existing data.
=> fix: Remove orphan members from inbox

app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue
Contact Form is tighly bound to edit modal which can be used in many other places in future
=> Chore: Refactor Edit contact modal to separate form

app/listeners/notification_listener.rb, app/models/notification.rb, app/views/api/v1/accounts/notifications/index.json.jbuilder, db/migrate/20210219085719_remove_old_notifications.rb, db/schema.rb, spec/models/notification_spec.rb
Clean up the notifications and change assigned_conver_new_message notifications' primary actor to message
=> chore: Notification cleanups

app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue, app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/CreateContact.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue, app/javascript/dashboard/store/modules/contacts/actions.js, app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js, app/javascript/shared/helpers/CustomErrors.js
- Adds create contact form in a model
=> Feat: Create contact from contacts page

app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
Fixes #1810  
Changes the dropdown UI to match the overall theme.
**After**
https://user-images.githubusercontent.com/64252451/108585004-af9e1580-736b-11eb-9bd7-07745e9e1235.mov
**Before**
https://user-images.githubusercontent.com/64252451/108585011-c2184f00-736b-11eb-8167-4fe3321ddc7e.mov
=> Enhancement: Changes the dropdown ui 

app/controllers/api/v1/accounts/inboxes_controller.rb, app/models/account.rb, app/models/concerns/out_of_offisable.rb, app/models/inbox.rb, app/models/working_hour.rb, app/services/message_templates/hook_execution_service.rb, app/views/api/v1/models/_inbox.json.jbuilder, db/migrate/20210222131048_change_working_hours_to_zero.rb, db/migrate/20210222131155_switch_time_zone_from_account_to_inbox.rb, db/schema.rb, lib/current.rb, spec/controllers/api/v1/accounts/inboxes_controller_spec.rb, spec/models/concerns/out_of_offisable_spec.rb, spec/services/message_templates/hook_execution_service_spec.rb
APIs to view and update business hours.
=> feat: Business hour Inbox APIs

app/controllers/widgets_controller.rb
Removing index method from Widget Controller as it is excluded from the routes.
Removing unused code.
=> Removing unused index method from Widget Controller

config/environments/production.rb, config/environments/staging.rb
fixes Log config env variable typecasting
=> fix: Log config env variable typecasting

app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/components/widgets/conversation/EmptyState.vue, app/javascript/dashboard/components/widgets/conversation/OnboardingView.vue, app/javascript/dashboard/i18n/locale/en/conversation.json
=> feat: Add a view to assist user while onboarding

app/javascript/dashboard/components/Modal.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/CreateContact.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue
=> feat: Update UI for edit contact modal

app/javascript/dashboard/i18n/locale/pt_BR/inboxMgmt.json
Fixing typo from "Confirgurações" to "Configurações"
=> chore: Fix inboxMgmt pt-BR locale typo

app/services/message_templates/hook_execution_service.rb, spec/services/message_templates/hook_execution_service_spec.rb
- Fix greeting messages not being sent
- Disable email collect when pre-chat is enabled
Fixes #1827 #1824
=> fix: greeting messages not sent

app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue, app/mailboxes/application_mailbox.rb, app/mailboxes/support_mailbox.rb, app/mailers/conversation_reply_mailer.rb, app/models/account.rb, app/models/channel/email.rb, app/presenters/mail_presenter.rb, app/views/api/v1/models/_inbox.json.jbuilder, config/features.yml, db/migrate/20210303192243_rename_channel_email_forward_address.rb, db/schema.rb, db/seeds.rb, spec/factories/channel/channel_email.rb, spec/mailboxes/application_mailbox_spec.rb, spec/mailers/conversation_reply_mailer_spec.rb
Enables email channel in chatwoot
=> chore: Enable email channel

app/mailers/application_mailer.rb
This will distinguish Chatwoot emails from other emails
Example - 
This does not show email is from Chatwoot.
If this makes sense, I will update other places where `account@chatwoot.com` is used without name.
=> Use name for the sender email id

app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
**Why**
Emoji box getting overlayed by recent changes to move header up the conversation box
=> Fix: emoji box not showing up

app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
Fixes #1880 
**After**
**Before**
=> Fix: Short code table width breaking

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
**Describe the issues**
Fixes user thumbnail padding related issue is conversations
**After**
**Before**
=> Fix: Conversation timestamp and thumbnail position issue

app/listeners/action_cable_listener.rb, app/models/concerns/assignment_handler.rb, app/models/concerns/round_robin_handler.rb, app/models/conversation.rb, config/locales/en.yml, lib/events/types.rb, spec/models/concerns/assignment_handler_spec.rb, spec/models/concerns/round_robin_handler_spec.rb, spec/models/conversation_spec.rb
- assignment messages when the conversation team is changed
- change assignee based on team
- move round-robin and assignee logic to concerns
=> feat: Activity messages for team assignments

.env.example, app/mailers/conversation_reply_mailer.rb, app/models/account.rb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/initializers/devise.rb, config/initializers/mailer.rb, spec/mailers/conversation_reply_mailer_spec.rb
=> chore: Make SMTP environment variables configurable

app/javascript/dashboard/components/layout/SidebarItem.vue, app/javascript/dashboard/helper/inbox.js, app/javascript/dashboard/helper/specs/inbox.spec.js
Added hover styles that matches overall UI
**After**
**Before**
=> chore: Added hover styles

config/initializers/mailer.rb
Fixes SMTP config sending empty auth 
#1903
=> chore: fix empty user_name. & password

config/initializers/mailer.rb
=> chore: fix smtp_domain mailer config

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, app/javascript/dashboard/helper/URLHelper.js, app/javascript/dashboard/helper/specs/URLHelper.spec.js, app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
=> fix: Use team conversationURL in team section

app/javascript/dashboard/helper/actionCable.js
=> Fix: Error when assigns a conversation to user

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
Fixes error reported on sentry
```
Cannot read property 'dataFetched' of undefined
```
=> Fix: Refactors error prone checks 

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/store/modules/conversations/getters.js, app/javascript/dashboard/store/modules/conversations/helpers.js, app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js, app/javascript/dashboard/store/modules/specs/conversations/helpers.spec.js
The conversations state wasn't filtering the inbox/label etc which would result in showing up unrelated conversations in chat-list.
=> Fix: sidebar filters not applying bug for chatlist 

app/javascript/dashboard/helper/actionCable.js, app/javascript/dashboard/routes/login/Login.vue
Fix error messages during login for non-verified users
Fixes #1915
Local + tests
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
=> Fix error messages during login for non-verified users

app/javascript/dashboard/routes/dashboard/conversation/labels/AddLabelToConversation.vue
=> Chore: Sort labels in conversation label edit modal

app/javascript/widget/components/ChatHeaderExpanded.vue, app/javascript/widget/components/TeamAvailability.vue, app/javascript/widget/i18n/locale/en.json
- Changes away message
- Border-radius for header logo
=> Chore: Change widget offline message

app/javascript/dashboard/components/widgets/conversation/Message.vue
=> fix: Revert quoted text styles

app/views/api/v2/accounts/reports/agents.csv.erb, config/locales/en.yml, config/locales/ml.yml
- Add missing translation for report title
=> fix: Add missing translations in agent reports

app/mailers/agent_notifications/conversation_notifications_mailer.rb, lib/local_resource.rb, lib/webhooks/trigger.rb, spec/lib/webhooks/trigger_spec.rb, spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
Reduce the timeout values for webhook requests
=> chore: Add timeouts to requests

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/SidemenuIcon.vue, app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
Fixes #1904 
**After**
https://user-images.githubusercontent.com/64252451/113275600-912d2180-92fc-11eb-949a-bf934cf0f6cb.mov
**Before**
=> Fixes: Responsive issue in chat list

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
Fixes #2033 
**After**
**Before**
=> Fixes: Reply box overflow issue

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue, yarn.lock
Fixes #2008 
Conversation overflow for text and email in bubbles and other responsive issues.
=> fix: Allow text overflow in a conversation for wide emails

app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
=> fix: Alert mixin in profile settings page

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Fixes #2058 
https://user-images.githubusercontent.com/64252451/113699837-b900f880-96f3-11eb-8935-345a948058f6.mov
=> Enhancement: Added hover effect for conversations

app/javascript/dashboard/components/layout/Sidebar.vue
Fixes #1757 
Changed the shouldShowInboxes function name to shouldShowSidebarItem.
=> chore: Refactors shouldShowInboxes to a generic name 

app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
Fixes #1908 
Adds a new button that redirects to the inbox config page after creating an inbox.
=> Enhancement: Adds a new button that redirect to inbox config page

README.md
- Adding huntr.dev badge to report security vulnerabilities
=> chore: Add huntr.dev badge

app/javascript/dashboard/assets/scss/plugins/_dropdown.scss
**Describe the fixes**
Fixes dropdown width issue in the Safari browser 
**After**
https://user-images.githubusercontent.com/64252451/114265820-8f581200-9a10-11eb-8796-f24dbccb5eaf.mov
**Before**
https://user-images.githubusercontent.com/64252451/114265784-5f107380-9a10-11eb-9f65-80b59abbe2bf.mov
=> Fix: Dropdown width issue in safari browser.

app/javascript/dashboard/store/modules/auth.js
=> fix: Type error in auth validity check action

app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Changes contact location country flag position.
=> Enhancement: Changes contact location flag position

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/components/widgets/conversation/Message.vue
Fixes responsive issue in activity message.
=> Enhancement: Responsive issue in activity message

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
**Describe the issue**
Order list number break issue in chat list. 
**After**
**Before**
=> Fixes: Order list number break issue

app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue, app/javascript/shared/helpers/Validators.js
**Why?**
Supporting validation for phone number added on backend.
=> Chore: Add validation for contact phone field

app/javascript/packs/application.js, package.json, yarn.lock
- v-tooltip version upgraded to latest
- Possible fix for #2106
=> Chore: Upgrade v-tooltip version

app/javascript/dashboard/components/buttons/ResolveAction.vue
**Describe the fixes**
Fixes the resolve button issue where it changes size when clicked upon
**After**
https://user-images.githubusercontent.com/64252451/115253032-a0f49480-a149-11eb-9506-048ddda01fe1.mov
**Before**
https://user-images.githubusercontent.com/64252451/115253073-a94ccf80-a149-11eb-8a3b-139e2b121e3a.mov
=> Chore:  fix the resolve button padding issue.

app/javascript/dashboard/routes/auth/ResetPassword.vue
=> chore: Update reset password error message

app/controllers/api/v1/accounts/inboxes_controller.rb, app/policies/inbox_policy.rb, app/views/api/v1/accounts/inboxes/assignable_agents.json.jbuilder, config/routes.rb, spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
new API  `inboxes/id/assignable_agents` returns all users that have permission to a conversation happening in that inbox.
=> feat: Assignable agents API

app/javascript/dashboard/i18n/index.js, app/javascript/dashboard/i18n/locale/no/index.js, app/javascript/dashboard/i18n/locale/zh_CN/index.js, app/javascript/widget/i18n/index.js, config/initializers/languages.rb, config/locales/devise.zh_CN.yml, config/locales/zh_CN.yml
- Enable the languages no, zh-CN, hu
=> chore: Enable the languages no, zh-CN, hu

app/javascript/dashboard/components/widgets/conversation/AvailabilityStatusBadge.vue, app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
=> Chore: Availability badge shape issue.

app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
**Describe the fixes**
Fixes no result text break issue in multi-select and availability badge spacing issue in contact details.
**After**
https://user-images.githubusercontent.com/64252451/115523232-7e2dc180-a2aa-11eb-861d-76b92c10b324.mov
**Before**
https://user-images.githubusercontent.com/64252451/115523265-8685fc80-a2aa-11eb-92bf-76cc1cb5c924.mov
=> Fixes: Text break issue in multiselect and availability badge spacing issue

app/javascript/dashboard/api/inboxes.js, app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/store/index.js, app/javascript/dashboard/store/modules/inboxAssignableAgents.js, app/javascript/dashboard/store/modules/inboxAssignableMembers.js, app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/actions.spec.js, app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/fixtures.js, app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/getters.spec.js, app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/mutations.spec.js
Adds Ability to assign administrators as conversation assignees
=> Enhancement: Ability to assign administrators as conversation assignees

app/javascript/dashboard/store/modules/conversations/helpers.js
Fixes #2124
Tested on local machine.
=> Fix: console error message when setting assigned team of contact to none

.storybook/preview.js, app/javascript/shared/store/globalConfig.js
- This will fix i18n translations giving errors
=> chore: Add i18n and components  into storybook

app/controllers/api/v1/accounts/campaigns_controller.rb, app/models/campaign.rb, app/views/api/v1/models/_campaign.json.jbuilder, db/migrate/20210430095748_add_camp_dp_id_seq_for_existing_accounts.rb, db/migrate/20210430100138_rename_campaign_content_to_message.rb, db/schema.rb, spec/controllers/api/v1/accounts/campaigns_controller_spec.rb, spec/factories/campaigns.rb
- Add migration for existing Accounts
=> chore: Campaign ID migration for existing accounts

package.json, yarn.lock
=> fix: Set babel/preset-env to 7.13.15

.storybook/main.js, app/javascript/dashboard/routes/dashboard/contacts/components/AddNote.stories.js, app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.stories.js
- Changed the stories path configuration
- Moved `AddNote` and `ContactNote` stories to relative to components
=> fix: Change storybook relative path

app/javascript/widget/components/Branding.vue
=> fix: Use full width for branding

app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
Fixes part of https://github.com/chatwoot/chatwoot/issues/1710#issuecomment-804015603
- Truncates and refactors to use better markup
**Before** 
**After**
=> fix: Truncates overlapping name in contact table

app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
=> fix: undefined WootButton in contact table

app/javascript/dashboard/modules/contact/components/ContactIntro.vue, app/javascript/dashboard/modules/contact/stories/ContactIntro.stories.js
- The variables are no more used
- Changes the story name in storybook
=> Chore: Removes unused impports in ContactIntro

.codeclimate.yml, app/javascript/dashboard/modules/contact/components/ContactAttribute.vue, app/javascript/dashboard/modules/contact/stories/ContactAttribute.stories.js, app/javascript/shared/components/EmojiOrIcon.vue
**On hover shows inline edit view**
=> feat: Add a component to display contact attributes in CRM

app/javascript/dashboard/assets/scss/_foundation-custom.scss, app/javascript/dashboard/assets/scss/_foundation-settings.scss, app/javascript/dashboard/components/widgets/Label.stories.js, app/javascript/dashboard/components/widgets/Label.vue
https://user-images.githubusercontent.com/64252451/117128683-5c106500-adbb-11eb-8b4f-6985dbdfa9c0.mov
=> Enhancement: Adds story for label component

Gemfile, Gemfile.lock, swagger/definitions/index.yml, swagger/definitions/request/team/create_update_payload.yml, swagger/definitions/resource/team.yml, swagger/index.html, swagger/index.yml, swagger/parameters/account_id.yml, swagger/parameters/index.yml, swagger/parameters/team_id.yml, swagger/paths/conversation/assignments.yml, swagger/paths/index.yml, swagger/paths/teams/create.yml, swagger/paths/teams/delete.yml, swagger/paths/teams/index.yml, swagger/paths/teams/show.yml, swagger/paths/teams/update.yml, swagger/swagger.json
- Added path parameter definitions for account_id, team_id
- Updated json_refs to latest
- Changed the version to "2.0" from 2.0 to fix the redoc error
- Changed the default redoc font to system / Helvetica Neue
- Added the definition for team model
- Added the definitions for team APIs
=> chore: Add API documentation for teams

app/controllers/widgets_controller.rb, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Api.vue, app/listeners/webhook_listener.rb, app/models/channel/api.rb, db/migrate/20210513083044_remove_not_null_from_webhook_url_channel_api.rb, db/schema.rb, spec/listeners/webhook_listener_spec.rb
- Remove restrictions on API Channel webhook URL
=> feat: Remove restrictions on API channel webhook_url

app/javascript/dashboard/api/inboxes.js, app/javascript/dashboard/api/specs/campaign.spec.js, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/components/Campaign.vue, app/javascript/dashboard/store/modules/campaigns.js, app/javascript/dashboard/store/modules/specs/campaigns/actions.spec.js
- Added inbox id in get campaigns api
=> chore: Add inbox id in get campaigns API

app/javascript/widget/components/UnreadMessage.vue, app/javascript/widget/i18n/locale/en.json, app/javascript/widget/views/Unread.vue
- Show sender name and company name in the first unread message
- Reduced the width of the unread message holder
**Before**
**![Screenshot 2021-05-17 at 8 34 49 PM](https://user-images.githubusercontent.com/12408980/118511243-909eed80-b6e6-11eb-8009-c68b1dd6a164.png)**
**After (Left position)**
**After (Right position)**
=> chore: Add sender details in unread message

app/javascript/widget/App.vue, app/javascript/widget/helpers/campaignHelper.js, app/javascript/widget/helpers/campaignTimer.js, app/javascript/widget/helpers/specs/campaignHelper.spec.js, app/javascript/widget/store/modules/campaign.js, app/javascript/widget/store/modules/specs/campaign/actions.spec.js, app/javascript/widget/store/modules/specs/campaign/getters.spec.js, app/javascript/widget/store/modules/specs/campaign/mutations.spec.js
- The campaign API call resulted in a loop if the campaigns were empty.
=> fix: Resolve infinite loop with campaign API call

app/views/api/v1/models/_app.json.jbuilder, app/views/api/v1/models/_hook.json.jbuilder, spec/controllers/api/v1/accounts/integrations/hooks_controller_spec.rb, swagger/definitions/index.yml, swagger/definitions/request/integrations/hook_create_payload.yml, swagger/definitions/request/integrations/hook_update_payload.yml, swagger/definitions/resource/integrations/app.yml, swagger/definitions/resource/integrations/hook.yml, swagger/definitions/resource/team.yml, swagger/parameters/hook_id.yml, swagger/parameters/index.yml, swagger/parameters/team_id.yml, swagger/paths/contact/conversations.yml, swagger/paths/contact/crud.yml, swagger/paths/contact_inboxes/create.yml, swagger/paths/conversation/update_last_seen.yml, swagger/paths/index.yml, swagger/paths/integrations/apps/show.yml, swagger/paths/integrations/hooks/create.yml, swagger/paths/integrations/hooks/delete.yml, swagger/paths/integrations/hooks/update.yml, swagger/paths/teams/show.yml, swagger/swagger.json
docs: Adds documentation for Integration APIs
=> docs: Adds documentation for Integration APIs

app/javascript/dashboard/assets/scss/_foundation-settings.scss, app/javascript/dashboard/routes/dashboard/contacts/components/AddNote.vue
- Reduces styles
- Uses existing classes
=> Chore: Refactor add note component to use foundation card

app/javascript/dashboard/assets/scss/_foundation-custom.scss, app/javascript/dashboard/assets/scss/_foundation-settings.scss, app/javascript/dashboard/routes/dashboard/contacts/components/AddNote.vue, app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
- Reduces css code
- Reuses card component
=> Chore: Refactors view note component

docker-compose.production.yaml
=> fix: Broken Docker production config

app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
- This is a side of the recent button refactor PR
=> Chore: Fixes style issue of webhook button

app/javascript/packs/application.js, package.json, yarn.lock
- Upgrade sentry to the latest version
- Add tracing
=> chore: Upgrade @sentry/vue to 6.4.1

app/javascript/dashboard/components/ui/Label.vue, app/javascript/shared/components/ui/dropdown/AddLabel.vue
**Why**
The current add label uses button which doesn't match the label size.
**After**
=> fix: Uses label component for add label button

app/javascript/dashboard/assets/scss/_woot.scss, app/javascript/dashboard/components/widgets/InboxListItem.vue, app/javascript/dashboard/components/widgets/WootWriter/Editor.vue, app/javascript/dashboard/constants.js, app/javascript/dashboard/helper/APIHelper.js, app/javascript/dashboard/helper/actionCable.js, app/javascript/dashboard/routes/auth/Confirmation.vue, app/javascript/dashboard/routes/auth/PasswordEdit.vue, app/javascript/dashboard/routes/auth/ResetPassword.vue, app/javascript/dashboard/routes/auth/Signup.vue, app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/New.vue, app/javascript/dashboard/routes/index.js, app/javascript/dashboard/routes/index.spec.js, app/javascript/dashboard/store/modules/auth.js, app/javascript/shared/helpers/BaseActionCableConnector.js, app/views/layouts/vueapp.html.erb
- Use chatwootConfig to set baseURL and webSocketURL
- Fix redirects, set default path as /app
- Move prosemirror CSS import to the component.
=> chore: Adjust Chatwoot Config to deploy frontend as a separate app

app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
=> fix: Update the translation key for Custom Attributes

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
=> fix: Retain focus after sending message in rich content editor

app/javascript/shared/assets/stylesheets/colors.scss
=> chore: Adds new color shades and tints for violet

app/javascript/dashboard/components/index.js, app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/i18n/locale/en/teamsSettings.json, app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue, app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
=> feat: Ask to confirm with name before inbox/team deletion

swagger/parameters/index.yml, swagger/parameters/platform_user_id.yml, swagger/paths/index.yml, swagger/swagger.json
- Add missing definition for user id
=> fix: Add swagger definition for platform_user_id

app/controllers/api/v1/accounts/conversations_controller.rb, spec/controllers/api/v1/accounts/conversations_controller_spec.rb, spec/controllers/api/v1/profiles_controller_spec.rb, swagger/paths/conversation/index_or_create.yml, swagger/swagger.json
=> chore: Improvements in conversation APIs

app/controllers/dashboard_controller.rb, app/javascript/dashboard/assets/scss/views/settings/channel.scss, app/javascript/dashboard/components/widgets/ChannelItem.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue, app/javascript/shared/store/globalConfig.js, config/installation_config.yml
Use `API_CHANNEL_NAME` and `API_CHANNEL_THUMBNAIL`
=> chore: Configure channel name and thumbnail

app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.stories.js, app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
=> chore: Cleans up style for contact note

app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
=> enhancement: Ability to edit inbox name

app/javascript/dashboard/assets/scss/views/settings/inbox.scss, app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/widgets/SettingIntroBanner.stories.js, app/javascript/dashboard/components/widgets/SettingIntroBanner.vue, app/javascript/dashboard/components/widgets/SettingsHeader.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/components/AddCampaign.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
=> chore: Cleanup page-top-bar style conflicts

app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Website.vue
=> fix: Add missing translation in inbox settings page

app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
https://user-images.githubusercontent.com/64252451/121634736-bc718100-caa2-11eb-85b5-4c5331b61b53.mov
Fixes https://github.com/chatwoot/chatwoot/issues/1257
=> feat: Add assign to me button next to assign agents.

app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
**Why**
Scroller for contact panel in contacts page was not showing up
=> chore: Fixes contact panel scroll issue

.storybook/preview.js, app/javascript/dashboard/assets/scss/plugins/_multiselect.scss, app/javascript/dashboard/assets/scss/storybook.scss
**Why**
- This will make it possible to use multiselect in stories
=> chore: Adds support for  multiselect in stories

app/models/inbox.rb, db/migrate/20210618095823_add_csat_toggle_for_inbox.rb, db/schema.rb
Add CSAT survey toggle for Inboxes 
ref: #1890
=> chore: CSAT survey attribute for Inboxes

app/controllers/api/v1/accounts/contacts_controller.rb, app/javascript/dashboard/api/contacts.js, app/javascript/dashboard/api/specs/contacts.spec.js, app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/SidebarItem.vue, app/javascript/dashboard/i18n/default-sidebar.js, app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/i18n/locale/en/settings.json, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue, app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue, app/javascript/dashboard/routes/dashboard/contacts/routes.js, app/javascript/dashboard/routes/dashboard/settings/labels/specs/validationMixin.spec.js, app/javascript/dashboard/routes/dashboard/settings/labels/validationMixin.js, app/javascript/dashboard/store/modules/contacts/actions.js, lib/redis/config.rb, spec/controllers/api/v1/accounts/contacts_controller_spec.rb
- Add a filter for the label on contacts.
- Add a view on the UI to filter contacts by a label.
=> feat: Add contact label filter

app/javascript/dashboard/components/widgets/conversation/Message.vue
=> chore: Disable tooltip for sender in bot messages

app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
=> chore: Refined attachments preview

app/models/account.rb, app/models/contact.rb, app/models/inbox.rb, app/models/note.rb, app/models/user.rb, db/migrate/20210618073042_create_notes.rb, db/schema.rb, spec/factories/notes.rb, spec/models/note_spec.rb
- Added contact note model, test cases
=> chore: Add contact note model

app/javascript/widget/components/Form/Input.stories.js
=> chore: Adds storybook for woot input

.codeclimate.yml, app/javascript/dashboard/i18n/locale/en/csatMgmt.json, app/javascript/dashboard/i18n/locale/en/index.js, app/javascript/shared/components/CustomerSatisfaction.stories.js, app/javascript/shared/components/CustomerSatisfaction.vue, app/javascript/shared/constants/messages.js, app/javascript/widget/components/AgentMessageBubble.vue, app/javascript/widget/i18n/locale/en.json, app/models/message.rb, db/seeds.rb, lib/woot_message_seeder.rb
=> feat: Add customer satisfaction component

app/models/inbox.rb, app/services/message_templates/hook_execution_service.rb, app/services/message_templates/template/csat_survey.rb, config/locales/en.yml, spec/services/message_templates/hook_execution_service_spec.rb, spec/services/message_templates/template/csat_survey_spec.rb
Triggers CSAT Survey Messages when a conversation is resolved for inboxes where CSAT is enabled.
fixes: #2470
=> feat: Add CSAT Message Template Hooks 

app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
=> feat: Adds inbox info to previous conversations

app/controllers/api/v1/widget/messages_controller.rb, app/javascript/shared/components/CustomerSatisfaction.vue, app/javascript/shared/constants/messages.js, app/javascript/widget/components/AgentMessage.vue, app/javascript/widget/components/AgentMessageBubble.vue, app/javascript/widget/i18n/locale/en.json
=> feat: Add CSAT response submit actions

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/helpers/EmailContentParser.js, app/javascript/dashboard/components/widgets/conversation/helpers/specs/EmailContentParser.spec.js
- Remove `<style>` tag 
- Remove `style="`
=> fix: Remove style tags from email content

app/helpers/message_format_helper.rb, app/models/notification.rb, config/locales/en.yml, lib/regex_helper.rb, spec/helpers/message_format_helper_spec.rb, spec/models/notification_spec.rb
=> chore: Change the notification text for mention notification type

app/controllers/api/v1/accounts/custom_filters_controller.rb, app/models/account.rb, app/models/custom_filter.rb, app/models/user.rb, app/views/api/v1/accounts/custom_filters/create.json.jbuilder, app/views/api/v1/accounts/custom_filters/index.json.jbuilder, app/views/api/v1/accounts/custom_filters/show.json.jbuilder, app/views/api/v1/accounts/custom_filters/update.json.jbuilder, app/views/api/v1/models/_custom_filter.json.jbuilder, config/routes.rb, db/migrate/20201123195011_create_platform_apps.rb, db/migrate/20210623150613_create_custom_filters.rb, db/schema.rb, spec/controllers/api/v1/accounts/custom_filters_controller_spec.rb, spec/factories/custom_filters.rb, swagger/definitions/index.yml, swagger/definitions/request/custom_filter/create_update_payload.yml, swagger/definitions/resource/custom_filter.yml, swagger/index.yml, swagger/parameters/custom_filter_id.yml, swagger/parameters/index.yml, swagger/paths/custom_filters/create.yml, swagger/paths/custom_filters/delete.yml, swagger/paths/custom_filters/index.yml, swagger/paths/custom_filters/show.yml, swagger/paths/custom_filters/update.yml, swagger/paths/index.yml, swagger/swagger.json
- Add a model to save custom filters
- Add APIs to save/list/update/destroy custom filter
- Add specs for the controller APIs
- Add documentation for the controller APIs.
=> feat: Add APIs to create custom views on the dashboard

app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/shared/assets/stylesheets/colors.scss
Fixes #1219 
https://user-images.githubusercontent.com/64252451/123906807-779a8500-d992-11eb-8a3c-f6d61aae24e4.mov
=> feat: Adds drag and drop for images/files in the agent input box

app/javascript/shared/components/CustomerSatisfaction.vue
=> chore: Change behaviour of CSAT submit actions

app/javascript/shared/components/CustomerSatisfaction.vue, app/javascript/widget/components/AgentMessageBubble.vue, app/javascript/widget/components/template/EmailInput.vue, app/models/contact.rb
=> chore: Add loader for email and csat submit buttons

app/javascript/dashboard/components/widgets/conversation/Message.vue
=> bug: Fixes alignment issue with deleted messages

app/javascript/dashboard/assets/scss/views/settings/channel.scss, app/javascript/dashboard/components/widgets/ChannelItem.vue, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/InboxChannels.vue
| Mobile | Medium devices | Large devices
| -- | -- | -- |
| <img width="450" alt="Screenshot 2021-07-13 at 5 35 46 PM" src="https://user-images.githubusercontent.com/2246121/125448703-3b399b46-abec-4f1f-85d6-99b943e94b6b.png"> | <img width="968" alt="Screenshot 2021-07-13 at 5 36 19 PM" src="https://user-images.githubusercontent.com/2246121/125448738-c45a4f4d-6adf-4325-8737-4e6a55cef5db.png"> | <img width="1440" alt="Screenshot 2021-07-13 at 5 36 52 PM" src="https://user-images.githubusercontent.com/2246121/125448818-d439dd00-5f78-4f91-8905-c8941881b09f.png"> |
=> fix: Update styles to fix the image resolution on smaller devices

app/javascript/dashboard/components/widgets/conversation/Message.vue
=> fix: Disable sender tooltip and copy button in deleted messages

app/mailboxes/support_mailbox.rb, app/presenters/mail_presenter.rb
- Use mail.decoded unless multipart
- Use ActiveRecord transaction for email conversation creating
Fixes #2601, #2418, #2367
=> fix: Improve mail content parsing

app/javascript/dashboard/components/widgets/conversation/Message.vue
Use fallback for HTML only emails.
=> fix: Fix HTML only email rendering

app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
=> fix: Update attribute name to conversationsCount

app/finders/conversation_finder.rb, app/models/conversation.rb, app/views/api/v1/accounts/conversations/index.json.jbuilder, app/views/api/v1/accounts/conversations/meta.json.jbuilder, config/schedule.yml, spec/controllers/api/v1/accounts/conversations_controller_spec.rb, spec/finders/conversation_finder_spec.rb
=> chore: Add assigned_count to conversation APIs

app/controllers/api/v1/widget/base_controller.rb, app/controllers/api/v1/widget/campaigns_controller.rb, app/controllers/api/v1/widget/configs_controller.rb, app/controllers/api/v1/widget/inbox_members_controller.rb, app/controllers/widgets_controller.rb, app/views/api/v1/widget/configs/create.json.jbuilder, config/routes.rb, spec/controllers/api/v1/widget/configs_controller_spec.rb
- APIs exposing widget config so that we can decouple the widget UI
=> chore: Expose widget config via an API

app/controllers/api/v1/accounts/conversations_controller.rb, app/javascript/dashboard/components/buttons/ResolveAction.vue, app/javascript/dashboard/constants.js, app/javascript/dashboard/i18n/locale/en/chatlist.json, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/widget/store/modules/specs/conversationAttributes/actions.spec.js, app/javascript/widget/store/modules/specs/conversationAttributes/getters.spec.js, app/javascript/widget/store/modules/specs/conversationAttributes/mutations.spec.js, app/listeners/notification_listener.rb, app/models/conversation.rb, config/locales/en.yml, lib/integrations/dialogflow/processor_service.rb, spec/controllers/api/base_controller_spec.rb, spec/controllers/api/v1/accounts/conversations_controller_spec.rb, spec/lib/integrations/dialogflow/processor_service_spec.rb, spec/models/concerns/round_robin_handler_spec.rb, spec/models/conversation_spec.rb, swagger/definitions/resource/conversation.yml, swagger/paths/conversation/create.yml, swagger/paths/conversation/index.yml, swagger/paths/conversation/toggle_status.yml, swagger/swagger.json
=> chore: Change the `bot` status to `pending`

deployment/setup_20.04.sh
- Switch from `addgroup` to `adduser` for linux installation script
- Tested on a linux vm
=> chore: switch from addgroup to adduser

app/controllers/api/v1/accounts/contacts_controller.rb, app/finders/conversation_finder.rb, app/javascript/dashboard/api/contacts.js, app/javascript/dashboard/api/specs/contacts.spec.js, app/models/contact.rb, app/models/conversation.rb, app/views/api/v1/accounts/contacts/index.json.jbuilder, app/views/api/v1/accounts/contacts/search.json.jbuilder, app/views/api/v1/models/_team.json.jbuilder, db/migrate/20210723094412_add_index_to_conversations.rb, db/migrate/20210723095657_add_index_to_contacts.rb, db/schema.rb, spec/controllers/api/v1/accounts/contacts_controller_spec.rb
- Add index on conversations/contacts
- Remove contact_inboxes payload from UI
=> chore: Improve search, list performance of contact/conversation APIs

app/javascript/dashboard/i18n/locale/de/conversation.json, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
Just a simple translation addition. 
No tests - but did a successfull heroku deploy :-)
=> feat: Make "Search Results" in PopOverSearch translateable

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Added undefined & null check for the message before it's being used for trim
reference: https://sentry.io/share/issue/579a99050bc84a24b92ef6f31ece11fb/
=> Fix: type error trim of undefined#2595

.env.example, .rubocop.yml, Gemfile, Gemfile.lock, config/initializers/01_redis.rb, config/initializers/rack_attack.rb
Add `rack-attack` to block and throttle abusive requests
ref: https://github.com/rack/rack-attack/issues/399
https://github.com/rack/rack-attack/issues/102
=> chore: Block & throttle abusive requests

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/bubble/MailHead.vue, app/javascript/dashboard/i18n/locale/en/conversation.json
- Shows CC, Bcc, To for mail bubbles
=> feat: show mail meta data for conversations

app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
=> enhancemnet: Show links for custom attributes

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
- Avoid flickering while updating the view.
=> fix: Avoid flicker while updating the view with new messages

README.md, SECURITY.md
Updates to chatwoot Vulnerability Disclosure Program guidelines.
- Define out of scope issues
n/a
=> docs: update chatwoot VDP guidelines

app/javascript/shared/components/CustomerSatisfaction.vue
=> fix: Add brand color in csat card component

app/javascript/dashboard/i18n/locale/fi/agentMgmt.json, app/javascript/dashboard/i18n/locale/fi/campaign.json, app/javascript/dashboard/i18n/locale/fi/chatlist.json, app/javascript/dashboard/i18n/locale/fi/contact.json, app/javascript/dashboard/i18n/locale/fi/conversation.json, app/javascript/dashboard/i18n/locale/fi/csatMgmt.json, app/javascript/dashboard/i18n/locale/fi/generalSettings.json, app/javascript/dashboard/i18n/locale/fi/inboxMgmt.json, app/javascript/dashboard/i18n/locale/fi/integrationApps.json, app/javascript/dashboard/i18n/locale/fi/login.json, app/javascript/dashboard/i18n/locale/fi/report.json, app/javascript/dashboard/i18n/locale/fi/settings.json, app/javascript/dashboard/i18n/locale/fi/teamsSettings.json, app/javascript/widget/i18n/locale/fi.json, config/locales/fi.yml
Translated rest of the finnish language
Issue #2752 
Just changed the language to Finnish
=> Fix finnish language

app/services/twilio/oneoff_sms_campaign_service.rb, app/services/twilio/send_on_twilio_service.rb
=> Fix: Twilio messages not get sent

README.md
- add questions sub-section and mention discord
- improve formatting
n/a
=> docs: Update README to add question/support sub-section

app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue, app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
Fixes #2742 
**Before**
https://user-images.githubusercontent.com/64252451/128664168-98a16d62-394c-4a2f-9aba-1863bcbfba90.mov
**After**
https://user-images.githubusercontent.com/64252451/128664185-a54d81bc-b188-49f8-a1ac-5012a26e93a8.mov
=> chore: fixes text retain issue in confirm delete modal

app/javascript/shared/components/ui/MultiselectDropdown.vue
=> fix: Reduces spacing for custom drop-downs

app/controllers/api/v1/accounts/contacts_controller.rb, lib/exception_list.rb, spec/controllers/api/v1/accounts/contacts_controller_spec.rb, swagger/definitions/request/contact/create.yml, swagger/definitions/request/contact/update.yml, swagger/paths/contact/search.yml, swagger/swagger.json
- Verify the usage of identifiers across contact APIs
- Update swagger doc
=> chore: Ability to create contact with identifiers

app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
Fix for - https://sentry.io/share/issue/dcecadd36fbb4bbab9a11199bb0e8147/
- Checks for type of value before parsing 
- Now supports object/array and number along with string
- Displays undefined and null as undefined and null
=> fix: Fixes parsing issue with custom attributes

app/javascript/shared/components/ui/dropdown/DropdownMenu.vue
Fixes: #2795
This PR also refactors code
=> fix: Fixes error when dropdown button is focused

app/actions/contact_identify_action.rb, app/controllers/api/v1/widget/contacts_controller.rb, app/javascript/widget/store/modules/contacts.js, app/views/widget_tests/index.html.erb, spec/actions/contact_identify_action_spec.rb
Set phone_number through Website SDK
Fixes #2599
Test case in contact_identify_action_spec.rb
=> Set phone_number through Website SDK

app/javascript/dashboard/assets/scss/super_admin/index.scss, app/views/installation/onboarding/index.html.erb
This makes the description text for the "Subscribe to updates" checkbox on the onboarding page clickable and is semantically more correct.
Tested locally
=> fix: Use label for "Subscribe to updates" checkbox

app/javascript/shared/components/ui/dropdown/DropdownMenu.vue
* Remove the focus of the first item in the dropdown when the dropdown is active.
**Before**
https://user-images.githubusercontent.com/64252451/129515724-ae6f7ab7-ef54-41a0-932e-c27c70dbd101.mov
**After**
https://user-images.githubusercontent.com/64252451/129515690-45cbf6b2-b976-4788-b742-9060f58a15e3.mov
=> enhancement: Removes the focus of the first item in the dropdown when active

README.md
- add uptime and response time badges
n/a
=> feat: add uptime and response time badges

app/models/custom_attribute_definition.rb, db/migrate/20210824152852_add_description_to_custom_attribute_definition.rb, db/schema.rb
=> chore: Add `description` column in custom attribute model

app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
Fixes the email for conversation mentions style.
Fixes #2825 
Tested on local with a letter opener. And Via test cases.
=> Fix: 2825 Email conversation mention style fix

app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
=> fix: Disable "none" option from team dropdown If team is not selected 

swagger/paths/conversation/messages/create_attachment.yml, swagger/swagger.json
Update param name to `attachments[]`
=> fix: Update param name for attachments

app/javascript/widget/api/endPoints.js, app/javascript/widget/api/events.js, app/javascript/widget/api/specs/endPoints.spec.js
- Add missing referer, initiated_at.timestamp to the campaign/webwidget.triggered events.
=> fix: Add missing referer & initiated_at.timestamp to events

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
This change adds an attachment button for email conversations. So that users can add attachments to their conversations.
Fixes #2165
Verified the uploaded attachment using the LETTER_OPENER environment variable.
=> enhancement: Add attachment button for email conversation

lib/exception_list.rb
=> fix: Handle more rest client exceptions

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
**What does this pr fix**
When we send message from dashboard there's small jumping issue which is caused by the styles being not considered for the unread toast item.
**Before**
https://user-images.githubusercontent.com/1277421/131547092-90b418ac-8173-4830-b41f-988b166347a8.mov
**After**
https://user-images.githubusercontent.com/1277421/131546750-dd81cbc3-1eef-4f45-9a7e-c50d73104fcb.mov
=> fix: Fixes messages jumping issue for newly created message

app/builders/notification_subscription_builder.rb
- Update refreshed FCM token in notification subscription
=> fix: Notification subscription update 

app/javascript/widget/components/ChatHeaderExpanded.vue
|Before|After|
|--|--|
| <img width="461" alt="Screenshot 2021-09-06 at 12 55 46 AM" src="https://user-images.githubusercontent.com/2246121/132139003-16d0b8d6-2a13-4069-bf94-b842f4f7c585.png"> | <img width="451" alt="Screenshot 2021-09-06 at 12 51 32 AM" src="https://user-images.githubusercontent.com/2246121/132139013-81396549-4f37-4a81-83b4-147e016abe08.png"> |
=> fix: Update actions position if avatar image is unavailable

app/javascript/survey/components/Feedback.vue, app/javascript/survey/components/Rating.vue, app/javascript/survey/i18n/locale/en.json, app/javascript/survey/views/Response.vue, app/views/public/api/v1/models/_csat_survey.json.jbuilder
| -- | -- |
| <img width="1440" alt="Screenshot 2021-09-06 at 2 12 00 AM" src="https://user-images.githubusercontent.com/2246121/132140883-e6ae8505-1583-42f2-b757-cfd848fbac7a.png"> <img width="1440" alt="Screenshot 2021-09-06 at 2 12 10 AM" src="https://user-images.githubusercontent.com/2246121/132140884-c3ec07ba-7c5b-4bf7-bac8-d3bafcf48430.png"> | <img width="1438" alt="Screenshot 2021-09-06 at 2 00 14 AM" src="https://user-images.githubusercontent.com/2246121/132140876-1ad471ee-c278-4be3-9b76-268bb3520838.png"> <img width="1438" alt="Screenshot 2021-09-06 at 2 00 29 AM" src="https://user-images.githubusercontent.com/2246121/132140879-e1c68940-00fc-47de-9318-c20e69b3ef79.png"> |
=> feat: Update design - CSAT survey page

app/javascript/dashboard/components/Accordion/AccordionItem.vue
Fixes duplicate emit event in the accordion item component.
=> fix: Remove duplicate emit event

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/services/twilio/send_on_twilio_service.rb, spec/services/twilio/send_on_twilio_service_spec.rb
Send MMS message to customer for Twilio integration inbox.
Fixes #2311 
1. Able to attach a file
2. Able to receive the file at the configured phone number.
=> feat: Send MMS through Twilio Inbox

app/controllers/dashboard_controller.rb, app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue, app/javascript/dashboard/helper/scriptHelpers.js, app/javascript/dashboard/store/modules/auth.js, app/javascript/dashboard/store/utils/api.js, app/javascript/packs/application.js, app/views/devise/token.json.jbuilder, app/views/layouts/vueapp.html.erb, config/installation_config.yml, package.json, yarn.lock
This PR introduces Chatwoot inside Chatwoot and PostHog as an analytics provider.
- This would not affect any Self-hosted installations, the SDK gets initialized only if the token and set in InstallationConfig.
=> feat: Configure Chatwoot & Analytics for SaaS app

app/javascript/dashboard/i18n/locale/ar/chatlist.json, app/javascript/dashboard/i18n/locale/cs/chatlist.json, app/javascript/dashboard/i18n/locale/el/chatlist.json, app/javascript/dashboard/i18n/locale/fa/chatlist.json, app/javascript/dashboard/i18n/locale/nl/chatlist.json, app/javascript/dashboard/i18n/locale/pl/chatlist.json, app/javascript/dashboard/i18n/locale/pt/chatlist.json, app/javascript/dashboard/i18n/locale/pt_BR/chatlist.json, app/javascript/dashboard/i18n/locale/ru/chatlist.json, app/javascript/dashboard/i18n/locale/th/chatlist.json, app/javascript/dashboard/i18n/locale/zh/chatlist.json, app/javascript/dashboard/i18n/locale/zh_TW/chatlist.json
- Revert values to actual values.
=> fix: Revert translated values in CHAT_STATUS_ITEMS

app/javascript/dashboard/components/widgets/conversation/OnboardingView.vue
- Update changelog URL to `https://www.chatwoot.com/changelog`
=> chore: Update Changelog URL

Gemfile, Gemfile.lock, spec/controllers/devise/session_controller_spec.rb
Strong password characters included with the new fork here https://github.com/chatwoot/devise-secure_password
Fixes #2919 
Tested on local with the new password update with the new extra characters.
=> chore: Support for special characters in password

app/jobs/webhooks/facebook_events_job.rb, config/initializers/facebook_messenger.rb, lib/integrations/facebook/message_creator.rb, lib/integrations/facebook/message_parser.rb, spec/builders/messages/facebook/message_builder_spec.rb, spec/factories/facebook_message/incoming_fb_text_message.rb, spec/jobs/webhooks/facebook_events_job_spec.rb
- Move Facebook event processing to worker
=> chore: Move Facebook event processing to worker

app/javascript/dashboard/components/widgets/LabelSelector.vue, app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/mixins/specs/uiSettings.spec.js, app/javascript/dashboard/mixins/uiSettings.js, app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
Fixes #2973 
- Use accordion in the sidebar.
- Move sidebar toggle to mixins.
=> chore: Update contact sidebar with accordion

package.json, yarn.lock
Upgrades vue router to the latest version (v3.5.2 as of now)
Fixes #1815 
=> chore: Upgrade vue router to the latest version

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue, app/javascript/dashboard/i18n/locale/en/chatlist.json, app/javascript/shared/mixins/messageFormatterMixin.js
Fixes https://github.com/chatwoot/chatwoot/issues/2009
Fixes https://github.com/chatwoot/chatwoot/issues/2365
=> fix: Hide quoted replies by default from messages

app/javascript/dashboard/i18n/locale/it/chatlist.json
- Revert keys getting translated
=> fix: Revert key changes in `it` translation files

deployment/setup_18.04.sh, deployment/setup_20.04.sh
- to align with other installation env values
n/a
=> chore: Update installation env value for linux script

app/controllers/super_admin/dashboard_controller.rb, app/services/telegram/incoming_message_service.rb, app/views/super_admin/dashboard/index.html.erb, spec/services/telegram/incoming_message_service_spec.rb
=> Chore: Release Fixes

app/controllers/api/v1/accounts/inboxes_controller.rb, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/shared/mixins/inboxMixin.js, app/models/inbox.rb, app/services/line/incoming_message_service.rb, app/views/api/v1/models/_inbox.json.jbuilder, spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
=> chore: API fixes

app/builders/messages/facebook/message_builder.rb, app/javascript/dashboard/components/layout/SidebarItem.vue, app/javascript/dashboard/helper/inbox.js, app/javascript/shared/mixins/inboxMixin.js, app/jobs/contact_ip_lookup_job.rb, config/initializers/rack_attack.rb, lib/integrations/dialogflow/processor_service.rb, lib/integrations/slack/send_on_slack_service.rb
- sidebar icons for line and telegram inboxes
- sentry fix for contact IP lookup job
=> chore: Sidebar icons for new inboxes

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/buttons/ResolveAction.vue, app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/SidebarItem.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/sdk/sdk.js, app/javascript/shared/mixins/eventListenerMixins.js
- Reject keyboard shortcut listeners if an input box is active
=> fix: Reject keyboard shortcut listeners if input box is active

app/builders/messages/facebook/message_builder.rb, app/models/inbox.rb, app/views/api/v1/models/_inbox.json.jbuilder
- Return medium attribute in inbox APIs
=> chore: Return medium in inbox APIs

app/javascript/dashboard/i18n/locale/ca/inboxMgmt.json, app/javascript/dashboard/i18n/locale/cs/inboxMgmt.json, app/javascript/dashboard/i18n/locale/da/inboxMgmt.json, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/i18n/locale/fi/inboxMgmt.json, app/javascript/dashboard/i18n/locale/he/inboxMgmt.json, app/javascript/dashboard/i18n/locale/hi/inboxMgmt.json, app/javascript/dashboard/i18n/locale/it/inboxMgmt.json, app/javascript/dashboard/i18n/locale/ja/inboxMgmt.json, app/javascript/dashboard/i18n/locale/ml/inboxMgmt.json, app/javascript/dashboard/i18n/locale/ne/inboxMgmt.json, app/javascript/dashboard/i18n/locale/nl/inboxMgmt.json, app/javascript/dashboard/i18n/locale/no/inboxMgmt.json, app/javascript/dashboard/i18n/locale/ro/inboxMgmt.json, app/javascript/dashboard/i18n/locale/sk/inboxMgmt.json, app/javascript/dashboard/i18n/locale/sv/inboxMgmt.json, app/javascript/dashboard/i18n/locale/ta/inboxMgmt.json, app/javascript/dashboard/i18n/locale/th/inboxMgmt.json, app/javascript/dashboard/i18n/locale/tr/inboxMgmt.json, app/javascript/dashboard/i18n/locale/uk/inboxMgmt.json, app/javascript/dashboard/i18n/locale/vi/inboxMgmt.json, app/javascript/dashboard/i18n/locale/zh_CN/inboxMgmt.json
=> fix: Update title for `out of office message`

app/services/message_templates/hook_execution_service.rb, spec/services/message_templates/hook_execution_service_spec.rb
=> fix: Outbound messages triggering out of office

app/services/telegram/incoming_message_service.rb
Unused memoization (account) in telegram incoming service removed.
Run all the tests cases using RSpec.
=> Chores: Refactoring unused memoization in telegram services removed

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/store/modules/conversations/actions.js
Fixes #2928 
It can be tested by attaching an unsupported file like SVG by drag and drop and sent it.
=> bug: Adds meaningful alert error message if file upload fails

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/shared/components/emoji/EmojiInput.vue
Fixes #3045  #3118 
**Browser info**
Can be tested on iPad pro & Safari
=> fixes: Reply box goes hidden and emoji input header section is broken.

app/builders/v2/report_builder.rb, app/javascript/dashboard/api/reports.js, app/javascript/dashboard/api/specs/reports.spec.js, app/javascript/dashboard/helper/downloadCsvFile.js, app/javascript/dashboard/helper/specs/downloadCsvFile.spec.js, app/javascript/dashboard/i18n/locale/en/report.json, app/javascript/dashboard/i18n/locale/en/settings.json, app/javascript/dashboard/i18n/sidebarItems/reports.js, app/javascript/dashboard/routes/dashboard/settings/reports/TeamReports.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue, app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js, app/javascript/dashboard/store/modules/reports.js, app/javascript/dashboard/store/modules/specs/reports/actions.spec.js, spec/builders/v2/report_builder_spec.rb
Adds ability to get reports for teams.
Fixes #3058 
1. Tested locally by creating teams and assigning agents to them.
2. Test cases for Vuex actions and File download helpers.
=> feat: Add Reports for teams

app/controllers/api/v1/accounts/conversations_controller.rb, app/javascript/dashboard/api/inbox/conversation.js, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/store/modules/conversationTypingStatus.js, app/javascript/widget/helpers/actionCable.js, app/listeners/action_cable_listener.rb, spec/controllers/api/v1/accounts/conversations_controller_spec.rb, spec/controllers/api/v1/widget/conversations_controller_spec.rb, spec/listeners/action_cable_listener_spec.rb
=> Added private flag for typing indicator status

app/javascript/dashboard/i18n/locale/ar/chatlist.json, app/javascript/dashboard/i18n/locale/cs/chatlist.json, app/javascript/dashboard/i18n/locale/el/chatlist.json, app/javascript/dashboard/i18n/locale/fa/chatlist.json, app/javascript/dashboard/i18n/locale/nl/chatlist.json, app/javascript/dashboard/i18n/locale/pl/chatlist.json, app/javascript/dashboard/i18n/locale/pt/chatlist.json, app/javascript/dashboard/i18n/locale/pt_BR/chatlist.json, app/javascript/dashboard/i18n/locale/ru/chatlist.json, app/javascript/dashboard/i18n/locale/th/chatlist.json, app/javascript/dashboard/i18n/locale/tr/chatlist.json, app/javascript/dashboard/i18n/locale/zh_TW/chatlist.json
Revert keys gettings translated
=> fix: Revert translated keys in conversation status

app/controllers/api/v1/widget/contacts_controller.rb, spec/controllers/api/v1/widget/contacts_controller_spec.rb
Add missing condition checking if hmac is mandatory.
Fixes #3349
Added specs
=> fix: Add missing condition checking if hmac is mandatory

lib/global_config_service.rb
fix: make GlobalConfig migrated from .env editable from UI
- Tested locally. Created a config using this method and verified it is editable from super admin UI.
=> fix: make GlobalConfig migrated from .env editable from UI

app/services/filter_service.rb, lib/filters/filter_keys.json, spec/services/conversations/filter_service_spec.rb
- Update backend query for present and not present filter operator.
- Update conversation identifier filter attribute key.
Fixes #3187 
Added test cases for the same.
=> Feat: Update custom filter for present/not_present operator

app/javascript/dashboard/store/modules/conversations/actions.js, app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
Remove * as import from conversation actions.
=> fix: Remove * as import from conversation module

app/services/filter_service.rb, spec/services/conversations/filter_service_spec.rb, swagger/paths/application/conversation/filter.yml, swagger/paths/index.yml, swagger/swagger.json
Swagger doc updated for custom filter endpoint.
1. Tested on local: status all filter
2. Checked swagger on local
3. Added test cases for pagination
=> Feat: Swagger updated for the custom filter endpoint

app/javascript/dashboard/mixins/specs/uiSettings.spec.js, app/javascript/dashboard/mixins/uiSettings.js
- Update conversation sidebar items default order
=> chore: Update conversation sidebar items default order

app/javascript/dashboard/i18n/locale/en/attributesMgmt.json, app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue, app/javascript/dashboard/routes/dashboard/settings/attributes/EditAttribute.vue, app/javascript/dashboard/store/modules/attributes.js
- Add the option to edit attribute display name
- Show proper error message while adding/updating a new attribute
- Add validation for `attribute_key`
=> chore: Add the option to edit custom attribute display name

app/models/custom_attribute_definition.rb, db/migrate/20211116131740_add_values_to_custom_attribute_definitions.rb, db/schema.rb
=> chore: Add the support for list and checkbox in custom attribute model

app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
`sortBy` needs the default value to be an empty string not undefined.
=> fix: Set default value of sortBy to empty string

app/javascript/dashboard/i18n/locale/en/automation.json, app/javascript/dashboard/i18n/locale/en/index.js, app/javascript/dashboard/i18n/locale/en/settings.json, app/javascript/dashboard/i18n/sidebarItems/settings.js, app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue, app/javascript/dashboard/routes/dashboard/settings/automation/automation.routes.js, app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
Fixes #3401
Please import `automation.routes` in `settings.routes.js` file.
=> feat: Add automation route

app/javascript/widget/store/modules/conversation/actions.js, app/javascript/widget/store/modules/conversation/getters.js, app/javascript/widget/store/modules/conversation/helpers.js, app/javascript/widget/store/modules/conversation/index.js, app/javascript/widget/store/modules/conversation/mutations.js
`widget/v2` is the feature branch where we need to merge the new state.
More info about state can be found here #2879
=> feat: Updates widget conversation state to support multiple conversations

app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
FIxes the required validation bug for Conversation Filters
Fixes #3431
=> fix: Required check for Conversation filters

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
Fixes #3409 
**After**
https://user-images.githubusercontent.com/64252451/143001207-3c5ed81f-fb70-41fa-94be-154a8c069f6a.mov
**Before**
https://user-images.githubusercontent.com/64252451/143001256-a5254639-d1f9-4a83-8ce2-c237801d907b.mov
=> fix: Link in campaign editor

db/migrate/20211122112607_remove_invalid_migration.rb, db/schema.rb
=> Update schema files

app/javascript/dashboard/routes/index.js, app/javascript/dashboard/routes/index.spec.js, app/javascript/dashboard/store/modules/auth.js
Fixes #https://github.com/chatwoot/chatwoot/issues/2557
=> fix: Use role permissions from accounts instead of role attribute

app/services/contacts/filter_service.rb
Fixing filter values for custom filters.
=> Fix: contact filter values

app/controllers/api/v1/accounts/contacts_controller.rb
=> Feat: Fix contact filter pagination

app/javascript/dashboard/components/widgets/conversation/components/FilterInput.vue
**Before**
https://user-images.githubusercontent.com/64252451/143545042-b4a83a59-4fba-4ec1-b82e-675490634a93.mp4
**After**
https://user-images.githubusercontent.com/64252451/143545112-15a1d209-f9a5-4a2f-9112-95f79b25132f.mov
=> chore: fixes filter input multiselect height issue

.rubocop.yml, app/controllers/api/v1/accounts/canned_responses_controller.rb, app/presenters/agent_bot_presenter.rb, app/views/api/v1/accounts/agent_bots/create.json.jbuilder, app/views/api/v1/accounts/agent_bots/index.json.jbuilder, app/views/api/v1/accounts/agent_bots/show.json.jbuilder, app/views/api/v1/accounts/agent_bots/update.json.jbuilder, app/views/api/v1/models/_agent_bot.json.jbuilder, app/views/platform/api/v1/models/_agent_bot.json.jbuilder, db/seeds.rb, lib/seeders/account_seeder.rb, lib/seeders/message_seeder.rb, spec/controllers/api/v1/accounts/agent_bots_controller_spec.rb
-  Improve search of canned responses
-  Account seeding class 
ref: #3429
=> Chore: API Improvements

app/drops/conversation_drop.rb, app/drops/inbox_drop.rb, app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.liquid
Display recent messages in the notification email when a new conversation is created.
Fixes #2041 
New feature (non-breaking change which adds functionality)
Tested manually.
<details>
<summary>Screenshots</summary>
</details>
=> Feat: Include recent customer messages for new conversation

config/schedule.yml
fixes the duplicate schedule job key
=> chore: fix scheduled jobs

app/javascript/dashboard/components/widgets/conversation/MoreActions.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
- Fixes the text kept to debug editor
- Conversation header button
=> chore: Fixes issue with reply box

crowdin.yml
- Added the ability to update survey related translations
=> chore: Add survey pack translation in crowdin

app/listeners/action_cable_listener.rb
=> fix: Conversation status change event in web widget

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
=> fix: Fixes sidebar toggle icon breaking message view

app/models/custom_attribute_definition.rb, db/migrate/20211207113102_remove_attribute_key_index_on_custom_attribute_definition.rb, db/schema.rb
=> fix: Index custom attribute uniqueness on account

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
=> fix: Fixes cc bcc being sent when mail head is empty  

app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
**Screen recording** 
https://user-images.githubusercontent.com/64252451/145156174-dd012871-374a-45d6-bdeb-4e4ebfd8c9d6.mov
=> bug: Fixes throwing error with secondary sidebar while switching to profile settings 

app/models/custom_attribute_definition.rb, db/migrate/20211208081344_add_attribute_model_index_on_custom_attribute_definition.rb, db/schema.rb
- Added attribute model in custom attribute index
=> chore: Add the ability to use same key for conversation and contact

.eslintrc.js, .husky/pre-commit, .husky/pre-push, app/javascript/dashboard/components/Snackbar.vue, app/javascript/dashboard/components/ui/Switch.vue, app/javascript/dashboard/components/widgets/EmptyState.vue, app/javascript/dashboard/components/widgets/LoadingState.vue, app/javascript/dashboard/components/widgets/conversation/OnboardingView.vue, app/javascript/dashboard/components/widgets/forms/AvatarUploader.vue, app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Line.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Sms.vue, app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue, app/javascript/dashboard/routes/login/Login.vue, app/javascript/dashboard/store/modules/conversations/index.js, app/javascript/shared/components/GreetingsEditor.vue, app/javascript/shared/components/TextArea.vue, app/models/custom_attribute_definition.rb, package.json, yarn.lock
- Upgraded husky from 6 to 7
- Git hooks are configured using individual files for hooks in a `.husky/` directory.
=> chore: Fix pre-commit hooks

enterprise/LICENSE
Removes double words in a sentence
=> Updates Enterprise Licence

README.md
- Update readme to include Line Messenger
n/a
=> add line messenger in readme

app/javascript/dashboard/assets/scss/widgets/_buttons.scss, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/buttons/ResolveAction.vue, app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue, app/javascript/dashboard/components/ui/WootButton.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue, app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue, app/javascript/dashboard/components/widgets/conversation/MoreActions.vue, app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue, app/javascript/dashboard/modules/notes/components/ContactNote.vue, app/javascript/dashboard/routes/dashboard/conversation/ConversationAction.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
=> Chore: Fixes icon size in button

app/javascript/dashboard/assets/scss/widgets/_buttons.scss, app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
=> fix: Fixes wrong color for note tab in reply box

.rubocop.yml, app/models/account_user.rb, app/models/agent_bot.rb, app/models/campaign.rb, app/models/contact_inbox.rb, app/models/conversation.rb, app/models/csat_survey_response.rb, app/models/data_import.rb, app/models/mention.rb, app/models/note.rb, app/models/team.rb, app/models/team_member.rb, db/migrate/20211219031453_update_foreign_keys_on_delete.rb, db/schema.rb
=> chore: Clean up migrations

config/initializers/languages.rb
ref: https://app.chatwoot.com/app/accounts/1/conversations/11358 
Slovak translations are 60% completed.
=> chore: Enable Slovak Language

app/controllers/api/v1/accounts/inboxes_controller.rb
Fixes https://sentry.io/organizations/thoughtwoot-04/issues/2872438814/?environment=production&project=5410824&referrer=alert_email
=> Fix: Editable attrs presence check for the channel class

app/presenters/mail_presenter.rb, lib/exception_list.rb, spec/mailboxes/reply_mailbox_spec.rb
- exception list updated
- revert mail presenter changes
=> chore: Minor API cleanups

.eslintrc.js, app/javascript/dashboard/components/Snackbar.vue, app/javascript/dashboard/components/ui/Switch.vue, app/javascript/dashboard/components/widgets/EmptyState.vue, app/javascript/dashboard/components/widgets/LoadingState.vue, app/javascript/dashboard/components/widgets/ReportStatsCard.vue, app/javascript/dashboard/components/widgets/modal/DeleteModal.vue, app/javascript/dashboard/routes/auth/PasswordEdit.vue, app/javascript/dashboard/routes/dashboard/settings/SettingsSubPageHeader.vue, app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue, app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue, app/javascript/dashboard/routes/dashboard/settings/integrationapps/IntegrationItem.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Integration.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/ShowIntegration.vue, app/javascript/shared/components/GreetingsEditor.vue, app/javascript/widget/components/ImageBubble.vue, app/javascript/widget/components/UserAvatar.vue, db/schema.rb
- Fixed all the Eslint warnings and errors
=> chore: Fix `Eslint` warnings

app/listeners/notification_listener.rb, app/models/conversation.rb, spec/models/concerns/assignment_handler_shared.rb, spec/models/conversation_spec.rb
fixes issue with conversation assignment notifications not working in certain cases.
=> chore: Fix issue with conversation assignment notifications

app/javascript/dashboard/i18n/locale/en/settings.json
- Field title updates
- Placeholder updates
- [Y] Bug fix (non-breaking change which fixes an issue)
Tested locally
- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [Y] I have commented on my code, particularly in hard-to-understand areas
- [Y] My changes generate no new warnings
=> Fixes #3656 Updates tile and placeholder

app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
- Currently the secondary sidebar shows scrollbar always, This PR will show the scrollbar only when it's hovered
- Changes clickable name on contact side to only the icon
=> chore: Show scrollbar for sidebar only on hover

.github/CODEOWNERS, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
1.  Updates date from 2021 to 2022 and fix grammar suggestions. 
2. Adds the CODEOWNER file and adds the feature of automatically requesting for a CODEOWNER to review the PR.
=> General updates and add CODEOWNERS

app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
Unnecessary space removed.
#3669
=> Cloes #3669 Unnecessary spacing removed

config/locales/de.yml
Two bumpy german translations fixed.
That's just a fixed translation.
=> Fix german translations

.rubocop.yml, app/models/contact.rb, db/migrate/20220111200105_update_nil_contact_attributes_to_empty_hash.rb, db/schema.rb, spec/models/contact_spec.rb
- migration to update existing records
- validations and tests for the model
=> chore: Prevent null in Contact JSONB attributes

app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.liquid, app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.liquid, app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
=> fix: Update broken CSS Styles in liquid template

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
=> fix: fixes private note not getting added on twitter channel

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
=> fix: Contact bio overflow issue

app/models/concerns/assignment_handler.rb, app/models/notification.rb
=> chore: Clean up Assignment logic

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/i18n/locale/en/advancedFilters.json, app/javascript/dashboard/routes/dashboard/customviews/DeleteCustomViews.vue
Fixes #3744 
**Screen recording** 
https://user-images.githubusercontent.com/64252451/149706327-fe6dd882-1e8a-42ae-864d-874a9a9d03ef.mov
=> feat: Adds the ability to delete the saved custom views

app/javascript/widget/components/UnreadMessageList.vue
=> fix: Fixes alignment of widget unread view close button

app/javascript/dashboard/store/modules/inboxes.js
=> fix: File and emoji pickers are disabled by default

app/controllers/api/v1/accounts/automation_rules_controller.rb, app/listeners/automation_rule_listener.rb, app/policies/automation_rule_policy.rb, app/views/api/v1/accounts/automation_rules/clone.json.jbuilder, app/views/api/v1/accounts/automation_rules/edit.json.jbuilder, app/views/api/v1/accounts/automation_rules/show.json.jbuilder, app/views/api/v1/accounts/automation_rules/update.json.jbuilder, config/routes.rb, lib/filters/filter_keys.json, spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
Update, destroy and clone the automation rules.
Fixes #3740 
=> feat: Clone and update automation rules

app/services/whatsapp/incoming_message_service.rb, spec/services/whatsapp/incoming_message_service_spec.rb
=> feat: Support 360Dialog Interactive Templates 

app/javascript/dashboard/i18n/locale/en/teamsSettings.json
=> fix: Fixes typo in documentation for sidebar

app/javascript/dashboard/api/customViews.js, app/javascript/dashboard/i18n/locale/en/advancedFilters.json, app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue, app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue, app/javascript/dashboard/routes/dashboard/customviews/DeleteCustomViews.vue, app/javascript/dashboard/store/modules/customViews.js, app/javascript/dashboard/store/modules/specs/customViews/actions.spec.js
Fixes #3824 
1. Create a segment and open it.
2. Now you can see the delete button.
=> feat: Adds the ability to delete a segment

app/models/concerns/avatarable.rb
Avatar validation should run only if the avatar has changed.
Fixes #3596 
Tested manually
=> bug: validate avatar only if it has changed

app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.liquid, app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.liquid, app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
=> fix: Fix email template to render the chat bubble properly

app/mailboxes/mailbox_helper.rb, app/presenters/html_parser.rb, app/presenters/mail_presenter.rb
Fixes #3731 
Tested on staging and on local
=> Fix: parse verification mail

app/javascript/dashboard/components/NetworkNotification.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/widget/components/ChatAttachment.vue
- Use globalConfig Mixin.
- Fixes linter issues in JS files.
Fixes https://github.com/chatwoot/product/issues/302
=> chore: Use globalConfig in NetworkNotification

lib/integrations/dialogflow/processor_service.rb, spec/lib/integrations/dialogflow/processor_service_spec.rb
=> chore: Add resolve action in Dialogflow Integration

app/javascript/dashboard/components/widgets/conversation/Message.vue
Fixes comment mentioned on original PR - https://github.com/chatwoot/chatwoot/pull/3884#issuecomment-1027596085
=> fix: Shows tooltip and avatar for template messages

app/finders/conversation_finder.rb, spec/finders/conversation_finder_spec.rb
fixes: https://github.com/chatwoot/product/issues/225
=> Fix: Conversation filter permissions

app/services/contacts/filter_service.rb, app/services/conversations/filter_service.rb, app/services/filter_service.rb, lib/filters/filter_keys.json, spec/services/contacts/filter_service_spec.rb, spec/services/conversations/filter_service_spec.rb
Date based filter 
Fixes #3840 
Tested on local with postman
=> feat: Add date custom filter

app/javascript/dashboard/components/CustomAttribute.vue, app/javascript/dashboard/helper/URLHelper.js, app/javascript/dashboard/helper/specs/URLHelper.spec.js, app/javascript/dashboard/mixins/attributeMixin.js, app/javascript/dashboard/mixins/specs/attributeMixin.spec.js
Fixes https://github.com/chatwoot/product/issues/293
=> fix: Omit invalid urls in custom attributes

app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue, app/javascript/dashboard/store/modules/contactConversations.js
=> chore: Assign to agent who create new message from contact panel

app/javascript/dashboard/components/ChatList.vue
Fixes https://github.com/chatwoot/product/issues/308
=> feat: Show assignee name in folder view

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Fixes #3913 
**Screenrecording**
https://user-images.githubusercontent.com/64252451/153134394-558bb7d6-7ef4-49c6-be3e-51ddb69e311e.mov
=> fix: Blank page after deleting contact

app/javascript/widget/components/ImageBubble.vue
Fixes the warning that appears on console with invalid method
=> fix: Fixes console error with image component in widget

app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Fixes #3762 
**Screenshot**
**After**
**Before**
=> fix: Icon colors are not recognizable in bubble

app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
=> chore: Reduces clutter in inbox settings page

app/listeners/webhook_listener.rb, spec/listeners/webhook_listener_spec.rb
=> feat: Add `conversation_created` event in webhooks

app/views/api/v1/models/_campaign.json.jbuilder, spec/controllers/api/v1/accounts/campaigns_controller_spec.rb
=> fix: campaign scheduled at json format

app/javascript/dashboard/components/widgets/conversation/bubble/MailHead.vue, app/javascript/dashboard/i18n/locale/en/conversation.json
=> feat: Show the sender email address

app/javascript/dashboard/components/CustomAttribute.vue
=> fix: Custom attribute not getting changed on conversations

app/controllers/api/v1/profiles_controller.rb, app/javascript/dashboard/api/auth.js, app/javascript/dashboard/routes/dashboard/settings/profile/MessageSignature.vue, app/models/super_admin.rb, app/models/user.rb, app/views/api/v1/models/_user.json.jbuilder, app/views/platform/api/v1/models/_user.json.jbuilder, db/migrate/20220215060751_remove_message_signature_enabled.rb, db/schema.rb, spec/controllers/api/v1/profiles_controller_spec.rb
=> chore: Remove message_signature_enabled from users

app/models/message.rb, spec/models/message_spec.rb
- Do not send emails for activity messages
=> chore: Discard activities from email notifiable messages

app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue, app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
Fixes lock icon colour issue in private messages occurred after merging PR https://github.com/chatwoot/chatwoot/pull/3957
**Screenshot**
**Before**
**After**
=> fix: Lock icon colour issue in private messages

app/javascript/dashboard/components/ChatList.vue
=> fix: Throwing error when click load more conversation

app/models/conversation.rb, spec/models/conversation_spec.rb
=> fix: Automation loop on conversation_update

app/javascript/dashboard/api/auth.js, app/javascript/dashboard/helper/URLHelper.js, app/javascript/dashboard/helper/specs/URLHelper.spec.js, app/javascript/dashboard/routes/index.js, app/javascript/dashboard/routes/login/Login.vue, app/javascript/dashboard/routes/login/login.routes.js, app/javascript/dashboard/store/modules/auth.js, app/javascript/dashboard/store/utils/api.js
- Redirect the user to the correct account if sso_account_id is passed in the SSO URL.
Fixes https://github.com/chatwoot/product/issues/324
=> chore: Pass sso_account_id to select the account during SSO Login

app/views/devise/mailer/confirmation_instructions.html.erb, yarn.lock
Fixes https://github.com/chatwoot/product/issues/351
=> fix: Update brand name in mailers

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Fixes showing error after merging PR #4100
=> fixes: Showing vue warning in the console

app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Fixes #4067 
**Before**
**After**
=> feat: Adds ability to delete contact without having to type name

app/channels/room_channel.rb
=> fix: NoMethodError: undefined method `id' for nil:NilClass

app/controllers/api/v1/accounts/agents_controller.rb, app/models/user.rb, app/views/api/v1/models/_agent.json.jbuilder
Fixes the n+1 queries that get triggered while accessing agents endpoint
=> chore: Improve n+1 queries in agents endpoint

.codeclimate.yml, .eslintrc.js, app/javascript/packs/survey.js, app/javascript/shared/components/Branding.vue, app/javascript/survey/i18n/index.js, app/javascript/survey/store/index.js, app/javascript/survey/views/Response.vue, app/views/public/api/v1/models/_csat_survey.json.jbuilder
Fixes locale issue in survey pack
Fixes https://github.com/chatwoot/chatwoot/issues/3784
=> fix: Update survey locale based on the account

app/javascript/widget/views/Home.vue
=> fix: Disable pre-chat for identified users

app/javascript/dashboard/store/modules/conversations/index.js, app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
=> fix: Update scroll event name to fix auto-scroll

spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb, spec/listeners/automation_rule_listener_spec.rb
The ordering of these is not specified and is not guaranteed.
On my laptop I'm getting failures for these tests due to ordering.
=> Use "contain_exactly" in some tests

app/javascript/widget/components/GroupedAvatars.vue, app/javascript/widget/components/TeamAvailability.vue
Fixes available agents avatar get cropped on the widget
**Before**
**After**
=> fix: Avatars get cropped on the widget

app/javascript/sdk/IFrameHelper.js
=> fix: Remove unnecessary dispatchWindowEvent

config/routes.rb, swagger/definitions/index.yml, swagger/definitions/request/canned_response/create_update_payload.yml, swagger/definitions/resource/canned_response.yml, swagger/index.yml, swagger/paths/application/canned_responses/create.yml, swagger/paths/application/canned_responses/delete.yml, swagger/paths/application/canned_responses/index.yml, swagger/paths/application/canned_responses/update.yml, swagger/paths/index.yml, swagger/swagger.json
=> chore: Add swagger docs for Canned Responses
