chatwoot/chatwoot

spec/controllers/api/v2/accounts/report_controller_spec.rb
Fix for report_controller spec.
=> fix: Report controller specs

app/builders/contact_builder.rb, app/builders/messages/facebook/message_builder.rb, app/controllers/api/v1/accounts/callbacks_controller.rb, app/controllers/twitter/callbacks_controller.rb, app/controllers/webhooks/instagram_controller.rb, app/jobs/contact_avatar_job.rb, app/jobs/contact_ip_lookup_job.rb, app/mailers/application_mailer.rb, app/models/channel/facebook_page.rb, app/models/channel/twitter_profile.rb, app/models/channel/web_widget.rb, app/services/instagram/send_on_instagram_service.rb, app/services/notification/push_notification_service.rb, app/services/twilio/webhook_setup_service.rb, app/services/twitter/send_on_twitter_service.rb, config/initializers/rack_attack.rb, lib/chatwoot_hub.rb, lib/integrations/slack/send_on_slack_service.rb, spec/cypress/app_commands/log_fail.rb
Change log levels to reflect appropriate importance levels. 
Fixes #4313 
=> feat: fix logging levels

swagger/paths/index.yml, swagger/swagger.json
- Fix the documentation for inbox_members
=> fix: Update the URL for POST inbox_members

app/listeners/base_listener.rb, app/models/user.rb
=> fix:  Unread notification count in multiple accounts

lib/online_status_tracker.rb
Ability to customize the online presence duration via the environment variable `PRESENCE_DURATION`
=> feat: Ability to customize the online presence duration

app/javascript/widget/App.vue, app/javascript/widget/components/ConversationWrap.vue
**Screenshot**
`Before`
`After`
=> fix: Background colour issue in the unread message view

app/javascript/dashboard/components/buttons/ToggleButton.vue, app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
- Added toggle button component
=> feat: Add toggle button component

app/controllers/api/v1/widget/base_controller.rb, app/controllers/api/v1/widget/conversations_controller.rb, app/javascript/widget/api/endPoints.js
- Added support for adding `phone_number` & `custom_attributes` in widget create conversation end point
=> feat: Add `phone_number` & `custom_attributes` in create conversation end point

app/views/api/v1/widget/conversations/create.json.jbuilder, spec/controllers/api/v1/widget/conversations_controller_spec.rb
- Added missing test cases in the PR https://github.com/chatwoot/chatwoot/pull/4421
=> chore: Add missing test cases in `conversations_controller_spec`

.github/workflows/publish_foss_docker.yml, lib/chatwoot_hub.rb
- Set `CW_EDITION=ce` for community edition docker images
- Include Chatwoot edition in payload to hub
- Built via GitHub action and manually verified
=> feat: add chatwoot_edition variable for CE docker images

swagger/parameters/report_type.yml, swagger/swagger.json
Fixes #4466 
Manually verified
=> Fix: Changes report_type to type in report API docs

app/javascript/shared/helpers/DateHelper.js, app/javascript/shared/helpers/specs/DateHelper.spec.js, app/javascript/widget/components/TeamAvailability.vue, app/javascript/widget/mixins/availability.js, app/javascript/widget/mixins/specs/availabilityMixin.spec.js, package.json, yarn.lock
https://www.loom.com/share/5986f76066ec421ca549c4a7b746a385
Fixes https://github.com/chatwoot/product/issues/403
=> fix: Update between business hour calculation

app/javascript/widget/mixins/availability.js, app/javascript/widget/mixins/specs/availabilityMixin.spec.js
I made a mistake in the https://github.com/chatwoot/chatwoot/pull/4496/files PR. Accidentally merged the conditions for open all day and closed all day. This PR fixes it. I have added 2 test cases to cover these cases. 
@sojan-official We need a hot-fix release for this.
=> fix: Issue with closed all hours

app/models/conversation.rb, app/models/reporting_event.rb, db/migrate/20220428101325_add_index_to_conversation_and_reporting_event.rb, db/schema.rb
Fixes https://github.com/chatwoot/product/issues/422
=> fix: Add index in conversation and reporting event

Gemfile, Gemfile.lock
Updates `sidekiq-cron` to fix the deprecation warnings
Fixes #4090 
Tested manually by running sidekiq server before and after updating `sidekiq-cron`
=> Fix: sidekiq cron deprecation warnings

app/controllers/public/api/v1/inboxes/contacts_controller.rb, app/views/public/api/v1/models/_contact.json.jbuilder, spec/controllers/public/api/v1/inbox/contacts_controller_spec.rb, swagger/definitions/request/public/contact/create_update_payload.yml, swagger/swagger.json
This PR makes it possible to pass a phone number to the public contacts API.
Fixes #4023 
Modified the existing tests
=> Fix: Accept phone number in public contact api

app/models/inbox_member.rb, lib/integrations/slack/incoming_message_builder.rb, spec/models/inbox_member_spec.rb
Addresses the following sentry issues
https://github.com/chatwoot/chatwoot/issues/4616
https://github.com/chatwoot/chatwoot/issues/4617
=> chore: Sentry Issue fixes

config/schedule.yml, yarn.lock
- Update missing packages in yarn.lock
- Change the schedule for trigger_imap_email_inboxes_job to 5mins
=> chore: Update missing packages in yarn.lock

app/builders/contact_builder.rb, app/builders/messages/facebook/message_builder.rb, app/channels/room_channel.rb, app/controllers/api/v1/accounts/channels/twilio_channels_controller.rb, app/controllers/api/v1/accounts/conversations/base_controller.rb, app/finders/message_finder.rb, app/jobs/hook_job.rb, lib/webhooks/trigger.rb
Fixes various issues reported on sentry
- Twilio channel creation validation errors
- Room Channel error with nil class
- webhook uri exception
=> chore: Sentry issues

app/services/instagram/message_text.rb
Check if the Instagram contact is already present in the system before throwing the exception.
Fixes #4666 
Tested on staging.
=> Fix: Creating contacts for already outgoing/echo messages

app/javascript/dashboard/i18n/locale/bg/settings.json
This content edit removes the ambiguity around the channels that support personal message signature.
=> chore: Update the note of Personal message signature

app/javascript/packs/application.js, app/javascript/packs/widget.js, app/javascript/shared/helpers/HTMLSanitizer.js, app/javascript/shared/helpers/MessageFormatter.js, package.json, yarn.lock
Fixes #4684 
Introduced via https://github.com/chatwoot/chatwoot/pull/4498
=> fix: Render links with target attribute

app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue
Fixes https://github.com/chatwoot/chatwoot/issues/4653
=> chore: Enable New Message Button on Contact Panel

app/javascript/dashboard/helper/downloadHelper.js, app/javascript/dashboard/helper/specs/downloadHelper.spec.js, app/javascript/dashboard/store/modules/specs/reports/actions.spec.js, app/views/api/v1/accounts/csat_survey_responses/download.csv.erb, app/views/api/v2/accounts/reports/agents.csv.erb, app/views/api/v2/accounts/reports/inboxes.csv.erb, app/views/api/v2/accounts/reports/labels.csv.erb, app/views/api/v2/accounts/reports/teams.csv.erb
- Updated the methods in frontend to fix the issue with special characters
=> fix: Update report method to fix issues with special characters

swagger/definitions/index.yml, swagger/definitions/request/webhooks/create_update_payload.yml, swagger/definitions/resource/webhook.yml, swagger/index.yml, swagger/parameters/index.yml, swagger/parameters/webhook_id.yml, swagger/paths/application/webhooks/create.yml, swagger/paths/application/webhooks/delete.yml, swagger/paths/application/webhooks/index.yml, swagger/paths/application/webhooks/update.yml, swagger/paths/index.yml, swagger/swagger.json
=> chore: Update the documentation for configuring webhooks in the account

config/initializers/languages.rb
Fixes https://github.com/chatwoot/chatwoot/issues/4716
=> chore: Enable Ukrainian language (uk)

.circleci/config.yml
- Update cache name to fix Circle CI builds
=> chore: Update cache name in Circle CI builds

deployment/setup_20.04.sh
fix: command execution in heredoc comment
-  Tested on a Ubuntu 20.04 instance
=> fix: command execution in heredoc comment

app/controllers/dashboard_controller.rb
Upgrade Facebook login API version to 14.0
Fixes #4762 
Tested on staging.
=> chore: upgrade FB api version

app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/360DialogWhatsapp.vue
- Remove 360Dialog partner signup link
=> chore: Remove partner signup link

swagger/definitions/index.yml, swagger/definitions/request/automation_rule/create_update_payload.yml, swagger/definitions/resource/automation_rule.yml, swagger/definitions/resource/contact.yml, swagger/definitions/resource/conversation.yml, swagger/index.yml, swagger/paths/application/automation_rule/create.yml, swagger/paths/application/automation_rule/delete.yml, swagger/paths/application/automation_rule/index.yml, swagger/paths/application/automation_rule/show.yml, swagger/paths/application/automation_rule/update.yml, swagger/paths/application/conversation/index.yml, swagger/paths/application/custom_attributes/delete.yml, swagger/paths/application/custom_attributes/show.yml, swagger/paths/application/team_members/index.yml, swagger/paths/index.yml, swagger/swagger.json
- Swagger API doc updates for Automation Rule
- Fixed the Swagger JSON failure for team members and custom attribute definitions
- Added custom attribute params for conversation and contact.
- 
Fixes #4583 
Added Swagger doc.
=> Chore: Automation rule api

app/javascript/dashboard/routes/dashboard/settings/profile/profile.routes.js
=> fix: Update profile settings header title

app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/LabelActions.vue, app/javascript/shared/assets/stylesheets/spacing.scss
Fixes the loading block while calling assignable agents api 
https://user-images.githubusercontent.com/15716057/173853225-886caa2f-7ddd-42ad-ac30-7fb0641d9fa0.mp4
=> fix: Bulk actions agent loading

.devcontainer/scripts/setup.sh
fixes the webpacker error when running `overmind start -f Procfile.dev`
=> chore: Codespace Webpacker fix

app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
=> fix: Display missing agent avatar in bulk actions and reports

app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/ImapSettings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/SmtpSettings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Website.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue, app/javascript/dashboard/store/modules/inboxes.js, app/javascript/dashboard/store/modules/specs/inboxes/actions.spec.js, app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js, app/javascript/dashboard/store/utils/api.js, app/javascript/dashboard/store/utils/specs/api.spec.js
Fixes loading state in the inbox settings page.
Loom: https://www.loom.com/share/883027831ca146ed98f1d271cc5860ea
=> chore: Fix loader in inbox settings page

app/controllers/api/v1/accounts/articles_controller.rb, app/controllers/api/v1/accounts/portals_controller.rb, app/controllers/public/api/v1/portals/categories_controller.rb, app/controllers/public/api/v1/portals_controller.rb, app/models/article.rb, app/models/portal.rb, app/views/public/api/v1/kbase/portal/show.json.jbuilder, app/views/public/api/v1/models/_associated_category.json.jbuilder, app/views/public/api/v1/models/_category.json.jbuilder, app/views/public/api/v1/models/_portal.json.jbuilder, app/views/public/api/v1/portals/categories/index.json.jbuilder, app/views/public/api/v1/portals/categories/show.json.jbuilder, app/views/public/api/v1/portals/index.json.jbuilder, app/views/public/api/v1/portals/show.json.jbuilder, config/routes.rb, spec/controllers/api/v1/accounts/articles_controller_spec.rb, spec/controllers/public/api/v1/portals/categories_controller_spec.rb, spec/controllers/public/api/v1/portals_controller_spec.rb
1. Return the portals available on the account
2. Return all the categories belonging to the portal with slug
Fixes #4600 
1. Written the test cases to get the information passed.
2. As it is a public API no check for authorization is involved.
=> feat: Portal and Category public APIs

app/models/agent_bot.rb, app/models/channel/twilio_sms.rb, db/schema.rb
fix the schema errors occured from previous PR merges
=> chore: fix schema error from PR merge

yarn.lock
Fixes deployment issue due to yarn.lock integrity check
=> fix: Update yarn.lock file to fix deployment issue

app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/routes/dashboard/dashboard.routes.js, app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js, app/javascript/dashboard/routes/dashboard/helpcenter/helpers/routeHelper.js, app/javascript/dashboard/routes/dashboard/helpcenter/helpers/specs/routeHelper.spec.js, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListArchivedArticles.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListCategoryArticles.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListDraftArticles.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListMyArticles.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/EditCategory.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ListAllCategories.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/NewCategory.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ShowCategory.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortal.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/NewPortal.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ShowPortal.vue
This PR creates placeholder routes for the help center module. 
**List all portals**: `/app/accounts/:accountId/portals`
**Create a new portal**: `/app/accounts/:accountId/portals/new`
**View portal details**: `/app/accounts/:accountId/portals/:portalSlug`
**Edit a portal**: `/app/accounts/:accountId/portals/:portalSlug/edit`
**List all articles**: `/app/accounts/:accountId/portals/:portalSlug/:locale/articles`
**List archived articles**: `/app/accounts/:accountId/portals/:portalSlug/:locale/articles/archived`
**List draft articles**: `/app/accounts/:accountId/portals/:portalSlug/:locale/articles/draft`
**List my articles**: `/app/accounts/:accountId/portals/:portalSlug/:locale/articles/mine`
**Create a new article**: `/app/accounts/:accountId/portals/:portalSlug/:locale/articles/new` …
=> feat: Init HelpCenter Routes

.env.example, Gemfile, Gemfile.lock, app/javascript/dashboard/api/ApiClient.js, app/javascript/dashboard/store/modules/inboxes.js, app/javascript/dashboard/store/utils/api.js, app/javascript/dashboard/store/utils/specs/api.spec.js, app/models/account.rb, app/views/api/v1/accounts/show.json.jbuilder, app/views/api/v1/accounts/update.json.jbuilder, app/views/api/v1/models/_account.json.jbuilder, config/initializers/stripe.rb, db/migrate/20220718123938_add_custom_attributes_to_account.rb, db/schema.rb
=> chore: Add ee helper, custom_attributes to account

app/javascript/shared/helpers/AudioNotificationHelper.js
Prevent errors in decoding and playing sounds from propagating
by catching them in the promise chain.
Fixes #4281.
=> chore: Catch audio context errors

app/controllers/api/v1/accounts/articles_controller.rb, app/controllers/api/v1/accounts/macros_controller.rb, app/models/account.rb, app/models/custom_attribute_definition.rb, app/models/macro.rb, app/models/user.rb, app/policies/macro_policy.rb, app/views/api/v1/accounts/macros/create.json.jbuilder, app/views/api/v1/accounts/macros/index.json.jbuilder, app/views/api/v1/accounts/macros/show.json.jbuilder, app/views/api/v1/accounts/macros/update.json.jbuilder, app/views/api/v1/models/_macro.json.jbuilder, config/routes.rb, db/migrate/20220711090528_create_macros.rb, db/schema.rb, spec/controllers/api/v1/accounts/macros_controller_spec.rb, spec/factories/macros.rb, spec/models/macro_spec.rb
Macro CRUD operations.
Fixes #5012 
Local Postman and Test cases.
=> feat: Macros CRUD api

app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
=> fix: Console warnings from help-center routes

enterprise/app/models/enterprise/account.rb
Fixes https://github.com/chatwoot/chatwoot/issues/5168
=> fix: Convert limits to Integer

app/javascript/dashboard/i18n/locale/en/helpCenter.json, app/javascript/dashboard/routes/dashboard/helpcenter/components/AllPortals.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/AllPortals.stories.js
Fixes https://github.com/chatwoot/product/issues/500
**Screenshot**
=> feat: Created a view for listing all the portals

app/javascript/dashboard/components/helpCenter/AddCategory.vue, app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue, app/javascript/dashboard/components/widgets/forms/Input.vue
Fixes https://github.com/chatwoot/chatwoot/issues/5175
**Screenshot**
| **Before**                                                                                                                                     | **After**                                                                                                                                      |
| ------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------ |
| <img width="448" alt="Screenshot 2022-08-03 at 8 52 31 AM" src="https://user-images.githubusercontent.com/64252451/182517193-999eed78-8a0a-46ff-8c8b-0d1 …
=> fix: Broken styles in the editor

app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
Fixes https://github.com/chatwoot/chatwoot/issues/5175
=> chore: Update styles in cc/bcc input

app/javascript/dashboard/components/app/UpdateBanner.vue, app/javascript/dashboard/components/app/specs/versionCheckHelper.spec.js, app/javascript/dashboard/components/app/versionCheckHelper.js, app/javascript/dashboard/helper/localStorage.js, app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue
=> chore: Cleanup update banner with localstorage updates

lib/online_status_tracker.rb, lib/redis/alfred.rb, spec/lib/online_status_tracker_spec.rb
fixes: https://github.com/chatwoot/product/issues/493
=> chore: Remove stale contact presence records

package.json, yarn.lock
Fixes #5198 
Reference: https://github.com/vuelidate/vuelidate/issues/959
=> chore(deps): Upgrade vuelidate to 0.7.7

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
| -- | -- |
| <img width="148" alt="Screenshot 2022-08-09 at 11 52 11 AM" src="https://user-images.githubusercontent.com/2246121/183579065-1644d375-837d-4e0b-87b7-b17956244c09.png"> | <img width="198" alt="Screenshot 2022-08-09 at 11 52 46 AM" src="https://user-images.githubusercontent.com/2246121/183579077-6c74aee1-5cd7-4c25-8811-d66ef846fcad.png"> |
=> fix: Update styles to fix the status filter dropdown

app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
Fixes https://github.com/chatwoot/product/issues/531
**Screencast**
https://user-images.githubusercontent.com/64252451/185300611-7716c246-7bff-4dc6-b60b-8d19516f1896.mov
=> chore: Handled help center sidebar in small screen

app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue, app/javascript/shared/mixins/inboxMixin.js, app/javascript/shared/mixins/specs/inboxMixin.spec.js
Fixes https://github.com/chatwoot/chatwoot/issues/5286
**Screenshot**
=> chore: Displayed WhatsApp API provider name in inbox settings

app/javascript/dashboard/i18n/locale/en/helpCenter.json, app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
- Adds articles settings sidebar in new articles page.
- Fixes scroll bar issue.
Fixes https://github.com/chatwoot/product/issues/549
**Screencast**
https://www.loom.com/share/2d79b7f2edec44919b75ca6f1596ba4f
=> feat: Article settings sidebar in new article page

app/javascript/dashboard/i18n/locale/en/helpCenter.json, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItemTable.vue
Fixes https://github.com/chatwoot/product/issues/558 and https://github.com/chatwoot/product/issues/535
- Added the option set default locale in portal
- Added the option delete locale from the portal
=> feat: Add the ability update/edit locale in portal 

app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsCustomizationForm.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalBasic.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalCustomization.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalCustomization.vue, app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
- Fixed portal update issue
- Removed hard coded default locales in update portal object.
=> chore: Portal update fixes

SECURITY.md
=> chore: Update security guidelines

app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue, app/javascript/dashboard/components/ui/Label.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
1. Spacing adjustments
2. Border changes
3. Changes label color
4. Font size changes
=> Design: Fixes to make portal page design close to figma mockups

app/controllers/api/v1/accounts/team_members_controller.rb, spec/controllers/api/v1/accounts/team_members_controller_spec.rb
fixes: https://github.com/chatwoot/product/issues/539
=> fix: Validations for updating team members

app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
**Screenshot**
| **Before**                                                                                                                                     | **After**                                                                                                                                      |
| ------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------ |
| <img width="1453" alt="Screenshot 2022-09-02 at 10 50 54 PM" src="https://user-images.githubusercontent.com/64252451/188206152-bf49e7d2-7f08-4ee5-9254-a6f7293fa1b5.png"> | <img width="1453" alt="Screenshot …
=> fix: Alignment issue of edit article dropdown

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/widget/components/ChatInputWrap.vue
Fixes https://github.com/chatwoot/chatwoot/issues/5396
**Screenshot**
=> fix: Emoji picker is not working on the expanded layout

app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/sidebarComponents/AccountContext.vue, app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue, app/javascript/dashboard/routes/dashboard/Dashboard.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue, app/javascript/dashboard/routes/dashboard/notifications/routes.js, app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue, app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue
**Screen recording**
https://user-images.githubusercontent.com/64252451/188566597-189e1255-2798-4388-bd93-c2bb2bcf47ca.mov
=> chore: Sidebar improvements in small screens

app/models/message.rb, config/features.yml
- Add the ability to toggle conversation continuity in API channel
=> chore: Add feature flag for conversation continuity in API

app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue, app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
**Screen recordings**
https://user-images.githubusercontent.com/64252451/188864580-51798af7-cb39-44c4-866a-3d918bce4a41.mov
=> chore: Fixes height issues with seconday sidebar

app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/AddCategory.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalLocales.vue
If you are in the list all portal screen and want to create a new category, you will now get an API error. This PR will fix this issue.
You can test it by following the steps,
1. Go to all portals screen.
2. Click plus icon near the category section in the sidebar, and
3. Add values and click create button.
4. Done!
=> fix: Not able to create a new category through the sidebar

app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
The portal switch component was using the default locale, making the active locale to show a different locale.
=> fix: Fixes bug with locale switching from popover

.github/workflows/nightly_installer.yml
- GitHub action marks an action as a failure if a single step fails. This causes our nightly install github action to be marked as a failure even though it is successful. There is no way to mark an action as a success manually.
- This PR modifies the script to play nice with github action environment. 
- Tested via gh action
=> chore: fix gh nightly failure

app/controllers/super_admin/accounts_controller.rb, app/dashboards/account_dashboard.rb, app/fields/enterprise/account_features_field.rb, app/views/fields/account_features_field/_form.html.erb, app/views/fields/account_features_field/_show.html.erb
- This PR add the ability to enable and disable features for an account from super admin
=> feat: Ability to manage account features from super admin

app/javascript/widget/App.vue
Fixes https://github.com/chatwoot/chatwoot/issues/5251
https://www.loom.com/share/2c6307f2381a457c8ce30152ce405abf
- [s] My changes generate no new warnings
- [s] New and existing unit tests pass locally with my changes
=> fix: Read status not updated in widget popout mode

.env.example, app/controllers/dashboard_controller.rb, app/controllers/public/api/v1/portals/articles_controller.rb, app/controllers/public/api/v1/portals/categories_controller.rb, app/controllers/public/api/v1/portals_controller.rb, app/controllers/public_controller.rb, app/models/portal.rb, app/views/public/api/v1/portals/show.html.erb, db/migrate/20220919225556_make_help_center_custom_domain_unique.rb, db/schema.rb
- Support rendering articles over frontend URL
- Support rendering articles over help center URL
- Support rendering help center home page in custom domain root
=> chore: Improve Help Center custom domains

db/migrate/20220920014549_enable_help_center.rb, db/schema.rb
- migration to enable a help center for self-hosted accounts
=> chore: Enable help center for self-hosted accounts

app/javascript/dashboard/components/layout/Sidebar.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
Shows article sidebar by default
Fixes portal preview URL
=> Chore: Helpcenter routing and UI fixes

app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue, app/views/public/api/v1/portals/_category-block.html.erb
Adds multiline support for article title input
=> Bug: Adds support multiline text input on article edit page

app/controllers/dashboard_controller.rb, app/controllers/public/api/v1/portals_controller.rb, app/views/public/api/v1/portals/show.html.erb, config/routes.rb
Fixes #5464 
Tested on local machine.
=> Fix: Redirect to portal with default locale

app/controllers/public/api/v1/portals_controller.rb, app/javascript/dashboard/helper/portalHelper.js, app/javascript/dashboard/helper/specs/portalHelper.spec.js, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue, app/views/api/v1/accounts/articles/_article.json.jbuilder, app/views/public/api/v1/portals/_category-block.html.erb, app/views/public/api/v1/portals/_header.html.erb
- Fix portal redirect
- Add locale in article slug
- Show locale switch only if there is more than one locale
=> chore: Fix link generation logic in help-center

app/controllers/api/v1/accounts/articles_controller.rb, app/models/article.rb, db/migrate/20220926164441_add_slug_to_article.rb, db/schema.rb, spec/controllers/api/v1/accounts/articles_controller_spec.rb, spec/factories/articles.rb, spec/models/article_spec.rb
=> fix: Add slug to articles

app/views/api/v1/accounts/articles/index.json.jbuilder, spec/controllers/api/v1/accounts/articles_controller_spec.rb
=> fix: Add all articles count to article API

app/controllers/api/v1/notification_subscriptions_controller.rb
=> fix: Remove the notification subscription if present

app/controllers/dashboard_controller.rb
- Set default locale as locale in the controller
=> chore: Set locale in default_locale

app/models/article.rb, db/migrate/20220930025317_add_unique_index_to_slug.rb, db/schema.rb, spec/factories/articles.rb, spec/models/article_spec.rb
Article slug textbox is not available at frontend till then we are adding the slug from backend.
=> fix: Article slug auto saves

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/helper/localStorage.js, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
Fixes #4876 and refactors state variable usages and watch functions.
=> bug: Fixes editor formatting issues when canned response text is edited

.circleci/config.yml, Gemfile, Gemfile.lock, spec/factories/articles.rb
Fixing the recent flakiness in CI pipelines
=> fix: Flakiness in CI pipeline

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue, app/javascript/dashboard/components/widgets/conversation/TagAgents.vue, app/javascript/dashboard/components/widgets/mentions/MentionBox.vue, app/javascript/dashboard/components/widgets/mentions/mentionSelectionKeyboardMixin.js, app/javascript/dashboard/components/widgets/mentions/specs/mentionSelectionKeyboardMixin.spec.js
=> feat: Update the design of mentions with thumbnail

app/models/attachment.rb, app/models/conversation.rb, db/migrate/20221010212946_add_index_to_message_attachments.rb, db/schema.rb
- index for attachments table
- index for conversations table
=> chore: Add missing indexes for attachments table

app/controllers/devise_overrides/passwords_controller.rb
Fixes #5591 
The issue was with the PR https://github.com/chatwoot/chatwoot/commit/bd445216e9e8413666deb32b5b09d202e91ec2fe with the deprecation warning fix; it didn't add the changes in the controller.
=> fix: Password reset page format updated

app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/CloudWhatsapp.vue, app/models/channel/whatsapp.rb, lib/regex_helper.rb, spec/factories/channel/channel_whatsapp.rb, spec/models/channel/whatsapp_spec.rb, spec/models/contact_inbox_spec.rb
=> chore: Generate webhook-verify-token automatically

.gitignore, .vscode/extensions.json
- Added the VS Code extensions recommendations for the better developer experience.
=> chore: `Vscode` extension recommendations

.editorconfig
=> fix: Fix .editorconfig syntax

app/javascript/packs/sdk.js, app/javascript/sdk/DOMHelpers.js, app/javascript/sdk/IFrameHelper.js, app/javascript/sdk/bubbleHelpers.js
=> chore: Improve widget SDK

app/javascript/dashboard/components/widgets/Avatar.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue, app/javascript/shared/mixins/campaignMixin.js, app/javascript/survey/views/Response.vue, app/models/working_hour.rb
=> chore: Replace deprecated functions

app/javascript/dashboard/components/layout/config/sidebarItems/primaryMenu.js, app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/DefaultPortalArticles.vue
Fixes https://github.com/chatwoot/product/issues/582
=> feat: Show last active portal page when sidebar portal icon is clicked

app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
- Show webhook URL only on WhatsApp Inbox
=> fix: Show webhook url only on WhatsApp inbox

app/javascript/dashboard/assets/scss/widgets/_buttons.scss, app/javascript/dashboard/assets/scss/widgets/_modal.scss, app/javascript/dashboard/components/Modal.vue, app/javascript/shared/components/ui/MultiselectDropdown.vue, app/javascript/shared/components/ui/MultiselectDropdownItems.vue, app/javascript/shared/components/ui/dropdown/DropdownItem.vue
1. Adds close button for dropdowns
2. Uses woot-button component and other code improvements 
**Before**
**After**
=> enhancement: Updates design for dropdown buttons

.rubocop.yml, app/builders/contact_inbox_builder.rb, app/builders/contact_inbox_with_contact_builder.rb, app/builders/messages/facebook/message_builder.rb, app/controllers/api/v1/accounts/contacts/contact_inboxes_controller.rb, app/controllers/api/v1/accounts/contacts_controller.rb, app/controllers/api/v1/accounts/conversations_controller.rb, app/controllers/concerns/request_exception_handler.rb, app/controllers/public/api/v1/inboxes/contacts_controller.rb, app/mailboxes/mailbox_helper.rb, app/models/channel/facebook_page.rb, app/models/channel/twitter_profile.rb, app/models/channel/web_widget.rb, app/services/line/incoming_message_service.rb, app/services/sms/incoming_message_service.rb, app/services/telegram/incoming_message_service.rb, app/services/twilio/incoming_message_service.rb, app/services/whatsapp/incoming_message_base_service.rb, db/seeds.rb, spec/builders/contact_inbox_builder_spec.rb, spec/builders/contact_inbox_with_contact_builder_spec.rb
- Remove duplicate code and move everything to builders
- attempt to fix : #https://github.com/chatwoot/chatwoot/issues/4680
=> chore: Refactor Contact Inbox Builders

app/javascript/widget/api/agent.js, app/javascript/widget/api/campaign.js, app/javascript/widget/api/conversation.js, app/javascript/widget/assets/scss/woot.scss, app/javascript/widget/components/AgentMessage.vue, app/javascript/widget/components/ChatAttachment.vue, app/javascript/widget/components/ChatHeaderExpanded.vue, app/javascript/widget/components/ChatInputWrap.vue, app/javascript/widget/components/FileBubble.vue, app/javascript/widget/components/PreChat/Form.vue, app/javascript/widget/components/TeamAvailability.vue, app/javascript/widget/components/UnreadMessageList.vue, app/javascript/widget/helpers/IframeEventHelper.js, app/javascript/widget/helpers/utils.js, app/javascript/widget/store/modules/conversation/getters.js, app/javascript/widget/store/modules/conversation/helpers.js, app/javascript/widget/store/modules/conversation/mutations.js, app/javascript/widget/store/modules/conversationLabels.js
=> chore: Refactor widget

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
- Changed the icon variant from 'link' to 'clear' which modified the shape on hover from a rectangle to a square.
- Added a size property with the value of 'tiny' which remove unnecessary vertical spacing between the rows.
Fixes #5597 
In my local environment.
=> fix: Avoid email icon getting distorted

app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/store/modules/inboxes.js
- Add editor toggle for API inbox allowing users to use rich content editor only if needed.
=> chore: Add editor toggle for API inbox

app/models/user.rb, config/routes.rb
This pull request is about adding ability to delete user in super admin console for the issue #4164. I had to fix an issue in user model definition (has_many :portals) during this updates.
Tested it in super admin console web UI in my local self-hosted ubuntu server.
https://www.loom.com/share/4d35b6d1afe0411692b097d086f75a7e
=> chore: ability to delete user in super admin console

app/views/public/api/v1/portals/_category-block.html.erb
Makes the entire block clickable instead of only the labels in helpcenter portal pages.
=> feat: Make links more accesible on helpcenter public views

app/javascript/widget/helpers/specs/urlParamsHelper.spec.js, app/javascript/widget/helpers/urlParamsHelper.js
=> chore: Refactor `urlParamsHelper.js`

tailwind.config.js
- Fix broken styles on production
=> fix: Add portal pack to tailwind config

app/javascript/dashboard/components/widgets/TableFooter.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue, app/javascript/shared/helpers/AudioNotificationHelper.js, app/views/api/v1/accounts/articles/index.json.jbuilder, app/views/api/v1/accounts/portals/_portal.json.jbuilder, spec/controllers/api/v1/accounts/articles_controller_spec.rb
- Fix help center pagination.
- Fix ESLint error
=> fix: Update pagination logic in the help center

app/javascript/dashboard/helper/actionCable.js, app/javascript/dashboard/store/modules/conversations/actions.js, app/models/conversation.rb, app/presenters/conversations/event_data_presenter.rb, spec/listeners/action_cable_listener_spec.rb, spec/models/conversation_spec.rb, spec/presenters/conversations/event_data_presenter_spec.rb
Enable action cable broadcast job on label update
=> fix: Add an action cable events for label updates

app/controllers/api/v1/accounts/articles_controller.rb, app/javascript/dashboard/components/layout/sidebarComponents/SecondaryChildNavItem.vue, app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/DefaultPortalArticles.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalDetails.vue, app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
=> chore: Refactors sidebar components used in help center

app/javascript/packs/sdk.js, app/javascript/widget/App.vue, app/views/widget_tests/index.html.erb, app/views/widgets/show.html.erb
Fixes #5082
https://www.loom.com/share/97ff5ae9826345ed86d914be6e9cff9c
=> fix: Add preference to choose browser lang for widget settings page

app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue, app/javascript/dashboard/routes/dashboard/notifications/components/NotificationsView.vue
=> Use @page-change instead of on-page-change

app/javascript/shared/components/CardButton.vue
Fixes https://github.com/chatwoot/chatwoot/issues/5719
| **Before**                                                                                                                                     | **After**                                                                                                                                      |
| ------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------ |
| <img width="423" alt="Screenshot 2022-10-25 at 3 22 08 PM" src="https://user-images.githubusercontent.com/64252451/197742666-9685dc66-a324-4e17-8ceb-828df3e0f794.png"> …
=> fix: Wrong colour for the action button in the card message

app/mailboxes/support_mailbox.rb, spec/mailboxes/support_mailbox_spec.rb
- Disable email processing for suspended accounts
=> chore: Disable email processing for suspended accounts

app/javascript/dashboard/components/widgets/Avatar.vue, app/javascript/dashboard/components/widgets/Thumbnail.vue
Remove unused code, simplify code and other minor improvements.
=> chore: Refactor thumbnail

app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/AddCategory.stories.js, app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleEditor.stories.js
=> chore: Fix import paths in storybook

app/javascript/dashboard/i18n/locale/en/helpCenter.json, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsBasicForm.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsCustomizationForm.vue
Added URL validation for the domain and the home page link for editing and creating a portal.
Fixes https://github.com/chatwoot/chatwoot/issues/5752
https://www.loom.com/share/037ebcee6415402ab4c164a0efcd6c6c
=> feat: Adds URL validation for domain and home page links

app/javascript/dashboard/components/widgets/Thumbnail.spec.js
Fixed `Thumbnail` component specs which go introduced after merging the https://github.com/chatwoot/chatwoot/pull/5682.
=> chore: Fix `Thumbnail` component specs

app/javascript/dashboard/helper/specs/macrosFixtures.js, app/javascript/dashboard/helper/specs/macrosHelper.spec.js, app/javascript/dashboard/i18n/locale/en/automation.json, app/javascript/dashboard/routes/dashboard/settings/macros/MacroForm.vue, app/javascript/dashboard/routes/dashboard/settings/macros/MacroNode.vue, app/javascript/dashboard/routes/dashboard/settings/macros/MacroNodes.vue, app/javascript/dashboard/routes/dashboard/settings/macros/macroHelper.js
File name is now displayed for attachment action in macros
Fixes #5732
=> fix: Filename issue while editing a macro with attachment action

app/javascript/shared/components/CardButton.vue, app/javascript/shared/components/ChatForm.vue, app/javascript/shared/components/CustomerSatisfaction.vue, app/javascript/widget/components/UserMessageBubble.vue, app/javascript/widget/components/template/EmailInput.vue
Fixes https://github.com/chatwoot/chatwoot/issues/5771
https://www.loom.com/share/a587e27c5cd14ae98c8142a08053238b
=> fix: Text colour is getting merged with the light background colour

config/initializers/01_redis.rb, config/initializers/rack_attack.rb, lib/global_config.rb, lib/redis/alfred.rb, spec/controllers/api/v1/accounts/csat_survey_responses_controller_spec.rb
=> chore:  Use connection_pool for redis

app/javascript/shared/constants/messages.js, app/javascript/widget/components/HeaderActions.vue
Fixes #5766
https://www.loom.com/share/31f0509edce241988ac9bc755193f01a
=> fix: Allow ending the conversation if snoozed or pending

app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
=> fix: Update invalid payload for template messages

app/controllers/api/v1/accounts/macros_controller.rb, app/models/macro.rb, app/models/user.rb, app/policies/macro_policy.rb, db/migrate/20221102082737_change_macros_created_by_to_null.rb, db/schema.rb, spec/controllers/api/v1/accounts/macros_controller_spec.rb, spec/models/macro_spec.rb
Macros policy update.
Fixes #5730 
Tested on local
=> fix: Macros authorizations

app/javascript/dashboard/components/widgets/conversation/bubble/Location.vue, app/javascript/dashboard/components/widgets/conversation/stories/LocationBubble.stories.js, app/javascript/dashboard/i18n/locale/en/settings.json
- Adds a component to show location type messages in dashboard
=> feat: Adds component to show location based messages

app/jobs/inboxes/fetch_imap_emails_job.rb, lib/exception_list.rb
=> fix: SocketError: getaddrinfo: for imap channels

app/javascript/dashboard/components/widgets/Thumbnail.spec.js, app/javascript/dashboard/components/widgets/Thumbnail.vue
**After**
https://user-images.githubusercontent.com/1277421/200721146-b2b82aa9-b144-49fa-980a-c6c4ee0d25dc.mov
**Before**
https://user-images.githubusercontent.com/1277421/200721215-1bae1115-ad33-46d1-981d-b939a32721ef.mov
=> feat: Improves image loading for thumbnails

app/views/api/v1/models/_user.json.jbuilder, config/features.yml
- Added feature flag `mobile_v2` to roll out new UI changes in the mobile app.
- Added `features` in `sign_in` response payload.
=> chore: Add feature flag for mobile v2

app/javascript/dashboard/helper/specs/macrosFixtures.js, app/javascript/dashboard/helper/specs/macrosHelper.spec.js, app/javascript/dashboard/mixins/macrosMixin.js, app/javascript/dashboard/mixins/specs/macros.spec.js, app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue, app/javascript/dashboard/routes/dashboard/settings/macros/MacroEditor.vue, app/javascript/dashboard/routes/dashboard/settings/macros/MacroNode.vue, app/javascript/dashboard/routes/dashboard/settings/macros/constants.js, app/javascript/dashboard/routes/dashboard/settings/macros/macroHelper.js
=> Feat: add agents in macros

app/javascript/dashboard/components/widgets/Avatar.vue, app/javascript/dashboard/components/widgets/Thumbnail.vue, app/javascript/dashboard/components/widgets/ThumbnailGroup.vue, app/javascript/shared/components/ui/MultiselectDropdownItems.vue
- Disables selection cursor on Thumbnails with a name to give image feel
- Adds title property on thumbnail for screen reader support
- Adds gap property for group thumbnails
- Dropdown selection design more visually identifiable
=> chore: Design improvements for Thumbnails and dropdown

app/models/concerns/activity_message_handler.rb
chore: Activity message generation for team assignment automation
Tested on local
=> fix: Activity message generation for team assignment automation

config/features.yml, db/migrate/20221116000514_enable_macros_for_all_accounts.rb, db/schema.rb
- migrations to enable macros for all accounts
=> chore: Enable Macros for all accounts

app/javascript/dashboard/modules/widget-preview/components/Widget.vue, app/javascript/dashboard/modules/widget-preview/components/WidgetBody.vue, app/javascript/dashboard/modules/widget-preview/components/WidgetHead.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue
Fixes https://github.com/chatwoot/product/issues/644
=> chore: Cleanup the design in the widget builder

app/javascript/dashboard/mixins/macrosMixin.js, app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue, app/javascript/dashboard/routes/dashboard/settings/macros/constants.js, app/models/macro.rb, app/services/action_service.rb, spec/controllers/api/v1/accounts/macros_controller_spec.rb
Fixes #5734 
https://user-images.githubusercontent.com/10827585/202176037-51a0738c-d91f-49fa-abcf-2b66c8fd146f.mov
=> feat: Remove labels in macro

app/javascript/dashboard/routes/dashboard/Dashboard.vue
Fixes https://github.com/chatwoot/product/issues/669
**Screenshot**
=> fix: Sidebar missing at 1200px width

app/javascript/dashboard/i18n/index.js, app/javascript/dashboard/i18n/locale/en/generalSettings.json, app/javascript/survey/i18n/index.js, app/javascript/widget/i18n/index.js, config/initializers/languages.rb
=> chore: Enable Latvian (lv) language

app/jobs/webhooks/whatsapp_events_job.rb, app/mailers/administrator_notifications/channel_notifications_mailer.rb, app/models/channel/whatsapp.rb, app/models/concerns/reauthorizable.rb, app/services/whatsapp/incoming_message_base_service.rb, app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb, app/views/mailers/administrator_notifications/channel_notifications_mailer/whatsapp_disconnect.liquid, spec/jobs/webhooks/whatsapp_events_job_spec.rb, spec/mailers/administrator_notifications/channel_notifications_mailer_spec.rb, spec/models/channel/whatsapp_spec.rb, spec/services/whatsapp/incoming_message_whatsapp_cloud_service_spec.rb
fixes: https://github.com/chatwoot/chatwoot/issues/5782
=> chore: Add reauthorization prompt for Whatsapp Channel

app/models/concerns/activity_message_handler.rb, spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
unassign team activity message
Fixes #5911 
https://user-images.githubusercontent.com/10827585/204370830-0c600536-9e1e-4249-b45f-9523af42a658.mov
=> fix: unassign team activity message

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Fixes #6000 
https://www.loom.com/share/34935da28b854fb1a7f17156cb5a9db3
=> fix: Avoid conversationId getting undefined in unattended view

app/javascript/dashboard/i18n/locale/en/signup.json, app/javascript/dashboard/routes/auth/Signup.vue, app/javascript/dashboard/routes/auth/auth.routes.js, package.json, yarn.lock
Use business email address to signup to Chatwoot.
=> chore: Add business email validation on signup

app/javascript/dashboard/routes/auth/components/Signup/Form.vue
Remove duplicate submit action introduced in #6002
=> fix: Remove duplicate submit action

app/javascript/dashboard/helper/actionQueryGenerator.js
Fixes https://github.com/chatwoot/chatwoot/issues/6007
https://www.loom.com/share/fd7948c0cbcb4db89d1066f2e4480e06
=> fix: Unable to save automation "send email to team"

app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsBasicForm.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ListAllCategories.vue, app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
Fixes https://github.com/chatwoot/product/issues/715
https://www.loom.com/share/15298a4164584db7a964918a2066ba6d
Also, you can refer loom video in the issue.
=> fix: Helpcenter improvements

app/javascript/dashboard/components/ui/Label.vue, app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue, app/javascript/dashboard/i18n/locale/en/conversation.json
Co-authored-by: Nithin David Thomas <webofnithin@gmail.com>
This is a spin-off PR from #6026, taking on the changes required for https://github.com/chatwoot/chatwoot/issues/4085
Fixes #4085
=> feat: Display labels in the conversation card

app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss, app/javascript/dashboard/components/SidemenuIcon.vue, app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue, app/javascript/dashboard/components/specs/__snapshots__/SidemenuIcon.spec.js.snap, app/javascript/dashboard/routes/dashboard/Dashboard.vue, app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
Fixes https://github.com/chatwoot/chatwoot/issues/5360
https://www.loom.com/share/403153b8269d45c3b75d50ead1ec0b2d
=> feat: Adds the ability to toggle the secondary sidebar in all display breakpoints

app/javascript/survey/views/Response.vue
Fixes https://github.com/chatwoot/chatwoot/issues/5450
https://www.loom.com/share/88207245613d4ebcb62fef22e81d744a
=> chore: Fixes issue showing the CSAT error message

enterprise/app/models/enterprise/account.rb, spec/enterprise/models/account_spec.rb
Fixes the issue the selection of the agent and inbox limits
=> fix: Update account limit selection logic

app/javascript/dashboard/helper/AudioAlerts/DashboardAudioNotificationHelper.js, app/javascript/dashboard/helper/scriptHelpers.js, app/javascript/dashboard/i18n/locale/en/settings.json, app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
This PR allows us to play an audio alert every 30 seconds if we have an unread conversation in mine list.
Fixes https://github.com/chatwoot/product/issues/732
**Screenshot**
=> feat: Adds the ability to play audio alert every 30 sec

app/javascript/dashboard/components/widgets/modal/WootKeyShortcutModal.vue, app/javascript/dashboard/i18n/locale/en/settings.json, app/javascript/dashboard/routes/dashboard/Dashboard.vue
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
=> chore: Refactor shortcuts modal to use modal component

app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue, app/javascript/dashboard/store/modules/conversations/index.js, app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js, app/models/message.rb
Fixes https://github.com/chatwoot/chatwoot/issues/6130
=> fix: Update unread_messages count in WhatsApp inboxes

app/javascript/sdk/bubbleHelpers.js
Buttons must have discernible text
https://dequeuniversity.com/rules/axe/4.4/button-name?utm_source=lighthouse&utm_medium=lr
=> Buttons must have discernible text

app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
Context: [InApp#20824](https://app.chatwoot.com/app/accounts/1/conversations/20824)
- The page size was wrong in the table
- The sort by name was unusable if you have phone number contacts. Changed it to last_activity.
=> fix: Update the page size to 15, change default sort to last_activity

app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
=> Update error message in Custom Attributes

app/javascript/dashboard/assets/scss/_foundation-settings.scss, app/javascript/dashboard/assets/scss/widgets/_modal.scss, app/javascript/dashboard/components/ModalHeader.vue, app/javascript/dashboard/components/widgets/modal/ConfirmationModal.vue, app/javascript/dashboard/routes/dashboard/settings/macros/MacroNode.vue
=> fix: Fixes broken style in automation page

app/services/instagram/message_text.rb
=> chore: Fix sentry errors for Instagram channel

app/drops/contact_drop.rb, app/drops/user_drop.rb, app/models/concerns/liquidable.rb, app/models/message.rb, spec/drops/contact_drop_spec.rb, spec/drops/user_drop_spec.rb, spec/models/concerns/liquidable_shared.rb, spec/models/message_spec.rb
Fixes https://github.com/chatwoot/chatwoot/issues/6078
=> feat: Add variable support in outgoing messages

app/javascript/packs/sdk.js, app/javascript/widget/App.vue
Fixes https://github.com/chatwoot/product/issues/714
https://www.loom.com/share/3e241f230ed04747b743d1de8a9a6ebd
=> fix: Use account locale as the default locale on widget

app/javascript/sdk/sdk.js
**Fixes** https://github.com/chatwoot/product/issues/741
https://user-images.githubusercontent.com/1277421/212156931-22af9455-6939-468f-9b62-304335453cb2.mov
https://user-images.githubusercontent.com/1277421/212157096-b72716a7-3a91-4fc2-845f-1d7aebfd1bd3.mov
https://user-images.githubusercontent.com/1277421/212157120-219fa71f-8605-42ee-a5e0-e5f361142038.mov
=> fix: Adds animation to live chat trigger button

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue, app/javascript/dashboard/components/widgets/conversation/TagAgents.vue, app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
Revert canned response styles from https://github.com/chatwoot/chatwoot/pull/6145
=> chore: Update styles for canned response

app/javascript/dashboard/i18n/locale/en/settings.json
Success toast content for copy action made generic that fits all the context and scenarios.
=> Fixes #3670

app/javascript/dashboard/routes/dashboard/settings/campaigns/EditCampaign.vue
=> fix: Update the inbox id if changed

app/javascript/dashboard/i18n/locale/en/signup.json
Fixes #3655
The language used on Sign up page is made consistent throughout the flow.
Register and Sign up have been replaced with Create.
=> chore: Update Inconsistent lang

app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplatesPicker.vue
Enforce lowercasing the template status value before checking the value
=> fix: Whatsapp template picker bug

app/javascript/dashboard/store/modules/conversations/actions.js
=> Fix: more events tracking for SaaS (#6234)

app/javascript/packs/application.js
This PR ignores errors from chrome and safari extensions, and any local scripts by developers
=> feat: ignore errors from extensions

app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue, app/javascript/dashboard/helper/AnalyticsHelper/events.js
- Add an event for conversation filter
=> chore: Add an event for conversation filter

app/javascript/dashboard/components/widgets/conversation/CannedResponse.vue, app/javascript/dashboard/components/widgets/conversation/VariableList.vue, app/javascript/dashboard/components/widgets/mentions/MentionBox.vue, app/javascript/dashboard/routes/dashboard/settings/canned/AddCanned.vue, app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue
=> fix: Update styles for canned responses modal

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
=> fix: Fixes enter key sending text while mentions menu is active

config/initializers/languages.rb
- Enable Icelandic language
ref: https://discord.com/channels/647412545203994635/705731737652559995/1066008289806131200
=> chore: Enable language Icelandic(is)

spec/builders/messages/message_builder_spec.rb
refer: https://github.com/chatwoot/chatwoot/pull/6320
=> Chore: specs for process_emails in message builder

app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
Fixes https://github.com/chatwoot/product/issues/788
This PR will increase the size of the canned response item. 
=> fix: Increases font size for canned response list item

.github/workflows/lock.yml
=> feat: Don't run lock action on forks

Gemfile.lock
- update new relic agent to 8.15
=> chore: Update New relic agent

app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/views/api/v1/models/_contact.json.jbuilder
Shows contact created date in contact panel and contacts listing page
=> feat: Show contact created date in contact panel

app/javascript/dashboard/i18n/locale/pt_BR/conversation.json
The "open action" translation would be "Abrir" (verb) instead of "Abertas" (which is the adjective).
Changed pt_br translation of the "open_action" in conversation.json
=> Translation Fix

app/controllers/platform/api/v1/users_controller.rb, app/models/concerns/sso_authenticatable.rb, app/views/super_admin/users/_impersonate.erb, app/views/super_admin/users/show.html.erb, lib/seeders/account_seeder.rb, lib/seeders/seed_data.yml
- adds the ability to impersonate a user
- fix issues with generate seed data
- add labels to generate seed data
Fixes: https://github.com/chatwoot/product/issues/778
1. impersonate user
2. updated seed data
=> feat: Ability for super admin to impersonate a user

app/javascript/dashboard/components/widgets/conversation/Message.vue
Fixes frontend rendering error.
=> fix: data.attachments is undefined for emails without body

lib/integrations/slack/send_on_slack_service.rb, spec/lib/integrations/slack/send_on_slack_service_spec.rb
=> chore: Add subject line to the slack message summary

app/models/macro.rb
Removes pagination form macros get endpoint
Fixes #6410
=> chore: Remove pagination from macros listing api

app/javascript/dashboard/mixins/specs/time.spec.js
Fix time.spec.js test breaking Circle CI builds
=> test: fix test breaking circle CI

.rubocop.yml, app/javascript/dashboard/i18n/locale/en/integrations.json, app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookForm.vue, app/listeners/webhook_listener.rb, app/models/contact.rb, app/models/webhook.rb, db/migrate/20230209033203_update_default_on_subscriptions_webhooks.rb, db/schema.rb, spec/controllers/api/v1/accounts/webhook_controller_spec.rb, spec/factories/webhooks.rb, spec/listeners/webhook_listener_spec.rb, swagger/definitions/resource/webhook.yml, swagger/swagger.json
Fixes #6176 
- Added webhooks for contacts
=> feat: Add contacts webhooks

Gemfile, Gemfile.lock, app/views/api/v2/accounts/reports/agents.csv.erb, app/views/api/v2/accounts/reports/inboxes.csv.erb, app/views/api/v2/accounts/reports/labels.csv.erb, app/views/api/v2/accounts/reports/teams.csv.erb
- Adds `csv-safe` gem to avoid csv injection
fixes: https://github.com/chatwoot/product/issues/651
=> chore: Switch to csv-safe gem to avoid csv injection

app/controllers/public/api/v1/portals/articles_controller.rb, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue, app/models/article.rb, spec/controllers/public/api/v1/portals/articles_controller_spec.rb, spec/factories/articles.rb
Followup from #6429
- Use update_column, add specs.
=> chore: Add formatting for the view count

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Fixes #https://github.com/chatwoot/product/issues/704
=> fix: Send attachments as multiple messages for whatsapp channel

config/initializers/rack_attack.rb
ref: https://github.com/chatwoot/chatwoot/issues/1007#issuecomment-1427156094
=> chore: Limit widget endpoint with rack attack

app/javascript/dashboard/routes/dashboard/conversation/ConversationParticipant.vue
=> fix: Add scoped CSS for participants

app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue, app/views/layouts/vueapp.html.erb
Fixes https://github.com/chatwoot/chatwoot/issues/3620
Fixes https://github.com/chatwoot/chatwoot/issues/5525
--- 
Works on Safari 16+
https://www.loom.com/share/66e7e2421851477dbfe39cf84503c672
=> chore: Enable push permissions if available

app/javascript/dashboard/routes/dashboard/conversation/ConversationParticipant.vue
=> fix: Warning in conversations page from participants

.github/workflows/run_foss_spec.yml
- Upload rails log folder as an artifact after foss_spec github action
- Pin node version to 16
=> fix: foss_spec github action

.env.example, app/javascript/dashboard/helper/scriptHelpers.js, app/javascript/dashboard/store/index.js, app/javascript/packs/application.js, app/views/layouts/vueapp.html.erb, package.json, yarn.lock
This PR integrates LogRocket on the frontend
To test this locally create an account on LogRocket, set the project ID in the .env file and run the app. The LogRocket dashboard should start receiving events automatically
=> feat: Integrate LogRocket

.devcontainer/Dockerfile.base
Bumped Ruby version on codespace docker image to match the new Ruby version 3.1.3, which is required since from 2.14.
Updated on my own registry and it worked fine.
=> Bumped Ruby version on codespace image to 3.1.3

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/SidemenuIcon.vue, app/javascript/dashboard/components/layout/AvailabilityStatus.vue, app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue, app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue, app/javascript/dashboard/routes/dashboard/conversation/search/SwitchLayout.vue
**Before**
**After**
With direction RTL
=> chore: Refactors chatlist header css to work with RTL

app/javascript/dashboard/assets/scss/views/settings/integrations.scss, app/javascript/dashboard/routes/dashboard/settings/integrationapps/IntegrationItem.vue, app/javascript/dashboard/routes/dashboard/settings/integrationapps/SingleIntegrationHooks.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Integration.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/IntegrationHelpText.vue
Refactor integrations and application pages
=> chore: Refactor integrations pages for RTL

app/controllers/widgets_controller.rb, spec/controllers/widgets_controller_spec.rb
=> fix: ActiveRecord::RecordNotFound Couldn't find Channel::WebWidget

app/javascript/dashboard/assets/scss/_date-picker.scss, app/javascript/dashboard/assets/scss/_foundation-custom.scss, app/javascript/dashboard/assets/scss/_utility-helpers.scss, app/javascript/dashboard/assets/scss/plugins/_multiselect.scss, app/javascript/dashboard/assets/scss/widgets/_reports.scss, app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue, app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue, app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue, app/javascript/dashboard/routes/dashboard/settings/campaigns/AddCampaign.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookForm.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
Refactor reports and removed `margin-right-small` class to `margin-right-1` same for left
=> chore: Refactor reports for RTL

app/javascript/dashboard/components/widgets/conversation/Message.vue
Add missing CSAT responses in the message.
=> chore: Display CSAT responses in the message itself

app/javascript/dashboard/assets/scss/_rtl.scss, app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss, app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/components/widgets/InboxName.vue, app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
=> chore: Refactor chat list for RTL

app/javascript/dashboard/assets/scss/_rtl.scss, app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss, app/javascript/dashboard/components/widgets/BackButton.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue, app/javascript/dashboard/modules/contact/components/ContactDropdownItem.vue, app/javascript/dashboard/modules/notes/components/ContactNote.vue, app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue, app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue, app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/SocialIcons.vue
- Emoji box
- Back button in all header view
- Bulk action
- Contact info panel on all screens
=> chore: Refactor conversation info panel for RTL

app/javascript/dashboard/assets/scss/_rtl.scss, app/javascript/dashboard/assets/scss/plugins/_multiselect.scss, app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss, app/javascript/dashboard/components/widgets/TableFooter.vue, app/javascript/dashboard/components/widgets/UserAvatarWithName.vue, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue, app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanel.vue, app/javascript/dashboard/routes/dashboard/settings/campaigns/CampaignsTable.vue, app/javascript/dashboard/routes/dashboard/settings/macros/MacrosTableRow.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
=> chore: Refactor tables in all screen for RTL

app/javascript/dashboard/assets/scss/widgets/_report.scss, app/javascript/dashboard/assets/scss/widgets/_reports.scss, app/javascript/dashboard/components/widgets/UserAvatarWithName.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetricCard.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetrics.vue
This is PR is related to reports page SCSS clean up and minor spacing issues
=> chore: Refactor reports css for RTL

app/javascript/dashboard/App.vue, app/javascript/shared/mixins/rtlMixin.js
Fixes https://github.com/chatwoot/product/issues/813
>Also, not that the RTL doesn't work automatically if I've previously selected Arabic. I've to go to the Account Settings and update it.
This PR will fix this issue.
=> chore: Adds the ability to automatically initialize the RTL direction

app/controllers/public/api/v1/portals/articles_controller.rb, app/controllers/public/api/v1/portals/base_controller.rb, app/controllers/public/api/v1/portals/categories_controller.rb, app/controllers/public/api/v1/portals_controller.rb, app/controllers/public_controller.rb, app/views/public/api/v1/portals/_article_count.html.erb, app/views/public/api/v1/portals/_category-block.html.erb, app/views/public/api/v1/portals/_footer.html.erb, app/views/public/api/v1/portals/_header.html.erb, app/views/public/api/v1/portals/articles/index.html.erb, app/views/public/api/v1/portals/articles/show.html.erb, app/views/public/api/v1/portals/categories/_category-block.html.erb, app/views/public/api/v1/portals/categories/_hero.html.erb, app/views/public/api/v1/portals/categories/show.html.erb, config/locales/en.yml, config/locales/fr.yml
Fixes the following
- Fix search in the public portal with multiple locales.
- Fix the i18n selection in the portal.
- Fix the issues with locale variants used in the portal.
- Fix the language, and plurals.
=> fix: Fix i18n issues with help center

app/controllers/api/v1/accounts/search_controller.rb, app/jobs/migration/add_search_indexes_job.rb, app/models/contact.rb, app/models/message.rb, app/services/search_service.rb, app/views/api/v1/accounts/search/_agent.json.jbuilder, app/views/api/v1/accounts/search/_contact.json.jbuilder, app/views/api/v1/accounts/search/_inbox.json.jbuilder, app/views/api/v1/accounts/search/_message.json.jbuilder, app/views/api/v1/accounts/search/contacts.json.jbuilder, app/views/api/v1/accounts/search/conversations.json.jbuilder, app/views/api/v1/accounts/search/index.json.jbuilder, app/views/api/v1/accounts/search/messages.json.jbuilder, config/routes.rb, db/migrate/20230224124632_add_index_for_search_operations.rb, db/schema.rb, spec/controllers/api/v1/accounts/search_controller_spec.rb, spec/services/search_service_spec.rb
- Adding new API endpoints for search
- migrations to add appropriate indexes
=> feat: New APIs for search

app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
This issue occurred with the click away used in the component. By this PR, the click away was handled in some instances.
Fixes https://github.com/chatwoot/product/issues/814
https://www.loom.com/share/1d5f8fae883a4765b94fb062b6284a8b
=> bug: Bulk actions Assign agent is not working

app/views/public/api/v1/portals/show.html.erb
Refer: https://github.com/chatwoot/chatwoot/issues/5462
=> fix: Show only categories where published articles count > 0

spec/services/search_service_spec.rb
- fixing flaky test in search service spec
=> chore: Fix flaky test in search service spec

app/javascript/dashboard/modules/search/components/SearchResultConversationItem.vue, app/javascript/dashboard/modules/search/stories/SearchResultConversationItem.stories.js
This component will be used in the upcoming search revamp to display conversation results from search.
=> feat: Creates component to display conversation search results

swagger/definitions/resource/contact.yml, swagger/swagger.json
=> Update: contact create swagger JSON

config/schedule.yml
Minor change, fixing comments in schedule.yml
This change do not need to be tested.
=> Fix comment in schedule.yml

app/services/message_templates/hook_execution_service.rb
=> chore: Ensure Template messages work even when bot is connected

app/services/whatsapp/providers/whatsapp_cloud_service.rb
refs https://github.com/chatwoot/chatwoot/pull/5142
=> feat: add env WHATSAPP_CLOUD_BASE_URL

config/locales/en.yml
Refer: https://github.com/chatwoot/product/issues/804
Sentry issue: [CHATWOOT-3VN](https://chatwoot-p3.sentry.io/issues/3979498183/?referrer=github_integration)
=> fix: String interpolation

app/controllers/api/v1/accounts/articles_controller.rb, app/controllers/public/api/v1/portals/articles_controller.rb, app/controllers/public/api/v1/portals/categories_controller.rb, app/models/article.rb, app/views/api/v1/accounts/articles/_article.json.jbuilder, app/views/public/api/v1/models/_article.json.jbuilder, app/views/public/api/v1/portals/_category-block.html.erb, app/views/public/api/v1/portals/categories/_category-block.html.erb, app/views/public/api/v1/portals/show.html.erb, db/migrate/20230313113920_add_position_to_articles.rb, db/schema.rb, spec/controllers/api/v1/accounts/articles_controller_spec.rb, spec/controllers/api/v1/accounts/categories_controller_spec.rb
Fixes: #819 
https://www.loom.com/share/de927a627df248eb91b1542f6cb1ab6d
=> feat: Backend changes for article and categories ordering

app/models/contact.rb, app/models/installation_config.rb, app/models/message.rb, app/models/notification.rb, app/services/search_service.rb, spec/controllers/api/v1/accounts/search_controller_spec.rb, spec/services/search_service_spec.rb
- strip search term before searching
- order messages by created_at desc
- order contacts by last_activity_at desc
- order conversations by created_at desc
- Search only resolved contacts 
- optimize resolved contacts query 
ref: #6583
=> chore: Search optimisations

Gemfile, Gemfile.lock, config/application.rb
- Capture sidekiq metric in newrelic
=> chore: Add sidekiq metrics to newrelic

app/controllers/api/v1/accounts/agents_controller.rb, spec/controllers/api/v1/accounts/agents_controller_spec.rb
=> fix: delete user record if belongs to no account

app/javascript/survey/i18n/index.js, app/javascript/widget/i18n/index.js
=> chore: Enable Icelandic language

yarn.lock
Fixes: https://github.com/chatwoot/product/issues/781
=> chore: Upgrade prosemirror package to fix link rendering issue

app/controllers/api/v1/accounts/microsoft/authorizations_controller.rb, app/controllers/microsoft/callbacks_controller.rb, spec/controllers/api/v1/accounts/microsoft/authorization_controller_spec.rb
The microsoft outlook inbox channel has issues:
- Case sensitivity of the email
- The lack of request for profile during the login step in the scope
We used this internally for a few weeks
=> Fix issues with Microsoft Provider

app/controllers/api/v1/accounts/inboxes_controller.rb, config/locales/en.yml, spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1342/inboxes-with-large-number-of-conversations-and-messages-cannot-be
=> [CW-1342]: Inbox deletion in background job

app/javascript/dashboard/modules/search/components/SearchView.vue
Fixes the scrolling issue with the search page.
https://user-images.githubusercontent.com/1277421/226525298-b980ec3e-cfa4-41b8-bdee-4951286ffbf4.mov
=> fix: Fixes scroll behaviour for search page

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
This PR includes a fix for
1. Chat list header for custom views
2. Contact header
Fixes https://linear.app/chatwoot/issue/CW-1314/design-issues-after-rtl-changes
https://www.loom.com/share/1a62141f07f44df0a61e81c2a964c1e9
=> fix: Design issues after RTL changes [CW-1314]

app/finders/message_finder.rb, app/javascript/dashboard/api/inbox/message.js, app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/bubble/TranslateModal.vue, app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItem.vue, app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue, app/javascript/dashboard/store/modules/conversations/actions.js
- Move translate modal to another component
- Add a before check for the after params (after param wouldn't work without a before param)
- Remove unused CSS
- Fix a bug with the opacity (percentages in opactity doesn't work due to the webpack bug, need to upgrade the versions)
=> chore: Refactor messages to support right click context menu

app/drops/contact_drop.rb, app/drops/user_drop.rb, app/javascript/dashboard/helper/messageHelper.js, app/javascript/dashboard/helper/specs/messageHelper.spec.js, spec/drops/contact_drop_spec.rb, spec/drops/user_drop_spec.rb
=> chore: Auto capitalize the last name field while sending the canned response/variables

lib/integrations/slack/send_on_slack_service.rb, spec/lib/integrations/slack/send_on_slack_service_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1352/mentions-are-not-rendered-properly-in-slack
=> fix: mentions are not rendered properly in slack

app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Follow up fix for https://github.com/chatwoot/chatwoot/pull/6701
=> chore: Fixes avatar position on failed messages

app/models/concerns/auto_assignment_handler.rb, app/services/messages/mention_service.rb, spec/models/concerns/auto_assignment_handler_shared.rb
- Ensures that the assignee is added as a participant during auto-assign
=> fix: Adds assignee as a participant during auto-assign

app/services/whatsapp/incoming_message_base_service.rb, app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb, spec/services/whatsapp/incoming_message_whatsapp_cloud_service_spec.rb
Fixes #https://github.com/chatwoot/chatwoot/issues/6779
=> fix: Check valid params are exist in `WhatsAapp` payload

app/javascript/dashboard/routes/dashboard/settings/automation/constants.js, lib/automation_rules/conditions.json
https://linear.app/chatwoot/issue/CW-1426/run-automation-on-contactemail-address
https://www.loom.com/share/9a52bea472c9449c9448cf284ef7cc20
=> fix: Email based automation conditions filter

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Fixes https://linear.app/chatwoot/issue/CW-1428/copy-phone-number-from-user-details-on-the-right-side-of-the-panel
https://www.loom.com/share/81ad1e7070754470abe3fb6b7512f00e
=> chore: Adds the ability to copy phone number from user details

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Fixes #6776
https://user-images.githubusercontent.com/12408980/228447351-eeb8f49b-6550-4fc7-9e3f-d2ba876eb3e0.mov
=> fix: Agent avatar instead of bot avatar in pending message

app/javascript/dashboard/i18n/locale/en/advancedFilters.json, app/javascript/dashboard/routes/dashboard/settings/automation/constants.js, app/javascript/dashboard/routes/dashboard/settings/automation/operators.js, app/models/article.rb, app/models/automation_rule.rb, app/services/automation_rules/conditions_filter_service.rb, app/services/filter_service.rb, lib/automation_rules/conditions.json, lib/filters/filter_keys.json, spec/services/automation_rules/conditions_filter_service_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1427/run-automation-on-contactphone-number
https://www.loom.com/share/2ea7b683efa3455283e21ca7f4e1b321
=> feat: Phone number based automation conditions

lib/integrations/slack/send_on_slack_service.rb, spec/lib/integrations/slack/send_on_slack_service_spec.rb
| -- | -- |
| <img width="672" alt="Screenshot 2023-04-02 at 10 13 03 PM" src="https://user-images.githubusercontent.com/2246121/229417126-79c0fffd-7d7f-4288-ae49-01b2d43378cf.png"> | <img width="454" alt="Screenshot 2023-04-02 at 10 13 41 PM" src="https://user-images.githubusercontent.com/2246121/229417215-44a799c5-f2bc-4005-adbc-ce8a750fc550.png"> | 
- Set unfurl_links to false in the first message.
- Update the message text.
=> chore: Update conversation thread rendering in Slack

lib/integrations/slack/send_on_slack_service.rb
=> slack with template message link

app/javascript/widget/components/PreChat/Form.vue
Fixes https://linear.app/chatwoot/issue/CW-1458/pre-chat-form
https://www.loom.com/share/5fdd8de01feb4669afe42c7fe134ee7a
=> fix: Disable the pre-chat form in new conversation if pre-chat is disabled

app/jobs/data_import_job.rb, spec/assets/contacts.csv, spec/jobs/data_import_job_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1399/contacts-import-does-not-assign-phone-number-field
=> CW-1399 Phone number import

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Updates the frontend to allow agents to merge contacts
=> feat: allow agents to merge contacts

app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
Fixes https://github.com/chatwoot/chatwoot/issues/6642
Search bar is very little visible in chatwoot. This PR implements adding background color for search bar 
- Run the app and visit account dashboard
- Check search bar is highlighted with background color
=> Search bar improvements

app/services/whatsapp/providers/whatsapp_cloud_service.rb
Fixes: https://linear.app/chatwoot/issue/CW-1464/message-templates-pagination-is-missing
=> Feat: Fetch whatsapp templates till next cursor

.gitignore, enterprise/app/controllers/api/v1/accounts/audit_logs_controller.rb, spec/enterprise/controllers/api/v1/accounts/audit_logs_controller_spec.rb
- add pagination support for audit logs api
-  Tested locally via an API client
`{{host}}/api/{{api_version}}/accounts/{{account_id}}/audit_logs?page=1&per_page=1`
<details>
<summary>response</summary>
```json
{
"audit_logs": [
{
"id": 41,
"auditable_id": 8,
"auditable_type": "Label",
"associated_id": 1,
"associated_type": "Account",
"user_id": 1,
"user_type": "User",
"username": "john@acme.inc",
"action": "create",
"audited_changes": {
"color": "#950C83",
"title": "test10",
"account_id": 1,
"description": "test10",
"show_on_sidebar": true
},
"version": 1,
"comment": null,
"remote_address": "127.0.0.1",
"request_uuid": "66f53c31-cf07-4075-bda9-070e327e8278",
"created_at": "2023-02-23T10:45:59.597Z"
},
{
"id": 42,
"auditable_id": 1, …
```
=> feat: add pagination support for auditlogs api

app/mailers/conversation_reply_mailer.rb, config/locales/en.yml, spec/mailers/conversation_reply_mailer_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1422/smtp-error
=> Add email address in from header of email

app/controllers/twitter/callbacks_controller.rb, spec/controllers/twitter/callbacks_controller_spec.rb
fixes: https://chatwoot-p3.sentry.io/share/issue/355dcb62b2194bfbb3d11434e90dcffe/
=> fix: response body in twitter callback

app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
=> feat: show webhook verify token for WhatsApp

app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue, app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/helper/scriptHelpers.js
- Add account_id in the custom_attributes while signing in.
- Reset the dashboard app index to 0 on switching a conversation.
=> chore: Cloud account management updates

swagger/paths/index.yml, swagger/swagger.json
Fixes: https://linear.app/chatwoot/issue/CW-1394/delete-agent-in-inbox-inbox-id-in-path-and-body
=> Delete inbox api doc update

app/services/action_service.rb, spec/listeners/automation_rule_listener_old_spec.rb, spec/services/automation_rules/action_service_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1432/allow-variables-in-automation
https://www.loom.com/share/e41a20766ab74e88bc4938688f540be7
=> feat: Support multiple emails in email transcript automation

app/models/message.rb, app/services/whatsapp/incoming_message_base_service.rb, app/services/whatsapp/incoming_message_service_helpers.rb
- Process `message.context.id`.
- Save the reply_to id and search for messages with the id.
=> feat: Save in_reply_to from WhatsApp messages

app/javascript/dashboard/components/widgets/conversation/PriorityMark.vue, app/models/conversation.rb, app/presenters/conversations/event_data_presenter.rb, spec/models/conversation_spec.rb, spec/presenters/conversations/event_data_presenter_spec.rb
Includes the following changes
1. Update the colors of urgent icon
2. Trigger `conversation.updated` event on priority change
=> feat: improvements to priority 

app/javascript/dashboard/i18n/locale/en/login.json, app/javascript/dashboard/i18n/locale/en/resetPassword.json, app/javascript/dashboard/i18n/locale/en/setNewPassword.json, app/javascript/dashboard/i18n/locale/en/signup.json
=> feat: update product copy [CWM-45]

app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue
Fixes https://linear.app/chatwoot/issue/CW-1603/enable-woot-message-editor-for-business-hours-message-with-enable
=>  feat: Enable rich editor support for unavailable message

app/models/contact.rb, db/migrate/20230426130150_add_index_for_widget_contact_look_up.rb, db/schema.rb
- Adds an index to improve the contact lookup performance while calling `setUser` from widget
=> chore: Add Index for widget contact lookup

lib/seeders/seed_data.yml
Update the seed_data.yml to remove `hello-world` messages and add messages that would look good on demos and screenshots
=> feat: update demo data to include better messages

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/mixins/conversations.js, app/javascript/dashboard/mixins/specs/conversation.spec.js
Temporary fix for https://linear.app/chatwoot/issue/CW-1525/duplicate-messages-in-whatsapp-conversations
=> fix: Remove duplicates message in WhatsApp Channel

Gemfile.lock, app/views/public/api/v1/portals/_header.html.erb, app/views/public/api/v1/portals/show.html.erb
- Do not display Uncategorized if the article is 0
- Fix the link from the articles
=> fix: Fix rendering issues in Help Center

Gemfile, Gemfile.lock, app/controllers/api/v1/accounts/portals_controller.rb, app/javascript/portal/application.scss, app/javascript/portal/components/PublicArticleSearch.vue, app/javascript/portal/components/PublicSearchInput.vue, app/javascript/shared/assets/stylesheets/shadows.scss, app/models/portal.rb, app/views/layouts/portal.html.erb, app/views/public/api/v1/models/_article.json.jbuilder, app/views/public/api/v1/portals/_category-block.html.erb, app/views/public/api/v1/portals/_header.html.erb, app/views/public/api/v1/portals/_hero.html.erb, app/views/public/api/v1/portals/_uncategorized-block.html.erb, app/views/public/api/v1/portals/articles/index.html.erb, app/views/public/api/v1/portals/articles/show.html.erb, app/views/public/api/v1/portals/categories/_category-block.html.erb, app/views/public/api/v1/portals/categories/_hero.html.erb, app/views/public/api/v1/portals/categories/index.html.erb, app/views/public/api/v1/portals/categories/show.html.erb, app/views/public/api/v1/portals/show.html.erb, public/assets/images/hc/grid.svg
=> chore: Update the design of the help center portal

app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/shared/constants/messages.js
Fixes #7045 
Tested sending messages on Facebook and Web boxes and sending audio in .wav format.
WhatsApp box sends audio in .ogg.
=> fix: Record audio in wav format for web/facebook

app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js, app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js, app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
Added all the specs missed in the PR https://github.com/chatwoot/chatwoot/pull/6853
=> chore: Add the specs for sort conversation

app/finders/conversation_finder.rb, app/javascript/dashboard/constants/globals.js, app/javascript/dashboard/i18n/locale/en/chatlist.json, app/javascript/dashboard/mixins/specs/time.spec.js, app/javascript/dashboard/store/modules/conversations/getters.js, app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js, app/javascript/shared/constants/messages.js
Fixes https://linear.app/chatwoot/issue/CW-1714/ui-sort-conversation-by-priority
https://github.com/chatwoot/chatwoot/assets/12408980/584e24e1-0038-4ca2-bdd1-eab3096ef716
=> feat: Order conversation by priority

app/javascript/dashboard/components/widgets/AIAssistanceButton.vue, app/javascript/dashboard/helper/AnalyticsHelper/events.js
- Added the analytics event for OpenAI features.
=> feat: Add analytics event for OpenAI

db/migrate/20230515051424_update_article_image_keys.rb, db/schema.rb
This PR introduces a migration `UpdateArticleImageKeys` that updates the image keys used in articles. It uses the `ArticleKeyConverter` class to perform the conversion process.
The ArticleKeyConverter class is responsible for replacing image keys within the content of an article. It utilizes the `ActiveSupport::KeyGenerator` and `ActiveSupport::MessageVerifier` classes to generate and verify keys for Active Storage blobs.
The process method within ArticleKeyConverter takes an article as input and performs the following steps:
1. Retrieves the content of the article.
2. Identifies image keys within the content.
3. Converts each image key using the convert_key method.
4. Replaces the original image key with the new key in the article's content, if a new key is found.
5. Updates the …
=> feat: add migration to fix image signed keys

app/javascript/survey/i18n/index.js, app/javascript/widget/i18n/index.js
=> chore: Enable Hebrew language for widget

app/jobs/inboxes/fetch_imap_emails_job.rb, spec/fixtures/files/mail_with_no_date.eml, spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1738/typeerror-no-implicit-conversion-of-nil-into-string-typeerror
=> fix: Email date attribute not being set

app/javascript/packs/portal.js, app/javascript/portal/application.scss, app/javascript/portal/components/TableOfContents.vue, app/javascript/portal/portalHelpers.js, app/javascript/portal/specs/portal.spec.js, app/views/layouts/portal.html.erb, app/views/public/api/v1/portals/articles/show.html.erb, config/locales/en.yml, package.json, tailwind.config.js, yarn.lock
=> feat: Show Table of Contents in the article sidebar

app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanelList.vue, app/javascript/dashboard/routes/dashboard/notifications/components/NotificationTable.vue
Fixes https://linear.app/chatwoot/issue/CW-1778/typeerror-cannot-read-properties-of-null-reading-assignee
=> chore: Check assignee exists or not before rendering the assignee avatar

app/javascript/dashboard/assets/scss/_rtl.scss
Fixes https://linear.app/chatwoot/issue/CW-1784/rtl-issue
=> fix: RTL issue for basic filter dropdown

spec/controllers/public/api/v1/inbox/conversations_controller_spec.rb
- fixes rubocop failures on develop
=> chore: Fix Rubocop failures

app/javascript/widget/store/modules/specs/appConfig/actions.spec.js
Fix breaking specs from https://github.com/chatwoot/chatwoot/pull/7167/files
=> fix: Update breaking specs

app/views/devise/mailer/confirmation_instructions.html.erb, spec/mailers/confirmation_instructions_spec.rb
Fixes copy issues with email being to sent to users who were invited to Chatwoot.
https://linear.app/chatwoot/issue/CW-1290/minor-ui-issues
=> fix: Fixes wrong copy being sent to users via email invite [cw-1290]

app/jobs/hook_job.rb, app/jobs/send_on_slack_job.rb, spec/jobs/hook_job_spec.rb, spec/jobs/send_on_slack_job_spec.rb
@sojan-official @pranavrajs This will resolve the issue tested it on production with exact changes :|
=> fix: issue with slack job

app/javascript/dashboard/components/widgets/conversation/Message.vue
Fixes https://linear.app/chatwoot/issue/CW-1820/ig-instagram-story-with-video-not-rendering
=> fix: Instagram story with video not rendering

swagger/definitions/index.yml, swagger/definitions/request/portal/article_create_update_payload.yml, swagger/definitions/request/portal/category_create_update_payload.yml, swagger/definitions/request/portal/portal_create_update_payload.yml, swagger/definitions/resource/article.yml, swagger/definitions/resource/category.yml, swagger/definitions/resource/portal.yml, swagger/index.yml, swagger/parameters/portal_id.yml, swagger/paths/application/article/create.yml, swagger/paths/application/category/create.yml, swagger/paths/application/portal/create.yml, swagger/paths/application/portal/index.yml, swagger/paths/application/portal/update.yml, swagger/paths/index.yml, swagger/swagger.json
Fixes: https://linear.app/chatwoot/issue/CW-1858/chore-swagger-doc-for-help-center-apis
=> fix: Help center api doc

app/models/concerns/pubsubable.rb, spec/models/user_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1350/
=> chore: Rotate pubsub token on password change

app/controllers/api/v1/accounts/contacts/contact_inboxes_controller.rb, app/controllers/api/v1/accounts/conversations_controller.rb, app/controllers/concerns/hmac_concern.rb, spec/controllers/api/v1/accounts/contacts/contact_inboxes_controller_spec.rb, spec/controllers/api/v1/accounts/conversations_controller_spec.rb
=> feat: API to create HMAC verified conversations

app/javascript/widget/components/AgentMessage.vue
Fixes https://linear.app/chatwoot/issue/CW-1789/special-characters-not-being-decoded
**Screenshot**
=> fix: Special characters not being decoded

app/mailboxes/imap/imap_mailbox.rb, spec/fixtures/files/references.eml, spec/mailboxes/imap/imap_mailbox_spec.rb
Fixes: https://linear.app/chatwoot/issue/CW-1780/in-reply-to-not-working-for-outgoing-microsoft-email
=> fix: find mail message by references

yarn.lock
This reverts commit 1d0930ef63908677117f3cb270741f3980e99227.
=> Revert "fix: Updates editor to fix the extra slash issue 

.github/workflows/size-limit.yml, package.json, yarn.lock
Add size limit action with the following limits 
- widget: `270 KB`
- sdk: `40 KB`
These serve as good starting points for us to start optimizing
=> feat: add size limit action

app/models/concerns/message_filter_helpers.rb, spec/models/message_spec.rb
fixes: https://github.com/chatwoot/chatwoot/issues/5291
=> feat: Enable sending template messages in web-hooks

app/javascript/dashboard/i18n/locale/en/auditLogs.json, app/javascript/dashboard/routes/dashboard/settings/auditlogs/Index.vue
Fixes https://linear.app/chatwoot/issue/CW-1761/update-the-display-text-for-automation-logs
Fixes https://linear.app/chatwoot/issue/CW-1760/update-the-display-text-for-inbox-logs
Fixes https://linear.app/chatwoot/issue/CW-1759/update-the-display-text-for-webhook-logs
=> feat: update display text for auditlog entries

app/javascript/dashboard/helper/scriptHelpers.js, app/views/api/v1/accounts/create.json.jbuilder
Fixes https://linear.app/chatwoot/issue/CW-2029/typeerror-cannot-read-properties-of-undefined-reading-always-play
=> fix: Cannot read properties of undefined (always_play_audio_alert)

app/jobs/inboxes/fetch_imap_emails_job.rb
=> fix: mail logger for source-id email-id and message-id

app/javascript/dashboard/App.vue, app/javascript/dashboard/components/app/UpdateBanner.vue, app/javascript/dashboard/components/ui/Banner.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Pull banner design changes from https://github.com/chatwoot/chatwoot/pull/7242
###Assign yourself
=> feat: update banner design [CW-1491]

app/views/mailers/conversation_reply_mailer/conversation_transcript.html.erb
Fixes sentry issue - https://chatwoot-p3.sentry.io/issues/4251693916/?referrer=webhooks_plugin
=> fix: Fixes wrong variable usage in email transcript template

spec/enterprise/services/enterprise/billing/handle_stripe_event_service_spec.rb
Fix failing specs for stripe handler
=> test: use as_json for formatting the date

app/services/widget/token_service.rb
This will look at environment variables and Rails Credentials and Rails Secrets.
See documentation here: https://api.rubyonrails.org/v7.0.5/classes/Rails/Application.html#method-i-secret_key_base
=> Update method to access "secret_key_base"

.github/workflows/lint_pr.yml
Ensure PR titles are in semantic format
ref: https://github.com/amannn/action-semantic-pull-request
=> chore(ci): Ensure PR titles are in semantic format

crowdin.yml
- add pull request titles
- skip ci for crowdin commits
=> chore: Update Crowdin Config

tailwind.config.js
Fix tailwind config missed during the upgrade.
=> chore: Fix darkMode styles in widget

app/javascript/dashboard/components/app/UpgradeBanner.vue, app/javascript/dashboard/i18n/locale/en/generalSettings.json, app/javascript/dashboard/i18n/locale/en/settings.json, app/javascript/dashboard/routes/dashboard/settings/billing/Index.vue
This PR adds a banner for 4th of July billing promo
=> feat: 4th july promo banner

app/javascript/dashboard/store/modules/conversations/index.js
Javascript error Cannot use 'in' operator to search for 'last_activity_at'
Use chatwoot and not show the error.
=> Cannot use 'in' operator to search for 'last_activity_at'

.circleci/config.yml, app/javascript/dashboard/components/ModalHeader.vue, app/javascript/dashboard/components/layout/sidebarComponents/AccountSelector.vue, app/javascript/dashboard/components/layout/sidebarComponents/specs/AccountSelector.spec.js, app/javascript/dashboard/components/layout/specs/AvailabilityStatus.spec.js, app/javascript/dashboard/components/specs/SidemenuIcon.spec.js, app/javascript/dashboard/components/specs/__snapshots__/SidemenuIcon.spec.js.snap, app/javascript/dashboard/components/widgets/conversation/specs/MoreActions.spec.js, app/javascript/dashboard/routes/dashboard/contacts/components/specs/AddReminder.spec.js, app/javascript/shared/components/specs/DateSeparator.spec.js, app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js, app/javascript/v3/components/GoogleOauth/Button.spec.js
- Update the breaking specs
- Remove unknown element warning in some of the specs.
=> chore: Update specs and warnings in console

app/javascript/dashboard/assets/scss/widgets/_buttons.scss, app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue, app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
This PR includes fixes -
- Shadow missing for options menu in prod
- Incorrect border for the reply box header
- Quoted text should come in the same line.
=> fix: dark mode hot fix

app/javascript/dashboard/components/widgets/ChannelItem.vue, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
This PR removes twitter creation flow from the UI and the copy text across the app
=> feat: remove twitter

app/javascript/dashboard/i18n/locale/en/login.json, app/javascript/v3/views/login/Index.vue, tailwind.config.js
This PR adds the following changes
1. Update login layout to center the login box
2. Add macOS like wiggle animation to login box on error
3. Update create account copy
https://github.com/chatwoot/chatwoot/assets/18097732/8fdecbeb-35ec-4c49-a26d-6a0eacb29b2e
=> feat: minor improvements to login UI

spec/lib/integrations/openai/processor_service_spec.rb, spec/models/message_spec.rb
- Fix breaking specs due to sentiment changes
- Fix breaking specs on Open AI integration
=> fix: Update breaking specs on sentiment and open AI integration

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, enterprise/app/jobs/enterprise/sentiment_analysis_job.rb
Fix https://linear.app/chatwoot/issue/CW-2215/typeerror-object-null-is-not-iterable-cannot-read-property
=> fix: Fix issue `null is not iterable`

enterprise/app/jobs/enterprise/sentiment_analysis_job.rb, enterprise/app/models/enterprise/message.rb, spec/enterprise/models/message_spec.rb
Fixes: https://radar-api.service.newrelic.com/accounts/3437125/issues/1a58b468-cfe1-4a5b-ac95-cc69e7500362?notifier=WEBHOOK
https://chatwoot-p3.sentry.io/issues/4325850233/?project=6382945&referrer=webhooks_plugin
=> fix: Sentiment analysis queue update

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss, app/javascript/dashboard/components/widgets/UserAvatarWithName.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetricCard.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetrics.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Heatmap.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/MetricCard.vue
- Reports overview page
- CSAT page
=> feat: Reports

enterprise/app/models/enterprise/concerns/inbox.rb
- Fix the bug in inbox associations that crept up in previous PR
=> chore: Fix response associations for inbox

lib/integrations/openai_base_service.rb
Fixes: https://chatwoot-p3.sentry.io/issues/4313886754/?referrer=Linear
=> fix: undefined method `first` for nil:NilClass

app/models/concerns/account_cache_revalidator.rb
Fixes: https://chatwoot-p3.sentry.io/issues/4312154361/?referrer=Linear
=> fix: undefined method `update_cache_key` for nil:NilClass

.storybook/main.js, .storybook/preview.js, app/javascript/dashboard/assets/scss/storybook.scss, package.json, yarn.lock
=> chore: Update storybook settings to widget stories

app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue, app/models/inbox.rb, lib/limits.rb
Fixes # CW-2260
Triggering the validation.
=> fix: Fixes CW-2260

app/javascript/dashboard/components/widgets/conversation/conversation/LabelSuggestion.vue, app/javascript/dashboard/mixins/aiMixin.js, enterprise/lib/enterprise/integrations/openai_processor_service.rb
Fixes: https://chatwoot-p3.sentry.io/issues/4314511928/
=> fix: no method error when conversation is nil

app/javascript/widget/api/article.js, app/javascript/widget/api/endPoints.js, app/javascript/widget/store/index.js, app/javascript/widget/store/modules/articles.js, app/javascript/widget/store/modules/specs/article/actions.spec.js
=> feat: Adds store and API to support articles in widget

enterprise/app/models/enterprise/concerns/inbox.rb
In several files with the english text there is an error in the text.
Change "dowanlod" to "download"
Text change in english language file
=> Text error

app/javascript/dashboard/components/layout/sidebarComponents/AccountContext.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplatesPicker.vue, app/javascript/dashboard/modules/notes/components/AddNote.vue, app/javascript/dashboard/modules/notes/components/ContactNote.vue, app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue, app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ListAllCategories.vue, app/javascript/shared/components/emoji/EmojiInput.vue
- Account context hover animation not showing in production
- Contact notes page to support dark mode
- Emoji Input (a common component used for widget and dashboard)
- Cleanups
=> feat: Dark Mode (PR -12)

app/javascript/widget/components/UnreadMessage.vue, app/views/api/v1/widget/campaigns/index.json.jbuilder
=> fix: Use Display name for campaigns

app/javascript/dashboard/App.vue, app/javascript/dashboard/assets/scss/app.scss, app/javascript/dashboard/assets/scss/widgets/_buttons.scss, app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/assets/scss/widgets/_reply-box.scss, app/javascript/dashboard/components/ui/Banner.vue, app/javascript/dashboard/components/widgets/WootWriter/Editor.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue, app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, tailwind.config.js
Fixes https://linear.app/chatwoot/issue/CW-2336/dark-mode-issues
1. Fixes banner button and color issues.
2. Fixes order list is not showing in message bubbles.
3. Fixes issue with private note bg color and text color.
4. Private note editor text color issue.
5. Fixes gradient issue for attachment bubbles that cause timestamp is not visible with which images
https://linear.app/chatwoot/issue/CW-2336#comment-e62ab146
=> feat: Dark mode improvements

app/javascript/dashboard/helper/customViewsHelper.js, app/javascript/dashboard/helper/specs/customViewsHelper.spec.js
This PR adds a fix for editing the custom views folder,
Suppose we update the status with multiple values like open, resolved, etc. Then it will update in API, but it does not show the active status in the UI.
**Bug**
https://www.loom.com/share/698a673a036a4189aa30565d964db827?sid=610222a3-b36c-41db-ac35-3b72466ccbfd
**Screencast**
https://www.loom.com/share/294f7dbf452f47378a053daa7c072505?sid=97d9bc19-c34b-45ef-9e4c-c5d888fa89f2
=> fix: Edit custom views folder

spec/enterprise/services/page_crawler_service_spec.rb
- Adds specs for the page crawler Service
=> chore: Specs for pageCrawler Service

app/javascript/dashboard/routes/dashboard/settings/campaigns/CampaignCard.vue, config/initializers/mailer.rb, lib/seeders/account_seeder.rb, lib/seeders/seed_data.yml
- The message sender was incorrect. Incoming messages were created under the contact's name, and outgoing messages were created under the user's name instead of the reverse.
- The seed user's email address was incorrect in the message data.
- The Sendmail configuration overrode the Letter Opener config which made it difficult to test the email.
This PR also fixes an ESLint lint issue on develop.
=> fix: Update account data seeder to avoid invalid information

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
This PR includes a fix for sentry error.
Fixes https://chatwoot-p3.sentry.io/issues/4260314133/events/b5400fb98b5a46cc8fbe6134558d7aa2/
=> fix: Cannot read properties of undefined

enterprise/lib/enterprise/integrations/openai_processor_service.rb, enterprise/spec/integrations/openai/processor_service_spec.rb, lib/integrations/openai_base_service.rb
- add check for `nil` condition
- add logs
=> chore: Fix OpenAI sentry errors

lib/integrations/openai/openai_prompts/summary.txt
Fix prompt that broke summary tests
=> fix: Summary prompt test

app/javascript/widget/components/AgentTypingBubble.vue, app/javascript/widget/components/ConversationWrap.vue, app/javascript/widget/store/modules/conversation/getters.js, enterprise/app/services/enterprise/message_templates/response_bot_service.rb
- Show the indicator if the last message is incoming and the conversation is in pending status.
- Remove list of articles displayed in the bot response.
=> feat: Update bot typing indicator based on the conversation status

app/javascript/dashboard/components/widgets/conversation/EmptyState/EmptyStateMessage.vue
=> fix: Fix breaking storybook build

config/initializers/rack_attack.rb
Ability to disable rack attack specifically for widget endpoints
=> chore: Ability to disable rack attack on widget endpoints

app/javascript/dashboard/components/layout/sidebarComponents/Primary.vue, app/javascript/dashboard/helper/AnalyticsHelper/events.js, app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanel.vue, app/javascript/dashboard/routes/dashboard/notifications/components/NotificationsView.vue
- Added analytics for notification page usage.
=> feat: Add analytics events for notifications

app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
1. The Pagination footer will be removed if it is unnecessary. (Only show if the article length is greater than 25).
2. If there is a scroll in the article list section, then it will cause the article header and footer to get hidden. This PR will fix this issue
Fixes https://linear.app/chatwoot/issue/CW-2393/remove-pagination-plugin-if-there-is-no-need-for-it
**Screencast**
https://www.loom.com/share/3593987a43d7478ba7513a9d4a0422a5?sid=355cc7d8-1aa9-4b1e-8de7-336cef78469d
=> chore: Article list enhancements

app/javascript/dashboard/i18n/locale/en/integrations.json, app/javascript/dashboard/routes/dashboard/settings/integrations/Slack.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Slack/SelectChannelWarning.vue, app/views/api/v1/models/_hook.json.jbuilder, app/views/mailers/administrator_notifications/channel_notifications_mailer/slack_disconnect.liquid, lib/integrations/slack/send_on_slack_service.rb, spec/lib/integrations/slack/send_on_slack_service_spec.rb, spec/models/integrations/hook_spec.rb
- Ensure that emails are sent when slack is disconnected
- handles missing scope error
=> chore: Fix slack email alerts

app/javascript/dashboard/i18n/locale/es/chatlist.json, app/javascript/dashboard/i18n/locale/es/generalSettings.json, app/javascript/dashboard/i18n/locale/es/settings.json
2 minor corrections in Spanish locale.
- [ x ] Bug fix (non-breaking change which fixes an issue)
N/A
=> fix: translation changes in Spanish

app/javascript/dashboard/components/widgets/UserAvatarWithName.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetrics.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/__snapshots__/CSATMetrics.spec.js.snap, app/javascript/shared/constants/messages.js
1. Fix for CSAT meter color order issue
2. Fix spacing with thumbnail and agent name
Fixes https://linear.app/chatwoot/issue/CW-2429/fix-csat-meter-color-order
**Screenshot**
=> fix: CSAT meter color order

app/javascript/dashboard/routes/dashboard/settings/profile/MessageSignature.vue, package.json, yarn.lock
- Re-arrange the plugins.
- Remove watcher for currentUser
- Disable suggestions plugin on the signature editor
=> fix: Re-arrange plugins to fix canned-responses/mentions not working

app/controllers/api/v1/accounts/articles_controller.rb, app/controllers/api/v1/accounts/automation_rules_controller.rb, app/controllers/api/v1/accounts/macros_controller.rb, app/controllers/api/v1/accounts/portals_controller.rb, app/policies/article_policy.rb, app/policies/automation_rule_policy.rb, app/policies/macro_policy.rb, app/policies/portal_policy.rb, config/initializers/rack_attack.rb, config/routes.rb, spec/controllers/api/v1/accounts/articles_controller_spec.rb, spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb, spec/controllers/api/v1/accounts/macros_controller_spec.rb, spec/controllers/api/v1/accounts/portals_controller_spec.rb
1. Enable rack attack for the upload endpoint
2. Remove `attach_file` from portals, articles, macros and automation rule controllers
3. Update tests for the controllers
4. Remove `attach_file` from policies
=> feat: common attachment endpoint follow-up changes

config/locales/tr.yml
tr locale file updated for Portal Turkish language translations.
I ran it on my docker container.
=> fix: Portal Turkish Translations | Updated tr.yml

app/javascript/shared/components/ArticleSkeletonLoader.vue, app/javascript/shared/components/IframeLoader.vue, app/javascript/widget/components/ArticleCardSkeletonLoader.vue, app/javascript/widget/views/ArticleViewer.vue
Creates a view to show articles in widget and skeleton type loaders. The loaders are for article page and the article card component to be used in widget.
This PR introduces 2 loaders as well
1. Article Card Skeleton 
2. Article Viewer page Skeleton
=> feat: Creates components to show article in an IFrame 

app/javascript/dashboard/routes/dashboard/settings/integrations/Integration.vue
=> fix: Integration page responsiveness issues

enterprise/app/services/enterprise/message_templates/response_bot_service.rb, enterprise/lib/chat_gpt.rb
- Update prompt for article bot to respond with JSON
=> chore: Updated prompt for Article Bot

app/controllers/api/v1/accounts/contacts_controller.rb, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue, spec/controllers/api/v1/accounts/contacts_controller_spec.rb
- Remove conversation count in the contacts page to improve performance
=> feat: perf remove conversation count in contacts list view

app/views/public/api/v1/portals/articles/index.json.jbuilder
- Improve the query for fetching articles in widget help center
=> refactor: Optimise article query in chat widget

app/assets/stylesheets/administrate/application.scss, app/assets/stylesheets/administrate/custom_styles.scss, app/views/fields/account_features_field/_form.html.erb, app/views/fields/account_features_field/_show.html.erb
=> chore: Improve the feature management styles in super admin

app/services/filter_service.rb
Content attribute was not working after https://github.com/chatwoot/chatwoot/pull/7871. 
This fix ensures that the filter works.
=> fix: Downcase content filter values to fix the query

app/javascript/dashboard/helper/specs/editorHelper.spec.js, app/javascript/dashboard/i18n/locale/en/settings.json
Update message signature description
=> chore: Update message signature description

.github/workflows/run_response_bot_spec.yml, enterprise/app/services/enterprise/message_templates/response_bot_service.rb, spec/enterprise/services/enterprise/message_templates/response_bot_service_spec.rb
- GPT bot should pass conversation to agent if AI returns invalid json
=> chore: pass to agent if there is error parsing json

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue, app/javascript/dashboard/routes/dashboard/settings/campaigns/AddCampaign.vue, app/javascript/dashboard/routes/dashboard/settings/campaigns/EditCampaign.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue, app/javascript/shared/components/GreetingsEditor.vue
This pull request fixes the issue of the file upload browser appearing when clicking the editor.
**Issue** 
https://www.loom.com/share/f1fc7ed7260c49faaa5bf1cabf80d165
**Test places**
1. New message modal editor
2. Add and edit the campaign editor section
3. Pre-chat form editor section editor
4. Business hours editor section editor
5. Inbox setting greeting message editor section
=> fix: Editor file upload browser showing bug

app/controllers/concerns/request_exception_handler.rb
Logging this info is invaluable when using logs to track down the reason why a particular request failed.
=> chore: Log errors handled by RequestExceptionHandler

app/controllers/public/api/v1/inboxes/conversations_controller.rb, spec/controllers/public/api/v1/inbox/conversations_controller_spec.rb, swagger/definitions/index.yml, swagger/definitions/request/public/conversation/create_payload.yml, swagger/paths/public/inboxes/conversations/create.yml, swagger/swagger.json
- Update client API create conversations to accept custom attributes as well
=> chore: Create client API conversations with custom attributes

.env.example, config/initializers/rack_attack.rb
=> fix: Application not loading after setting RACK_ATTACK_LIMIT ENV variable [CW-2587]

app/javascript/dashboard/routes/dashboard/settings/account/Index.vue, app/javascript/dashboard/routes/dashboard/settings/billing/Index.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
Fix infinite-loop fetch caused by `initializeAccount`
=> refactor: remove redundant accounts/get

app/models/message.rb, db/migrate/20231011041615_ensure_message_private_not_null.rb, db/schema.rb, enterprise/app/models/response.rb
- Ensure null validation for private attribute in messages
=> chore: Ensure null validation for private attribute in messages

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/MessagePreview.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/components/widgets/conversation/ReplyToMessage.vue, app/javascript/dashboard/components/widgets/conversation/bubble/ReplyTo.vue, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/store/modules/conversations/actions.js, app/javascript/shared/constants/messages.js
1. Setup reply to bubble for message texts
2. Handle attachments in `ReplyToMessage.vue`
3. Handle attachement in bubble
https://github.com/chatwoot/chatwoot/assets/18097732/b0edb8d2-e15b-43bf-b29f-ea5e7da295ca
=> feat: implement message bubble reply to

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/CollaboratorsPage.vue
Add checks for the following
1. https://chatwoot-p3.sentry.io/issues/4159540136/events/fb98cde0bbf641d491df1d04f3ee4a69/?project=6382945
2. https://chatwoot-p3.sentry.io/issues/4159540136/events/69397ccbe43a4bd3a4afc056746bb666/?project=6382945
3. https://chatwoot-p3.sentry.io/issues/4159540136/events/113b14ee7b2946bf8aeb76401670ffa9/?project=6382945
https://github.com/chatwoot/chatwoot/assets/18097732/6660c2fd-8893-45f8-b502-9629e894c3c6
=> refactor: add null checks

app/controllers/api/v1/widget/conversations_controller.rb, app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue, app/jobs/conversations/mark_messages_as_read_job.rb, spec/controllers/api/v1/widget/conversations_controller_spec.rb, spec/jobs/conversations/mark_messages_as_read_job_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2646/delivery-reports-for-live-chat
=> feat: Add delivery reports for live chat

app/javascript/widget/components/ChatFooter.vue, app/javascript/widget/components/TeamAvailability.vue, app/views/widget_tests/index.html.erb
Adds a new flag on the on-start-conversation event.
=> chore: Adds hasConversation flag in chatwoot:on-start-conversation event

app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue, app/jobs/webhooks/instagram_events_job.rb, app/services/instagram/read_status_service.rb, spec/factories/instagram/instagram_message_create_event.rb, spec/jobs/webhooks/instagram_events_job_spec.rb, spec/services/instagram/read_status_service_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2571/delivery-report-for-instagram
=> feat: Instagram delivery reports

app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Fixes https://github.com/chatwoot/chatwoot/pull/8125#discussion_r1364985852
=> fix: Show sent status for messenger channel

app/javascript/dashboard/helper/AnalyticsHelper/events.js, app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
Fixes https://linear.app/chatwoot/issue/CW-2659/add-an-event-for-the-google-translate-usage
=> feat: Adds an event for the Google Translate usage

spec/models/channel/telegram_spec.rb
Fixes the spec issues from the [PR](https://github.com/chatwoot/chatwoot/issues/8173).
=> fix: Telegram model specs

swagger/definitions/request/conversation/create_message.yml, swagger/paths/application/conversation/index.yml, swagger/swagger.json
=> chore: Update API documentation for whatsapp templates

app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue, app/javascript/dashboard/routes/dashboard/conversation/search/SwitchLayout.vue
This PR includes fixing the file missing errors in the latest develop branch. From this PR https://github.com/chatwoot/chatwoot/pull/8203/commits/9520e8bed87e1e5e6714f2dddf4d38da7b4da44d
=> fix: Revert missing files for search

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
| -- | -- |
| <img width="160" alt="Screenshot 2023-10-25 at 9 28 35 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/57fcd263-7dd4-4cfa-8b72-a0942f5a3d7f"> | <img width="151" alt="Screenshot 2023-10-25 at 9 29 39 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/c82678b8-0ade-44c5-bc54-ace0be0a076b"> |
=> fix: Update the alignment of the info icon on contact info panel

app/javascript/dashboard/i18n/locale/en/advancedFilters.json, app/javascript/dashboard/i18n/locale/en/agentBots.json, app/javascript/dashboard/i18n/locale/en/bulkActions.json, app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
Update UI copy for `cannedMgmt.json`, `bulkActions.json`, `agentBots.json` & `advancedFilters.json`
=> chore: update UI copy

app/jobs/custom_filters_records_count_update_job.rb, app/jobs/sync_custom_filter_count_job.rb, app/models/custom_filter.rb, app/views/api/v1/models/_custom_filter.json.jbuilder, config/schedule.yml, lib/redis/redis_keys.rb, spec/controllers/api/v1/accounts/custom_filters_controller_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2701/activerecordstatementinvalid-pgsyntaxerror-error-syntax-error-at-or
=> fix: Revert the changes for SyncCustomFilterCountJob

app/javascript/widget/components/AgentMessage.vue, app/javascript/widget/components/ChatFooter.vue, app/javascript/widget/components/DragWrapper.vue, app/javascript/widget/components/FooterReplyTo.vue, app/javascript/widget/components/ReplyToChip.vue, app/javascript/widget/components/UserMessage.vue, app/views/widgets/show.html.erb
This PR adds condition rendering to widget reply to feature, based on an account level feature flag
=> feat: toggle reply to on widget based on feature flag

swagger/definitions/index.yml, swagger/definitions/resource/extension/contact/labels.yml, swagger/index.yml, swagger/paths/application/contacts/labels/create.yml, swagger/paths/application/contacts/labels/index.yml, swagger/paths/index.yml, swagger/swagger.json
- Added swagger documentation for contact Labels(list and create) API.
=> chore: Swagger documentation for contact labels APIs

app/controllers/api/v1/widget/configs_controller.rb, app/views/api/v1/widget/configs/create.json.jbuilder, spec/controllers/api/v1/widget/configs_controller_spec.rb
Update the keys in the widget config API to support loading the widget separately from the Rails App.
=> chore: Update widget config API to migrate the widget

enterprise/lib/chat_gpt.rb
- Add loggers to debug ChatGPT responses
=> chore: Debug ChatGpt response

enterprise/app/services/enterprise/message_templates/response_bot_service.rb, spec/enterprise/services/enterprise/message_templates/response_bot_service_spec.rb
- Fix the bug where wrong messages was used to search response sources
=> chore: Fix trigger message for response Bot

app/views/public/api/v1/portals/_uncategorized-block.html.erb
This PR will update uncategorized block design
https://www.loom.com/share/cd5c04ce271448b7903bc2c83b477ea3?sid=f52bef9d-3921-4c78-b144-df69f2e4a8bf
=> feat: Update uncategorized block design

app/views/public/api/v1/portals/_header.html.erb, config/locales/es.yml
=> fix: Fixes line break issue with link in portal header

app/views/layouts/portal.html.erb
=> chore: Add meta viewport tag to public portal

README.md
- Update dashboard screenshots to include dark mode and light mode
- Update the missing logos
=> chore: Update dashboard screenshots and the logo

app/javascript/dashboard/helper/automationHelper.js, app/javascript/dashboard/routes/dashboard/settings/automation/constants.js, app/models/automation_rule.rb
This PR allows users to configure automation rules to remove labels
https://github.com/chatwoot/chatwoot/assets/18097732/7d34afb2-71f8-4657-9eba-3cc10d907333
Tested locally, the backend changes for this already existed
=> feat: allow automation rules to remove labels

lib/seeders/account_seeder.rb
This change lets you rerun the seed_contacts multiple times to generate as many conversations you want into an account for testing purposes.
```
seeder = Seeders::AccountSeeder.new(account: Account.find(id))
seeder.seed_contacts
```
=> chore: Improve account seeding

app/services/facebook/send_on_facebook_service.rb
- add logging for Facebook errors
=> chore: Add logging for facebook errors

config/initializers/filter_parameter_logging.rb
- Log website_token into request logs to identify specific widgets
=> chore: Add website_token in to request logs

app/controllers/api/v1/accounts/portals_controller.rb, app/policies/portal_policy.rb, config/routes.rb, spec/controllers/api/v1/accounts/portals_controller_spec.rb
- Adds an endpoint to purge portal logo
=> chore: Endpoint to purge portal logo

app/views/api/v1/models/_contact.json.jbuilder
- Remove conversation count from the contact object
=> perf: Remove unwanted conversation count query

app/javascript/dashboard/modules/widget-preview/components/WidgetFooter.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue, app/javascript/shared/components/GreetingsEditor.vue, app/javascript/shared/components/ResizableTextArea.vue, app/javascript/widget/components/ChatInputWrap.vue
Fixes the height based on the number of rows in the textarea.
=> fix: Update the height of the input based on the rows

app/javascript/dashboard/assets/scss/_formulate.scss, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/mixins/aiMixin.js, app/javascript/dashboard/routes/dashboard/settings/integrationapps/NewHook.vue, config/integration/apps.yml, enterprise/lib/enterprise/integrations/openai_processor_service.rb
- Ability to toggle open AI label suggestion
=> chore: Making OpenAI label suggestions optional

app/javascript/dashboard/components/widgets/AIAssistanceButton.vue, app/javascript/shared/store/globalConfig.js
=> fix: Disable AI Assist CTA if not required

app/javascript/dashboard/modules/search/search.routes.js, app/javascript/dashboard/routes/dashboard/contacts/routes.js, app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js, app/javascript/dashboard/routes/dashboard/dashboard.routes.js, app/javascript/dashboard/routes/dashboard/notifications/routes.js, app/javascript/dashboard/routes/dashboard/settings/account/account.routes.js, app/javascript/dashboard/routes/dashboard/settings/agentBots/agentBot.routes.js, app/javascript/dashboard/routes/dashboard/settings/agents/agent.routes.js, app/javascript/dashboard/routes/dashboard/settings/attributes/attributes.routes.js, app/javascript/dashboard/routes/dashboard/settings/auditlogs/audit.routes.js, app/javascript/dashboard/routes/dashboard/settings/automation/automation.routes.js, app/javascript/dashboard/routes/dashboard/settings/billing/billing.routes.js, app/javascript/dashboard/routes/dashboard/settings/campaigns/campaigns.routes.js, app/javascript/dashboard/routes/dashboard/settings/canned/canned.routes.js, app/javascript/dashboard/routes/dashboard/settings/inbox/inbox.routes.js, app/javascript/dashboard/routes/dashboard/settings/integrationapps/integrations.routes.js, app/javascript/dashboard/routes/dashboard/settings/integrations/integrations.routes.js, app/javascript/dashboard/routes/dashboard/settings/labels/labels.routes.js, app/javascript/dashboard/routes/dashboard/settings/macros/macros.routes.js, app/javascript/dashboard/routes/dashboard/settings/profile/profile.routes.js, app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js, app/javascript/dashboard/routes/dashboard/settings/teams/teams.routes.js
- improve build performance by enabling chunks
=> feat: Split dashboard to chunks for build performance

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/helper/AnalyticsHelper/events.js
Adds event to know when an article is inserted with reply insert feature
=> chore: Add GA event for insert article feature

app/controllers/api/v1/accounts/notifications_controller.rb, app/models/notification.rb, config/routes.rb, db/migrate/20231129091149_add_snoozed_until_to_notifications.rb, db/schema.rb, spec/controllers/api/v1/accounts/notifications_controller_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2844/snooze-notification-api
=> feat: Snooze notification API

app/helpers/portal_helper.rb, spec/helpers/portal_helper_spec.rb
Sentry https://chatwoot-p3.sentry.io/issues/4683348482/?referrer=Linear
Fixes https://linear.app/chatwoot/issue/CW-2814/actionviewtemplateerror-undefined-method-length-for-nilnilclass
=> fix: Undefined method `length' for nil:NilClass

app/mailers/agent_notifications/conversation_notifications_mailer.rb, app/services/notification/email_notification_service.rb, spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
This PR will resolve the email issue that emerged following the merge of this [PR](https://github.com/chatwoot/chatwoot/pull/8490).
=> fix: Email notifications

app/finders/conversation_finder.rb, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/IntersectionObserver.vue
- Add a option to increase the number of conversations returned per page.
- Implement infinite loader in the conversations list.
=> feat: Add infinite loader, option for increasing page size

app/finders/conversation_finder.rb, app/models/concerns/sort_handler.rb, app/services/conversations/filter_service.rb, spec/models/conversation_spec.rb, spec/models/mention_spec.rb
- Add support for ascending and descending sort options.
- Set fallbacks for previously used options
=> feat: Add support for ascending and descending options in sort

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/ConversationItem.vue, app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, package.json, yarn.lock
This PR adds virtualization for the conversation list to improve performance.
Fixes https://linear.app/chatwoot/issue/CW-2892/conversation-list-virtualization
=> feat: Conversation list virtualization

app/views/public/api/v1/portals/_authors.html.erb
**Sentry**: https://chatwoot-p3.sentry.io/issues/4711656604/?project=6382945&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
Fixes https://linear.app/chatwoot/issue/CW-2898/actionviewtemplateerror-undefined-method-name-for-nilnilclass
=> fix: Undefined method `name' for nil:NilClass

app/services/instagram/message_text.rb
Fixes https://linear.app/chatwoot/issue/CW-2903/nomethoderror-undefined-method-inbox-for
=> fix: Fix the issue "Undefined method `inbox' for Instagram::MessageText"

README.md
=> chore: 2023 -> 2024

enterprise/app/controllers/enterprise/super_admin/app_configs_controller.rb
- add config for darkmode logo
=> chore: add config for Darkmode logo for whitelabeling

config/newrelic.yml
This enables [local decorating of logs](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-ruby/) when using new relic. It can be used when you use a log forwarding agent to do additional enrichment on APM logs before forwarding to new relic. 
Tested locally
=> feat: enable new relic log decorations

app/javascript/dashboard/mixins/specs/time.spec.js
- Fix the github action failure related to messagetimestamp test
=> fix: messageTimestamp test

app/javascript/dashboard/mixins/specs/time.spec.js, app/javascript/dashboard/store/modules/conversations/helpers.js, app/javascript/dashboard/store/modules/specs/conversations/conversations.fixtures.js, app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
- Use fakeTimer for time.spec.js
- Use default sort as last_activity_at_desc
- Update specs for getAllConversations getter
=> fix: Update broken specs

app/javascript/widget/components/AgentMessage.vue
| After | Before |
| -- | -- |
| ![IMG_0390](https://github.com/chatwoot/chatwoot/assets/2246121/04a1d17b-34e0-4ecc-91ae-cd1e7d668197) | ![IMG_0391](https://github.com/chatwoot/chatwoot/assets/2246121/651a7308-6076-453e-b945-9c217b22fc50) |
=> fix: Remove the usage of DragWrapper to fix the Dyte integration

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss, app/javascript/dashboard/components/widgets/conversation/Message.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/i18n/locale/en/conversation.json
=> feat: UI for unsupported message

app/mailboxes/reply_mailbox.rb
fix: https://linear.app/chatwoot/issue/CW-2912/runtimeerror-nilclass-not-found-runtimeerror
=> fix: nil class not found error

app/javascript/dashboard/components/widgets/conversation/VariableList.vue
Hide the variable list if the array is empty.
Ref: https://github.com/chatwoot/chatwoot/pull/8671
=> chore: Hide the variable list if its empty.

app/mailers/application_mailer.rb, app/mailers/conversation_reply_mailer.rb, app/mailers/conversation_reply_mailer_helper.rb
- Log details related to emails sent from Chatwoot to assist in debugging email delivery/bounces/complaints
=> chore: log emails sent from chatwoot

app/models/dashboard_app.rb, spec/controllers/api/v1/accounts/dashboard_apps_controller_spec.rb
This PR ensures correct validation of the URL for a dashboard app. Fixes: https://huntr.com/bounties/08b3bebf-ce3c-4416-b75e-1927ba61de85/
Tested locally, as well as with unit tests
=> fix: validate url for Dashboard Apps [CW-2979]

app/jobs/application_job.rb
Improve active job error logs.
=> chore: Improve active job error logs

app/javascript/dashboard/components/ChatList.vue
teamId does not change, added watch
=> fix: change teamid

app/javascript/dashboard/components/widgets/forms/PhoneInput.vue
Fixes https://linear.app/chatwoot/issue/CW-2948/typeerror-cannot-read-properties-of-undefined-reading-emoji
=> fix: TypeError: Cannot read properties of undefined (reading 'emoji')

app/models/contact.rb, db/migrate/20240124054340_add_contact_type_to_contacts.rb, db/schema.rb
Fixes https://linear.app/chatwoot/issue/CW-2998/add-an-attribute-contact-type-to-contacts-model
=> feat: Add `contact_type` attribute to contact model

app/models/contact.rb, db/migrate/20240124084032_add_middle_name_and_last_name_to_contacts.rb, db/schema.rb
Fixes https://linear.app/chatwoot/issue/CW-3002/add-the-fields-middle-name-and-last-name
=> feat: Add `middle_name` and `last_name`  to contact model 

app/mailboxes/reply_mailbox.rb
- fix: change email conversation not found exception to log
Fixes https://linear.app/chatwoot/issue/CW-3021/runtimeerror-email-conversation-with-uuid-2cf63042-a687-449a-9856#comment-2fd6bb75
=> fix: change email conversation not found exception to log

swagger/definitions/request/public/message/update_payload.yml, swagger/parameters/index.yml, swagger/paths/application/contacts/filter.yml, swagger/swagger.json
=> fix: Small fixes to make spec adhere to swagger 2.0

app/javascript/dashboard/routes/dashboard/inbox/components/InboxListHeader.vue
This PR includes the Inbox list header component.
Fixes https://linear.app/chatwoot/issue/CW-3047/ui-inbox-list-header
**Screenshot**
=> feat: Inbox list header

app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/i18n/locale/en/inbox.json, app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js, app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue, app/javascript/dashboard/routes/dashboard/inbox/InboxView.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxCard.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxItemHeader.vue, app/javascript/dashboard/routes/dashboard/inbox/components/PaginationButton.vue
This PR includes the message view for the inbox page.
Fixes https://linear.app/chatwoot/issue/CW-3048/inbox-full-view
https://github.com/chatwoot/chatwoot/assets/64252451/c7493ebe-5163-42b7-850d-1ed94637aba0
=> feat: Inbox page view

app/javascript/dashboard/i18n/locale/en/inbox.json, app/javascript/dashboard/routes/dashboard/inbox/InboxView.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxDisplayMenu.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxListHeader.vue
This PR involves the implementation of the inbox list display menu component for the inbox view.
Fixes https://linear.app/chatwoot/issue/CW-2965/ui-inbox-filters
**Screencast**
https://github.com/chatwoot/chatwoot/assets/64252451/b9c07d25-3eb0-40fc-b7ba-4368d74dd120
=> feat: Inbox list display menu

app/javascript/v3/components/Form/Select.vue, app/javascript/v3/components/Form/WithLabel.vue
**Description**
Adds form select component that needs to be used across onboarding wizard.
=> feat: Form select component to use with onboarding form

app/javascript/dashboard/api/notifications.js, app/javascript/dashboard/api/specs/notifications.spec.js, app/javascript/dashboard/constants/globals.js, app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue, app/javascript/dashboard/routes/dashboard/inbox/InboxView.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxCard.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxDisplayMenu.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxItemHeader.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxListHeader.vue, app/javascript/dashboard/store/modules/notifications/actions.js, app/javascript/dashboard/store/modules/notifications/getters.js, app/javascript/dashboard/store/modules/notifications/helpers.js, app/javascript/dashboard/store/modules/specs/notifications/getters.spec.js, app/javascript/dashboard/store/modules/specs/notifications/helpers.spec.js
This PR includes, 
1. Inbox list sorting based on newest/oldest
2. Inbox list filtering based on snoozed status
3. Inbox list filtering based on read type
4. Save filtering and sorting to UI settings
5. Realtime notification filtering and sorting
6. Minor bug fixes and styling fixes
Fixes https://linear.app/chatwoot/issue/CW-2975/sort-notifications-by-statussnoozedread-and-order-newestoldest
**Loom video**
https://www.loom.com/share/5f2bd2b49e7a45d3b3249d1a46a50ba8?sid=7825ccce-f4f6-46ac-9bb5-8a403e3689fd
=> feat: Inbox list filter

app/javascript/v3/views/onboarding/SetupProfile.vue
**Description**
- Adds profile page with logo upload and validations
=> feat: creates page for setting user profile

app/javascript/v3/views/onboarding/SetupCompany.vue
=> feat: Adds onboarding page for setup company.

app/javascript/dashboard/store/modules/conversations/actions.js, app/javascript/dashboard/store/modules/conversations/helpers/actionHelpers.js, app/javascript/dashboard/store/modules/conversations/helpers/specs/actionHelpers.spec.js, app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
This is a copy of the fix done in a private fork at Bitespeed, also opening PR here by recommendation of @pranavrajs 
Fixes #8890 
Aside from the unit tests, create new conversations via API (using Postman etc.) locally and then notice that they don't show up in the folder view
=> fix: Conversation filters are not working correctly

config/initializers/rack_attack.rb
- Throttle contact_search endpoint to prevent abuse/maintain db perf
ref: https://discord.com/channels/897869226579222540/899920096972111883/1206919316402999326
=> fix: throttle contact search endpoint to prevent abuse

app/javascript/v3/components/Form/Input.vue, app/javascript/v3/components/Form/WithLabel.vue, app/javascript/v3/views/login/Index.vue
- Fixes focus ring not appearing issue
- Fixes missing forgot password link
https://linear.app/chatwoot/issue/CW-3090/fix-fixes-issues-with-login-form
Tested on local for both dark mode and light mode for the focus issue.
=> fix: Adds forgot password link for login form

app/javascript/dashboard/api/agents.js, app/javascript/dashboard/api/specs/agents.spec.js, app/javascript/v3/api/auth.js
New API endpoint support for bulk email invite and account setup
=> feat: Adds new APIs on frontend to use in onboarding view

spec/controllers/api/v1/accounts/contacts_controller_spec.rb
- Fixes flaky spec relying on order, which isn't guaranteed
ref: https://github.com/chatwoot/chatwoot/actions/runs/7930640040/job/21653323313?pr=8922
=> chore: fix flaky spec relying on unguaranteed order

app/javascript/v3/components/Form/Input.vue, app/javascript/v3/components/Form/Textarea.vue
**Description**
Adds form input component that needs to be used across onboarding wizard.
=> feat: Adds textarea component to use in forms

app/javascript/dashboard/featureFlags.js, config/features.yml, enterprise/config/premium_features.yml
- Add feature_flag for SLA
Fixes https://linear.app/chatwoot/issue/CW-3079/feature-flag
=> feat: sla-8 add feature flag for SLA

app.json
- Seed DB for heroku review apps
=> feat: seed db for heroku review apps

.github/workflows/run_response_bot_spec.yml, app/jobs/account/conversations_resolution_scheduler_job.rb, app/listeners/reporting_event_listener.rb, enterprise/app/jobs/enterprise/account/conversations_resolution_scheduler_job.rb, enterprise/app/jobs/response_bot/inbox_pending_conversations_resolution_job.rb, enterprise/app/jobs/response_bot/response_bot_job.rb, enterprise/app/jobs/response_bot/response_builder_job.rb, enterprise/app/jobs/response_bot/response_document_content_job.rb, enterprise/app/models/response_document.rb, enterprise/app/services/enterprise/message_templates/hook_execution_service.rb, enterprise/app/services/enterprise/message_templates/response_bot_service.rb, enterprise/app/services/features/response_bot_service.rb, spec/enterprise/controllers/api/v1/accounts/response_sources_controller_spec.rb, spec/enterprise/controllers/enterprise/api/v1/accounts/inboxes_controller_spec.rb, spec/enterprise/jobs/enterprise/account/conversations_resolution_scheduler_job_spec.rb, spec/enterprise/jobs/response_bot/inbox_pending_conversations_resolution_job_spec.rb, spec/enterprise/services/enterprise/message_templates/response_bot_service_spec.rb, spec/factories/inbox_response_source.rb, spec/listeners/reporting_event_listener_spec.rb, spec/spec_helper.rb
note: other changes include organizing the related code into appropriate namespaces and additional specs
=> chore: Reporting Events for Bots

Gemfile, Gemfile.lock, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetrics.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/CSATMetrics.spec.js, app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/__snapshots__/CSATMetrics.spec.js.snap
Fixes broken builds due to CVE-2024-27456
=> fix: Downgrade rack-cors to 2.0.0 to fix CVE-2024-27456

app/javascript/v3/components/Form/Input.vue, app/javascript/v3/components/Form/Select.vue, app/javascript/v3/components/Form/Textarea.vue
=> fix: border radius

app/javascript/dashboard/assets/scss/widgets/_base.scss, app/javascript/dashboard/assets/scss/widgets/_tabs.scss, app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, app/javascript/dashboard/components/widgets/mentions/MentionBox.vue, app/javascript/dashboard/routes/dashboard/inbox/components/MenuItem.vue, tailwind.config.js
Fixes 
1. `<ul/>` tag broken styles
2. Adds missing conversation card active animation
3. Fix extra borders in the mention box component used for canned responses, variables, etc
4. And fix some terminal warnings
=> fix: Broken styles

README.md
Remove the Huntr Badge as it is broken.
=> docs: Update README.md, remove broken badge

app/jobs/inboxes/fetch_imap_emails_job.rb
- Enhance the email Channel errors for easier look up in logs
=> chore: Verbose errors for Imap Email Channels

app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/__snapshots__/CSATMetrics.spec.js.snap
- Fix `CSATMetrics` component snap shot spec
=> chore: Fix `CSATMetrics` component snap shot spec

app/javascript/dashboard/components/widgets/conversation/components/SLACardLabel.vue, app/javascript/dashboard/helper/directives/resize.js, app/javascript/dashboard/helper/specs/directives/resize.spec.js, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/packs/application.js
This PR includes
1. Component to display SLA timer in the conversation card and header
2. Resize directive that I took from this [commit](https://github.com/chatwoot/chatwoot/pull/9109/commits/af90e3a56cff138db408a698d1a5a21b69072263) by @scmmishra 
=> feat: SLA threshold card component

app/mailers/agent_notifications/conversation_notifications_mailer.rb, app/models/application_record.rb, enterprise/app/mailers/enterprise/agent_notifications/conversation_notifications_mailer.rb, enterprise/app/services/sla/evaluate_applied_sla_service.rb
Fixes https://linear.app/chatwoot/issue/CW-3184/fix-sla-policy-name-in-email-notifications
=> chore: fix sla email notifications

Makefile
- Add `db_reset` make command
- tested locally
=> chore: add db_reset make command

app/javascript/dashboard/i18n/locale/en/sla.json, app/javascript/dashboard/routes/dashboard/settings/sla/Index.vue, app/javascript/dashboard/routes/dashboard/settings/sla/components/SLAHeader.vue
=> feat: better empty state for SLA

app/javascript/dashboard/components/widgets/conversation/components/SLACardLabel.vue
This PR includes a style fix for the SLA timer card.
1. Fix the border color to match with the card label.
2. Fix the height to match with the card label.
**Before**
**After**
=> fix: SLA card style

app/javascript/dashboard/assets/scss/widgets/_base.scss, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterButton.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterDropdownEmptyState.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterDropdownSearch.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterListDropdown.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterListItemButton.vue
This PR includes the following components,
1. Reports filter button component
2. Reports filter dropdown component
3. Reports filter dropdown button component
4. Report filter search component
Fixes https://linear.app/chatwoot/issue/CW-3188/ui-filter-components
**Screencast**
https://github.com/chatwoot/chatwoot/assets/64252451/f78d4641-f9c6-4d86-b9cb-02e6f24c7cf9
=> feat: Reports filter components

app/javascript/dashboard/components/widgets/TableFooter.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/SLA/SLATable.vue
=> fix: Remove background color from table footer

app/javascript/dashboard/components/widgets/conversation/components/SLACardLabel.vue, app/javascript/dashboard/components/widgets/conversation/components/SLAEventItem.vue, app/javascript/dashboard/components/widgets/conversation/components/SLAPopoverCard.vue, app/javascript/dashboard/constants/globals.js, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/i18n/locale/en/sla.json, app/javascript/dashboard/routes/dashboard/settings/reports/components/SLA/SLAViewDetails.vue
Fixes https://linear.app/chatwoot/issue/CW-3198/update-the-popover-ui-for-long-list-of-misses
**Light theme**
**Dark theme**
=> feat: Better SLA missed events popover 

app/javascript/dashboard/api/slaReports.js, app/javascript/dashboard/api/specs/slaReports.spec.js, app/javascript/dashboard/assets/scss/_date-picker.scss, app/javascript/dashboard/assets/scss/plugins/_multiselect.scss, app/javascript/dashboard/components/widgets/TableFooterPagination.vue, app/javascript/dashboard/i18n/locale/en/report.json, app/javascript/dashboard/routes/dashboard/settings/reports/SLAReports.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/ActiveFilterChip.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/AddFilterChip.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterButton.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterDropdownSearch.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterListDropdown.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/v3/FilterListItemButton.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/SLA/SLAFilter.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/SLA/SLAReportFilters.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/SLA/helpers/SLAFilterHelpers.js, app/javascript/packs/application.js, enterprise/app/models/applied_sla.rb, spec/enterprise/controllers/api/v1/accounts/applied_slas_controller_spec.rb
This PR includes filtering SLA reports by agents, Inboxes, SLA policies, teams, and labels.
Fixes https://linear.app/chatwoot/issue/CW-3190/use-the-filter-components-in-the-reports
**Loom video**
https://www.loom.com/share/abb07e83bf7e4ac89abeb22802a0aff7?sid=22e7e36f-3a11-4582-b0be-3d22a63e0edf
=> feat: SLA report filter

app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
This PR will fix the style issues related to the reports filter.
**Screencast**
https://github.com/chatwoot/chatwoot/assets/64252451/2928cf57-315b-498d-aa71-33ff2fa0603d
=> fix: Reports filter style issue

enterprise/app/jobs/portal/article_indexing_job.rb, enterprise/app/models/enterprise/concerns/article.rb
- Move Article embeddings generation to sidekiq
=> chore: Move embedding generation to sidekiq

app/javascript/shared/mixins/keyboardEventListenerMixins.js
Fixes https://linear.app/chatwoot/issue/CW-3263/typeerror-cannot-set-properties-of-undefined-setting
https://chatwoot-p3.sentry.io/issues/5280928904/?project=6382945&referrer=github-pr-bot
=> fix: TypeError cannot set properties of undefined (setting 'keydownHandlerIndex')

app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
Fixes https://github.com/chatwoot/chatwoot/issues/9273
=> chore: fix typos in inboxmgmt.json

app/views/layouts/vueapp.html.erb
Add a new Sentry project for frontend errors only.
=> chore: Add a separate Sentry project for frontend error

yarn.lock
=> chore: run `update-browserslist-db`

app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Whatsapp.vue
- Disabling the creation of new WhatsApp inboxes via 360 Dialog
=> chore: Disable 360 Dialog for Whatsapp

app/controllers/api/v1/accounts/bulk_actions_controller.rb, app/jobs/bulk_actions_job.rb, spec/jobs/bulk_actions_job_spec.rb
This PR adds backend support to include a custom snooze option in the bulk action dropdown.
=> feat: Add support for bulk snooze until

app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue, app/javascript/dashboard/components/widgets/WootWriter/utils/mp3ConversionUtils.js, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, package.json, yarn.lock
Last week, the WhatsApp API has started returning an error message for the voice notes, `Unsupported Audio mime type audio/opus. Please use one of audio/ogg; codecs=opus, audio/mpeg, audio/amr, audio/mp4, audio/aac`. This error began appearing on May 1. Even though there was no change in the files and content type, FB API started rejecting the file. 
I've started a thread [here](https://developers.facebook.com/community/threads/442831395096696/?post_id=442831398430029). However, I didn't get any response so far. Voice notes being one of the most used feature in WhatsApp channel, I'd like to push an interim fix.
In this PR, we are converting the audio recordings from Wav to Mp3 from frontend itself. I've explored a couple of packages to this, read the below list.
- …
=> fix: Convert audio file to mp3 before sending it to WhatsApp

app/javascript/v3/views/login/Index.vue
Fixes: https://chatwoot-p3.sentry.io/share/issue/a081e3eda9704c46a822bc6307704889/
=> fix: Safari compatibility for `requestIdleCallback`

app/javascript/dashboard/routes/dashboard/settings/macros/MacrosTableRow.vue
Fixes https://chatwoot-p3.sentry.io/share/issue/29730a9df77b402b8ee384f86d80081c
Tried finding a root cause, but couldn't seems like the best solution for now
=> fix: no fallback for created_by & updated_by

enterprise/app/models/enterprise/concerns/article.rb, enterprise/lib/chat_gpt.rb
- Switch model to `gpt-4o`  from `gpt-4-turbo`
=> chore: Switch models to gpt-4o

spec/controllers/api/v1/accounts/contacts_controller_spec.rb
- Add a debug statement to check the failed specs
=> chore: Add debug statement in spec

app/javascript/dashboard/api/integrations/linear.js, app/javascript/dashboard/components/widgets/conversation/linear/CreateIssue.vue, app/javascript/dashboard/components/widgets/conversation/linear/CreateOrLinkIssue.vue, app/javascript/dashboard/components/widgets/conversation/linear/LinkIssue.vue, app/javascript/dashboard/components/widgets/conversation/linear/index.vue, app/javascript/dashboard/i18n/locale/en/integrations.json
=> feat: Add title while linking the linear issue

app/javascript/dashboard/i18n/locale/en/bulkActions.json
Fixed typo assigned vs assigned
A typo with _assigned_ word. 
Add missing n, assigned vs assiged
it's not necessary
=> fix: typo bulkActions.json

.env.example
- add more info on SECRET_KEY_BASE
- add a link to env variable section in selfhosted docs
Fixes https://github.com/chatwoot/chatwoot/issues/9517
- n/a
=> doc: update .env.example

app/javascript/dashboard/routes/dashboard/conversation/ConversationInfo.vue
fixed getting browser data
In Vue, without computed properties, the data doesn't update, and because of this, it doesn't display information about the browser.
=> fix: browser info

app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalLocales.vue
The previous changes made on Portal locales introduced a bug where users were not able to set the default locale, this PR fixes that
=> fix: locales settings on portal

app/javascript/v3/views/auth/reset/password/Index.vue, app/javascript/v3/views/login/Index.vue
- Replace `showAlert` with `showAlertMessage` in auth related pages.
=> fix: Reset loader state on error

app/services/auto_assignment/inbox_round_robin_service.rb
=> chore: Update typo in inbox_round_robin_service

.env.example, config/initializers/mailer.rb
Added two Actionmailer's option (open_timeout & read_timeout) to environment variables.
=> feat: Add smtp timeout options

app/services/notification/push_notification_service.rb
Fix notification payload to avoid argument error.
=> fix: Update notification payload

app/javascript/dashboard/helper/automationHelper.js, app/models/concerns/json_schema_validator.rb, app/services/action_service.rb, spec/factories/conversations.rb, spec/services/action_service_spec.rb
Add none to team list in automation
=> feat: Add the ability to un-assign teams using automation

config/locales/vi.yml
=> Update Translate vi.yml

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
Currently, when a user navigates to a chat and attempts to access the custom snooze modal, it is not visible, making it unable to set custom snooze options. With this fix, the custom snooze modal will correctly display even when a chat is open in mobile view.
**Cause of this issue**
The `<custom-snooze-modal/>` component is added to the `<chat-list/>` component. To accommodate small screen views, we are using the expanded view. However, if we open a chat and select the custom snooze option from the chat header in the message view, the `<custom-snooze-modal/>` component is hidden in the `<chat-list/>` component. 
**Solution**
So, I moved the `<custom-snooze-modal/>` to the wrapper component `<conversation-view/>` so we can use in all cases like, 
1. Right-click to custom snooze
2. CMD bar …
=> fix: Custom snooze is not working in mobile view

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
=> feat: Localize 'Social Profiles' in ContactForm.vue using $t and adjust input styling to remove left border-radius.

app/javascript/dashboard/components/widgets/conversation/Message.vue
=> fix: TypeError cannot read properties of null (reading 'file_type')

docker/Dockerfile
Fixes # (issue) unable to select packages #9782
docker compose build base
=> fix: Docker compose  build of unable to select packages

app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItemTable.vue, app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/CategoryListItem.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue
This PR will fix table style breakage in the portal and inbox pre-chat form settings pages.
**Before**
1. 
2. 
3. 
4. 
**After**
1.
2. 
3. 
4.
=> fix: Table styles

Gemfile.lock
- update rexml  due to security advisory
=> chore: Security advisory fix for rexml

app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
`requiredIf('isAnEmailInbox')` was not evaluated properly. This PR fixes it by moving it to a method and using the `this.[variable]` pattern.
=> fix: Fix issues with new conversation form

app/javascript/dashboard/composables/useKeyboardEvents.js
… correctly
This PR fixes an issue where the key down handler in the `useKeyboardEvent` composable was not registering correctly.
=> fix: Keydown handler in `useKeyboardEvent` composable not registering correctly

app/javascript/dashboard/i18n/locale/en/teamsSettings.json, app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue, app/javascript/dashboard/routes/dashboard/settings/teams/teams.routes.js
This PR updates the design for the team listing page. This PR is part of the design revamp project for all the settings pages.
| Light | Dark |
| -- | -- |
| <img width="1433" alt="teams-light" src="https://github.com/user-attachments/assets/b152a6a4-01a7-43c6-8116-613b93c3966c"> | <img width="1429" alt="teams-dark" src="https://github.com/user-attachments/assets/20ad73aa-8bf7-4553-b80c-41ba64b02c3b"> |
=> feat: Update the design for teams

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/widgets/ChatTypeTabs.vue
=> fix: tab styles

app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue, app/javascript/dashboard/i18n/locale/en/advancedFilters.json, app/javascript/dashboard/i18n/locale/en/contactFilters.json, app/javascript/dashboard/routes/dashboard/contacts/components/ContactsAdvancedFilters.vue, app/javascript/shared/composables/useFilter.js
The contact filters broken after merging the [PR](https://github.com/chatwoot/chatwoot/pull/10036). This issue arise because the contact filters were incorrectly sourcing input from conversation filter constants.
Fixes: https://chatwoot-p3.sentry.io/issues/5792836959/?project=4507182691975168&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=1
=> fix: Contact filter attribute groups

lib/integrations/openai_base_service.rb, spec/lib/integrations/openai/processor_service_spec.rb
- update the open AI model, as 3.5 is being deprecated. Provide as option to swap out models via environment variables.
=> chore: Update GPT Model

app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/featureFlags.js
Fixes #10107
Removes feature flag for the feature insert article to editor.
=> fix: Remove feature flag for insert article into editor

app/models/message.rb, app/views/api/v1/accounts/search/_message.json.jbuilder, app/views/api/v1/models/_conversation.json.jbuilder, app/views/api/v1/models/_message.json.jbuilder, app/views/api/v1/models/_widget_message.json.jbuilder, app/views/api/v1/widget/messages/create.json.jbuilder, app/views/api/v1/widget/messages/index.json.jbuilder, app/views/public/api/v1/models/_message.json.jbuilder, spec/controllers/api/v1/accounts/search_controller_spec.rb, spec/controllers/api/v1/widget/conversations_controller_spec.rb, spec/controllers/api/v1/widget/messages_controller_spec.rb, spec/controllers/public/api/v1/inbox/messages_controller_spec.rb, spec/models/message_spec.rb
Reverts chatwoot/chatwoot#10108
=> revert: "fix: `message_type` inconsistency across message end points"

app/controllers/api/v1/accounts/conversations/messages_controller.rb, spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
- fix issue with deleting interactive messages
=> chore: Fix issue with deleting interactive messages

app/models/integrations/app.rb, app/models/integrations/hook.rb, config/integration/apps.yml, lib/chatwoot_hub.rb, spec/lib/chatwoot_hub_spec.rb, spec/models/integrations/app_spec.rb, spec/models/integrations/hook_spec.rb
- Provision accounts on Chatwoot cloud automatically if the feature is enabled
=> feat: Provision captain accounts automatically

README.md, package.json, pnpm-lock.yaml
Reference: https://github.com/chatwoot/chatwoot/pull/10195
=> feat: Upgrade vite to 5.4.8 to fix dependabot/186

.github/workflows/run_response_bot_spec.yml, .github/workflows/size-limit.yml, package.json
Fixes https://linear.app/chatwoot/issue/CW-3604/fix-gh-actions-for-vite-build
- Tests are passing
=> fix: gh actions for vite build

app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue
=> fix: Update card labels button with a new one to fix the CSS issue

docker/Dockerfile
- Switch to `pnpm` from `yarn` for docker builds
- Tested building manually on a fresh machine with latest docker
```
root@ip-172-31-8-13:/home/ubuntu# docker images
REPOSITORY      TAG                IMAGE ID       CREATED        SIZE
chatwoot-vite   latest             fa168d561770   5 hours ago    1.56GB
ruby            3.3.3-alpine3.19   938a3408645e   3 months ago   80.4MB
```
=> feat: support vite build for docker based installations

app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Fixes https://linear.app/chatwoot/issue/CW-3617/drag-and-drop-not-working
**Loom video**
https://www.loom.com/share/e3de3ed02811490dbca3f165ad58dc47?sid=b44250c0-233d-4ea6-a91d-28dae4c5e259
=> fix: Drag and drop attachments

app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue, app/javascript/dashboard/routes/dashboard/conversation/contact/SocialIcons.vue
Fixes https://linear.app/chatwoot/issue/CW-3648/chore-show-telegram-user-name-next-to-the-contact-details-if-available
**Preview**
=> feat: Add telegram user name in contact details 

app/javascript/dashboard/components-next/dropdown-menu/DropdownMenu.story.vue, app/javascript/dashboard/components-next/dropdown-menu/DropdownMenu.vue
**Screenshot from story**
**Light**
**Dark**
NB: We can add more cases when we work on adding new designs
=> feat: New Dropdown menu component

app/javascript/dashboard/components-next/CardLayout.vue, app/javascript/dashboard/components-next/HelpCenter/ArticleCard/ArticleCard.story.vue, app/javascript/dashboard/components-next/HelpCenter/ArticleCard/ArticleCard.vue
**Screenshot from story**
**NB**: We need to merge all the base components. (DropdownMenu, Button, etc) PR.
**Light**
**Dark**
=> feat: Article card component

app/javascript/dashboard/components-next/CardLayout.vue, app/javascript/dashboard/components-next/HelpCenter/CategoryCard/CategoryCard.story.vue, app/javascript/dashboard/components-next/HelpCenter/CategoryCard/CategoryCard.vue
**Screenshot from story**
**NB**: We need to merge all the base components. (DropdownMenu, Button, etc) PR.
**Light**
**Dark**
=> feat: Category card component

app/javascript/dashboard/components-next/CardLayout.vue, app/javascript/dashboard/components-next/HelpCenter/LocaleCard/LocaleCard.story.vue, app/javascript/dashboard/components-next/HelpCenter/LocaleCard/LocaleCard.vue
**Screenshot from story**
**NB**: We need to merge all the base components. (DropdownMenu, Button, etc) PR.
**Light**
**Dark**
=> feat: Locale card component

Makefile
=> fix: Use pnpm in make setup command

deployment/setup_20.04.sh
=> chore: increment cwctl version

app/javascript/dashboard/components-next/spinner/Spinner.story.vue, app/javascript/dashboard/components-next/spinner/Spinner.vue
=> feat: Add Spinner to new components

docker-compose.yaml, docker/dockerfiles/vite.Dockerfile, docker/entrypoints/vite.sh
- Fix docker development 
- Switch from webpack to vite 
=> feat: switch docker dev from webpack to vite

app/javascript/dashboard/components-next/sidebar/SidebarGroup.vue, app/javascript/dashboard/modules/search/search.routes.js, app/javascript/dashboard/routes/dashboard/contacts/routes.js, app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js, app/javascript/dashboard/routes/dashboard/dashboard.routes.js, app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js, app/javascript/dashboard/routes/dashboard/inbox/routes.js, app/javascript/dashboard/routes/dashboard/notifications/routes.js, app/javascript/dashboard/routes/dashboard/settings/account/account.routes.js, app/javascript/dashboard/routes/dashboard/settings/agentBots/agentBot.routes.js, app/javascript/dashboard/routes/dashboard/settings/agents/agent.routes.js, app/javascript/dashboard/routes/dashboard/settings/attributes/attributes.routes.js, app/javascript/dashboard/routes/dashboard/settings/auditlogs/audit.routes.js, app/javascript/dashboard/routes/dashboard/settings/automation/automation.routes.js, app/javascript/dashboard/routes/dashboard/settings/billing/billing.routes.js, app/javascript/dashboard/routes/dashboard/settings/campaigns/campaigns.routes.js, app/javascript/dashboard/routes/dashboard/settings/canned/canned.routes.js, app/javascript/dashboard/routes/dashboard/settings/customRoles/customRole.routes.js, app/javascript/dashboard/routes/dashboard/settings/inbox/inbox.routes.js, app/javascript/dashboard/routes/dashboard/settings/integrations/integrations.routes.js, app/javascript/dashboard/routes/dashboard/settings/labels/labels.routes.js, app/javascript/dashboard/routes/dashboard/settings/macros/macros.routes.js, app/javascript/dashboard/routes/dashboard/settings/profile/profile.routes.js, app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js, app/javascript/dashboard/routes/dashboard/settings/sla/sla.routes.js, app/javascript/dashboard/routes/dashboard/settings/teams/teams.routes.js, app/javascript/entrypoints/widget.js, app/javascript/v3/views/routes.js
This pull request updates the navigation in `SidebarGroup.vue` component to update navigation functionality within the sidebar. Here's the behavior
  | isExpanded | isCollapsed
-- | -- | --
Has Active Children | Collapse | Expand Only
No Active Children | Collapse | Expand and select first item
=> feat: automatically toggle first item

app/javascript/dashboard/components-next/HelpCenter/ArticleCard/ArticleCard.vue, app/javascript/dashboard/components-next/HelpCenter/Pages/ArticleEditorPage/ArticleEditorControls.vue, app/javascript/dashboard/components-next/HelpCenter/Pages/ArticlePage/ArticlesPage.vue, app/javascript/dashboard/components-next/HelpCenter/Pages/LocalePage/LocalesPage.vue, app/javascript/dashboard/components-next/HelpCenter/PortalSwitcher/PortalSwitcher.vue, app/javascript/dashboard/components-next/tabbar/TabBar.vue, app/javascript/dashboard/components-next/thumbnail/Thumbnail.vue, app/javascript/dashboard/i18n/locale/en/components.json, app/javascript/dashboard/i18n/locale/en/helpCenter.json, app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js, app/javascript/shared/components/FluentIcon/dashboard-icons.json
This PR includes portal redesign improvements.
**Improvements**
1. Automatically select the category when creating a new article if a filter is applied in article list.
2. Add a button to preview public portal in the portal switcher.
3. Add a loader for the locale screen when switching portals from the switcher.
4. Remove the font weight in the active state of the tab bar.
5. Update the copy text for empty state.
6. Handle the case where the original author is removed from the account. (Previously, it displayed the current user's name automatically without selection. Now, we show an icon on the thumbnail with a tooltip text 'Author is not available.' This only applies to existing articles.)
**Loom video**
https://www.loom.com/share/160b4512d26442f0b906df91869f2a2f?sid=4af8a0c0-7ef3-4630-9d …
=> feat(v4): Help center portal redesign improvements

docker/entrypoints/vite.sh
- Force `pnpm install` during vite docker image
=> chore: force pnpm install in vite docker

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/helper/commons.js, app/javascript/dashboard/helper/specs/commons.spec.js, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/i18n/locale/pt_BR/conversation.json
I decided to close PR #10360 and split it into 2 separate PRs.
This fix consists of translating the message when another user is typing on the other side.
When sending a message from widget_test to an agent, the message that the user on the other end is typing will be translated.
=> fix: Translation to the isAnyoneTyping() method

app/javascript/dashboard/components-next/HelpCenter/Pages/ArticleEditorPage/ArticleEditor.vue
Quick fix for CW-3721 until we work on a better solution
=> feat: update debounce duration for article editor

app/javascript/dashboard/components-next/selectmenu/SelectMenu.story.vue, app/javascript/dashboard/components-next/selectmenu/SelectMenu.vue
=> feat: New select menu component

app/javascript/dashboard/components-next/dropdown-menu/base/DropdownBody.vue, app/javascript/dashboard/components-next/dropdown-menu/base/DropdownItem.vue
This PR updates the background used in dropdown to match our design system. Previous PR failed to add this correctly.
=> fix: dropdown bg

deployment/setup_20.04.sh
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
=> refactor: clear apt warning

app/javascript/dashboard/components-next/Contacts/ContactsHeader/ContactHeader.vue, app/javascript/dashboard/components-next/Contacts/ContactsHeader/ContactListHeaderWrapper.vue, app/javascript/dashboard/components-next/filter/ContactsFilter.vue, app/javascript/dashboard/components-next/filter/contactProvider.js, app/javascript/dashboard/components-next/filter/helper/filterHelper.js, app/javascript/dashboard/components-next/filter/helper/filterHelper.spec.js, app/javascript/dashboard/components-next/filter/provider.js, app/javascript/dashboard/i18n/locale/en/contact.json, app/javascript/dashboard/store/modules/contacts/getters.js
=> feat: New contacts advanced filter

app/javascript/dashboard/components-next/Contacts/ContactsDetailsLayout.vue, app/javascript/dashboard/components-next/Contacts/ContactsHeader/ContactHeader.vue, app/javascript/dashboard/components-next/Contacts/ContactsHeader/components/ContactsActiveFiltersPreview.vue, app/javascript/dashboard/components-next/Contacts/ContactsListLayout.vue, app/javascript/dashboard/components-next/Contacts/ContactsSidebar/ContactHistory.vue, app/javascript/dashboard/components-next/Contacts/ContactsSidebar/components/ContactNoteItem.vue, app/javascript/dashboard/components-next/Conversation/ConversationCard/ConversationCard.vue, app/javascript/dashboard/components-next/filter/ActiveFilterPreview.vue, app/javascript/dashboard/routes/dashboard/contacts/pages/ContactsIndex.vue
Fixes https://linear.app/chatwoot/issue/CW-3774/contact-details-dropdown-overflow
**Changes/Fix**
1. Fix scroll inside contact details has a padding.
2. Add padding to `ContactNotes` and `ContactConversations`
3. Show applied filers view in the segments view.
4. Label List Overflow **(Not fixed)**
=> chore: Contact improvements

app/javascript/dashboard/components-next/Contacts/ContactsDetailsLayout.vue, app/javascript/dashboard/components-next/NewConversation/ComposeConversation.vue, app/javascript/dashboard/components-next/NewConversation/components/ContactSelector.vue, app/javascript/dashboard/components-next/NewConversation/helpers/composeConversationHelper.js, app/javascript/dashboard/components-next/NewConversation/helpers/specs/composeConversationHelper.spec.js, app/javascript/dashboard/components-next/dropdown-menu/DropdownMenu.vue, app/javascript/dashboard/components-next/sidebar/Sidebar.vue, app/javascript/dashboard/components-next/taginput/TagInput.vue, app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue, app/javascript/dashboard/helper/inbox.js
**Fixes**
1. Only show suggestion in dropdown if it's a valid email.
2. Handle case where we cannot remove the contact 
3. Adds outside click
4. Show active state for contacts in old sidebar
5. Fix icons not showing
=> fix: New compose conversation form

app/jobs/internal/process_stale_redis_keys_job.rb, app/jobs/internal/remove_stale_redis_keys_job.rb, app/services/internal/remove_stale_redis_keys_service.rb, spec/jobs/internal/process_stale_redis_keys_job_spec.rb, spec/jobs/internal/remove_stale_redis_keys_job_spec.rb, spec/services/internal/remove_stale_redis_keys_service_spec.rb
- Fix RemoveStaleRedisKeys service 
=> fix: RemoveStaleRedisKeys service

app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue, app/javascript/dashboard/components/widgets/conversation/ConversationSidebar.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/constants/globals.js, app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
- Increase the sidebar and chatlist width on screens bigger than 2xl
- Fix background of the copilot sidebar
- Increase the breakpoint for hiding chatlist from 1024 to 1200
=> fix: Update design of the conversation sidebar, chatlist

app/javascript/dashboard/components/ChatListHeader.vue
This PR fixes the overflow issue with the chat list header title.
**Before**
**After**
=> fix: Chat list header overflow issue

.github/workflows/publish_foss_docker.yml
- Add multiarch arm64 support for docker ce images
=> feat: add multiarch arm64 support in ce docker images

.circleci/config.yml
- pin bundler version to 2.5.x in circleci
- tested on circle ci
=> chore: pin bundler version to 2.5.x in circleci

app/javascript/dashboard/components-next/Contacts/ContactLabels/ContactLabels.vue, app/javascript/dashboard/components-next/Label/LabelItem.vue
This PR adds the ability to remove contact labels from the label card. This way, you don't need to go to the label dropdown to remove the label.
**Loom video**
https://www.loom.com/share/5a83fe844df442008fa643232f15fff3?sid=3ecbcacb-95d7-4c68-946d-2306c5cfe798
=> chore: Adds the ability to remove labels from label card

app/javascript/dashboard/components-next/Inbox/InboxCard.vue, app/javascript/dashboard/components-next/message/Message.vue, app/javascript/dashboard/components-next/message/bubbles/InstagramStory.vue, app/javascript/dashboard/components-next/message/bubbles/Text/FormattedContent.vue
This PR has the following fixes
1. Remove leading `:` in inbox view push message content
2. Styles for block quotes in text
3. Better condition for checking bot message
4. Use dompurify
=> fix: v4 ui issues

app/javascript/dashboard/components-next/message/chips/File.vue
https://github.com/user-attachments/assets/e84d94d5-876d-4c00-88be-a460f917bf3b
=> fix: attachment url in file chip

app/javascript/dashboard/components-next/message/bubbles/Email/Index.vue, app/javascript/dashboard/components-next/message/bubbles/Text/FormattedContent.vue, tailwind.config.js
=> fix: bubble typograhy

app/javascript/dashboard/components-next/message/MessageError.vue, app/javascript/dashboard/components/ui/Banner.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
=> fix: reply box banner UI

app/javascript/dashboard/components-next/message/Message.vue, app/javascript/dashboard/components-next/message/bubbles/Base.vue
Fix bubble radius when grouping based on timestamp
=> fix: bubble style when grouping with next

app/javascript/dashboard/components-next/Conversation/ConversationCard/ConversationCard.vue
This PR will fix an overflow issue with the new conversation card.
**Before**
**After**
=> fix(v4): Overflow issue in conversation card

app/javascript/dashboard/components-next/Editor/Editor.vue, app/javascript/dashboard/components-next/NewConversation/ComposeConversation.vue, app/javascript/dashboard/components-next/NewConversation/components/ActionButtons.vue, app/javascript/dashboard/components-next/NewConversation/components/ComposeNewConversationForm.vue, app/javascript/dashboard/components-next/NewConversation/components/MessageEditor.vue, app/javascript/dashboard/components-next/textarea/TextArea.vue
**Message Signature**
1. Adds support for message signature in TextArea(v4) component
2. Adds the ability to use message signature for all inboxes except WhatsApp ⇒
(**NB:** Before only Email and Web widget inbox)
**Canned response/Variables**
1. Adds variable support for Advance Editor (Email and Web widget inboxes)
2. Adds canned response support for Plain editor (All other inboxes except WhatsApp) ⇒
Fixes https://github.com/chatwoot/chatwoot/issues/10655 https://linear.app/chatwoot/issue/CW-3859/canned-responses-not-showing-on-new-contacts-page-when-sending
**Loom video**
https://www.loom.com/share/e342c937f0da4cd5b21478b101076469?sid=4de27a51-1873-4a9b-ad7f-e6c359993a5a
=> chore: Improve new conversation form

app/javascript/dashboard/components/Accordion/AccordionItem.vue, app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroItem.vue, app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
This PR fixes the following problem.
=> fix: Remove overflow-hidden on accordionItem

app/javascript/dashboard/components-next/captain/assistant/AssistantCard.story.vue, app/javascript/dashboard/components-next/captain/assistant/DocumentCard.story.vue, app/javascript/dashboard/components-next/captain/assistant/InboxCard.story.vue, app/javascript/dashboard/components-next/captain/assistant/ResponseCard.story.vue, app/javascript/dashboard/components-next/captain/pageComponents/emptyStates/AssistantPageEmptyState.vue, app/javascript/dashboard/components-next/captain/pageComponents/emptyStates/DocumentPageEmptyState.vue, app/javascript/dashboard/components-next/captain/pageComponents/emptyStates/InboxPageEmptyState.vue, app/javascript/dashboard/components-next/captain/pageComponents/emptyStates/ResponsePageEmptyState.vue, app/javascript/dashboard/components-next/captain/pageComponents/emptyStates/captainEmptyStateContent.js, app/javascript/dashboard/i18n/locale/en/integrations.json, app/javascript/dashboard/routes/dashboard/captain/assistants/Index.vue, app/javascript/dashboard/routes/dashboard/captain/assistants/inboxes/Index.vue, app/javascript/dashboard/routes/dashboard/captain/documents/Index.vue, app/javascript/dashboard/routes/dashboard/captain/responses/Index.vue
This PR introduces an empty state view for all captain pages.
**Assistant**
**Inbox**
**Documents**
**Response(FAQs)**
=> feat: Implement Empty State UI for Captain Pages

app/javascript/dashboard/assets/scss/widgets/_buttons.scss, app/javascript/dashboard/components-next/Label/AddLabel.vue, app/javascript/dashboard/components/CustomAttribute.vue, app/javascript/dashboard/components/ui/Label.vue, app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue, app/javascript/dashboard/components/widgets/conversation/PriorityMark.vue, app/javascript/dashboard/components/widgets/conversation/contextMenu/Index.vue, app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItem.vue, app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/LabelActions.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/TeamActions.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/UpdateActions.vue, app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue, app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
| **Before**  | **After** |
| ------------- | ------------- |
| <img width="281" alt="image" src="https://github.com/user-attachments/assets/9d52651c-2281-43d3-91b9-e210e5c29a8c" /> | <img width="284" alt="image" src="https://github.com/user-attachments/assets/785d0a8c-2c65-4dc5-922a-819f0cfb7be0" /> |
| <img width="213" alt="image" src="https://github.com/user-attachments/assets/7362de5b-e5a8-4df9-a8f7-ff898a0d716a" /> | <img width="204" alt="image" src="https://github.com/user-attachments/assets/873773fb-ad9e-4f18-ac2e-7e1f0ded25dc" /> |
| <img width="393" alt="image" src="https://github.com/user-attachments/assets/541b2559-8409-463b-b85b-7efd3d77f56d" /> | <img width="410" alt="image" src="https://github.com/user-attachments/assets/6d972cc3-76c3-4f5f-aa34-75cd61ac378a" …
=> chore(v4): Update colors

app/javascript/dashboard/components-next/Conversation/ConversationCard/CardMessagePreview.vue, app/javascript/dashboard/components-next/Conversation/ConversationCard/CardMessagePreviewWithMeta.vue, app/javascript/dashboard/components-next/message/chips/Audio.vue, app/javascript/dashboard/composables/chatlist/useChatListKeyboardEvents.js, app/javascript/dashboard/store/modules/conversations/actions.js
1. Ensure audio player ref is accessible before triggering calls ([Sentry](https://chatwoot-p3.sentry.io/issues/6221981610))
2. Use correct default for attachments, this was incorrectly set to `null` in a previous PR ([Sentry](https://chatwoot-p3.sentry.io/issues/5966738120))
3. Fix `lastNonActivityMessage` is not present ([Sentry](https://chatwoot-p3.sentry.io/issues/6116038455))
4. Fix `Alt+J` & `Alt+K` shortcuts not working ([Sentry](https://chatwoot-p3.sentry.io/issues/6075125384))
=> fix: sentry issues

config/schedule.yml
During Captain, scheduled jobs were disabled. This PR would re-enable them
=> fix: Re-enable scheduled jobs

app/javascript/dashboard/components-next/message/Message.vue, app/javascript/dashboard/components-next/message/bubbles/CSAT.vue, app/javascript/dashboard/components-next/message/bubbles/Form.vue, app/javascript/dashboard/i18n/locale/en/conversation.json
=> feat: add CSAT & Form bubble

app/javascript/dashboard/components-next/HelpCenter/HelpCenterLayout.vue, app/javascript/dashboard/components-next/pagination/PaginationFooter.vue
1. Adds depth effect for pagination when scrolling
https://github.com/user-attachments/assets/32b8dbe0-2088-49a6-97ba-defb32afe8cf
2. Adds left and right padding for Help center Header and Main section
=> chore: Design improvements

app/javascript/dashboard/components-next/copilot/Copilot.vue, app/javascript/dashboard/components-next/copilot/CopilotAssistantMessage.vue, app/javascript/dashboard/components/copilot/CopilotContainer.vue, app/javascript/dashboard/helper/AnalyticsHelper/events.js, app/javascript/dashboard/i18n/locale/en/conversation.json, app/javascript/dashboard/i18n/locale/en/integrations.json, config/installation_config.yml, enterprise/app/controllers/enterprise/api/v1/accounts/conversations_controller.rb, enterprise/app/controllers/enterprise/super_admin/app_configs_controller.rb, enterprise/app/helpers/captain/chat_helper.rb, enterprise/app/services/captain/copilot/chat_service.rb, enterprise/app/services/captain/llm/assistant_chat_service.rb, enterprise/app/services/captain/llm/base_open_ai_service.rb, enterprise/app/services/captain/llm/contact_attributes_service.rb, enterprise/app/services/captain/llm/contact_notes_service.rb, enterprise/app/services/captain/llm/conversation_faq_service.rb, enterprise/app/services/captain/llm/faq_generator_service.rb, enterprise/app/services/captain/llm/system_prompts_service.rb, enterprise/lib/captain/agent.rb, enterprise/lib/captain/llm_service.rb, spec/enterprise/services/captain/llm/conversation_faq_service_spec.rb
This PR adds the following two features
1. Prompt suggestions to get started with Copilot Chat
2. June events for each action
=> feat: add prompt suggestions and June events

app/javascript/dashboard/components-next/message/bubbles/Image.vue, app/javascript/dashboard/components/widgets/conversation/components/GalleryView.vue
This PR improves attachment download functionality and fixes related issues:
- Adds loading states for better user feedback:
- Shows loading indicator on the download button during download
- Disables download button while download is in progress to prevent duplicate requests
- Fixes gallery view interaction issues:
- Prevents gallery view from closing when downloading attachments
- Fixes gallery view opening when downloading button is clicked from message bubble
- Fixes zoom-out not working after reaching max zoom (Through mouse click)
**Screen recordings**
https://github.com/user-attachments/assets/bee02f06-fdfa-4358-b894-b2a8ffcaf24b
https://github.com/user-attachments/assets/00c80132-081d-4e00-b783-a2df554d2d72
=> chore: Adds loader for attachment download buttons

app/fields/enterprise/account_limits_field.rb, config/locales/en.yml, enterprise/app/controllers/api/v1/accounts/captain/documents_controller.rb, enterprise/app/controllers/enterprise/api/v1/accounts/conversations_controller.rb, enterprise/app/controllers/enterprise/super_admin/app_configs_controller.rb, enterprise/app/helpers/captain/chat_helper.rb, enterprise/app/jobs/captain/conversation/response_builder_job.rb, enterprise/app/jobs/captain/tools/simple_page_crawl_parser_job.rb, enterprise/app/models/captain/document.rb, enterprise/app/models/enterprise/account.rb, enterprise/app/models/enterprise/inbox.rb, enterprise/app/services/captain/copilot/chat_service.rb, enterprise/app/services/enterprise/billing/handle_stripe_event_service.rb, enterprise/app/services/enterprise/message_templates/hook_execution_service.rb, enterprise/listeners/captain_listener.rb, spec/enterprise/controllers/api/v1/accounts/captain/documents_controller_spec.rb, spec/enterprise/jobs/captain/conversation/response_builder_job_spec.rb, spec/enterprise/models/account_spec.rb, spec/enterprise/services/captain/copilot/chat_service_spec.rb, spec/enterprise/services/enterprise/billing/handle_stripe_event_service_spec.rb, spec/models/account_spec.rb
This pull request introduces several changes to implement and manage usage limits for the Captain AI service. The key changes include adding configuration for plan limits, updating error messages, modifying controllers and models to handle usage limits, and updating tests to ensure the new functionality works correctly.
Limits
```json
{
"hacker": {
"documents": 0,
"responses": 0
},
"startups": {
"documents": 100,
"responses": 100
},
"business": {
"documents": 200,
"responses": 300
},
"enterprise": {
"documents": 300,
"responses": 500
}
}
```
  | Is within limit | Limit exceeded | Limit exceeds mid-way
-- | -- | -- | --
Copilot Chat | Correctly responds | Responds with a limit | Works
Widget Chat | Starts the conversation in pending and replies correctly | Opens the conversation directly | …
=> feat: setup captain limits

app/javascript/dashboard/components/widgets/conversation/components/GalleryView.vue, package.json, pnpm-lock.yaml
Ref: https://github.com/chatwoot/utils/pull/39
=> fix: Download file `CORS` issue

deployment/chatwoot-worker.1.service
- Add OOM policy for `sidekiq` `systemd` service
- This ensures `sidekiq` does not consume all the memory available in the system
=> feat: add OOMPolicy for sidekiq systemd service

.github/workflows/publish_foss_docker.yml
- Fix the docker tag issue during push stage for ce image build
- Tested via github action
=> fix: docker github action for ce images

app/javascript/dashboard/components-next/sidebar/Sidebar.vue, app/javascript/dashboard/components-next/sidebar/SidebarGroup.vue, app/javascript/dashboard/components-next/sidebar/SidebarGroupHeader.vue, app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue, app/javascript/dashboard/store/modules/notifications/getters.js, app/javascript/dashboard/store/modules/notifications/index.js, app/javascript/dashboard/store/modules/specs/notifications/getters.spec.js
This PR adds a badge to the icon in the sidebar group header and an unread highlight for the inbox view.
**Loom video**
https://www.loom.com/share/1a880aa16de249a1836b8d014325c067?sid=87cc7b64-667b-4066-8993-d33abccf7b67
=> feat: Add unread badge to sidebar for inbox view

app/javascript/dashboard/components-next/Contacts/ContactsForm/ContactsForm.vue, app/javascript/dashboard/components-next/Contacts/ContactsForm/CreateNewContactDialog.vue
This PR updates the contact form validation to allow a minimum length of one character for the first name.
Fixes https://linear.app/chatwoot/issue/CW-3993/update-the-validation-on-contact-form-to-support-just-one-character
https://github.com/user-attachments/assets/2b95af80-ee70-4f4b-8d0d-b01779db9d94
=> chore: Update name field min-length validation in contact form

README.md
Update copyright year to 2025
This PR updates the copyright year in the README
=> docs: Update copyright year to 2025

app/javascript/dashboard/components-next/message/bubbles/Email/EmailMeta.vue
Fixes https://github.com/chatwoot/chatwoot/issues/10807
=> fix: incorrect sender name on email meta

app/presenters/conversations/event_data_presenter.rb, app/views/api/v1/conversations/partials/_conversation.json.jbuilder, spec/models/conversation_spec.rb, spec/presenters/conversations/event_data_presenter_spec.rb
This PR adds updated_at attribute to the conversation event.
=> chore: Add updated_at attribute to the conversation event

app/javascript/dashboard/helper/AudioAlerts/DashboardAudioNotificationHelper.js
Handle `mine` condition, missed in https://github.com/chatwoot/chatwoot/pull/10529
=> feat: handle mine event for incoming messages

app/javascript/dashboard/components/Modal.vue, app/javascript/dashboard/components/buttons/Button.vue, app/javascript/dashboard/components/widgets/forms/Input.vue, app/javascript/v3/components/Button/SubmitButton.vue
Fixes: https://github.com/chatwoot/chatwoot/issues/10734
=> refactor: show deprecation warnings in dev only

config/locales/en.yml, enterprise/app/jobs/captain/inbox_pending_conversations_resolution_job.rb
Move the text content to i18n file.
=> fix: Move auto resolution message text content to i18n file

app/javascript/dashboard/routes/dashboard/inbox/components/InboxDisplayMenu.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxListHeader.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxOptionMenu.vue, app/javascript/dashboard/routes/dashboard/inbox/components/MenuItem.vue
Fixes https://linear.app/chatwoot/issue/CW-4041/issues-with-pt-br-locale
=> fix: UI issue with `pt-Br` locale

app/javascript/dashboard/components-next/Campaigns/Pages/CampaignPage/LiveChatCampaign/LiveChatCampaignDialog.vue
Fixes https://linear.app/chatwoot/issue/CW-4050/wrong-toast-message-on-creation-of-a-live-chat-campaign
https://github.com/chatwoot/chatwoot/issues/10913
=> fix: Wrong toast message on creation of a Live Chat campaign

Gemfile, Gemfile.lock
Hi! I've recently started helping maintain this gem as we use it heavily in our app as well. It's been updated to work with newer versions of nokogiri and has a few important fixes too.
Assuming you already have test coverage that would cover this.
=> chore(deps): switch html2text back to rubygems

app/javascript/dashboard/components-next/message/Message.vue, app/javascript/dashboard/components-next/message/chips/Audio.vue, tailwind.config.js
Just making it easier to test and merge https://github.com/chatwoot/chatwoot/pull/10796. 
This PR does the following: 
- Removes the change on br + br condition. 
- Support 1x, 1.5x, 2x playbacks
- Add a hover on the agent avatar
=> fix: Fix issues in bubble design

app/javascript/dashboard/components-next/message/bubbles/Dyte.vue
Fixes https://linear.app/chatwoot/issue/CW-4069/typeerror-cannot-set-properties-of-undefined-setting-dyteauthtoken
=> fix: Fix issues with leave room button

app/javascript/dashboard/components-next/message/bubbles/BaseAttachment.vue, app/javascript/dashboard/i18n/locale/en/contact.json
This PR includes fix for,
**1**. Incorrect error message translation for search in contact merge modal.
**2**. Z-index issue in chat screen
**1.** 
**2.**
=> fix: Incorrect translation in contact merge modal and resolve z-index issue

app/javascript/dashboard/components/widgets/Thumbnail.vue, app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
https://github.com/user-attachments/assets/5d7524c1-b1ca-454f-8e89-843ca25d017e
https://github.com/user-attachments/assets/49814190-d6b4-4553-bced-3987be3583e2
=> feat: don't hide thumbnail on hover

app/javascript/dashboard/components-next/sidebar/SidebarProfileMenu.vue
Update the rendering logic based on the branding installation type etc. Used CustomBrandPolicyWrapper to render the child component
=> fix: Update rendering logic for the "Read Documentation" link

config/routes.rb, spec/controllers/super_admin/platform_apps_controller_spec.rb
- Add the ability to delete platform app from super admin.
=> feat: Ability to delete platform app from super admin

enterprise/app/helpers/captain/chat_helper.rb, enterprise/app/services/captain/llm/system_prompts_service.rb
- Add support for citations in the captain`s responses
Citations in response
----
Citations in copilot
----
- Tested locally with multiple assistants using different documents
=> feat: add support for citations in captain responses

app/javascript/dashboard/components-next/NewConversation/ComposeConversation.vue, app/javascript/dashboard/components-next/NewConversation/helpers/composeConversationHelper.js, app/javascript/dashboard/components-next/NewConversation/helpers/specs/composeConversationHelper.spec.js, app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue, app/views/api/v1/models/_inbox_slim.json.jbuilder
The issue was introduced in https://github.com/chatwoot/chatwoot/pull/10888, where the conversation editor experienced a bug due to the use of templates, email, and phone number payloads in contactable inboxes.  
A temporary fix was applied on the backend in https://github.com/chatwoot/chatwoot/pull/10985.
This PR implements a proper fix on the frontend, ensuring the issue is resolved without relying on the backend workaround. It also removes the temporary backend fix.  
Fixes https://github.com/chatwoot/chatwoot/issues/10979
=> chore: Fix issue with compose conversation form

.gitignore, swagger/paths/application/conversation/custom_attributes.yml, swagger/paths/index.yml, swagger/swagger.json
- Add swagger endpoint for updating custom attributes in a conversation
=> chore: Add Swagger endpoint for updating custom attributes

app/javascript/dashboard/components/widgets/conversation/linear/CreateIssue.vue, app/javascript/dashboard/components/widgets/conversation/linear/LinkIssue.vue, app/javascript/dashboard/components/widgets/conversation/linear/index.vue, app/javascript/dashboard/helper/AnalyticsHelper/events.js
Fixes https://linear.app/chatwoot/issue/CW-3415/june-sdk-events
=> feat: Add june events for linear integration

.github/workflows/nightly_installer.yml
- chore: fix nightly linux installer github action
=> chore: fix nightly linux installer github action

app/javascript/dashboard/routes/dashboard/Dashboard.vue
Move old sidebar loading to async
=> chore: Dynamically load OldSidebar if needed

app/javascript/dashboard/assets/scss/widgets/_base.scss, app/javascript/dashboard/components/ui/Wizard.vue, app/javascript/dashboard/routes/dashboard/conversation/ConversationAction.vue, app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/macros/MacroProperties.vue
This PR fixes a copy issue in team's multi-select dropdown and the background in the settings page.
**Before**
**After**
=> fix: Wrong copy with teams multi-select dropdown

app/javascript/dashboard/composables/useAutomationValues.js, app/javascript/dashboard/helper/automationHelper.js, app/javascript/dashboard/helper/specs/automationHelper.spec.js, app/javascript/dashboard/i18n/locale/en/automation.json
This PR includes a translation update for the "None" option in the automation select for both agents and teams
=> fix: Translate "None" option in automation select

app/channels/room_channel.rb, app/jobs/action_cable_broadcast_job.rb, app/listeners/action_cable_listener.rb, spec/channels/room_channel_spec.rb, spec/listeners/action_cable_listener_spec.rb
=> fix: Move contact events to account stream rather than individual users

app/javascript/dashboard/i18n/locale/en/agentBots.json, app/javascript/dashboard/i18n/locale/en/integrationApps.json, app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue, app/javascript/dashboard/routes/dashboard/settings/agentBots/Index.vue, app/javascript/dashboard/routes/dashboard/settings/agentBots/agentBot.routes.js, app/javascript/dashboard/routes/dashboard/settings/agentBots/components/AgentBotRow.vue, app/javascript/dashboard/routes/dashboard/settings/agentBots/components/AgentBotType.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/IntegrationHooks.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/MultipleIntegrationHooks.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/integrations.routes.js
|Previous|Updated|
|--|--|
| <img width="1081" alt="image" src="https://github.com/user-attachments/assets/61e71e5c-d359-48e4-976f-09f1e34d14f0" /> | <img width="1081" alt="image" src="https://github.com/user-attachments/assets/0e045638-d2e1-4682-acb0-2f9e9c13a3c8" /> |
|Previous|Updated|
|--|--|
| <img width="1191" alt="image" src="https://github.com/user-attachments/assets/30c8e4a0-85cb-4ecd-aa27-87d70d16d078" /> | <img width="1191" alt="image" src="https://github.com/user-attachments/assets/9777244c-07f5-40f8-b732-c8a91d9f86a1" /> |
=> chore: Update settings to match the new design

app/controllers/api/v1/widget/campaigns_controller.rb, app/controllers/api/v1/widget/inbox_members_controller.rb, app/javascript/widget/store/modules/campaign.js, app/javascript/widget/store/modules/specs/campaign/actions.spec.js, app/javascript/widget/store/modules/specs/campaign/mutations.spec.js, app/views/public/api/v1/models/_category.json.jbuilder
- Cache campaigns for better performance
- Fix N+1 queries in inbox members
- Remove unused related articles
=> fix: Improve performance of most hit APIs in widget

app/javascript/dashboard/routes/dashboard/settings/customRoles/Index.vue, app/javascript/dashboard/routes/dashboard/settings/customRoles/component/CustomRoleModal.vue, app/javascript/dashboard/routes/dashboard/settings/customRoles/component/CustomRoleTableBody.vue
=> chore: Update buttons in custom role page

app/javascript/dashboard/routes/dashboard/settings/sla/SlaForm.vue, app/javascript/dashboard/routes/dashboard/settings/sla/components/SLAHeader.vue, app/javascript/dashboard/routes/dashboard/settings/sla/components/SLAListItem.vue
=> chore: Update buttons in SLA page

app/javascript/dashboard/routes/dashboard/settings/canned/AddCanned.vue, app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue, app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
=> chore: Update buttons in canned response page

app/javascript/dashboard/components/widgets/BackButton.vue, app/javascript/dashboard/routes/dashboard/settings/components/BaseSettingsHeader.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/DashboardAppModal.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/DashboardAppsRow.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/Index.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Integration.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/IntegrationItem.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/MultipleIntegrationHooks.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/NewHook.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Shopify.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/Index.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookForm.vue, app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookRow.vue
**Integration main page**
**Back button Icon**
**Webhooks**
**Dashboard Apps**
**Dialogflow**
=> chore: Update buttons in integrations page

app/javascript/dashboard/routes/dashboard/settings/agentBots/Index.vue, app/javascript/dashboard/routes/dashboard/settings/agentBots/components/AgentBotRow.vue, app/javascript/dashboard/routes/dashboard/settings/agentBots/components/CSMLBotEditor.vue
=> chore: Update buttons in bots page

app/javascript/dashboard/components/widgets/FilterInput/Index.vue, app/javascript/dashboard/routes/dashboard/settings/automation/AddAutomationRule.vue, app/javascript/dashboard/routes/dashboard/settings/automation/AutomationRuleRow.vue, app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue, app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
=> chore: Update buttons in automation page

app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue, app/javascript/dashboard/routes/dashboard/settings/labels/EditLabel.vue, app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue
=> chore: Update buttons in labels page

app/javascript/dashboard/routes/dashboard/settings/agents/AddAgent.vue, app/javascript/dashboard/routes/dashboard/settings/agents/EditAgent.vue, app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
=> chore: Update buttons in agents page

app/javascript/dashboard/routes/dashboard/settings/teams/AgentSelector.vue, app/javascript/dashboard/routes/dashboard/settings/teams/FinishSetup.vue, app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue, app/javascript/dashboard/routes/dashboard/settings/teams/TeamForm.vue
=> chore: Update buttons in teams page

app/javascript/dashboard/modules/widget-preview/components/WidgetFooter.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/components/BusinessDay.vue
**Fixed outline issue with widget builder input**
=> chore: Update buttons in Inbox and its settings page

app/javascript/sdk/IFrameHelper.js, app/javascript/shared/components/CardButton.vue, app/views/widget_tests/index.html.erb
Fixes https://github.com/chatwoot/chatwoot/issues/5956
Fixes https://github.com/chatwoot/chatwoot/issues/1895
=> feat: implement widget card postback

app/javascript/dashboard/components-next/Contacts/ContactsForm/CreateNewContactDialog.vue
Fix duplicate save contact action being sent when we click on the button.
=> fix: Duplicate action being sent when we click on save contact

app/javascript/widget/views/Home.vue
This PR will fix theme mismatch with portal pages and widget.
https://www.loom.com/share/67392f0f0fb3493e99564cd12debd3fd?sid=cb85d05d-46aa-4550-ba36-20d373f6f507
=> fix: Theme inconsistency between portal page and widget

app/javascript/dashboard/components-next/button/Button.vue, app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue, app/javascript/dashboard/components/widgets/conversation/MessageSignatureMissingAlert.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/components/widgets/conversation/ReplyToMessage.vue, app/javascript/dashboard/components/widgets/conversation/components/SLAPopoverCard.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/LabelActions.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/TeamActions.vue, app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/UpdateActions.vue, app/javascript/dashboard/components/widgets/conversation/linear/CreateIssue.vue, app/javascript/dashboard/components/widgets/conversation/linear/IssueHeader.vue, app/javascript/dashboard/components/widgets/conversation/linear/LinkIssue.vue, app/javascript/dashboard/components/widgets/conversation/linear/index.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/ArticleSearchResultItem.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/ArticleView.vue, app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/Header.vue, app/javascript/shared/components/ui/dropdown/AddLabel.vue
* Update linear link pop over
* Update linear modal link and create
* Update conversation sidebar toggle button
* Update reply to message close button
* Update add label button
* Update SLA pop-over show more button
* Update bulk action dropdown actions
* Update buttons in Insert article modal
=> chore: Update buttons in conversation screens - 3

app/models/account.rb, app/models/channel/instagram.rb, db/migrate/20250326034635_add_instagram_channel.rb, db/schema.rb, spec/factories/channel/channel_instagram.rb, spec/models/channel/instagram_spec.rb
This PR is part of https://github.com/chatwoot/chatwoot/pull/11054 to make the review cycle easier.
=> feat: Added Instagram channel migration

app/helpers/billing_helper.rb, app/javascript/dashboard/App.vue, app/javascript/dashboard/i18n/locale/en/generalSettings.json, app/javascript/dashboard/routes/dashboard/Dashboard.vue, app/javascript/dashboard/routes/dashboard/upgrade/UpgradePage.vue, app/policies/account_policy.rb, enterprise/app/controllers/enterprise/api/v1/accounts_controller.rb, spec/enterprise/controllers/enterprise/api/v1/accounts_controller_spec.rb
This PR will replace the upgrade banner with an upgrade page view.
https://www.loom.com/share/0f2b4b09acdd4404bf3211184a470227?sid=7ed60a99-0299-4642-b907-2af8c4dcc643
=> feat: Upgrade page instead of banner

app/javascript/v3/views/auth/signup/components/Signup/Form.vue
This PR improves password validation in the signup form and ensures proper captcha handling during form submission. 
**Changes:**  
1. Display an error message if the password is invalid.  
2. Disable the account creation button when the password is invalid.
Fixes https://linear.app/chatwoot/issue/CW-4199/signup-issues
https://www.loom.com/share/d0ff04f12b98473e837b7f43af444f85?sid=04473cea-4717-4de8-b3fe-33ab0faed5e9
=> fix: Signup form validation issue with captcha handling

app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/shared/constants/links.js, app/javascript/shared/constants/messages.js
- Fixed the can reply window links.
- Added the supported file types for Instagram.
=> chore: Reply window fixes

app/controllers/api/v1/accounts/agents_controller.rb
Removing repetitive name parameter in AgentsController
=> fix: Removing repetitive name parameter in AgentsController

app/javascript/dashboard/components-next/Contacts/ContactsForm/CreateNewContactDialog.vue, app/javascript/dashboard/components-next/Contacts/ContactsHeader/components/ContactSortMenu.vue
This PR removes the ability to sort the contact list by `phone_number`
**Before**
**After**
=> chore: Remove sorting by `phone_number` from contact list

app/javascript/dashboard/components-next/message/chips/File.vue
This PR includes updating the PDF text color from Ruby to Slate for improved readability
**Before**
| Dark Mode | Light Mode |
| ------------- | ------------- |
| <img width="258" alt="image" src="https://github.com/user-attachments/assets/6124c69d-8bf1-47f3-9a06-eeb21dbedbb2" />  | <img width="258" alt="image" src="https://github.com/user-attachments/assets/d0f2b90b-6796-45ae-a02a-05c07246d25c" />  |
**After**
| Dark Mode | Light Mode |
| ------------- | ------------- |
| <img width="258" alt="image" src="https://github.com/user-attachments/assets/c0285062-83b6-49d5-bdb0-2aebf977cf74" />  | <img width="258" alt="image" src="https://github.com/user-attachments/assets/6b153d45-ee8d-42ac-a863-0fa8b294a21b" />  |
=> chore: Update PDF file text color from ruby to slate

app/javascript/dashboard/components-next/message/bubbles/Email/Index.vue
=> fix: email expand color

app/controllers/dashboard_controller.rb, app/javascript/dashboard/components/widgets/ChannelItem.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue, app/views/layouts/vueapp.html.erb, config/features.yml
=> chore: Enable Instagram inbox

app/javascript/shared/constants/messages.js
=> chore: Add the support for xml file in attachment

app/javascript/dashboard/routes/dashboard/settings/inbox/channels/instagram/DuplicateInboxBanner.vue
=> chore: Migrated Instagram inbox warning style issues

app/javascript/dashboard/components-next/message/MessageMeta.vue, app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue, app/javascript/dashboard/components/widgets/conversation/MessagesView.vue, app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue, app/javascript/dashboard/composables/useInbox.js, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/shared/constants/messages.js, app/javascript/shared/helpers/MessageTypeHelper.js, app/javascript/shared/mixins/inboxMixin.js
- Audited message characters across all channels.
- Replaced `isAInstagramChannel` with `isAnInstagramChannel`
=> chore: Audit message characters across all channels

app/javascript/dashboard/components/widgets/conversation/linear/Issue.vue, app/javascript/dashboard/components/widgets/conversation/linear/index.vue
This PR will fix the hover issue with Linear issue popup. And updated the colors of the issue popup.
Fixes https://linear.app/chatwoot/issue/CW-4272/linear-hover-issue
**Screen recording**
https://github.com/user-attachments/assets/07cde87a-c886-4b88-b826-de650c36e987
=> fix: Hover issue with Linear issue popup

app/javascript/dashboard/components-next/captain/assistant/MessageList.vue, app/javascript/dashboard/components-next/captain/pageComponents/assistant/EditAssistantForm.vue, app/javascript/dashboard/i18n/locale/en/integrations.json
- Increase the Captain instruction size to 20k instead of 2k
- Fix a display issue in the Captain playground and i18n issue in Captain form.
=> fix: Update the character count for instructions

app/javascript/dashboard/components-next/selectmenu/SelectMenu.vue, app/javascript/dashboard/components/widgets/conversation/ConversationBasicFilter.vue
This PR updates the basic filter UI for conversations.
https://www.loom.com/share/df69a023a39c4dfca2c12b1ee42a0b2e?sid=977e802e-2865-46f1-ae8e-f89ab5eabc2a
=> feat: Update conversation basic filter

app/javascript/portal/components/TableOfContents.vue
=> chore: Make the table of contents in help center sticky

app/javascript/dashboard/components-next/captain/pageComponents/assistant/EditAssistantForm.vue, enterprise/app/models/captain/assistant.rb
Fixes https://linear.app/chatwoot/issue/CW-4366/actionviewtemplateerror-undefined-method-available-name-for-an
=> fix: Add available_name as method in captain_assistant

app/javascript/dashboard/components-next/Contacts/ContactsCard/ContactDeleteSection.vue, app/javascript/dashboard/components-next/Contacts/ContactsCard/ContactsCard.vue, app/javascript/dashboard/components-next/Contacts/ContactsForm/ConfirmContactDeleteDialog.vue, app/javascript/dashboard/components-next/button/Button.vue, app/javascript/dashboard/i18n/locale/en/contact.json
**This PR includes:**
1. Adds the ability to delete a contact from the contacts list accordion section.
2. Improves the expand/collapse transition for the accordion.
Fixes [CW-4375](https://linear.app/chatwoot/issue/CW-4375/allow-users-to-delete-a-contact-from-the-contacts-page)
https://www.loom.com/share/8c897d24737f40f6b8b29fef76ba18e2?sid=70910b9d-f3db-4d54-8bfc-820db680e537
=> feat: Delete a contact from the contacts page

enterprise/app/services/captain/tool_registry_service.rb, enterprise/app/services/captain/tools/base_service.rb, enterprise/app/services/captain/tools/copilot/get_article_service.rb, enterprise/app/services/captain/tools/copilot/get_contact_service.rb, enterprise/app/services/captain/tools/copilot/get_conversation_service.rb, enterprise/app/services/captain/tools/copilot/search_articles_service.rb, enterprise/app/services/captain/tools/copilot/search_contacts_service.rb, enterprise/app/services/captain/tools/copilot/search_conversations_service.rb, spec/enterprise/services/captain/tool_registry_service_spec.rb, spec/enterprise/services/captain/tools/copilot/get_article_service_spec.rb, spec/enterprise/services/captain/tools/copilot/get_contact_service_spec.rb, spec/enterprise/services/captain/tools/copilot/get_conversation_service_spec.rb, spec/enterprise/services/captain/tools/copilot/search_articles_service_spec.rb, spec/enterprise/services/captain/tools/copilot/search_contacts_service_spec.rb, spec/enterprise/services/captain/tools/copilot/search_conversations_service_spec.rb
- Added GetConversation, GetContact, GetArticle, SearchContacts, SearchArticles
- Update SearchConversations to handle the permissions properly.
=> feat: Add support for additional tools in Copilot

app/javascript/dashboard/components-next/copilot/CopilotAgentMessage.vue, app/javascript/dashboard/components-next/copilot/CopilotAssistantMessage.vue
Removes avatar from the components.
**Before:**
**After:**
=> chore: Update Copilot UI in favor of the new design

app/javascript/dashboard/components-next/captain/pageComponents/assistant/EditAssistantForm.vue, app/javascript/dashboard/i18n/locale/en/integrations.json, enterprise/app/controllers/api/v1/accounts/captain/assistants_controller.rb, enterprise/app/helpers/captain/chat_helper.rb
=> feat: Add support for the temperature field

app/javascript/portal/portalHelpers.js, package.json, pnpm-lock.yaml
This PR uses the ported `isSameHost` utility from the [`chatwoot/utils`](https://github.com/chatwoot/utils/pull/52).
Originally introduced by **PR**: [chatwoot/chatwoot#11609](https://github.com/chatwoot/chatwoot/pull/11609)
=> chore: Move URL comparison logic to utils

app/javascript/dashboard/assets/scss/widgets/_base.scss, app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue, app/javascript/v3/components/Form/Select.vue
This PR fixes styles issues with the select in profile settings and toggles the Hotkeys button.
**Select**
| Before  | After (Dark Mode) | After (Light Mode) |
| ------------- | ------------- | ------------- |
| <img width="162" alt="image" src="https://github.com/user-attachments/assets/6d4ebd45-d233-413e-aca8-7f4db5d6c8a2" /> <img width="699" alt="image" src="https://github.com/user-attachments/assets/62c2ca85-479f-4252-a4fc-ffd5a570cff0" /> | <img width="162" alt="image" src="https://github.com/user-attachments/assets/7c9780ea-8ab6-429e-82e3-6fb554141bc0" /> <img width="699" alt="image" src="https://github.com/user-attachments/assets/726d7a0a-bfbc-4bdc-aedc-a874146230d8" /> | <img width="162" alt="image" src="https://github.com/user-attachments/assets/f3022b5f-6ae2-48d6-a2c9-9961f4295b8 …
=> fix: Profile settings style issue

.devcontainer/Dockerfile.base, .devcontainer/devcontainer.json, .devcontainer/scripts/setup.sh, Makefile, config/environments/development.rb
- Remove the deprecated extensions
- Install claude code in base image 
- Fix rails deprecation warning
=> chore: Improvements to codespaces

app/javascript/dashboard/components/widgets/UserAvatarWithName.vue, app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue
This PR fixes an issue with text truncation and styling in the CSAT reports table.
**Before**
**After**
=> fix: Style issue with CSAT reports table

Makefile, Procfile.tunnel, config/initializers/rack_profiler.rb
- move to vite build instead of dev for codespaces
- disable miniprofiler
=> chore: Improvements for codespace

app/javascript/dashboard/components-next/copilot/CopilotLauncher.vue
This PR will hide Copilot launcher button on inbox view message screen.
**Before**
**After**
=> fix: Hide Copilot launcher on inbox view message screen

config/locales/en.yml, enterprise/app/controllers/api/v1/accounts/captain/copilot_threads_controller.rb, spec/enterprise/controllers/api/v1/accounts/captain/copilot_threads_controller_spec.rb
Disable copilot if the response usage is over.
=> chore: Disable copilot usage after the response count is over

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
=> fix: Unread badge style issue

app/javascript/dashboard/composables/useWhatsappReauthorization.js, app/javascript/dashboard/i18n/locale/en/inboxMgmt.json, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/channels/whatsapp/Reauthorize.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
=> feat: whatsapp es reauth flow fe

app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
This PR updates the inbox list on the settings page to be sorted alphabetically.
=> chore: Alphabetically sort inbox list on settings page

app/javascript/dashboard/components-next/captain/assistant/ResponseCard.vue, app/javascript/dashboard/routes/dashboard/captain/responses/Index.vue
This PR fixes an issue where approved FAQs were not removed from the list when filtered by `pending` status.
**Fix:** Implemented real-time client-side filtering using a `filteredResponses` computed property in `Index.vue`, updated all list and selection logic to use it, and also hide the card toggle dropdown button when the bulk action checkbox is selected.
https://www.loom.com/share/216221a4910c44ebb1d49ab9e34c820c?sid=98c9c239-54eb-4bd9-b04d-aeccc55bfb3a
=> fix: Approved FAQ not disappearing from pending list after filtering

app/javascript/dashboard/components-next/breadcrumb/Breadcrumb.vue, app/javascript/dashboard/components-next/captain/SettingsPageLayout.vue, app/javascript/dashboard/components-next/captain/pageComponents/assistant/settings/AssistantBasicSettingsForm.vue, app/javascript/dashboard/components-next/captain/pageComponents/assistant/settings/AssistantControlItems.vue, app/javascript/dashboard/components-next/captain/pageComponents/assistant/settings/AssistantSystemSettingsForm.vue, app/javascript/dashboard/featureFlags.js, app/javascript/dashboard/i18n/locale/en/integrations.json, app/javascript/dashboard/routes/dashboard/captain/assistants/Edit.vue, app/javascript/dashboard/routes/dashboard/captain/assistants/settings/Settings.vue, app/javascript/dashboard/routes/dashboard/captain/captain.routes.js, config/features.yml
Fixes https://linear.app/chatwoot/issue/CW-4602/assistants-edit-page
=> feat: New Assistants Edit Page

app/javascript/dashboard/components-next/Inbox/InboxCard.vue, app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue, app/javascript/dashboard/routes/dashboard/inbox/InboxView.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxItemHeader.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxListHeader.vue, app/javascript/dashboard/routes/dashboard/inbox/routes.js
This PR includes improvements to Inbox view:
1. **Update the route to `:type/:id`**
Previously, we used `notification_id` in the route. This has now been changed to use a more generic structure like `conversation/:id`, with `type` set to `"conversation"`. This refactor allows future support for other types like `contact`, making the route structure more flexible.
It also fixes a critical issue: when a notification is open and a new notification arrives for the same conversation, the conversation view used to close unexpectedly. This issue is now resolved.
2. **Migrate components from Options API to Composition API**
Both `InboxList.vue` and `InboxView.vue` have been updated to use the Composition API with `<script setup>`. 
3. **Auto-scroll inbox item into view when navigating**
When …
=> chore: Inbox view improvements

app/javascript/dashboard/components-next/Inbox/InboxCard.vue, app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue, app/javascript/dashboard/routes/dashboard/inbox/components/InboxContextMenu.vue
This PR updates the inbox view context menu to use the existing conversation card context menu for consistency.
**Before**
**After**
=> chore: Update inbox view context menu

app/services/whatsapp/incoming_message_base_service.rb, spec/services/whatsapp/incoming_message_service_spec.rb
Fixes https://github.com/chatwoot/chatwoot/issues/11999
=> fix: Populate meta field for whatsApp shared contacts

app/controllers/api/v1/accounts/portals_controller.rb, app/javascript/dashboard/components-next/HelpCenter/Pages/PortalSettingsPage/PortalBaseSettings.vue, app/javascript/dashboard/i18n/locale/en/helpCenter.json
This PR includes:
1. Previously, the URL fields accepted any value starting with `https`. Added proper URL validation to ensure valid URLs are entered.
2. Fixed an issue where form save errors displayed `[object Object]` in the toast due to inconsistent error formatting from the backend.
Fixes https://linear.app/chatwoot/issue/CW-5389/help-center-bugs
https://www.loom.com/share/63ddca2c5e2e45c99b66153ed146524f?sid=fd25331b-6b67-4722-9b36-1213496a0741
=> chore: Improve portal settings validation and error handling

app/javascript/dashboard/App.vue, app/javascript/dashboard/components-next/NewConversation/components/ActionButtons.vue, app/javascript/dashboard/components-next/NewConversation/components/AttachmentPreviews.vue, app/javascript/dashboard/components-next/NewConversation/components/InboxSelector.vue, app/javascript/dashboard/components-next/NewConversation/components/WhatsAppOptions.vue, app/javascript/dashboard/components-next/NewConversation/components/WhatsappTemplateParser.vue, app/javascript/dashboard/components-next/avatar/Avatar.vue, app/javascript/dashboard/components-next/captain/pageComponents/assistant/EditAssistantForm.vue, app/javascript/dashboard/components-next/captain/pageComponents/assistant/settings/AssistantBasicSettingsForm.vue, app/javascript/dashboard/components-next/sidebar/SidebarGroup.vue, app/javascript/dashboard/components-next/taginput/TagInput.vue
This PR fixes RTL alignment issues in the new conversation form, removes the unused [`form-checkbox`](https://github.com/chatwoot/chatwoot/pull/12151#discussion_r2266333315) class name and drops the `app-rtl--wrapper` class, which was previously used for RTL detection in `rtl.scss` (removed earlier)
Fixes https://linear.app/chatwoot/issue/CW-5410/rtl-issues
=> fix: RTL issues in new conversation form

app/javascript/dashboard/components-next/Contacts/ContactsDetailsLayout.vue, app/javascript/dashboard/components-next/Contacts/ContactsHeader/ContactHeader.vue, app/javascript/dashboard/components-next/Contacts/ContactsHeader/ContactListHeaderWrapper.vue, app/javascript/dashboard/components-next/Contacts/ContactsHeader/components/ContactSortMenu.vue, app/javascript/dashboard/components-next/Contacts/ContactsListLayout.vue, app/javascript/dashboard/components-next/Conversation/ConversationCard/CardMessagePreview.vue, app/javascript/dashboard/components-next/Conversation/ConversationCard/CardMessagePreviewWithMeta.vue, app/javascript/dashboard/components-next/breadcrumb/Breadcrumb.vue, app/javascript/dashboard/components-next/filter/ConditionRow.vue, app/javascript/dashboard/components-next/filter/ContactsFilter.vue
This PR optimizes the contact list and details pages for smaller screens.
https://github.com/user-attachments/assets/e2edc19a-dffc-4e13-b1dd-782ebbac4dd0
https://github.com/user-attachments/assets/d2ea1ab8-c65b-46ea-a1e0-054a8afdabab
=> chore: Optimize contact page for smaller displays
