chatwoot/chatwoot

- app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
- app/models/conversation.rb
- app/views/api/v1/conversations/partials/_conversation.json.jbuilder
The "unread count" feature provides the exact number of unread messages in a conversation at any given moment. However, we do not currently display this count on the dashboard. Instead, the conversation list displays "9+" for any number greater than 9 of unread messages.
If there are many unread messages, the query can become heavy. The additional computation doesn't add much value, so it may not be necessary. 
This PR limits the query to take only last 10 unread messages.
Fix https://linear.app/chatwoot/issue/CW-2384/dashboard-should-load-even-if-there-are-thousands-of-unread-messages
> fix: Limit count query to return only 10 values

- app/models/conversation.rb
- app/views/api/v1/conversations/partials/_conversation.json.jbuilder
This PR is a hacky fix to include account_id in the queries. This PR would reduce the query timing if there are quite a lot of messages in the database.
> fix: Force account_id in message filters

- app/views/api/v1/conversations/partials/_conversation.json.jbuilder
Force account_id scope to conversation.message to include account id in queries.
> chore: Add account_id scope for conversation.messages

- app/presenters/mail_presenter.rb
- app/views/api/v1/conversations/partials/_conversation.json.jbuilder
- enterprise/app/services/enterprise/message_templates/response_bot_service.rb
- spec/fixtures/files/multiple_in_reply_to.eml
- spec/presenters/mail_presenter_spec.rb
- Return the first message id for now to avoid the errors and subsequently missing the message.
- Use .last instead of .first to avoid expensive query.
- Fix array response in response bot.
Fixes https://linear.app/chatwoot/issue/CW-2358/activerecordstatementinvalid-pgdatatypemismatch-error-argument-of-and
> fix: Consider the emails where in-reply-to header has multiple values

- app/javascript/dashboard/routes/dashboard/settings/teams/AgentSelector.vue
- app/javascript/dashboard/routes/dashboard/settings/teams/Create/AddAgents.vue
Fixes https://linear.app/chatwoot/issue/CW-2399/agent-name-not-visible-in-team-page
Steps:
1. Create a new team.
2. And you can see the agent section as the next step.
**Screenshot**
> fix: Agent name not visible in team page

- app/services/twilio/webhook_setup_service.rb
- spec/services/twilio/webhook_setup_service_spec.rb
This update will mean that errors will roll back the current transaction and the error will be sent back to the frontend and the user will know that the Inbox did not finish setting up successfully. We already do this if the credentials are invalid (when `authenticate_twilio` fails in `TwilioChannelsController`).
The current code seems a bit unexpected to me.  When `Twilio::WebhookSetupService.new(...).perform` fails it doesn't return or raise anything that indicates it failed, besides having sent a message to the logs.
Is there a common use case here where failure is expected?  Is there a way to tell when failure is expected and only squelch the error in that case?
> feat: Allow Twilio::REST::TwilioError errors to raise and prevent Inbox creation

- app/models/agent_bot.rb
- spec/models/agent_bot_spec.rb
The agent bot which has sent a message was not deleted due to `ActiveRecord::DeleteRestrictionError:  Cannot delete record because of dependent messages`
This PR fixes the issue.
> fix: Delete agent bots without deleting the messages

- app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss
This fixes an issue where 'Go To' input was not correctly being over ridden with our custom styling.
This is because the VE table plugin has a higher selector than our current styling.
Fixes #7752 
By switching from light mode to dark mode noticing the 'Go To' input changing.
> fix: Fixed an issue where the 'Go To' table styling was not correctly being set

- app/javascript/dashboard/assets/scss/_foundation-custom.scss
- app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue
Before:
After:
Fixes #7757 
By creating an inbox and going to the Widget Builder page.
> fix: Improve the contrast for the code snippet on the Widget Builder page.

- app/javascript/dashboard/modules/widget-preview/components/WidgetHead.vue
This fixed an issue as described in the video below:
The problem occurs when the welcomeHeading and welcomeTagLine is not always a string.
[Chatwoot - 17 August 2023 - Watch Video](https://www.loom.com/share/f364167f7c9346c79c6de1450ebee9b8)
Fixes #7755 
By observing the Welcome Headline input being in sync with the Widget.
> fix: Fixed an issue where the Widget Builder was not correctly being in sync with the Welcome Header input

- Gemfile.lock
- updating redis client caused deployment issues in Heroku, hence reverting to prev version until its resolved
> chore: Revert gem update

- app/mailboxes/imap/imap_mailbox.rb
- spec/mailboxes/imap/imap_mailbox_spec.rb
The issue with the in-reply-to header containing multiple values has been fixed. While the email standard allows for multiple in-reply-to values, our system previously did not support this feature. We've implemented a solution [here](https://github.com/chatwoot/chatwoot/pull/7715) that considers the first in-reply-to value as the preferred one.
Instead of relying on the original mail object, we have to utilize the processed mail objects in most cases. This change prevents potential issues (like the reported sentry error) arising from using the wrong in-reply-to value and ensures more accurate handling of email conversations.
This PR changes the usage of in_reply_to in imap_mailbox. As followup, I will check other places where the in-reply-to header is used.
> fix: Update the in_reply_to to logic to use processed_mail

- lib/integrations/slack/send_on_slack_service.rb
Some of the production app records don't have enough scope or have invalid credentials stored in their settings. This throws 
an InvalidAuth error in the Slack API call. 
This PR would rescue the error and mark the integration as inactive rather than throwing errors again.
As per the Slack documentation: 
> `invalid_auth`: Some aspects of authentication cannot be validated. Either the provided token is invalid, or the request originates from an IP address disallowed from making the request.
In both these cases, we do not need to keep sending the messages to Slack.
> fix: Rescue InvalidAuth and mark integration as inactive

- app/jobs/data_import_job.rb
- spec/fixtures/data_import/with_emoji.csv
- spec/jobs/data_import_job_spec.rb
The previous fix would remove emojis in contact data. This change ensures they are persisited 
ref: https://github.com/chatwoot/chatwoot/pull/7787
> chore: Persist emojis in Contact Import

- app/jobs/webhooks/facebook_events_job.rb
- app/jobs/webhooks/instagram_events_job.rb
- lib/redis/redis_keys.rb
This PR adds a mutex for `InstagramEventsJob`; the key used is the ID of the users Instagram Professional account.
> feat: mutex for `InstagramEventsJob` [CW-2447]

- app/models/concerns/slack_message_creation.rb
- config/integration/apps.yml
- lib/integrations/slack/incoming_message_builder.rb
Fixes https://linear.app/chatwoot/issue/CW-2366/files-sent-from-slack-doesnt-reach-the-customer
https://www.loom.com/share/a606c17136284ec68e51a059508615e7
> fix: Attachment sent from slack doesn't reach to chatwoot

- app/javascript/sdk/sdk.js
- app/javascript/widget/api/endPoints.js
- app/javascript/widget/mixins/darkModeMixin.js
- app/javascript/widget/store/modules/specs/conversation/getters.spec.js
- tailwind.config.js
**What this PR does**
This PR makes minor changes to utils, which we are already using to show articles in widget. 
> chore: Improvements to utils to load article in widget

- app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
- app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
This PR includes a hotfix: the editor menu is not visible in other editors except the message editor. For example, in campaigns, new conversation editor. etc
https://www.loom.com/share/8c89cf4d40974355b12e28096f152c6c?sid=7f099830-885c-4b18-9f2d-a7070927954b
> fix: Editor menu option is not showing

- app/javascript/dashboard/routes/dashboard/commands/conversationHotKeys.js
This pull request fixes the issue where the AI assist is showing in the command bar, even though the user has not added the AI integration.
> fix: Disable AI assist if the AI integration not enabled

- lib/integrations/slack/channel_builder.rb
Fixes https://linear.app/chatwoot/issue/CW-2488/exclude-archived-channels-from-the-slack-integration
> chore: Disable archived channels from the slack integration

- app/services/twilio/incoming_message_service.rb
- spec/services/twilio/incoming_message_service_spec.rb
We've had some messages come in from a few different phone numbers that had null bytes in them. I don't know how this happens. They don't seem to be malicious.
They currently cause the Postgres gem to raise an error when Chatwoot attempts to save the message body to the database:
> ArgumentError (string contains null byte)
Related Rails GitHub issue: https://github.com/rails/rails/issues/26891
> fix: Erase null bytes from incoming Twilio messages

- app/services/twilio/incoming_message_service.rb
- spec/services/twilio/incoming_message_service_spec.rb
This PR will add the fix for checking body exist or not before deleting the null bytes in Twilio payload.
Reference https://github.com/chatwoot/chatwoot/pull/7901
> fix: Check body exists before deleting null bytes in Twilio

- app/controllers/super_admin/instance_statuses_controller.rb
Pending migrations are often cause for issues in Chatwoot self-hosted installation. This feature should help to identify such issues easily
> chore: Migration status in super admin

- app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
This PR includes a fix for the editor add link modal header issue.
Fixes https://linear.app/chatwoot/issue/CW-2529/dark-mode-issues
|  Dark mode  |  Light mode  |
|---|---|
| <img width="229" alt="image" src="https://github.com/chatwoot/chatwoot/assets/64252451/a9980130-7c28-4dca-8afb-c92eeba5b231"> |  <img width="229" alt="image" src="https://github.com/chatwoot/chatwoot/assets/64252451/b5a94378-ffc2-4bd8-97fe-a3ef0dd69104"> |
> fix: Editor add link modal header dark mode issue

- app/javascript/dashboard/components/widgets/WootWriter/FullEditor.vue
- app/javascript/dashboard/helper/editorHelper.js
- app/javascript/dashboard/helper/specs/editorHelper.spec.js
- app/javascript/shared/components/ResizableTextArea.vue
- package.json
- yarn.lock
This PR fixes an issue where a signature would not be replaced properly in the editor.  The problem is that when a signature reached our editor, which looks like the following `- Jane Doe`, it is fed to the editor, which converts it to commonmark, which looks like the following `* Jane Doe` 
The problem arises when we try to look for the signature, since the output and input don't match, the program concludes that there is no signature in the body, and we simply append it again. On every mount this happens and here we have it, infinite signature glitch
> fix: handling markdown before replacing or appending signature [CW-2532]

- app/services/contacts/filter_service.rb
- app/services/conversations/filter_service.rb
- app/services/filter_service.rb
- spec/services/contacts/filter_service_spec.rb
DISTINCT query with custom attributes return an error. To avoid the error, this PR refactors the query to include tags only when it is required.
Fixes https://github.com/chatwoot/chatwoot/issues/7931
Fixes https://github.com/chatwoot/chatwoot/issues/7836
> fix: Avoid joining tables to fix the distinct value query

- app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
- app/javascript/dashboard/mixins/fileUploadMixin.js
- app/javascript/dashboard/mixins/specs/fileUploadMixin.spec.js
This PR will move the file upload methods like `onFileUpload`, `onDirectFileUpload` and `onIndirectFileUpload` to a new mixin file to reuse it in this PR https://github.com/chatwoot/chatwoot/pull/7913
> chore: Moved file upload methods to mixin

- app/javascript/v3/App.vue
Fixes https://linear.app/chatwoot/issue/CW-2487/default-locale=pt-br-in-the-environment-variables 
Fixes #7894 
--- 
To test:
- Set DEFAULT_LOCALE = pt_BR in .env file
- Restart the application and see if the login / signup / reset password / set new password pages have the locale changed.
> fix: Use installation locale if configured

- app/controllers/api/v1/accounts/contact_inboxes_controller.rb
- app/views/api/v1/accounts/contact_inboxes/filter.json.jbuilder
- config/routes.rb
- spec/controllers/api/v1/accounts/contact_inboxes_controller_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2578/search-by-facebook-id
> chore: Add an API to find the contacts using contact inbox sourceId

- app/listeners/base_listener.rb
- app/listeners/webhook_listener.rb
- app/models/inbox.rb
- app/models/webhook.rb
- app/presenters/inbox/event_data_presenter.rb
- lib/events/types.rb
- spec/listeners/webhook_listener_spec.rb
- spec/models/inbox_spec.rb
- Add webhook events for inbox creation / updation.
- Right now, the feature is added under a feature_flag. It is not available by default on all installations.
> feat: Add inbox webhook events

- app/javascript/dashboard/helper/editorHelper.js
- app/javascript/dashboard/helper/specs/editorHelper.spec.js
For the message schema we provide, `---` which is a horizontal rule element is not handled. This results in an error. This PR adds a exception catch to ensure that the signatures continues to work
To test, update the signature from the DB console to the following
```
---
Signature
```
Try using the editor after that, the dashes should be gone without error
> fix: Token type `hr` not supported by Markdown parser

- app/views/api/v1/models/_response_source.json.jbuilder
- config/initializers/monkey_patches/schema_dumper.rb
- enterprise/app/controllers/api/v1/accounts/response_sources_controller.rb
- enterprise/app/dashboards/response_dashboard.rb
- enterprise/app/dashboards/response_document_dashboard.rb
- enterprise/app/dashboards/response_source_dashboard.rb
- enterprise/app/jobs/response_builder_job.rb
- enterprise/app/models/enterprise/audit_log.rb
- enterprise/app/models/enterprise/concerns/inbox.rb
- enterprise/app/models/enterprise/inbox.rb
- enterprise/app/models/inbox_response_source.rb
- enterprise/app/models/response.rb
- enterprise/app/models/response_document.rb
- enterprise/app/models/response_source.rb
- enterprise/app/services/features/response_bot_service.rb
- lib/tasks/auto_annotate_models.rake
- spec/enterprise/controllers/api/v1/accounts/response_sources_controller_spec.rb
- spec/enterprise/controllers/enterprise/api/v1/accounts/inboxes_controller_spec.rb
This PR refactors the schema we introduced in #7518 based on the feedback from production tests. Here is the change log
- Decouple Inbox association to a new table `inbox_response_sources` -> this lets us share the same response source between multiple inboxes
- Add a status field to `responses`. This ensures that, by default, responses are created in pending status.  You can do quality assurance before making them active. In future, this status can be leveraged by the bot to auto-generate response questions  from conversations which require a handoff
- Add `response_source` association to `responses` and remove hard dependency from `response_documents`. this lets users write free-form question answers based on conversations, which doesn't necessarily need a response source.
- This is a …
> chore: Refactor Response Bot Data Schema

- package.json
- yarn.lock
This PR has two changes
1. Pin `videojs-record` to `4.5.0`
2. Add `jest-environment-jsdom` which has become and external dependency in jest 29
> fix: videojs-record version

- app/javascript/sdk/IFrameHelper.js
- app/javascript/widget/components/ChatFooter.vue
- app/javascript/widget/components/TeamAvailability.vue
- app/javascript/widget/constants/sdkEvents.js
- app/javascript/widget/helpers/actionCable.js
- app/views/widget_tests/index.html.erb
- This PR will add a new event `chatwoot:on-start-conversation` to the chat widget which you can listen to and trigger custom interactions on your end.
> feat: Add an option to listen to the start conversation click events

- app/jobs/data_import_job.rb
- app/models/data_import.rb
- spec/jobs/data_import_job_spec.rb
- spec/models/data_import_spec.rb
- We have observed some failures for data import jobs in the cloud due to race conditions with job executions and active storage file uploading. This PR adds delays and retries to accommodate that.
> chore: Add delay before running dataimport job

- app/services/contacts/filter_service.rb
- app/services/conversations/filter_service.rb
- spec/services/conversations/filter_service_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2628/activerecordstatementinvalid-when-applying-tag-queries
> fix: Update query to support multiple tag conditions

- app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue
- app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
Fixes https://linear.app/chatwoot/issue/CW-2639/dashboard-app-issues
The dashboard app IDs were generated incorrectly. The query getElementById returns the first object all the time, irrespective of the element from which it was queried which results in the missing postMessage calls.
> fix: Update duplicate ids for dashboard app frame

- app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
- app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
- app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
1. A fix for long names hide the resolve button.
2. Info icon shrink issue when the name is long in the contact sidebar.
3. Adjust the top spacing of the sidebar toggle button.
Fixes https://linear.app/chatwoot/issue/CW-2638/long-names-hide-the-resolve-button
**Large screen**
**Small screen**
> fix: Long names hide the resolve button

- app/services/twilio/delivery_status_service.rb
- spec/services/twilio/delivery_status_service_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2648/argumenterror-undelivered-is-not-a-valid-status-argumenterror
> fix: Change the message status to `failed` if the Twilio message delivery status is `undelivered`

- app/builders/v2/report_builder.rb
- spec/builders/v2/report_builder_spec.rb
- Handle invalid metric in reports_controller
Fixes https://linear.app/chatwoot/issue/CW-2643/typeerror-nil-is-not-a-symbol-nor-a-string-typeerror
- Added rspec cases to test the cases
> fix: cw-2643 handle invalid metric in ReportsController

- app/controllers/api/v1/accounts/conversations_controller.rb
- spec/controllers/api/v1/accounts/conversations_controller_spec.rb
- Handle empty status in `convesation_controller`
Fixes https://linear.app/chatwoot/issue/CW-2644/activerecordnotnullviolation-pgnotnullviolation-error-null-value-in
- Added new specs
> fix: cw2644 handle empty status in conversation controller

- app/javascript/portal/portalHelpers.js
- app/javascript/widget/views/Home.vue
Shows articles in the widget in dark or light mode according to the exiting widget setting. 
https://github.com/chatwoot/chatwoot/assets/1277421/106c5fa8-5d3f-4a98-b221-2e3136d4dfb4
> chore: Shows articles in dark mode for widget

- app/javascript/dashboard/api/auth.js
Fixes https://linear.app/chatwoot/issue/CW-2657/cannot-reset-password-from-the-dashboard
> fix: Add reset password for edit agent screen

- app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
- app/javascript/shared/mixins/inboxMixin.js
Facebook does not support `ReplyTo` via their API, so we have to disable that explicitly for them. This PR handles that
> refactor: UI flags for Reply To

- app/models/conversation.rb
- spec/models/conversation_spec.rb
- Ensure that conversations originating from campaigns are created in the open state.
> chore: Campaign conversations should be created in open state

- app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Fixes #6391. Even when we're on the `Private Note` tab, when switching conversations, we need to update the To/CC/BCC values of the component, otherwise the values of the previous conversation will persist when switching from `Private Note` to `Reply`.
Manually tested.
> fix: Always reset CC/BCC emails when switching conversations

- .env.example
Updated the `.env.example` file to provide clearer instructions for setting up the Postmark inbound webhook. Many users, including myself, found the initial instructions ambiguous, leading to difficulties during setup. This change aims to simplify the process for future users by providing clearer instructions and examples. 
Fixes #8234
The updated instructions were tested during my personal setup of Chatwoot with Postmark. However, please note that these are documentation changes and do not directly affect the software's functionality.
> docs: Update .env.example for clearer inbound Postmark instructions

- app/javascript/dashboard/components/ChatList.vue
- app/javascript/dashboard/components/widgets/conversation/ConversationBasicFilter.vue
This PR will save the last sort value to the UI setting and retain the previous selection after reloading.
Fixes https://linear.app/chatwoot/issue/CW-2662/sort-conversations-by-creation-date-for-fair-client-handling
**Loom video**
https://www.loom.com/share/932370d0a19e4f538fc2b8693f8d9b05?sid=f7f85fde-e81d-4d21-aa5e-fe4de9d91737
> feat: Save sort Conversations filter

- app/mailers/administrator_notifications/channel_notifications_mailer.rb
- app/models/concerns/reauthorizable.rb
- app/models/inbox.rb
- app/models/integrations/hook.rb
- app/views/mailers/administrator_notifications/channel_notifications_mailer/dialogflow_disconnect.liquid
- lib/integrations/dialogflow/processor_service.rb
- spec/lib/integrations/dialogflow/processor_service_spec.rb
- spec/mailers/administrator_notifications/channel_notifications_mailer_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2699/googlecloudpermissiondeniederror-7iam-permission
> fix: Handle PermissionDeniedError for Dialogflow processor

- app/services/twilio/send_on_twilio_service.rb
- spec/services/twilio/send_on_twilio_service_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2235/twiliorestresterror-[http-400]-21211-unable-to-create-record
> fix: Handle `Twilio::REST::RestError`

- app/javascript/shared/components/ResizableTextArea.vue
Fixes the issue with textarea shifting height when user types something in between last empty lines.
https://linear.app/chatwoot/issue/CW-2438/messenger-editor-break-on-chatwoot-cloud
> fix: Fixes textarea with empty lines changing height while typing [CW-2438]

- app/services/facebook/send_on_facebook_service.rb
- spec/services/facebook/send_on_facebook_service_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2708/facebookmessengerfacebookerror-2022-you-have-been-temporarily-blocked
> fix: Update the message status to `failed` if the outgoing Facebook message fails.

- app/controllers/api/v1/accounts/articles_controller.rb
When I select the category from the sidebar, the API returns more articles than the expected page size 25. Thereby breaking the pagination.
> fix: Fixes wrong page size in category filter in articles page 

- app/services/facebook/send_on_facebook_service.rb
- app/services/twilio/send_on_twilio_service.rb
- Remove sending exceptions to Sentry after capturing the message failed errors.
> chore: Remove sentry exceptions for the message status failed errors

- app/controllers/public/api/v1/portals/articles_controller.rb
- app/controllers/public/api/v1/portals/base_controller.rb
- app/controllers/public/api/v1/portals/categories_controller.rb
- app/views/public/api/v1/portals/error/404.html.erb
- config/locales/en.yml
- Refactors the repeated portal method definition 
- 404 page for wrong category and article links
https://linear.app/chatwoot/issue/CW-2727/create-404-page-for-public-portal
> feat: Creates 404 page for public portal [CW-2727]

- app/javascript/dashboard/i18n/locale/pt_BR/login.json
1 letter change in PT_BR translation.
Its seems like that translation are not present in https://chatwoot.crowdin.com/
From:
To:
> Chore(Translation): Label from "login" to "Login" in Login page

- lib/webhooks/trigger.rb
Fixes https://linear.app/chatwoot/issue/CW-2751/socketerror-failed-to-open-tcp-connection-to-new-baileyssuperwaio443
> fix: Handle all types of errors in API channel webhooks

- Gemfile
- Gemfile.lock
- `rails_panel` gem gives detailed query debugging for requests to the rails app
-  need to install the associated browser extension as well to see the details : https://github.com/dejan/rails_panel
> chore: Add rails_panel gem for query debugging

- app/models/account.rb
- db/migrate/20231114111614_change_feature_flags_to_bigint_in_accounts.rb
- db/schema.rb
Adding new feature flag breaks the puny 4bytes limit for the `integer` field, this PR converts it to a `bigint` instead.
> feat: convert `feature_flag` to `bigint` [CW-2767]

- enterprise/app/models/enterprise/message.rb
Consider a method as follows. 
```rb
def is_present?(value)
value ? true : false
end
```
```rb
is_present?('') # => returns true
is_present?(nil) # => returns false
```
We have to add `.present?` to avoid false positives. 
Fixes https://github.com/chatwoot/chatwoot/issues/8347
> fix: Add a .present? check for sentiment file path to avoid false positives

- app/javascript/dashboard/routes/dashboard/settings/profile/MessageSignature.vue
The signature field had a validation that it requires at least 1 character. This led to a bug which doesn't let the user to remove the signature completely. 
This validation is not required as the field can have empty or null values. 
Fixes https://linear.app/chatwoot/issue/CW-2799/cannot-remove-signature
> fix: Remove validation for message signature

- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
Updates the alignment for the rows in between to the right side.  
> fix: Updates the text alignment on articles table

- app/controllers/super_admin/devise/sessions_controller.rb
- Remove the cryptic error for super admin auth and make it more readable.
> chore: Make super admin auth error readable

- app/javascript/dashboard/components/widgets/forms/AvatarUploader.vue
While testing chatwoot I noticed that the avatar upload form did not allow all the image templates (such as webp) that are allowed in other parts of the application.
> feat: Allow more image formats in avatar uploads form

- app/controllers/api/v1/accounts/notifications_controller.rb
- config/routes.rb
- spec/controllers/api/v1/accounts/notifications_controller_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2776/add-api-to-delete-a-notification-object
> feat: Delete notification by id API

- app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
- app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
- app/javascript/shared/constants/messages.js
- app/services/line/send_on_line_service.rb
- spec/services/line/send_on_line_service_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2797/line-integration-line-app-do-not-receive-images
**Preview**
> feat: Add support for attachments(image and video) in LINE channel

- app/listeners/action_cable_listener.rb
- app/models/notification.rb
- lib/events/types.rb
- spec/listeners/action_cable_listener_spec.rb
- spec/models/notification_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2774/websocket-events-for-notification-update-and-destroy
https://github.com/chatwoot/chatwoot/assets/12408980/68343366-28f7-4d5e-808a-239be0cb7369
> feat: Add `notification_deleted` action cable event

- app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue
This PR will fix article meta tags that are not saving when we remove tags.
Fixes https://linear.app/chatwoot/issue/CW-2804/remove-article-meta-tag-is-not-working
**Loom video**
https://www.loom.com/share/ce1e22cbfd7d4bbcb0d8d94b4244e192?sid=ab65e9ac-97ff-466c-a3aa-e9652025559c
> fix: Remove article meta tag is not working

- app/drops/contact_drop.rb
- app/drops/conversation_drop.rb
- spec/drops/contact_drop_spec.rb
- spec/models/concerns/liquidable_shared.rb
Fixes https://linear.app/chatwoot/issue/CW-2881/backend-add-the-support-for-custom-attributes-in-liquid-templates
> feat: Add the support for custom attributes in message variables

- app/jobs/migration/remove_message_notifications.rb
Fixes https://linear.app/chatwoot/issue/CW-2883/change-the-removemessagenotifications-job-implementation
We use `destroy` to clear primary actor message notifications. However, this approach triggers `after_destroy_commit` every time, creating many unnecessary jobs in the queue, as we call `notification_deleted` on delete. This Pull Request will essentially replace `delete` with `destroy`.
> chore: Change the `RemoveMessageNotifications` job implementation.

- app/controllers/api/v1/accounts/conversations/assignments_controller.rb
- app/controllers/api/v1/accounts/conversations_controller.rb
- app/jobs/migration/conversation_cache_label_job.rb
- app/models/conversation.rb
- app/views/api/v1/accounts/conversations/messages/index.json.jbuilder
- app/views/api/v1/conversations/partials/_conversation.json.jbuilder
- db/migrate/20231211010807_add_cached_labels_list.rb
- db/schema.rb
- spec/models/concerns/assignment_handler_shared.rb
I began by #8525, which increases the conversation page size to 100. However, this can't be reliably sent to all self-hosted instances because the response time is higher than the 25 items. (It took 6 seconds on my machine). 
This PR could decrease one query in the conversation jbuilder. Currently, we fetch those during runtime, which increases the API response time. In this PR, 
- Add an attribute `cached_label_list` on the conversation table to store the cached list of labels. 
- Run a migration to touch all the conversations to generate the cache for the first time.
> feat(perf): Cache labels on the conversation model

- app/models/conversation.rb
- spec/models/conversation_spec.rb
The cache stores the labels as `label1, label2`. Without removing the whitespace, the output of cached_label_list_array would be [`label1`,  `[whitespace]label2`], which doesn't match with the existing labels. This list is returned with proper label names.
> fix: Update the label name to use .strip to avoid unnecessary whitespace characters

- app/javascript/dashboard/api/inbox/message.js
- app/javascript/dashboard/components/widgets/conversation/Message.vue
- app/javascript/dashboard/store/modules/conversations/actions.js
- app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
- app/javascript/shared/helpers/DateHelper.js
- app/javascript/shared/helpers/specs/DateHelper.spec.js
This PR will fix the retry message not working if the message is failed with an external issue. And disable the retry button if the message is older than one day.
Fixes https://linear.app/chatwoot/issue/CW-2675/retry-messages-broken
**Loom video, tested with Telegram bot**
https://www.loom.com/share/8cbfdaeff1244b6d8217664c2fd68717?sid=02a95ca3-1fcb-4a64-9052-dac063133288
**Test cases**
1. Should test with normal messages
2. Should test with image attachments
3. Should test with file attachments
> fix: Retry message not working if the conversation has an external issue

- app/jobs/migration/conversation_batch_cache_label_job.rb
- app/jobs/migration/conversation_cache_label_job.rb
- db/migrate/20231211010807_add_cached_labels_list.rb
- db/migrate/20231219000743_re_run_cache_label_job.rb
- db/schema.rb
A support request that came to Chatwoot Cloud revealed that the job was timed prematurely. The default timeout for Sidekiq queues was set as 25 minutes in sidekiq.yml file. The cache was not created properly for the accounts with more than 100k conversations.
This change removes the cache logic in the previous migration and creates a new migration with a new job which processes conversations in batch.
> chore(migration): Re-run database migration job for caching.

- app/models/notification.rb
- db/migrate/20231219073832_add_last_activity_at_to_notifications.rb
- db/schema.rb
This PR will introduce a `last_activity_at` date-time field to the Notification model for ordering notifications by their snooze time. This means if a notification is snoozed, the last_activity_at field will update, bringing the notification to the top.
> feat: Add `last_activity_at` field to Notification model

- app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
- app/javascript/shared/components/ResizableTextArea.vue
- package.json
- yarn.lock
This PR utilizes the typing status functionality from the utils. The `typing on` status is triggered only when typing begins, and the `typing off` status is activated after 4 seconds of inactivity or when the user stops typing and the input field loses focus (on input blur).
**Loom video**
Cases with the normal editor (includes widget also) and advanced editor
https://www.loom.com/share/c779e44aeb834826bb6d3f5257e98fdb?sid=07a54080-d068-4bbf-87de-2cc6d979208f
> feat: Use typing status from utils

- app/builders/messages/instagram/message_builder.rb
- app/models/message.rb
- spec/factories/instagram/instagram_message_create_event.rb
- spec/jobs/webhooks/instagram_events_job_spec.rb
This PR logs additional information in `content_attributes` of a message in case it is unsupported. This info can be used by the client to render a fresh UI
Unit tests
> feat: handle unsupported media on the backend

- app/models/message.rb
We observed an issue in production where the external webhook for an API inbox was failing. This, in turn, calls message update to update message status to `failed`. This causes a loop because rails trigger after_update callbacks even for empty commits.
Ref: https://github.com/rails/rails/issues/44500
> chore: Fix for empty update case for messages

- app/controllers/api/v1/accounts/conversations_controller.rb
- app/controllers/concerns/access_token_auth_helper.rb
- app/policies/inbox_policy.rb
- spec/controllers/api/v1/accounts/conversations_controller_spec.rb
This PR adds a feature to auto-trigger handoff events when an Agent bot toggles a conversation status from `Pending` to `Open`
Unit tests, covers enough cases
> feat: trigger handoff when agent bot is the actor

- enterprise/lib/chat_gpt.rb
We have been observing JSON parsing errors for responses from GPT.  Switching to the `gpt-4-1106-preview` model along with using `response_format` has significantly improved the responses from OpenAI, hence making the switch in code.
ref: https://openai.com/blog/new-models-and-developer-products-announced-at-devday
fixes: #CW-2931
> chore: Improve Openai json rendering

- lib/integrations/slack/send_on_slack_service.rb
Fixes https://linear.app/chatwoot/issue/CW-2930/slackwebapierrorsnotinchannel-not-in-channel
**Where and how much impact did it have?**
There have been 8 incidents reported in the sentry error.
The primary cause of this issue is when Chatwoot sends a message to a channel that has either been deleted or is unauthorized.
I was able to reproduce the issue by sending a message after deleting the connected Slack channel.
**Why is the change you made the right solution?**
The right solution is simply to ask for prompt_reauthorization. So next time when connecting to Slack, users will only see the valid channels. This time, it should work without any issues.
> chore: Rescue `Slack::Web::Api::Errors::NotInChannel` error

- enterprise/app/services/enterprise/billing/handle_stripe_event_service.rb
`plan` isn't a guaranteed object in stripe `customer.subscription.updated` events.  It can be null for cases like `send_invoice` for `past_due` event as seen in the payload shown in sentry error.
fixes: https://linear.app/chatwoot/issue/CW-2925/nomethoderror-undefined-method-[]-for-nilnilclass-nomethoderror
> chore: Handle stripe events without plan data

- app/javascript/packs/application.js
- app/javascript/packs/v3app.js
This ResizeObserver issue is happening on the dashboard's chat list screen, and we aren't using ResizeObserver there. After an investigation, the problem might come from the `vue-resize` package used in `vue-tooltip`. And we couldn't find any issue created on their repo. Right now, there doesn't seem to be a straightforward way to fix this issue. 
So, I tried to ignore the ResizeObserver error from the sentry.
```
ignoreErrors: [
'ResizeObserver loop limit exceeded',
'ResizeObserver loop completed with undelivered notifications',
],
```
Fixes https://linear.app/chatwoot/issue/CW-2924/error-resizeobserver-loop-completed-with-undelivered-notifications
> fix: Error ResizeObserver loop completed with undelivered notifications.

- app/mailboxes/support_mailbox.rb
- spec/fixtures/files/bounced_with_no_from.eml
- spec/mailboxes/support_mailbox_spec.rb
This case occurs for bounce notification emails where the from address is `From: "" (Mail Delivery System)` . We will be discarding these emails for now.
Fixes: https://linear.app/chatwoot/issue/CW-2793/activerecordrecordinvalid-validation-failed-email-invalid-email
> chore: Fix sentry errors in email processing for bounce notifications

- spec/lib/redis/config_spec.rb
- The sentinel configuration set in this specification seems to be affecting other specifications. So let's ensure that the memoised config variable gets unset after execution of the spec.
> chore: Unset Redis config after spec

- config/newrelic.yml
ENV.fetch coerces all values to strings, setting `NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=false` yields the string "false" which is interpreted as `true`
Tested locally
> fix: logic error when setting new relic logging forwarding

- app/listeners/action_cable_listener.rb
Fixes https://linear.app/chatwoot/issue/CW-2927/nomethoderror-undefined-method-notifications-meta-for-nilnilclass
**Where did it impact, how much did it impact?**
A total of 55 events have been reported in Sentry. This issue occurred after implementing the notification [deleted action cable event](https://github.com/chatwoot/chatwoot/pull/8431)
The main root cause of the issue is that when a user is deleted, all associated notifications are also deleted from the database. As a result, the user record becomes empty.
**Solution**
I have added a check whether the user is exist not nor before broadcasting the notification.deleted event.
> chore: Add a check to verify if the user exists before broadcasting the `notification_deleted` event.

- app/services/twilio/incoming_message_service.rb
- spec/services/twilio/incoming_message_service_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2911/downclienterror-400-bad-request-downclienterror
**Where did it impact, how much did it impact?**
In the previous release, we enabled "HTTP Basic Authentication" to ensure that all attachments requiring HTTP authentication are secured. This is particularly important for media files that may contain sensitive data, as recommended by Twilio. However, some users experienced issues because they did not enable this option, despite our alerts prompting them to do so. (There are 2.6K events in sentry).
**Solution**
If the authenticated attachment download call fails, add another call to download the attachment without authentication.
> fix: Twilo attachment download fallback to the step where authorization headers are not passed.

- app/jobs/send_on_slack_job.rb
- lib/redis/lock_manager.rb
We notice a lot of `MutexApplicationJob::LockAcquisitionError` especially for high velocity instances. This PR attempts to address that
- Reducing the default timeout to 1 second instead 2. Theoretically this should release the lock faster, given that the wait time in all cases is 1 second, having a lock timeout more than that does not make sense. Beside for us, the Mutex providing a 1 second delay is sufficient to handle concurrency issues
- Increase the attempt count for slack to 8, previously this has shown to improve delivery for FB and Insta
> feat: set lock timeout to 1 second

- app/services/twilio/incoming_message_service.rb
Fixes https://linear.app/chatwoot/issue/CW-2950/nameerror-undefined-local-variable-or-method-logger-for
> fix: Log twillio attachment error

- app/javascript/dashboard/helper/CacheHelper/DataManager.js
- app/javascript/dashboard/store/utils/api.js
The `window.indexedDB.databases()` function is not available in all browsers. It's a non-standard method that's currently only supported in Chrome and Opera. This method returns a promise that resolves to a list of all database names associated with the origin of the calling script.
On Firefox, we won't be able to use this method as it's not supported. Instead, we will need to keep track of your database names in another way. One common approach is to store the names of your databases in a separate IndexedDB database or LocalStorage. This PR implements exactly that!
> feat: fallback to DB localStorage for idb names

- app/services/twilio/incoming_message_service.rb
Fixes https://linear.app/chatwoot/issue/CW-2951/nomethoderror-undefined-method-original-filename-for-225integer
> fix: Handle error if the Twillio attachment download fails to download

- app/controllers/super_admin/app_configs_controller.rb
- app/views/super_admin/app_configs/show.html.erb
- config/installation_config.yml
- enterprise/app/controllers/enterprise/super_admin/app_configs_controller.rb
- lib/config_loader.rb
- lib/global_config.rb
- adds display manifest to white label settings
- Improve the app config rendering with options for display name and description
> chore: Add display manifest to whitelabel settings

- app/services/automation_rules/conditions_filter_service.rb
This PR adds a `rescue` block for the `perform` method. This ensures that any error is logged with more details about the failure.  
The function then returns false, this ensures that the automation rule is not triggered
> feat: log errors on automation filter

- app/actions/contact_identify_action.rb
- spec/actions/contact_identify_action_spec.rb
While debugging a sentry error for "ActiveRecord::InvalidForeignKey ActiveStorage::Representations::RedirectController", it was noticed that we enqueue a `Avatar::AvatarFromUrlJob` for each `setUser` call, which is unnecessary. Hence making this call only if the contact doesn't have an existing avatar. 
If one needs to have this avatar updated, they can go to the contacts tab and delete the current avatar, Chatwoot will pick up the new avatar in subsequent API call.
> fix: Stop overwritting contact avatars unneccesarily 

- app/javascript/dashboard/assets/scss/widgets/_modal.scss
- app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/SearchPopover.vue
- tailwind.config.js
This PR includes a fix to support backdrop color for insert the article modal in dark mode.
Fixes https://linear.app/chatwoot/issue/CW-2954/fix-backdrop-color-for-insert-article-modal-in-dark-mode
**Loom video**
https://www.loom.com/share/c2945162be644896b475488cc5bdb516?sid=c0fd30e1-0df4-4f8f-bc94-2a18ed51950e
**Screens to be tested for both dark and light mode**
1. Insert article modal
2. Drag and drop
3. All other modals
> fix: Backdrop color for insert article modal in dark mode

- app/models/channel/telegram.rb
- spec/models/channel/telegram_spec.rb
https://github.com/chatwoot/chatwoot/pull/8640 Introduced using `MarkdownV2` rendering for telegram Channel. But using this format caused breakages since this format requires escaping of a lot of special characters
> In all other places characters '_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!' must be escaped with the preceding character '\'.
ref: https://core.telegram.org/bots/api#markdownv2-style
Hence, switching to the `Markdown` format doesn't require as much complexity. We will evaluate `MarkdownV2` later in future. 
ref: https://core.telegram.org/bots/api#markdown-style 
the caveat is that `Markdown` only supports a limited set of blocks, like bold, italics and code
> chore: Switch to Markdown instead of MarkdownV2 for telegram channel

- app/controllers/api/v1/accounts/notifications_controller.rb
- app/javascript/dashboard/routes/dashboard/notifications/components/NotificationsView.vue
The notification count is incorrect when the number of notifications exceeds the page size.
> fix:  Notification count is incorrect when the number of notifications exceeds the page size.

- app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanelItem.vue
- app/javascript/dashboard/routes/dashboard/notifications/components/NotificationTable.vue
- app/views/api/v1/accounts/notifications/index.json.jbuilder
We have updated the way notifications are displayed by using the last active time instead of the create time. Therefore, showing the "created at" information in the UI no longer makes sense for the user. This PR will resolve the issue.
> feat: Show notification last active time instead of  created time

- app/jobs/inboxes/fetch_imap_emails_job.rb
- lib/redis/redis_keys.rb
The `Inboxes::FetchImapEmailsJob` is designed to fetch the entire email object and check if its message id is already in the database. However, this process is resource-intensive and time-consuming, as fetching the full email object takes a significant amount of time.
On average, fetching 100 emails can take approximately 3-4 minutes to complete depending on the IMAP server. Since we are not using server flags to identify which emails have already been fetched (to avoid compatibility issues with flags in different email services), we have to fetch all previously available emails. Currently we fetch all the messages that were created from yesterday. This becomes problematic with services like Gmail, which throttle requests based on bandwidth usage.
To address this issue, I have updated the …
> fix: Optimize email fetching logic to fix bandwidth exceeded issues

- app/jobs/inboxes/fetch_imap_emails_job.rb
Fixes https://linear.app/chatwoot/issue/CW-2978/nameerror-undefined-local-variable-or-method-inbox-for
> fix: Use channel.inbox instead of inbox

- app/builders/v2/report_builder.rb
- app/helpers/api/v2/accounts/reports_helper.rb
This PR removes redundant queries that are made when downloading reports.
The `generate_readable_report_metrics` method only returned three metrics, so there is no point in calculating the rest. This should significantly speed up report generation for downloads
```rb
def generate_readable_report_metrics(report_metric)
[
report_metric[:conversations_count],
time_to_minutes(report_metric[:avg_first_response_time]),
time_to_minutes(report_metric[:avg_resolution_time])
]
end
```
> feat: use `short_summary` for downloading reports [CW-2962]

- app/helpers/api/v1/inboxes_helper.rb
The Mail connection error can happen for a myriad of reasons. This PR removes the exception tracker and adds a more straightforward log instead.
> refactor: remove exception tracker

- app/controllers/concerns/access_token_auth_helper.rb
- spec/controllers/api/base_controller_spec.rb
- Fixes the issue in release 3.5.0 which causes `SuperAdmin` tokens throwing error during API calls 
fixes: #8719
> fix: API error when using SuperAdmin token

- app/jobs/mutex_application_job.rb
- spec/jobs/mutex_application_job_spec.rb
Consider a scenario where two jobs are concurrently accessing a job with a lock mechanism. If the second job accesses `lock_manager.locked?` before the first job called `lock_manager.lock(lock_key)`, it would return a false positive. At this point, both jobs can execute freely.
To address this issue, the following change ensures that only the current thread that has set the lock can execute, otherwise a LockAcquisitionError will be thrown.
> fix: raise_lock_acquisition_error if the job cannot set the lock

- app/actions/contact_merge_action.rb
- spec/actions/contact_merge_action_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2987/migrate-notes-of-the-secondary-contact-to-primary-contact-when-merging
As per [this discussion](https://discord.com/channels/647412545203994635/1197921664760041532/1197921664760041532), the contact notes were not migrated when the contacts were merged. This PR would fix this issue. 
- Added a new method merge_contact_notes and update the contact_id similar to messages and conversations. 
- Added a spec to cover the case.
I've tested this locally as well and it is working fine.
> fix: Migrate notes when merging the contacts

- app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
Fixes the typo in Inbox Management copy -> `vistors` to `visitors`
> chore: Fix typo in Inbox Management copy

- app/jobs/inboxes/fetch_imap_emails_job.rb
> This error typically occurs when you're trying to connect to an SMTP server using IMAP protocol, or there's a misconfiguration in the server settings you are trying to connect to.
While further investigating this error, we ignore it from the sentry since it unnecessarily exhausts the quota.
> fix: Handle Net::IMAP::InvalidResponseError Exception bad response type "ESMTP"

- spec/controllers/api/v1/accounts/contacts_controller_spec.rb
- The ordering was not guaranteed; hence, the specs were failing randomly. Made changes to the expectation accordingly
> chore: Fix flaky contacts spec

- app/models/notification.rb
Fixes https://linear.app/chatwoot/issue/CW-3010/rangeerror-invalid-time-value
**Where and how much impact did it have?**
There have been 500+ incidents reported in the sentry error.
In the previous release, we enabled `last_activity_at` in the notification item instead of `created_at` and made the necessary changes.
However, we missed to add `last_activity_at` to the action cable event (`notification_created`). As a result, in the front end, the `last_activity_at` will be empty, causing the `dynamicTime` function to be called without a value and resulting in a **RangeError**.
**Solution**
The right solution is simply add the `last_activity_at` to push event data.
> fix: Add `last_activity_at` to notification push event data

- app/services/whatsapp/incoming_message_base_service.rb
- app/services/whatsapp/incoming_message_service_helpers.rb
- spec/jobs/webhooks/whatsapp_events_job_spec.rb
- spec/services/whatsapp/incoming_message_service_spec.rb
Currently, we do not support reactions, ephemeral messages, or the request_welcome event for the WhatsApp channel. However, if this is the first event we receive in Chatwoot (i.e., there is no previous conversation or contact in Chatwoot), it will create a contact and a conversation without any messages. This confuses our customer, as it may appear that Chatwoot has missed some messages. There are multiple cases where this might be the first event we receive in Chatwoot. One quick example is when the user has sent an outbound campaign from another tool and their customers reacted to the message.
Another event like this is request_welcome event. WhatsApp has a concept for welcome messages. You can send an outbound message even though the user has not send a message. You can receive …
> fix: Avoid processing reactions, ephemeral, request_welcome or unsupported messages

- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
- app/views/public/api/v1/portals/articles/_article_header.html.erb
- app/views/public/api/v1/portals/categories/show.html.erb
Please refer to this PR https://github.com/chatwoot/chatwoot/pull/8756
This PR includes:
1. Removed the author section from the article header and the category article list block
2. Fix an overflow issue in the help center dashboard occurred from this PR https://github.com/chatwoot/chatwoot/pull/8756
**Category list article block**
**Article header**
> fix: Removed author section from public help center

- app/services/facebook/send_on_facebook_service.rb
- app/services/instagram/send_on_instagram_service.rb
- spec/services/facebook/send_on_facebook_service_spec.rb
- spec/services/instagram/send_on_instagram_service_spec.rb
> feat: allow multiple files for FB and Insta [CW-3019]

- app/mailboxes/reply_mailbox.rb
- app/models/concerns/account_cache_revalidator.rb
- app/models/concerns/cache_keys.rb
- spec/controllers/super_admin/accounts_controller_spec.rb
- spec/models/concerns/cache_keys_spec.rb
- spec/models/inbox_spec.rb
This PR tackles to problems with current implementation
1. In a rare case, the cache might show stale data, this means unless something changes for that model, or someone resets the cache keys manually, it will continue to show stale data
2. The value `0000000000` also is a valid key, this means when someone reset the cache from superadmin, it won't reset the cache for someone holding the cache key `0000000000`
3. Destroy event didn't update cache
This PR addresses this with the following changes
1. Set a default expiry of 72 hours for the cache keys, this can be changed to a higher number, this ensures that new data is fetched after every 3 days
2. When reseting the cache, we set the value to the latest timestamp, that way the conflict for the `zero` epoch is solved
3. Trigger …
> feat: expiry for cache keys [CW-3038]

- app/javascript/dashboard/routes/dashboard/inbox/components/InboxItemHeader.vue
- app/javascript/dashboard/routes/dashboard/inbox/components/PaginationButton.vue
This PR includes a dummy component of the inbox item header with the pagination button for a new inbox view.
I used the existing `woot-button` as the buttons for this component, so it will not look the same as the design. And replaces the Unwatch button with Snooze button.
**Components**
1. Pagination buttons component
2. Inbox item header component
Fixes -
https://linear.app/chatwoot/issue/CW-2973/ui-inbox-pagination
https://linear.app/chatwoot/issue/CW-2968/ui-inbox-header
**Screenshot**
> feat: Inbox item header component

- app/javascript/dashboard/routes/dashboard/settings/agents/AddAgent.vue
- app/models/user.rb
- enterprise/app/models/enterprise/concerns/user.rb
- spec/enterprise/models/user_spec.rb
- Add validations based on purchased pricing_plan_quantity
- modify dashboard to support the new error message
> chore: Validation for purchased pricing_plan_quantity

- app/javascript/dashboard/routes/dashboard/settings/inbox/ImapSettings.vue
- app/models/channel/email.rb
- db/migrate/20240131040316_remove_imap_inbox_syned_at_from_channel_email.rb
- db/schema.rb
- spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
imap_inbox_synced_at is no longer used, this PR removes all the references to the same.
> chore: Remove unused attribute imap_inbox_synced_at

- app/services/microsoft/refresh_oauth_token_service.rb
- spec/factories/channel/channel_email.rb
- spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
- spec/services/microsoft/refresh_oauth_token_service_spec.rb
- Added a trait called `microsoft_email` for the Channel::Email factory.
- Rewrote the logic to make it simple to understand
- Rewrote the specs for readability
> chore: Refactor RefreshOauthTokenService to improve readability

- app/jobs/channels/whatsapp/templates_sync_scheduler_job.rb
- spec/jobs/channels/whatsapp/templates_sync_scheduler_job_spec.rb
This PR introduces a modification to the channel fetching logic, ensuring that channels with older `message_template_last_updated` timestamps are prioritized during synchronization. 
Currently, our system is designed to handle a limit of 25 bulk API calls every 5 minutes. This results in a total of 300 API calls per hour. Over a span of 3 hours, we approach nearly 900 API calls. However, there's an observation that after 3 hours, we might be re-fetching the same channels repeatedly.
To address this, the PR implements an ordering mechanism for fetching channels. The channels are now ordered by `message_template_last_updated` with `NULL` values being given the highest priority, followed by the oldest update dates (ascending order). This ensures that channels which haven't been synced …
> fix: Template sync issue for older Whatsapp channels

- app/javascript/dashboard/i18n/locale/en/inbox.json
- app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue
- app/javascript/dashboard/routes/dashboard/inbox/components/InboxListHeader.vue
- app/javascript/dashboard/routes/dashboard/inbox/components/InboxOptionMenu.vue
- app/javascript/dashboard/routes/dashboard/inbox/components/MenuItem.vue
This PR includes a dummy component of the new inbox view's inbox list header options menu. 
Fixes https://linear.app/chatwoot/issue/CW-2966/ui-inbox-options
**Screenshot**
> feat: Inbox options dropdown menu

- app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
> fix: Fixes overlapping issue with local selector dropdown in portal header

- app/builders/agent_builder.rb
- app/controllers/api/v1/accounts/agents_controller.rb
- app/policies/user_policy.rb
- config/routes.rb
- spec/builders/agent_builder_spec.rb
- spec/controllers/api/v1/accounts/agents_controller_spec.rb
- spec/enterprise/controllers/api/v1/accounts/agents_controller_spec.rb
This PR allows creating bulk invites via email. A `POST` request to `/api/v1/accounts/{account.id}/agents/bulk_create` with `{ emails: ['test1@example.com', 'test2@example.com'] }` will allow creation of multiple invites. This will also validate the agents limits before creating any users
1. New `AgentBuilder` this creates the agent and associates it with the account in a single transaction.
2. Refactor `AgentsController` to use the new `AgentBuilder`
3. Add `bulk_create` endpoint to allow creation of multiple agents during onboarding
> feat: allow bulk invite create via email

- app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
- app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js
- app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue
- app/javascript/dashboard/routes/dashboard/inbox/components/InboxItemHeader.vue
We already have a route named "inbox" when clicking on "inbox" from the sidebar, which is conflicting with the new inbox view. For now, I have renamed it to "inbox-view" until we find a better route name.
> fix: Change the route from `inbox` to `inbox-view`

- .github/workflows/logging_percentage_check.yml
- .github/workflows/nightly_installer.yml
- .github/workflows/publish_codespace_image.yml
- .github/workflows/publish_foss_docker.yml
- .github/workflows/run_foss_spec.yml
- .github/workflows/run_response_bot_spec.yml
- .github/workflows/size-limit.yml
- Github helper actions depending on `node16` have been deprecated. Switch to the latest version of helper actions to use `node20`.
Fixes https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
- gh action tests
> chore: upgrade to latest versions of gh helper actions

- app/helpers/api/v2/accounts/heatmap_helper.rb
- app/views/api/v2/accounts/reports/conversation_traffic.erb
| -- | -- |
| <img width="555" alt="Screenshot 2024-02-09 at 12 28 26 AM" src="https://github.com/chatwoot/chatwoot/assets/2246121/18756988-d52c-4125-ada3-d02bd7063ec9"> | <img width="524" alt="Screenshot 2024-02-09 at 12 28 07 AM" src="https://github.com/chatwoot/chatwoot/assets/2246121/47f58df8-26e4-4dd9-a453-a8472456670a"> |
Fixes https://linear.app/chatwoot/issue/CW-3068/update-the-heatmap-time-display-format
> chore: Render timestamp in a better format in conversation traffic export

- app/javascript/v3/components/Form/Input.vue
The outline on inputs would not be visible when placed on a background color `slate-800`, this PR changes it to use a reduced opacity color of slate-200, this blends perfectly on signup and login page with different bg colors
> fix: outline color on login page

- app/controllers/api/v1/accounts/agents_controller.rb
- spec/controllers/api/v1/accounts/agents_controller_spec.rb
This PR adds a `rescue` block for the `perform` method, this is to ignore any errors if the AgentUser already exists. This behaviour only affects the bulk create API
> feat: handle already invited user

- app/helpers/api/v2/accounts/reports_helper.rb
- app/presenters/reports/time_format_presenter.rb
- app/views/api/v2/accounts/reports/agents.csv.erb
- app/views/api/v2/accounts/reports/conversation_traffic.erb
- app/views/api/v2/accounts/reports/inboxes.csv.erb
- app/views/api/v2/accounts/reports/labels.csv.erb
- app/views/api/v2/accounts/reports/teams.csv.erb
- config/locales/en.yml
- spec/presenters/reports/time_format_presenter_spec.rb
- Move the duration details to the top of the CSV export
- Format the time to `hours minutes` format for better readability
Fixes https://linear.app/chatwoot/issue/CW-2745/agentlabel-and-team-report
> feat: Improve the rendering of CSV exports

- app/javascript/v3/components/Form/WithLabel.vue
**Before**
**After**
The label was appearing twice on all with-label used forms. This would remove the default 
> fix: Removes default slot for right of label

- app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
This PR addresses an issue where the hyperlink popup in the editor is hidden under the modal component.
Fixes https://linear.app/chatwoot/issue/CW-3093/cant-hyperlink-text-on-new-conversation-started-from-contacts
**Loom video**
https://www.loom.com/share/4248e18112804df085a0c167d3fccedb?sid=cf1d2cb2-2958-42da-b8de-7b5de60e6913
> fix: Editor hyperlink popup is hidden under modal

- app/finders/conversation_finder.rb
- spec/finders/conversation_finder_spec.rb
- `updated_within' accepts value in seconds and returns all conversations updated in the given period with out pagination. This API will assist in our refetch logic on socket disconnect  
ref: https://github.com/chatwoot/chatwoot/issues/8888
> chore: Support for updated_within in ConverationFinder

- app/jobs/notification/reopen_snoozed_notifications_job.rb
- spec/jobs/notification/reopen_snoozed_notifications_job_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-3089/mark-notification-as-unread-after-the-unsnooze
> fix: Mark notification as unread after the un-snooze

- app/models/account.rb
- spec/models/account_spec.rb
- While debugging a prod issue, we notified that if someone enabled `custom_reply_email' or `custom_reply_email` email features and updated their account. The account's values for attributes `domain` and `support_email` will change to "" instead of nil, which causes issues with email sending. Hence adding appropriate fixes for the same.
> fix: `support_email` and `inbound_email_domain` returning empty string

- app/javascript/shared/mixins/specs/automationMixin.spec.js
- enterprise/app/jobs/sla/trigger_slas_for_accounts_job.rb
- spec/enterprise/jobs/sla/trigger_slas_for_accounts_job_spec.rb
- Schedule `ProcessAccountAppliedSlasJob` only for `accounts` that have one or more sla_policy created against it 
Fixes https://linear.app/chatwoot/issue/CW-3095/perf-schedule-account-sla-job-only-for-accounts-with-sla-policy
> feat(perf): sla-9 improve perf of TriggerSlasForAccountsJob

- .github/workflows/deploy_check.yml
- Add GitHub action to ensure every PR is successfully deployed
Changelog
---
- curl the deployment URL with `/api` endpoint
- check if it returns a json matching the expected structure
- Tests via gh action
> chore: add gh action to ensure deployment success for every PR

- .github/workflows/deploy_check.yml
- Refactor deployment check gh action to account for the initial setup time required for heroku review apps
- Process `/api`  response via `jq` only if `http.status_code` is 200
> chore: refactor deploy check gh action

- app/javascript/dashboard/routes/dashboard/settings/reports/ReportContainer.vue
- app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetrics.vue
- app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportMetricCard.stories.js
- app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportMetricCard.vue
- app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/ReportMetricCard.spec.js
We want to reuse the existing reporting components for our upcoming bot reports. Hence, making the required changes and cleaning up existing components.
- `ReportContainer.vue` to accept report keys via prompts ( We will be using different report keys in bot reports )
-  `CsatMetricCard` to `ReportMetricCard`  for generic use since we are using it also for the bot reports.
----
> chore: Component changes for bot reports

- app/javascript/dashboard/i18n/locale/en/report.json
- The count displayed is of reporting events, ie the number of responses. Instead we were showing the copy as conversations which would confuse users.
ref: https://discord.com/channels/647412545203994635/1207337933854613595/1211654122974089216
> fix: reply_time report tooltip

- app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
- app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
- app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
- app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
This PR includes some UI breakage fixes
1. Fixes overflow of contact details in the contact side panel.
2. Fixes line height issue in article header.
3. Fixes overflow of category names in the article list.
4. Fixes typing indicator alignment issues
**Contact sidepanel**
**Article editor header**
**Article list**
**Typing indicator**
> fix: UI breakages

- app/javascript/dashboard/assets/scss/widgets/_buttons.scss
This PR fixes the issue of the success button displaying the wrong color in dark mode when we hover it.
**Before**
https://github.com/chatwoot/chatwoot/assets/64252451/5342666d-2826-4029-973d-f3d8627c33b8
**After**
https://github.com/chatwoot/chatwoot/assets/64252451/357a4c3b-dd9d-43eb-86b8-f5658caf5068
> fix: Variant success button in dark mode

- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/ArticleSearchResultItem.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/Header.vue
This PR will fix the breakage issue that occurred in the insert article modal, which happened due to the removal of the foundation.
| -- | -- |
|  <img width="340" alt="Screenshot 2024-04-03 at 7 53 20 PM" src="https://github.com/chatwoot/chatwoot/assets/64252451/91e19ef7-7ce0-481d-8cb5-0c2ef0d28e3c"> | <img width="340" alt="Screenshot 2024-03-03 at 7 53 20 PM" src="https://github.com/chatwoot/chatwoot/assets/64252451/e61f809f-4617-471d-963e-e27faa1211d2"> |
> fix: Insert article modal UI breakage

- app/javascript/dashboard/components/widgets/EmptyState.vue
- app/javascript/dashboard/components/widgets/TableFooter.vue
- app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItem.vue
- app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue
- app/javascript/dashboard/i18n/locale/en/helpCenter.json
- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/DefaultPortalArticles.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
- app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
- app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue
- Validate the last active portal against the list of portals in the account before navigation to avoid blank pages when switching the accounts. 
- Navigate back to the categories page if the user select the article to edit from the category page (Check the existence of history, if present - use .go(-1)
- Update the styles of article list to make it look similar to the other pages in the product.
> fix: Update help center styles, fix routing issues

- swagger/definitions/request/conversation/create_message.yml
- swagger/swagger.json
It adds the **text** type of message which is missing on the documentation, here a code that uses the text type:
```ruby
def process_image_messages(message_payload, conversation)
message = conversation.messages.new(
{
message_type: :outgoing,
account_id: conversation.account_id,
inbox_id: conversation.inbox_id,
content: '',
content_type: 'text',
sender: agent_bot
}
)
prepare_attachment(message_payload, message, conversation.account_id)
message.save!
end
```
Documentation
Pretty much doc updates
> docs: added missing type text

- app/mailboxes/mailbox_helper.rb
- spec/mailboxes/mailbox_helper_spec.rb
When processing inline images, `MailboxHelper` would find the image that looks like `[image: image.png]` and replace it with an `<img>` tag, however this search candidate is not present when the email is sent from Apple mail app (verified) or Yahoo mail (Yet to be verified).
This PR updates the method to handle both cases, in case the search candidate is not present, we simply append the image at the end
> fix: inline attachments not handled if tag was missing

- app/models/notification.rb
- spec/models/notification_spec.rb
As per the latest update, we display message content for all notifications. But In conversation assignments, the last message is an activity message, which isn't useful for the user. This PR resolves this issue by selecting the last incoming message.
> fix: Conversation assignment notification title

- app/models/notification_subscription.rb
- db/migrate/20240306201954_change_identifier_type_in_notifications_subscriptions.rb
- db/schema.rb
Fixes https://linear.app/chatwoot/issue/CW-3118/cannot-subscribe-to-notifications-on-microsoft-edge
Fix the issue with notifications in Microsoft Edge. The identifier generated from the Edge push notification payload has more than 255 characters. The API calls were failing due to this. This PR would fix the issue.
> fix: Change the column identifier from string to text to avoid overflow

- app/javascript/dashboard/i18n/locale/en/generalSettings.json
- app/javascript/dashboard/i18n/locale/en/inbox.json
- app/models/notification.rb
- config/locales/en.yml
- enterprise/app/models/sla_policy.rb
- enterprise/app/services/sla/evaluate_applied_sla_service.rb
- spec/enterprise/services/sla/evaluate_applied_sla_service_spec.rb
- Add in-app notification when SLA target is missed for a conversation
- ~~The notification is send to all users part of the conversation inbox~~
- Notification is sent to all conversation participants, admins and assignee if present
Fixes https://linear.app/chatwoot/issue/CW-3098/in-app-notification-if-sla-is-missed
- Tested locally by creating a conversation and waiting for the SLA target to miss
- This created an in-app notification
> feat: add push notification when SLA missed

- app/models/contact.rb
- spec/models/contact_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-3014/update-the-location-and-country-code-when-the-contact-createdupdated
> feat: Update the `location` and `country_code` when creating or updating the contact

- app/javascript/dashboard/components/widgets/conversation/bubble/Location.vue
- app/services/telegram/incoming_message_service.rb
- spec/services/telegram/incoming_message_service_spec.rb
This PR will fix text overflow in the location message. And moved to composition API
Fixes https://linear.app/chatwoot/issue/CW-3123/location-message-text-is-not-wrapped
**Before** 
<image width="500" src="https://github.com/chatwoot/chatwoot/assets/64252451/f46ceb85-2b10-4f30-b308-8bfb3c70a7d7"><image/>
**After**
<image width="500" src="https://github.com/chatwoot/chatwoot/assets/64252451/ab333b8e-fbd9-451a-9275-8b6d6d2fa244"><image/>
> fix: Location message name overflows

- app/javascript/dashboard/routes/dashboard/settings/profile/ChangePassword.vue
This PR will fix showing an incorrect error response message when resetting the password.
Fixes https://linear.app/chatwoot/issue/CW-3105/incorrect-error-response-for-reset-password
**Loom video**
https://www.loom.com/share/7d32d34bd44f4a678a6f9ef2a64c5122?sid=c6d67478-65d7-441f-bc99-4967a9c76556
> fix: Incorrect error response for reset password

- app/models/contact.rb
- app/models/user.rb
I used the safe navigation operator to avoid a `NoMethodError`, bringing behavior of the `from_email` method in line with `find_by` and previous behavior of Chatwoot.
Fixes #9138
- [✅] Bug fix (non-breaking change which fixes an issue)
I've verified that the previous working behavior via Slack bot response no longer crashes and makes its way into Chatwoot.
- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my code
- [N/A] I have commented on my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings
- [❌] I have added tests that prove my fix is effective or that my feature works
- [✅] New and existing …
> fix: use safe nav when downcasing email in from_email

- app/javascript/dashboard/routes/dashboard/settings/SettingsLayout.vue
- app/javascript/dashboard/routes/dashboard/settings/components/BaseSettingsListItem.vue
- app/javascript/dashboard/routes/dashboard/settings/sla/Index.vue
- app/javascript/dashboard/routes/dashboard/settings/sla/components/SLAListItem.vue
- app/javascript/dashboard/routes/dashboard/settings/sla/components/SLAListItemLoading.vue
1. Handle loading state in the `SettingsLayout` with default loader and message spinner
2. Create loading state using `BaseSettingsListItem`
https://github.com/chatwoot/chatwoot/assets/18097732/bc29f2de-036e-47ba-82b1-c4019e7852b7
> feat: use better loading state

- app/models/conversation.rb
- db/migrate/20240322071629_convert_cached_label_list_to_text.rb
- db/schema.rb
We use `cached_label_list` column to hold the list of labels attached to a conversation, however the column type for it was `string` with a limit of 255 chars, this is not sufficient, since a conversation can have virtually unlimited labels. 
This caused the addition of any new labels to break once the char count reached 255. This PR fixes that by changing the column type to text
Fixes: https://github.com/chatwoot/chatwoot/issues/9094
Tested locally for up and down queries both
> feat: Convert `cached_label_list` to text

- app/controllers/application_controller.rb
- app/finders/conversation_finder.rb
- app/models/conversation.rb
- app/presenters/conversations/event_data_presenter.rb
- app/views/api/v1/conversations/partials/_conversation.json.jbuilder
- app/views/api/v1/models/_conversation.json.jbuilder
- enterprise/app/controllers/api/v1/accounts/enterprise_accounts_controller.rb
- enterprise/app/controllers/enterprise/concerns/application_controller_concern.rb
- enterprise/app/finders/enterprise/conversation_finder.rb
- enterprise/app/models/applied_sla.rb
- enterprise/app/models/enterprise/concerns/conversation.rb
- enterprise/app/models/sla_event.rb
- enterprise/app/presenters/enterprise/conversations/event_data_presenter.rb
- enterprise/app/views/api/v1/models/_applied_sla.json.jbuilder
- enterprise/app/views/enterprise/api/v1/conversations/partials/_conversation.json.jbuilder
- spec/enterprise/controllers/api/v1/accounts/conversations_controller_spec.rb
- spec/enterprise/models/applied_sla_spec.rb
- spec/enterprise/models/sla_event_spec.rb
- spec/enterprise/presenters/conversations/event_data_presenter_spec.rb
- spec/presenters/conversations/event_data_presenter_spec.rb
- Include applied_sla and sla_events in conversation api endpoints
- Include applied_sla and sla_events in conversation push_data
fixes: https://linear.app/chatwoot/issue/CW-3143/update-the-conversation-api-to-return-the-sla-policy-breached-sla
> feat: Conversation API to return applied_sla and sla_events

- app/controllers/api/v1/accounts/channels/twilio_channels_controller.rb
Fixes https://linear.app/chatwoot/issue/CW-2902/bug-twilio-incorrect-error-toast-message-during-inbox-creation
**Problem**
In Twilio channels, we set up the webhooks after creating the inbox. We manage this within a transaction block to handle any potential issues with the webhook setup.
```ruby
def create
ActiveRecord::Base.transaction do
authenticate_twilio
build_inbox
setup_webhooks if @twilio_channel.sms?
rescue StandardError => e
render_could_not_create_error(e.message)
end
end
```
The `rescue` block catches and deals with the error, so it doesn't affect the rest of the program. This means, even if there's an issue, the inbox is created successfully. At first, you might see an error in front end, but if you refresh the inbox list, you'll see the new inbox.
**Solution**
```ruby
def …
```
> chore: Fix twilio inbox create transaction rollback

- app/controllers/api/v1/accounts/agents_controller.rb
- app/views/api/v1/accounts/agents/create.json.jbuilder
- spec/controllers/api/v1/accounts/agents_controller_spec.rb
- We were using the `@user` object in the view, which wasn't available when using api_access_token.  
- Also replaced the object to `@agent` and added additional specs to confirm the right object
fixes: https://linear.app/chatwoot/issue/CW-3185/agent-create-api-throwing-500-response
ref: https://discord.com/channels/647412545203994635/1219928138163949568/1219928138163949568
> chore: Fix agent API returning 500 error

- app/services/imap/base_fetch_email_service.rb
- app/services/imap/fetch_email_service.rb
- app/services/imap/microsoft_fetch_email_service.rb
- spec/services/imap/fetch_email_service_spec.rb
- spec/services/imap/microsoft_fetch_email_service_spec.rb
Fixes https://github.com/chatwoot/chatwoot/issues/8968
The existing IMAP connections were not immediately terminated after the job completion. This delay could lead to some providers throttling connections, ultimately causing the "Connection reset by peer - SSL_connect" error.
In this PR, I've introduced an option to log out from the IMAP server. If we fail to logout properly, a forced disconnect will occur. 
The underlying method that was overridden was `perform`, it has been changed to `fetch_emails`. The `perform` method remains the same—it accepts no input and returns the same list of inbound email, while also terminating the connection.
The suggestion [here](https://github.com/chatwoot/chatwoot/issues/8968#issuecomment-1977618980) made sense, however I've used `logout` in place of …
> fix: Terminate IMAP connection after the job is complete

- config/initializers/rack_attack.rb
The rate limit of 5 on the contact search endpoint is too low. application. Allowing 100 to 200 shouldn't be a major issue, especially during high traffic times when search queries may increase.
> chore: Increase the rate limit for contact search

- app/javascript/dashboard/i18n/locale/en/contact.json
- app/javascript/dashboard/i18n/locale/en/conversation.json
- app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
- app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
- app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
This PR will fix the when clicking on contact attributes doesn't do anything if there is no contact attributes defined.
Fixes https://linear.app/chatwoot/issue/CW-3217/clicking-on-contact-attributes-doesnt-do-anything-if-there-is-no
**Conversation sidebar**
**Contact sidebar**
> fix: Clicking on contact attributes doesn't do anything if contact attributes list is empty

- app/javascript/dashboard/components/widgets/conversation/Message.vue
This PR will fix the two tooltip popover messages when message sending failed
Fixes https://linear.app/chatwoot/issue/CW-3223/double-warning-popovers-when-message-sending-failed
**Screenshot**
> fix: Double tooltip when message sending failed

- enterprise/app/controllers/enterprise/public/api/v1/portals/articles_controller.rb
- Enabling vector search was breaking the widget help center integration [ Helpcenter articles were not being displayed on welcome screen ]
> fix: Vector search breaking widget hc integration

- lib/custom_markdown_renderer.rb
- spec/lib/custom_markdown_renderer_spec.rb
Added support for embedding loom videos in help center articles.
**Preview**
> feat: Add loom video embed support for help center articles

- package.json
Setting the size limit for the widget bundle to be 300KB, this is the max we should let it allow to grow. Once exceeded we can explore options to reduce this
> fix: set size limit to 300KB

- app/javascript/dashboard/i18n/locale/en/sla.json
- app/javascript/dashboard/routes/dashboard/settings/sla/components/SLAPaywallEnterprise.vue
This PR adds the following changes
1. Remove the bug where upgrade button was rendered twice
2. Add a "cancel anytime" notice to the upgrade banner for cloud
> feat: update SLA upgrade banner

- app/listeners/action_cable_listener.rb
- spec/listeners/action_cable_listener_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-3251/nomethoderror-undefined-method-display-id-for-nilnilclass
> fix: Remove unnecessary attributes from notification deleted action cable event payload

- app/views/layouts/portal.html.erb
The portal was rendering the widget inside the widget, this is because the widget script was getting injected even when the portal was rendered in plain layout. This PR fixes that
Fixes: https://github.com/chatwoot/chatwoot/issues/9274
> feat: don't show widget on plain layout

- app/jobs/inboxes/fetch_imap_emails_job.rb
- app/services/imap/base_fetch_email_service.rb
- spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
- spec/services/imap/microsoft_fetch_email_service_spec.rb
At present, the IMAP sync fetches emails from the previous day. If a disconnection occurs, and users want to retrieve all emails from the date of disconnection, they need to modify their settings. The service does not currently support this. This PR aims to update the IMAP sync services by including an 'interval' parameter, which allows fetching emails from different intervals.
> feat: Add configurable interval for IMAP sync

- app/javascript/dashboard/components/ui/DatePicker/DatePicker.vue
This PR will fix a small edge case(only for the last 7(already handled) and 30(In this PR) days) in which the start calendar view is not moving correctly in **the last 30 days range if it is the same month. For e.g., April 1 - April 30 case**
**Before**
https://github.com/chatwoot/chatwoot/assets/64252451/c3a0539d-e638-441c-a975-306ac048f481
**After**
https://github.com/chatwoot/chatwoot/assets/64252451/b4290f1f-3e5e-406a-b2bd-51b6364d0dd9
> fix: Start calender is not moving properly is last 30 days range

- app/jobs/inboxes/fetch_imap_emails_job.rb
- spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
Temporarily disabling the disconnection logic due to the creation of numerous false positives, which in turn leads to many support requests. I will investigate the errors and reimplement the disconnection feature as a followup.
> chore: Temporarily disable the disconnect logic for inboxes

- app/jobs/inboxes/fetch_imap_emails_job.rb
- spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-2910/oauth2error-invalid-grant-aadsts50079-due-to-a-configuration-change
> chore: Rescue Oauth2::Error and mark the channel as inactive

- app/javascript/dashboard/routes/dashboard/settings/profile/MessageSignature.vue
The `messageSignature` props has a default value of `''` however this is only selected when the value passed is undefined, in a case where `null` is passed, it is consumed as it is.
This value further propagates to the `Editor.vue` component where it fails in `createState` method at `MessageMarkdownTransformer(messageSchema).parse(content)`
This PR fixes it
> fix: message signature default value

- app/mailboxes/imap/imap_mailbox.rb
- spec/mailboxes/imap/imap_mailbox_spec.rb
We have observed in Sentry that sometimes `fetch_imap_emails_jobs` fails with a validation error when creating a contact. This happens when the `original_sender` isn't in a format supported by the Chatwoot contact model schema. Chatwoot validates contacts email with `Device.email_regexp`.
This PR will skip processing such emails. It also adds a log for each email processed in the email fetch job and an error for the ones we skip. 
Fixes: https://linear.app/chatwoot/issue/CW-3295/activerecordrecordinvalid-validation-failed-email-invalid-email
> chore: Handle invalid email address in IMAP channel

- app.json
Fixes https://linear.app/chatwoot/issue/CW-3299/upgrade-heroku-postgres-dynos-from-basic-to-essential-0-plan
> We’re deprecating [mini and basic Heroku Postgres plans](https://devcenter.heroku.com/articles/heroku-postgres-plans#essential-tier) on the Essential-tier. The planned end-of-life date for mini and basic plans is May 22, 2024. If your [review apps](https://devcenter.heroku.com/articles/github-integration-review-apps#environments-in-app-json) and [CI apps](https://devcenter.heroku.com/articles/heroku-ci-in-dyno-databases) use mini or basic databases in the app.json, you must update them to the new Essential-tier plans before the EOL date. If not, no action is required as we’ll migrate these add-ons to the new [Essential-tier …
> feat: switch heroku postgres basic to essential-0

- app/listeners/participation_listener.rb
- app/models/concerns/assignment_handler.rb
- spec/listeners/participation_listener_spec.rb
- spec/models/conversation_spec.rb
We observed some race condition errors in the conversation participation listner while trying to create a conversation participation assignment.  This PR handles this error and also adds additional debug information for future
fixes: https://linear.app/chatwoot/issue/CW-3296/activerecordrecordnotunique-pguniqueviolation-error-duplicate-key
- handles `ActiveRecord::RecordNotUnique, ActiveRecord::RecordInvald` errors so that they won't polite sentry
- Adds a debug statement to log the cases
- Add `previous_changes` into the dispatcher so that we know the exact attribute changes  which trigger `assignee_changed, team_changed` events ( would be handy in future )
> chore: Handle conversation participation creation race condition error

- lib/tasks/ip_lookup.rake
Since we download the GeoIP database during worker/server initialization, there is a high chance of spamming the server with too many requests for downloads, especially if the number of web and worker nodes is high. This PR provides the ability to specify a custom URL for the GeoLite database download, configurable via an environment variable. This helps in distributing the load and avoiding server overload during the initialization process
> chore: Make IP_LOOKUP_BASE_URL configurable

- app/javascript/dashboard/routes/dashboard/settings/inbox/channels/360DialogWhatsapp.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/channels/CloudWhatsapp.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Telegram.vue
At the moment, when creating an inbox for Whatsapp, Telegram, etc., we show a generic error message saying that inbox creation failed. This PR will show the error messages directly from the API call, which is more helpful as it says if the error is due to the provided credentials.
> chore: Show valid error messages on Inbox creation

- app/models/contact.rb
- app/models/conversation.rb
- db/migrate/20240515201632_index_improvements_conversations_contacts.rb
- db/schema.rb
Based on our recent performant optimisation exercises, We have identified a better indexing strategy for conversations and contacts. The previous index on `last_activity_at` for conversations significantly slowed down conversation filters. Similarly, the new index on Contacts will allow the page rendering to improve for accounts with many contacts. 
fixes: https://linear.app/chatwoot/issue/CW-3300/db-improvements
> chore: Improved indexes for Conversations & Contacts [CW-3300]

- app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue
- app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
- app/javascript/shared/constants/messages.js
Use MP3 as the default format to send voice notes recorded from Chatwoot. This change was made to fix the issue of Telegram voice notes not working with the error `WEBPAGE_CURL_FAILED` .
Telegram treats the mp3 recordings as audio attachments. Once we can identify a fix for the original issue, we will revisit the `ogg` implementation.
> fix: Update the voice note format to MP3 to fix the delivery issues 

- app/javascript/dashboard/components/widgets/forms/PhoneInput.vue
This PR will fix this sentry [issue](https://chatwoot-p3.sentry.io/issues/5291039795/)
**Issue**
The root cause of this issue is the usage of `keyboardEventListenerMixins`. The key events are always active when the edit conversation modal is active, even if the country dropdown is not visible. So, if we press the enter key, this error will be thrown into the console.
**Solution**
Remove the use of `keyboardEventListenerMixins` and handle it directly in the Vue native key events. Also, always check if the dropdown is active.
**Other changes**
1. Remove the `mouseup` event lister and use the click away directive.
2. Use inline Tailwind css
Fixes https://linear.app/chatwoot/issue/CW-3282/phonenumberinput-country-undefined-in-onselectcountry
**Steps**
1. Open a conversation.
3. And click the …
> fix: Dashboard phone number input country `undefined` in `onSelectCountry`

- app/models/message.rb
- db/migrate/20240516003531_add_index_for_message_type_account_date.rb
- db/schema.rb
- Adding a new index on (account_id,created_at,message_type) based on our performance improvement exercise. This index significantly improves the page load speeds of messaging reports.
> chore: Add indexes to improve reporting performance

- lib/online_status_tracker.rb
- spec/lib/online_status_tracker_spec.rb
Previously, we returned the static value 'online' when the status was not present in the Redis cache. This PR changes it to fall back to the DB value and updates the cache in such cases.
fixes: https://linear.app/chatwoot/issue/CW-3233/write-a-back-up-for-online-status-in-case-if-redis-keys-are-not
> fix: Get online status from db when not present in cache [CW-3233]

- app/javascript/portal/application.scss
The fonts on the portal were not loaded properly before due to a typo in the stylesheet. The font that is shown on the public portal is ui-sans right now. This PR fixes it.
> fix: Fix typo in the font for portals

- app/javascript/dashboard/components/ui/Dropdown/DropdownSearch.vue
This PR will fix an issue with the new filter dropdown. When the dropdown is active, we can search it and add space, but it gets closed.
**Reason for the issue**
The filter dropdown is done with the slot mechanism, so it is added inside the button. The button is active when the dropdown and its input are active. Then we click the space key, and on the key up, the dropdown is toggled.
**Solution**
I used the Vue native event `@keyup.space.prevent` to prevent the space key-up event in the dropdown search wrapper.
**Screenrecording**
**Before**
https://github.com/chatwoot/chatwoot/assets/64252451/0c7b062a-bea1-48e5-b3af-1c5837876078
**After**
https://github.com/chatwoot/chatwoot/assets/64252451/121b8a11-7f79-4a26-ac61-42f5751cdfe4
> fix: Space key in input closing dropdown

- app/javascript/dashboard/mixins/uiSettings.js
Tried to replicate the issue, but Sentry didn't have enough information. `toggleMessageSignature` is a user triggered action in `ReplyBottomPanel.vue`, the value for `channelType` is provided from `inboxMixin`. The error will occur if either `inbox` is an empty object `{}` or `channel_type` in `inbox` object is undefined.
I couldn't find any instance where this could be the case. The PR has a stop gap solution that ensures that no action is triggered
> fix: Cannot read properties of undefined (reading 'toLowerCase')

- app/javascript/dashboard/components/CustomAttribute.vue
This PR will enable a back edit option for custom attributes if there is the value present, which is removed by this [PR](https://github.com/chatwoot/chatwoot/pull/9070/files#diff-fe9b82bbef1da31faa513332ed6015c0ed23765a6368832137a5408547da8938R172)
Fixes https://linear.app/chatwoot/issue/CW-3345/edit-attribute-does-not-work-anymore
**Screenrecordings**
**Before**
https://github.com/chatwoot/chatwoot/assets/64252451/ab89e087-d919-404d-90a9-17982b425dc3
**After**
https://github.com/chatwoot/chatwoot/assets/64252451/98d8b0b2-2f8f-46ec-ace5-b3e2a721623e
> fix: Enable edit option for custom attributes if value is present

- app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
**Cause of this issue**
I tried replicating the issue by toggling the feature flags from the super admin, but it didn't work. The error `TypeError: undefined, is not an object (evaluating 'this.features.inbound_emails')`. It's because `this.features` is undefined when `featureInboundEmailEnabled` is called. This can happen if `this.features` is not properly initialized before this method is accessed. The `features` are set on mounted. 
**Solution**
To resolve this issue, you should ensure that `this.features` is defined before any computations or methods that rely on it are executed. So, I added a check in the `featureInboundEmailEnabled` method to handle cases where `features` might be undefined.
Fixes https://linear.app/chatwoot/issue/CW-3341/typeerror-undefined-is-not-an-object-evaluati …
> fix: TypeError undefined is not an object `(evaluating 'this.features.inbound_emails')`

- app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
**Cause of this issue**
I tried to replicate the issue by deleting the agent from super admin, but it didn't work. The error `"TypeError: Cannot read properties of undefined (reading 'name')"` suggests that `agentInformation` is `undefined` when accessing the name property. This likely occurs because the `getAgentInformation` method does not find an agent matching the given `id`, and thus returns `undefined`. 
**Solution**
To resolve this issue, I modified the `getAgentInformation` method to handle cases where no agent is found. And added a fallback to the `agent.name` with `agent.available_name`. This change ensures that `agentInformation` will always be an object with its properties
Fixes https://linear.app/chatwoot/issue/CW-3325/typeerror-cannot-read-properties-of-undefined-reading-name …
> fix: TypeError cannot read properties of undefined (reading 'name')

- app/javascript/dashboard/components/layout/sidebarComponents/SecondaryChildNavItem.vue
- app/javascript/dashboard/helper/inbox.js
- app/javascript/dashboard/i18n/locale/en/settings.json
- app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/facebook/Reauthorize.vue
- app/javascript/shared/mixins/inboxMixin.js
- app/views/api/v1/models/_inbox.json.jbuilder
1. Use `reauthorization_required` as standard instead of inbox specific flags
1. Show alert on the sidebar along with a tooltip for Microsoft and Facebook both
1. Update  `facebook/Reauthorize.vue` component to use the banner UI instead of the form
1. Update alert icon layout on the sidebar to make it more prominent
> feat: add reauthorization banner for Facebook

- app/javascript/dashboard/components/NetworkNotification.vue
- app/javascript/dashboard/composables/emitter.js
- app/javascript/dashboard/composables/spec/emitter.spec.js
- package.json
- yarn.lock
This PR makes the following changes
1. Add `@vueuse/core` package, it supports Vue 2.7, we should start using this across the board
2. Add `useEmitter` composable, this adds a listener on the emitter on `onMounted` and automatically removes it on `onBeforeUnmount`
3. Use `useEmitter` & `useEventListener` from in `NetworkNotification.vue`
> feat: use composables that automatically cleanup listeners on the `onBeforeUnmount` hook

- app/javascript/dashboard/components/widgets/conversation/Message.vue
Show the context menu visible on hover
https://github.com/chatwoot/chatwoot/assets/15716057/4eb8656b-823d-4776-bcb6-bd372a0c1fc0
> feat: Make context meny visible only on hover

- app/javascript/packs/v3app.js
Vue 3 instance of the pages missed the emitter initialization, this PR fixes this issue
> fix: Missing mitt.js in vue 3 instance of app

- app/javascript/dashboard/routes/dashboard/suspended/Index.vue
This PR updates the implementation of chat bubble on suspended account.
> fix: Update the suspended page to show the chat bubble

- app/listeners/reporting_event_listener.rb
- spec/listeners/reporting_event_listener_spec.rb
`conversation.assignee_id` was taken into consideration for first response time calculation. There was one flaw in this approach. A lot of customer support agents respond to the conversation first before assigning it to themselves. This makes the analytics broken.
To fix this, we will take the message sender instead of assignee in calculations, which should solve the issue with metric.
Fixes https://linear.app/chatwoot/issue/CW-3375/first-response-reporting-events-use-assignee-id-instead-of-agent-who
> fix: Use message sender ID in the analytics for first response time

- app/jobs/inboxes/fetch_imap_emails_job.rb
- app/mailers/conversation_reply_mailer_helper.rb
- app/services/base_refresh_oauth_token_service.rb
- app/services/google/refresh_oauth_token_service.rb
- app/services/imap/google_fetch_email_service.rb
- app/services/microsoft/refresh_oauth_token_service.rb
- app/views/api/v1/models/_inbox.json.jbuilder
- spec/mailers/conversation_reply_mailer_spec.rb
- spec/models/channel/email_spec.rb
- spec/services/google/refresh_oauth_token_service_spec.rb
This PR adds the following changes
1. Add `Imap::GoogleFetchEmailService` and `Google::RefreshOauthTokenService`. The `Google::RefreshOauthTokenService` uses `OmniAuth::Strategies::GoogleOauth2` which is already added as a packge
2. Update `Inboxes::FetchImapEmailsJob` to handle Google inboxes
3. Add SMTP settings for Google in `ConversationReplyMailerHelper` to allow sending emails
> feat: add Google Email fetch and OAuth token refresh service

- app/javascript/dashboard/components/widgets/conversation/Message.vue
- config/initializers/rack_attack.rb
This is hacky fix for plain text email rendering. The issue happens only for the text/plain only emails. If there was an HTML component, then the rendering works fine.
**How was this tested?**
Mac Email client allows you to send text/plain emails. I've sent one to myself and imported it on Chatwoot. I've also verified that the email contains only text/plain part.
Sample rendered email below.
Fixes https://github.com/chatwoot/chatwoot/issues/9649
Fixes https://github.com/chatwoot/chatwoot/issues/9480
> fix: Temporarily fix text/plain email rendering

- app/services/notification/push_notification_service.rb
- spec/factories/notification_subscriptions.rb
- spec/services/notification/push_notification_service_spec.rb
Webpush gem throws errors such as `WebPush::ExpiredSubscription`, `WebPush::InvalidSubscription`, `WebPush::Unauthorized`. We handled only ExpiredSubscription. 
If the SDK threw any other errors, it would pause sending the notification to all other devices for that user.  This change would update the logic to remove the expired subscription and handle the rest of the errors gracefully.
Fixes https://linear.app/chatwoot/issue/CW-3399/webpushinvalidsubscription-host-fcmgoogleapiscom-nethttpnotfound-404
> fix: Add catch for additional webpush errors

- app/javascript/widget/components/AgentMessage.vue
This PR will allow viewing, playing, or downloading video messages in the agent side widget bubble.
Addresses https://linear.app/chatwoot/issue/CW-3384/video-message-display-issue
**Screenrecordings**
https://github.com/chatwoot/chatwoot/assets/64252451/11227bf6-cc93-469c-8db4-70e8e8852cb8
> feat: Adds video message viewing in agent widget bubble

- app/models/account_user.rb
- app/views/api/v1/models/_user.json.jbuilder
- spec/controllers/devise/session_controller_spec.rb
- spec/models/account_user_spec.rb
This API change sets the foundation for an upcoming frontend update, transitioning from a role-based model to a permission-based model. This new approach will determine eligibility for various actions and UI elements based on specific permissions rather than roles, enhancing flexibility and security in user access management.
> chore: Add permissions to auth data

- Gemfile.lock
The following error starting is shown on the console after the ruby upgrade.
csv.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of csv-safe-3.2.1 to add csv into its gemspec.
Csv-safe has already added a patch via https://github.com/zvory/csv-safe/pull/20. 
This PR updates the version to the latest version of csv-safe (3.3.1)
> chore: Upgrade csv-safe to the latest version

- app/javascript/dashboard/helper/ReconnectService.js
- app/javascript/dashboard/helper/specs/ReconnectService.spec.js
The disconnect threshold is added to account for delays in identifying disconnections (for example, the websocket disconnection takes up to 3 seconds) while fetching the latest updated conversations or messages.
In this case, the cable disconnection event takes about 3 seconds to fire. If there was a conversation which was created in this 3 second, it would not be displayed in the UI until the refresh.
> fix: Add a DISCONNECT_DELAY_THRESHOLD while fetching the conversations

- app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/EditWebHook.vue
**Issue**
The error `Cannot read properties of undefined (reading 'data')` occurs because the `error.response.data` is accessed without checking if `error.response` is present.
I can able to reproduce this issue.
**Solution**
To resolve this issue, I can add a check to ensure that this `error.response` is defined before accessing the `error.response.data`
Fixes https://linear.app/chatwoot/issue/CW-3406/typeerror-cannot-read-properties-of-undefined-reading-data
> fix: TypeError cannot read properties of undefined (reading 'data')

- app/javascript/dashboard/helper/AudioAlerts/DashboardAudioNotificationHelper.js
**Cases**
https://linear.app/chatwoot/issue/CW-3396/typeerror-cannot-read-properties-of-undefined-reading-dollarstore#comment-f018b29c
Fixes https://linear.app/chatwoot/issue/CW-3396/typeerror-cannot-read-properties-of-undefined-reading-dollarstore
> fix: TypeError cannot read properties of undefined (reading '$store')

- app/javascript/shared/components/emoji/EmojiInput.vue
**Issue**
The error `Cannot read property 'focus' of undefined`occurs because the `this.$refs.searchbar` is undefined at the time `focusSearchInput()` method is called. This can happen if the method is called before the component has fully mounted or if the `ref="searchbar"` is not correctly attached to any element. 
I tried multiple ways to reproduce this issue, but none worked.
**Solution**
To resolve this issue, I can add a check to ensure that `this.$refs.searchbar` is defined before calling `focus()` method.
Fixes https://linear.app/chatwoot/issue/CW-3405/typeerror-cannot-read-property-focus-of-undefined
> fix: TypeError cannot read property 'focus' of undefined

- app/javascript/dashboard/routes/dashboard/settings/agents/AddAgent.vue
**Issue**
The error `Cannot read properties of undefined (reading 'status')` occurs because the `error.response.status` is accessed without checking if `error.response` is present.
I can't able to reproduce this issue.
**Solution**
To resolve this issue, I added a check to ensure that this `error.response` is defined before accessing the `error.response.status`
Fixes https://linear.app/chatwoot/issue/CW-3322/typeerror-cannot-read-properties-of-undefined-reading-status
> fix: TypeError cannot read properties of undefined (reading 'status')

- docker-compose.production.yaml
- Add `restart:always` policy for rails and sidekiq containers in the production compose file
Fixes #9501
Fixes https://linear.app/chatwoot/issue/PR-1099/missing-restart-always-at-docker-compose-file
> fix: add restart policy for rails/sidekiq containers

- app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue
This PR will fix the layout issue in connecting to the Facebook page layout.
Fixes https://linear.app/chatwoot/issue/CW-3489/connect-facebook-page-layout-is-broken
**Before**
**After**
> fix: Broken connect to facebook page layout

- app/models/attachment.rb
- spec/models/attachment_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-3497/instagram-outgoing-attachments-are-not-rendering
It seems like Instagram outgoing attachment rendering has been broken for a long time. We couldn't identify the issue because the check below only inspects Instagram mentions.
```
metadata[:data_url] = metadata[:thumb_url] = external_url if message.instagram_story_mention?
```
We recently worked on adding the [Instagram CDN URL for attachments.](https://github.com/chatwoot/chatwoot/pull/9287) 
After that, it started using external URLs as attachment data URLs for both outgoing and incoming attachments. The rendering broken for all the outgoing attachments since there were no external URLs, making the data URL empty. Adding an incoming message check will solve the issue.
> fix: Instagram outgoing attachments

- app/controllers/api/v1/accounts/integrations/captain_controller.rb
- spec/controllers/api/v1/accounts/integrations/captain_controller_spec.rb
Use `InstallationConfig.where(name: 'CAPTAIN_APP_URL')` instead of `ENV.fetch('CAPTAIN_APP_URL', '')`
> chore: Use installation config URL for captain app URL

- app/javascript/dashboard/routes/dashboard/settings/integrations/SingleIntegrationHooks.vue
issue
I have made adjustments so that the integration logos can display correctly
before
after
> fix: Logos of integrations in dark mode in integrations

- app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
This PR updates the profile settings page to completely disable the password section, including the heading, if the admin has disabled user profile updates. Previously, the section heading was shown with empty content, which caused confusion.
| -- | -- |
| <img width="813" alt="Screenshot 2024-08-07 at 9 36 24 AM" src="https://github.com/user-attachments/assets/120efab0-0094-4141-b23c-5103596a187e"> | <img width="805" alt="Screenshot 2024-08-07 at 9 36 35 AM" src="https://github.com/user-attachments/assets/35e2c76b-e8f5-4c6f-a51e-7c30b882cd9c"> |
> fix: Disable the password section is the admin has disabled user profile update

- app/javascript/dashboard/i18n/locale/en/labelsMgmt.json
- app/javascript/dashboard/routes/dashboard/settings/SettingsLayout.vue
- app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue
- app/javascript/dashboard/routes/dashboard/settings/labels/labels.routes.js
This PR is part of the settings design update series. It updates the design for the label management page. I've made a few changes to the SettingsLayout page to reduce boilerplate code.
| Light | Dark |
| -- | -- |
| <img width="1437" alt="Screenshot 2024-08-12 at 8 33 31 AM" src="https://github.com/user-attachments/assets/7b8b7c21-1ce0-46a6-9fd4-13b36c1650f1"> | <img width="1435" alt="Screenshot 2024-08-12 at 8 33 43 AM" src="https://github.com/user-attachments/assets/5d51daa4-ae89-4f8f-aba0-5b7554bd9e35"> |
> feat: Update the design for label management page

- app/models/conversation.rb
- app/presenters/conversations/event_data_presenter.rb
- spec/models/conversation_spec.rb
The payload does not include last_activity_at when the conversation is created. Becuase of this the frontend is not able to sort the conversations when appending this. Another problem is that the last_activity_at is not always present, it is added only when a message is created, and it updates it. So this can be nil when the conversation is created, so we fallback to created_at only at the presentation layer
feat: add last_activity_at fallack on conv model directly
test: fix specs for conv push data
test: last_activity_at property in conv model
Please describe the tests that you …
> fix: last_activity_at is nil when conv is created

- app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue
**Issue**
This PR will fix an issue with the `CardLabels` component, which throws these type errors: `TypeError: Cannot read properties of undefined (reading 'id')` and `TypeError: n is undefined`. It seems that `label` in the `v-for` directive is `undefined` at some point, or it happens because `activelabels` becomes undefined, which can occur if the assigned label is deleted.
Previously, it would try to find a matching label in `accountLabels` for each label in `props.conversationLabels`. For the deleted label, it would return `undefined`.
**Solution**
Now, we filter `accountLabels` based on whether their title is included in the `props.conversationLabels` array.
Fixes 
1. https://chatwoot-p3.sentry.io/issues/5707611629/?project=4507182691975168&query=is%3Aunresolved+issue.priority%3A%5B …
> fix: TypeError cannot read properties of undefined (reading 'id')

- app/javascript/dashboard/helper/conversationHelper.js
This PR will fix the type error related to `getLastMessage` to retrieve the last message and display it in the conversation card.
**Issue**
This method is part of newer JavaScript versions and might not be supported in all browsers.
Fixes https://chatwoot-p3.sentry.io/issues/5708410274/?alert_rule_id=15157525&alert_timestamp=1723552508790&alert_type=email&environment=production&notification_uuid=be5966b2-f17d-4273-8709-98e3322f1f6f&project=4507182691975168&referrer=alert_email
> fix: TypeError: t.messages.at is not a function

- app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
This PR will fix an error `TypeError cannot read properties of undefined (reading '$el')` with the keyboard shortcut `Alt+KeyA` for triggering the file picker.
**Issue**
I couldn't able reproduce this issue. It might be because `$children` was unavailable at the time of access.
**Solution**
Previously, it relied on `$children`. Now, it uses the more reliable `querySelector` method to find the target element.
Fixes https://chatwoot-p3.sentry.io/issues/5708410274/?alert_rule_id=15157525&alert_timestamp=1723552508790&alert_type=email&environment=production&notification_uuid=be5966b2-f17d-4273-8709-98e3322f1f6f&project=4507182691975168&referrer=alert_email
**Test cases**
1. Open a conversation
2. And click `Alt+KeyA` to trigger the file picker.
3. See if there is any issue or errors.
> fix: TypeError cannot read properties of undefined (reading '$el')

- app/javascript/dashboard/components/layout/Sidebar.vue
- app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
- app/javascript/dashboard/components/policy.vue
- app/javascript/dashboard/helper/permissionsHelper.js
- app/javascript/dashboard/helper/routeHelpers.js
- app/javascript/dashboard/helper/specs/permissionsHelper.spec.js
- app/javascript/dashboard/helper/specs/routeHelpers.spec.js
- app/javascript/dashboard/routes/index.spec.js
- app/views/api/v1/models/_user.json.jbuilder
- spec/controllers/devise/session_controller_spec.rb
Remove the `user.permissions` field and resolve the permissions directly from the accounts array in the user. This change ensures that the cache or previous values from the last active account don't affect the permissions.
In this PR: 
- Remove user.permissions usage, replace it with getUserPermissions method.
- Remove json.permissions from user.json.jbuilder
> fix: Remove user.permissions, resolve it from accounts

- app/services/instagram/message_text.rb
- spec/jobs/webhooks/instagram_events_job_spec.rb
Fixes https://github.com/chatwoot/chatwoot/issues/9963
This PR will fix the issue of removing attachments in real-time when someone unsends media (images, videos, and audio) from Instagram.
> fix: Delete attachments when removing them from Instagram in real-time

- enterprise/lib/enterprise/integrations/openai_processor_service.rb
- lib/redis/redis_keys.rb
- spec/enterprise/lib/integrations/openai/processor_service_spec.rb
We updated OpenAI's response to accommodate error messages via https://github.com/chatwoot/chatwoot/pull/9560. We've added a new payload format. However, we're using cache for label suggestions, so the old payload format is always used for old conversations. This leads to label suggestions not being displayed. This PR fixes these issues.
> fix: OpenAPI label suggestion response payload

- app/javascript/dashboard/components/widgets/conversation/linear/index.vue
We are fetching linked Linear issues when opening a conversation if Linear integration is enabled. There may be some cases where the API call fails. We don't need to show an error message every time a user opens the conversation, as it's not critical. However, when someone clicks on the Linear icon, we can inform them that the integration is disabled. This PR will fix the issue
> chore: Hide linear linked issues error toast messages

- app/javascript/dashboard/components/CustomAttribute.vue
- app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
- app/javascript/dashboard/routes/dashboard/settings/SettingsLayout.vue
- app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
- app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue
- app/javascript/dashboard/routes/dashboard/settings/attributes/Index.vue
- app/javascript/dashboard/routes/dashboard/settings/attributes/attributes.routes.js
This PR continues the design update series, updates the design for the custom attributes management page. This PR improves the interaction in the Add Custom Attribute feature. Now, the attribute model in the add attribute form will default to the currently selected tab.
| Light | Dark |
| -- | -- |
| <img width="1433" alt="Screenshot 2024-08-29 at 6 12 40 PM" src="https://github.com/user-attachments/assets/99d715b4-2b69-440c-9faf-a2222852b545"> | <img width="1436" alt="Screenshot 2024-08-29 at 6 12 52 PM" src="https://github.com/user-attachments/assets/3557759c-e830-4da6-8295-73cffe2ece66"> |
> feat(design): Update the design for the custom attribute console

- app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
- app/javascript/dashboard/components/widgets/WootWriter/keyboardEmojiSelector.vue
- app/javascript/dashboard/components/widgets/conversation/CannedResponse.vue
- app/javascript/dashboard/components/widgets/conversation/VariableList.vue
- app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
- app/javascript/dashboard/helper/AnalyticsHelper/events.js
- app/javascript/dashboard/helper/editorHelper.js
- app/javascript/dashboard/helper/specs/editorContentHelper.spec.js
- app/javascript/dashboard/helper/specs/editorHelper.spec.js
- package.json
- yarn.lock
1. This PR will add support for select emoji from keyboard by adding `:{search emoji name}`. 
2. Moved insert special content (Mention, canned response, variable and emoji selection) methods to helper. 
3. And made some changes in the **Prosemirror** repo to support min characters in `triggerCharacters` method, here is the PR https://github.com/chatwoot/prosemirror-schema/pull/30
Fixes https://linear.app/chatwoot/issue/CW-3549/add-support-for-selecting-emojis-using-the-keyboard
**Screen recording**
https://github.com/user-attachments/assets/65d9fd34-44a0-4bd1-9da3-ab652ddeb2b3
> feat: Adds support for selecting emojis using the keyboard

- app/javascript/dashboard/components/ChatList.vue
**Issue**
This PR addresses an sentry issue in the `ChatList.vue` component, where a `TypeError: Cannot read properties of undefined (reading 'click')` was thrown when navigating through the chat list using keyboard shortcuts. The error occurred because the code attempted to invoke the `click()` method on elements that were not present, typically happening when the chat list is empty.
**Solution**
I updated the keyboard navigation functions to include checks for the `allConversations` array's length, ensuring that `click()` actions are only attempted when the array contains elements. Additionally, I added comments to the code to improve clarity and maintainability.
Fixes https://linear.app/chatwoot/issue/CW-3535/typeerror-cannot-read-properties-of-undefined-reading-click
1. Open dashboard …
> fix: TypeError cannot read properties of undefined (reading 'click')

- spec/enterprise/controllers/api/v1/accounts/custom_roles_controller_spec.rb
- spec/factories/custom_roles.rb
- the permissions tests were failing when the random number turns out to be 0, fixing this case and ensuring that its always between, 1-4.
> chore: Fix flaky permissions test

- app/controllers/api/v1/accounts/upload_controller.rb
- app/javascript/dashboard/store/modules/helpCenterArticles/specs/action.spec.js
- spec/controllers/api/v1/upload_controller_spec.rb
We're adding support for copying and pasting images directly into the editor. Users can copy images from any platform and paste them seamlessly. These images will be stored in Chatwoot's storage, reducing reliance on external servers. This ensures that all images remain accessible even if the original source becomes unavailable. This PR extend the `upload` endpoint to support external URLs.
> feat: Extend `upload` API end point to support external images

- package.json
- yarn.lock
This PR will address an issue where editor controls, such as emoji insertion, canned responses, and variable insertion, were not functioning correctly after adding a newline using `Shift+Enter.`
**Screenrecording**
https://github.com/user-attachments/assets/799944c4-4862-4fb7-af50-03b796c91736
> fix: Editor controls not working after newline `(Shift+Enter)`

- app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
- app/javascript/dashboard/components/widgets/WootWriter/keyboardEmojiSelector.vue
This PR enhances the emoji search functionality in the editor's emoji selector by improving how emoji names are displayed and searched. 
The UI now shows emoji names instead of slugs, and the search logic has been updated to generate `searchString` without whitespaces, allowing users to search for emojis like 'face_with' using 'facewith'
> feat: Display emoji names and improve search

- app/controllers/public/api/v1/portals/articles_controller.rb
- spec/controllers/public/api/v1/portals/articles_controller_spec.rb
Limit the API to return only the published articles in public help center API.
Fixes https://github.com/chatwoot/chatwoot/issues/10026
> fix: Remove draft articles from the help center search

- app/controllers/api/v1/widget/conversations_controller.rb
- app/views/api/v1/models/_widget_message.json.jbuilder
- spec/controllers/api/v1/widget/conversations_controller_spec.rb
The `before_type_cast` method sometimes returns a string for `message_type`, creating inconsistencies in conversation create API response.
> fix: `message_type` in widget conversation create end point

- Gemfile.lock
- app/models/article.rb
- app/views/public/api/v1/portals/show.html.erb
- db/migrate/20240923215335_add_locale_to_article.rb
- db/schema.rb
- spec/controllers/api/v1/accounts/articles_controller_spec.rb
- spec/factories/articles.rb
- spec/models/article_spec.rb
Fixes https://github.com/chatwoot/chatwoot/issues/9935
Fixes https://github.com/chatwoot/chatwoot/issues/8213
The articles were grouped by category, with locale being a derived attribute from the category. If a category was deleted, the article wouldn't appear on the dashboard. However, due to a bug, it would show up in the uncategorized section on the public portal, leaving agents unable to edit or update the article.
To address this issue, I've added a locale attribute directly to the article. This attribute is automatically set from the category or the portal's default locale if not supplied. The API parameters now use this attribute to filter articles. As a result, the dashboard will display articles even if they're not associated with a category, improving the overall workflow. …
> fix: Include uncategorized articles in the all article section to allow edit/delete

- app/services/twilio/incoming_message_service.rb
We received customer reports that attachments in Twilio messages required page reloads to appear. This issue occurred because in the old Twilio builder, we saved the message and attachment in two stages. The new builders follow a streamlined approach, where both are saved in a single transaction. This update aligns the Twilio channel with the new builder format and resolves the issue.
Tests cover the attachment cases, ensuring that all original tests pass with these changes.
> fix: Twilio channel attachment issues

- app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/channels/google/Reauthorize.vue
- app/views/api/v1/models/_inbox.json.jbuilder
This PR allows migration of legacy GMail inbox users to new OAuth based inbox
1. Create an inbox from the seed data and set it's IMAP address to `imap.gmail.com` from the UI
2. Open `rails console` and run the following
```
inbox = Inbox.find(100) # use your inbox id here
channel = inbox.channel
channel.update(email: 'hello@chatwoot.com')
channel.prompt_reauthorization!
```
3. This will show the prompt on the UI. Once you click on Reauthorize, it should open Google Auth. Reauthroize with the same email address as used in the inbox and it should start working as usual
```sh
GOOGLE_OAUTH_CLIENT_ID=<some-hash>.apps.googleusercontent.com
GOOGLE_OAUTH_CLIENT_SECRET=<client-secret>
GOOGLE_OAUTH_CALLBACK_URL="http://localhost:3000/omniauth/google_oauth2/callback"
```
> feat: let users re auth legacy google inboxes

- config/initializers/lograge.rb
- config/initializers/sidekiq.rb
This PR addresses several issues related to logging:
- Enabling Lograge broke certain non-API URLs, such as password reset. This occurred due to the user ID tagging we had in Lograge, which has now been limited to API pages only.
- Disabled the start and done logs in Sidekiq.
- Investigated why Sidekiq logs weren’t being output as JSON. This is due to the use of ActiveJob instead of Sidekiq for the job base classes.
**Potential Options for Converting ActiveJob Logs to JSON:**
- https://glozer.rocks/ojb
- https://learnedreverie.medium.com/activejob-logs-as-json-6912403d8c81
- https://github.com/roidrage/lograge/pull/226
> fix: Lograge issue on non api pages

- app/javascript/dashboard/helper/AudioAlerts/DashboardAudioNotificationHelper.js
The `initOnEvents` was used to get the notification sound file and trigger the 30 second loop, but since the function was replaced to using class syntax, the removeEvent listener was not working. This PR fixes it by reverting to the old syntax but moving it inside the constructor instead and also adding a `once: true` to ensure it is always removed automatically
> fix: initOnEvents not removed [CW-3594]

- app/javascript/dashboard/routes/dashboard/settings/auditlogs/Index.vue
Vue i18n would automatically merge arrays previously, it does not do so now. This PR fixes it by cleaning up the payload before passing it for translation
> fix: translation payload for audit logs

- app/services/line/incoming_message_service.rb
Similar to the work we did with the legacy code of other channels like Twilio, we need to move the message creation and attachment creation to be under a single db commit for the line channel. Otherwise, the emitted webhook events for message creation will miss the attachment payload. 
ref: https://github.com/orgs/chatwoot/discussions/7546#discussioncomment-10814495
ref: https://github.com/chatwoot/chatwoot/pull/10167
> chore: Move line attachment creation to a single db commit

- config/locales/id.yml
- config/locales/ja.yml
- config/locales/ko.yml
- config/locales/ms.yml
- config/locales/th.yml
- config/locales/vi.yml
- config/locales/zh_CN.yml
- config/locales/zh_TW.yml
- add missing 'one' translations for time units in agent reports 
Fixes https://github.com/chatwoot/chatwoot/issues/10220
> fix: add missing 'one' translations for time units in agent-reports

- app/javascript/widget/components/ChatInputWrap.vue
- app/javascript/widget/router.js
- app/javascript/widget/views/ArticleViewer.vue
- app/javascript/widget/views/Home.vue
This PR has the following fixes
1. preview of article inside the iframe, earlier this didn't work because the iframe didn't get the URL correctly. We fix that by passing the URL is a query instead
2. Emoji picker caused a weird redirect, this was only happening when the chunk was loaded async, this PR changes it to use regular loading instead
> fix: widget issues [CW-3612]

- config/locales/zh_CN.yml
The integrations are displayed based on whether the integration object is available on the API. Since there are chances where empty objects can be returned, the check for the presence was done based on the "integration.name". The name was empty (this should be investigated) in the zh_CN locale, which led to the feature being disabled for a user.
In this PR, I just added the string which should enable the feature. In the followups, I will add a better check for the presence of the integration object.
> fix: Add webhook string to the zh_CN to fix missing webhook feature

- vite.config.ts
The UMD build was causing issues for a few customers, this PR reverts to using CJS like used in Webpack 4 before the vite migration
> feat: Use CJS build for SDK

- app/controllers/google/callbacks_controller.rb
- app/controllers/oauth_callback_controller.rb
- app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Email.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/channels/google/Reauthorize.vue
- spec/controllers/google/callbacks_controller_spec.rb
When moving form using Gmail Legacy auth to using OAuth, we need the email address that will be used to connect. This is because we need to store this email address in the cache and reuse when we get the callback to find the associated inbox. 
However there are cases where the imap login might be `support@company.com` and the email used to communicate will be `contact@company.com` (Probably an alias) In that case, we need to send the correct email address to Chatwoot when re-authenticating
At the moment, we used the inbox email. This PR adds a check that defaults to to `imap_login` if that is available and imap is enabled
This PR also fixes an unrelated problem where the email inbox creation flow was not working
---
Tested it, it is working correctly
> feat: use of imap login as default if present

- app/javascript/dashboard/components/ui/Dropdown/DropdownList.vue
In the `DropdownList.vue` component, the `onSearch` function was not properly passing the search value to the parent component. This resulted in the `onSearch` event in parent components (such as `LinkIssue.vue`) receiving an undefined value instead of the actual search term.
https://github.com/chatwoot/chatwoot/blob/f18ed01eb7725954fc9c0d45201ac3c53cd9855b/app/javascript/dashboard/components/ui/Dropdown/DropdownList.vue#L45-L52
The issue was resolved by modifying the `onSearch` function in `DropdownList.vue` to correctly pass the search value to the `debouncedEmit` function:
> fix: Search linear issues

- .gitignore
- app/javascript/dashboard/components/layout/sidebarComponents/Primary.vue
- vite.config.ts
This PR updates the sidebar component to use a native <a> tag for the Help Center URL component. It also updates the build pipeline to use the esbuild options minifyIdentifiers and keepNames set to true.
> fix: Use native a tag for https URL in the sidebar

- vite.config.ts
Vite uses `Rollup` for bundling, when building the sdk, we effectively run a separate vite config, with `Library Mode`. When migrating from Webpack to Vite, I selected `umd` format, i.e.  Universal Module Definition, which works as `amd`, `cjs` and `iife` all in one. However a lot of Chatwoot users ran into issues where UMD sdk.js won't work. Especially so when used with Google Tag Manager.
As a hotfix we moved the format from `umd` to `cjs`. Here's the thing CJS is supposed to be used for Node packages. But for some-reason it was working on browsers too, its no surprising, since the output is a valid JS and the code we wrote was written for the browser. 
There's a catch though, when minifying, esbuild would use tokens like `$` and `_`, since `CJS` build is not scoped, unlike a `UMD` …
> feat: use `iife` build for sdk

- app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/DashboardAppModal.vue
This PR will fix this sentry issue `Cannot read properties of undefined (reading '$touch')`, which has been separated from this PR: https://github.com/chatwoot/chatwoot/pull/10262
Fixes https://chatwoot-p3.sentry.io/issues/5966555379?project=4507182691975168
**Loom video**
**Before**
https://www.loom.com/share/71cd2191135c48e792b2c6d5976f4e58?sid=7f4a811e-8930-4af9-a01d-3fe13944e0fc
**After**
https://www.loom.com/share/de1e127e532549ee90b9724a2c21de98?sid=e7f71f58-ef73-41d7-af1c-72c1dc106b21
> fix: Cannot read properties of undefined (reading '$touch')

- app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/DashboardAppModal.vue
- app/javascript/dashboard/store/modules/contacts/mutations.js
- app/javascript/dashboard/store/modules/notifications/mutations.js
Fixes the following issues
- https://chatwoot-p3.sentry.io/issues/5966466083
- https://chatwoot-p3.sentry.io/issues/5966497518
- https://chatwoot-p3.sentry.io/issues/5966555379
For the first one, I am not sure if the fix is 100% correct, since I was not able to reproduce, but I am confident it will work.
For both, 1st and 2nd issues, the problem came from the fact that we set individual records to `undefined` when the intent was to remove it, explicitly using delete fixes the issue.
Glad you asked, this comes down to Vue reactivity, previously Vue didn't track undefined strictly, it just kinda ignored it, in Vue 3, the reactivity changed significantly when they introduced ES6 proxies. The Proxy tracks all property changes, including those set to undefined, so properties remain enumerable. …
> fix: sentry issues from Vite migration

- deployment/setup_20.04.sh
- fix pip install during cwctl upgrade in `ubuntu 24.04`
- add logs during pnpm installation
- fix `pnpm` installation during upgrade
Ref
> PEP 668 specification in Ubuntu 24.04, which marks the Python environment as "externally managed." This means it restricts using pip for system-wide package installations to avoid conflicts with system-managed packages.
- Tested on Ubuntu 20.04, 22.04, 24.04
> fix: cwctl upgrade in ubuntu 24.04

- app/javascript/dashboard/assets/scss/_woot.scss
Fix mismatch in CSS vars for `amber` and `blue` solid colors
> fix: solid colors

- app/javascript/dashboard/components/widgets/conversation/Message.vue
- app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
This PR resolves the issue where the modal in the context menu disappears when not being hovered over.
**Cause of issue.**
The problem occurred because the modal-related component was placed inside `MessageContextMenu.vue`, and the parent wrapper was using the classes `group-hover:visible invisible`. This caused the modal to only appear when the message item, where the context menu was opened, was hovered over.
**Solution**
To fix this, I removed the `group-hover:visible` invisible class from the parent wrapper and moved it into the `woot-button` within the `MessageContextMenu.vue` component. Additionally, I added a nested group with the class group/context-menu, allowing the focus to remain on the context menu itself.
Fixes https://linear.app/chatwoot/issue/PR-1415/modal-in-the-context-me …
> fix: Modal in the context menu disappears unless hovered

- app/javascript/dashboard/components/ChatList.vue
This PR fixes the issue where the bulk action inbox assignable agent list was not showing.
The issue started after merging this [feat: Vite+Vue 3 PR](https://github.com/chatwoot/chatwoot/pull/10047 ).
**Cause of issue**
Previously, `selectedInboxes` was accessed from the `ChatList.vue` component. However, after moving the bulk action logic from mixin to the `useBulkActions.js` composable, we were still referencing `selectedInboxes` from the `ChatList.vue` component, even though it was being set in the composable. This caused the API failed to load the assignable agent list.
Ref:https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/dashboard/composables/chatlist/useBulkActions.js#L18
**Solution**
Removed the usage of `selectedInboxes` from the `ChatList.vue` component ref and …
> fix: Agents list in bulk action is not loading

- app/javascript/dashboard/components-next/sidebar/SidebarAccountSwitcher.vue
- app/javascript/dashboard/components-next/sidebar/SidebarGroup.vue
This PR fixes two issues with the sidebar
1. Text does not truncate correctly on account switcher
2. `locateLastChild` would not work correctly on reloading
3. Spacing for create new account button in account switcher
4. Add separator in account switcher
> fix: next sidebar issues

- app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue
This one is a fix for an interesting issue pointed here: https://github.com/chatwoot/chatwoot/issues/10339
The user had two dashboard apps configured, each of which could request data from the parent Chatwoot window by posting a message with `window.parent.postMessage('chatwoot-dashboard-app:fetch-info', '*')`
The "Dashboard Frame" component had a listener set on window using `window.onmessage`, this was added during the `mounted` event
https://github.com/chatwoot/chatwoot/blob/601a0f8a766e8a02a48a743346a4f3b44b7019c6/app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue#L55-L65
The problem with this approach is the first iframe on mount attaches this event correctly, but every subsequent frame opened `onmessage` would be overridden. Now since the dashboard app frames are …
> feat: use addEventListener instead of onmessage

- config/initializers/rack_timeout.rb
40 % of Chatwoot's current log volume is from state transition logs generated by `rack-timeout`, which are logged at the `INFO` level. 
- Reduce the noise in logs
- Set RACK::TIMEOUT to log at `error` level
- Bring down log volume by 40% (cost-savings)
Fixes https://linear.app/chatwoot/issue/CW-3714/newrelic-set-rack-timeout-log-level-to-error
- Tested in staging
Logs before and after deploying the branch
----
Note: The graph is flat in the first half due to the paper trail running out of credits. I upgraded the paper trail first to ensure logs were coming in and then made the deployment.
> chore: set rack-timeout to log at ERROR level

- app/controllers/api/v1/accounts/integrations/captain_controller.rb
The proxy method adds an extra slash even if the route param has the character. It’s challenging to check the expected format on each route. The simplest solution is to check if the route param begins with a slash, and if not, append one.
NB: The existing tests are sufficient to cover this case. There’s no need for an additional test to specifically test this.
> fix: Remove duplicate `/` character on the proxy route

- Gemfile
- Gemfile.lock
- config/application.rb
- add judoscaler gem to allow judoscale use in heroku environments
- This will allow auto scaling for both web and worker dynos across both standard-1x/2x and performance dynos
- This will scaling in response to queue time rather than response time(heroku default)
- This also allows you to scale multiple dynos in and out at once, rather than scaling them one at a time, as is the default.
Ref
----
1. https://judoscale.com/
2. https://devcenter.heroku.com/articles/judoscale
- Tested on staging
> feat: add judoscaler gem for heroku autoscaling

- app/javascript/dashboard/components-next/sidebar/Sidebar.vue
The following warning occurred since the `ChannelLeaf` component was passed extra props. This PR fixes it by passing only the required props
> fix: Remove the warnings generated from the Sidebar component

- app/jobs/avatar/avatar_from_url_job.rb
- spec/jobs/avatar/avatar_from_url_job_spec.rb
Invalid urls supplied to the job was causing sentry issues.  The issue primarily occurs when the download file.original_filename comes out as empty
fixes: https://github.com/chatwoot/chatwoot/issues/10449
> fix: undefined method `encode' for nil for avatar from url job

- app/dashboards/account_dashboard.rb
- Viewing the account custom attributes is quite handy when debugging on Chatwoot cloud. Hence adding this option to Super Admin.
> feat: Display Account Custom Attributes in Super Admin

- app/mailboxes/application_mailbox.rb
- spec/mailboxes/application_mailbox_spec.rb
We don't need to raise error on sentry for malformed to address as it is already logged.
ref: https://linear.app/chatwoot/issue/CW-3151/standarderror-invalid-email-to-address-header-standarderror
> chore: Disable throwing error for malformed to address

- app/javascript/dashboard/components-next/icon/ChannelIcon.vue
- app/javascript/dashboard/components-next/icon/provider.js
- app/javascript/dashboard/components-next/icon/specs/provider.spec.js
- app/javascript/dashboard/components-next/sidebar/ChannelLeaf.vue
This pull request introduces a new `ChannelIcon` component and refactors the existing code to use this component, which simplifies the icon management for different channel types and providers. 
Preview:
> feat: add channel icon component

- app/javascript/dashboard/components/ui/Tabs/Tabs.vue
This PR will fix reactivity issue with `<woot-tabs />` component.
**Cause of issue**
The `<woot-tabs />` component used an internal ref, `internalActiveIndex` to track the `active` tab. However, it didn’t sync with the `index` prop when updated by the parent, causing mismatched tab selections.
**Solution**
The component now directly uses `props.index` to ensure it always reflects the latest value from the parent. The unnecessary `internalActiveIndex` ref has been removed. Changes to the active tab emit a `change` event to update the parent.
**Loom video**
**Before**
https://www.loom.com/share/76eb32f1e7f7422f84055a102bf80951?sid=bc28c6ff-9640-4d3b-956c-99c1ec164971
**After**
https://www.loom.com/share/6bd8125ede5d43dc8fe115c3f1fb159b?sid=c376617a-94fb-4f71-8664-e0bd9e7af0b4
> fix: Component `<woot-tabs />` reactivity issue.

- app/models/attachment.rb
- lib/integrations/slack/send_on_slack_service.rb
- spec/lib/integrations/slack/send_on_slack_service_spec.rb
- spec/models/attachment_spec.rb
Skip calling the Slack file upload API for message types such as fallback (e.g., Facebook and location messages) that lack actual file data in attachments. This prevents unnecessary API calls and resolves a Sentry error currently occurring in production.
fixes: https://github.com/chatwoot/chatwoot/issues/10460
> fix: avoid Slack file upload API for fallback messages

- app/jobs/internal/process_stale_redis_keys_job.rb
- app/jobs/internal/remove_stale_redis_keys_job.rb
- app/services/internal/remove_stale_redis_keys_service.rb
- config/schedule.yml
50% of Redis memory size comes from ONLINE_PRESENCE keys. This PR adds a periodic job to remove stale keys from all accounts.
Fixes https://linear.app/chatwoot/issue/CW-3231/investigate-appropriate-strategy-for-redis-key-expiry
> feat: remove stale ONLINE_PRESENCE contact keys in redis

- app/javascript/dashboard/components-next/Contacts/ContactsForm/ContactsForm.vue
- app/javascript/dashboard/components-next/Contacts/ContactsForm/CreateNewContactDialog.vue
- app/javascript/dashboard/components-next/Contacts/ContactsHeader/ContactListHeaderWrapper.vue
- app/javascript/dashboard/components-next/phonenumberinput/PhoneNumberInput.vue
- app/javascript/dashboard/i18n/locale/en/contact.json
- app/javascript/dashboard/store/modules/customViews.js
This PR will resolve the issues raised in this PR comment. https://github.com/chatwoot/chatwoot/pull/10501#issuecomment-2505082041
Fixes
> feat: Contact list improvements

- app/javascript/dashboard/components-next/Contacts/Pages/ContactDetails.vue
Fixes https://linear.app/chatwoot/issue/CW-3773/contact-attributes-getting-reset-when-the-form-is-updated
**Cause of issue**
The issue occurs because the `contactData` state is updated with the selected contact's data. Upon updating the contact form, the `contactData` object is reassigned with the updated values.
Initially, on component mount, the `contactData` reference is set with the full selected contact's values. When the update button is clicked, the `contactData` reference is passed as a parameter. This includes non-updated or outdated custom attribute values if custom attributes are edited but not properly managed during the update. As a result, the custom attributes are reset when the form is updated.
**Solution**
During the update contact trigger, only the base contact data is …
> fix: Contact Attributes resetting when form is updated

- app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
Fixes https://linear.app/chatwoot/issue/CW-3771/list-of-the-agents-are-not-appearing-in-the-full-width-layout
**Cause of issue**
The watcher in `ConversationBox` component did not handle the initial state correctly when mounted in the expanded layout. This was due to:
1. Differences in the mounting and chat selection timing between the expanded and condensed layouts.
2. The `currentChat.inbox_id` watcher wasn't set up to handle the initial state properly.
**Solution**
The watcher was updated to use the object syntax with a handler function and the `immediate: true` option. This ensures that the watcher executes immediately upon component mounting, irrespective of the layout type. Consequently, inbox assignable agents are fetched promptly whenever an `inbox_id` becomes available in both …
> fix: Fetch assignable agents in expanded layout

- app/controllers/api/v1/accounts/contacts_controller.rb
- app/javascript/dashboard/api/contacts.js
- app/javascript/dashboard/components-next/Contacts/Pages/ContactDetails.vue
- app/javascript/dashboard/components-next/NewConversation/ComposeConversation.vue
- app/javascript/dashboard/components-next/NewConversation/helpers/composeConversationHelper.js
- app/javascript/dashboard/components-next/NewConversation/helpers/specs/composeConversationHelper.spec.js
- app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue
- app/javascript/dashboard/store/modules/contacts/actions.js
- app/views/api/v1/accounts/contacts/show.json.jbuilder
- app/views/api/v1/accounts/contacts/update.json.jbuilder
This PR will fix the duplicate contact inbox issue in the new compose conversation form.
Fixes https://linear.app/chatwoot/issue/CW-3784/show-a-duplicate-of-inboxes-in-the-contactable-inboxes-dropdown
> fix: Showing duplicate contact inbox in new conversation form.

- app/javascript/dashboard/components-next/sidebar/SidebarGroup.vue
When reloading a page, the sidebar item that is actively selected is collapsed by default. This PR fixes it by expanding it on reload
> fix: sidebar collapsed on reload

- app/javascript/dashboard/assets/scss/_woot.scss
- app/javascript/dashboard/components-next/Contacts/ContactsCard/ContactsCard.vue
- app/javascript/dashboard/components-next/flag/Flag.vue
- app/javascript/dashboard/components-next/flag/story/Flag.story.vue
- app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
- app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
- package.json
- pnpm-lock.yaml
This PR introduces a new `Flag` component that provides a way to display country flags using the [flag-icons](https://github.com/lipis/flag-icons?tab=readme-ov-file#flag-icons) library.
| Prop | Type | Required | Default | Description |
|------|------|----------|---------|-------------|
| `country` | String | Yes | - | ISO 3166-1-alpha-2 country code (e.g., 'US', 'GB', 'FR') |
| `squared` | Boolean | No | `false` | Display flag in square format |
- Supports all country flags from ISO 3166-1-alpha-2 standard
- Customizable size using Tailwind's size utilities
- Supports both rectangular and squared formats
- Inherits custom classes for additional styling
- Prevents shrinking with `flex-shrink-0`
**All flags**
**Contact card**
**Conversation sidebar**
> feat: Flag icon component

- app/javascript/dashboard/components-next/dropdown-menu/base/DropdownItem.vue
- app/javascript/dashboard/components-next/sidebar/SidebarProfileMenu.vue
This pull request includes several changes to the `DropdownItem.vue` and `SidebarProfileMenu.vue` components to improve the handling of links.
Earlier we passed the link `/super_admin` to RouterLink directly, which would trigger validations internally and the dropdown item would not render in case of any errors
This PR fixes this by handling the native links appropriately
Fixes #10571
---
* Added a new `nativeLink` prop to distinguish between native and router links.
* Modified the `componentIs` computed property to return `'a'` for native links and `'router-link'` for router links.
* Updated the template to use the appropriate attributes (`href` or `to`) based on the link type.
> fix: links rendering in sidebar profile

- app/javascript/dashboard/components-next/Contacts/ContactsForm/ContactsForm.vue
- Handles the case where the form and contact display page breaks if name is `null`
> fix: Contact form breaks if name is empty

- db/migrate/20241217041352_fix_old_audio_alert_data.rb
- db/schema.rb
The following lines caused issues for some users, specifically those who signed up in 2021 when audio alerts were implemented as a flag. The data type update for the flag was not handled correctly. This PR fixes the issue by updating it to a compatible value.
https://github.com/chatwoot/chatwoot/blob/9410b3bcbbb7aba4b790f33bea52a430bf69466c/app/javascript/dashboard/helper/AudioAlerts/DashboardAudioNotificationHelper.js#L76-L81
> fix: Update old data to fix login issues

- lib/custom_markdown_renderer.rb
- spec/lib/custom_markdown_renderer_spec.rb
This PR adds support for rendering Arcade videos on articles.
Fixes https://linear.app/chatwoot/issue/CW-3779/add-support-for-arcade-videos-on-articles-loom-alternative
**Loom video**
https://www.loom.com/share/917bdecb4eaf4d3f9782b4fa84ee4bd4?sid=d11f0d71-0cf5-424a-9268-9d9fb3797ee2
> feat: Add support for Arcade videos on articles

- app/builders/v2/reports/agent_summary_builder.rb
- app/builders/v2/reports/base_summary_builder.rb
- app/builders/v2/reports/inbox_summary_builder.rb
- app/builders/v2/reports/team_summary_builder.rb
- spec/builders/v2/reports/agent_summary_builder_spec.rb
- spec/builders/v2/reports/team_summary_builder_spec.rb
Following https://github.com/chatwoot/chatwoot/pull/10604, this PR introduces similar reporting features for Agents and Teams.
Updates in this PR:
- Added additional methods to the base class to avoid repetition.
- Improve reporting for Teams and Agents to include resolution count.
> feat(v4): Update team, agent summary builder to include resolution metrics

- app/javascript/dashboard/components-next/message/Message.vue
- app/javascript/dashboard/components-next/message/MessageList.vue
- app/javascript/dashboard/components-next/message/MessageMeta.vue
- app/javascript/dashboard/components-next/message/bubbles/Activity.vue
- app/javascript/dashboard/components-next/message/bubbles/Base.vue
- app/javascript/dashboard/components-next/message/bubbles/Email/EmailMeta.vue
- app/javascript/dashboard/components-next/message/bubbles/Email/Index.vue
- app/javascript/dashboard/components-next/message/bubbles/Text/FormattedContent.vue
- app/javascript/dashboard/components-next/message/bubbles/Text/Index.vue
- tailwind.config.js
This PR has fixes for the following issues
- Inconsistent spacing between meta and text in text bubble
- Activity bubble overflows for longer text (for now I have truncated it, I'll work with @absurdiya on a better solution)
- Ugly lookinh gradient for expand button on email bubble
- Email bubble overflow issues and text rendering issues
- Alignment for error message
- Minute-wise grouping not working
- Link color should not be blue
- Use `gray-3` for bubble background instead of `gray-4`
> fix: bubble UI issues

- app/actions/contact_merge_action.rb
We observed some rare instances on prod where a contact inbox was getting deleted during the contact merge action. the potential suspect is contact inbox objects already loaded into the memory getting cleared through the destroy association job. Reloading the object to avoid this case !!!
> chore: Avoid contact inboxes getting deleted

- app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
Changed to make use of nullish coalescing operator to only short circuit in cases when the `metric` variable is not zero. This change also begs the question as to whether the `stringToFloat` test function should exist - to me it seems interesting to have test code embedded into production code for the frontend?
Fixes #10640
Tested by opening the report overview page and reviewing that this shows `---` for agents with no conversations assigned to them.
> fix: AgentTable report showing test value for zero conversations

- app/builders/notification_builder.rb
- spec/builders/notification_builder_spec.rb
- Prevents notifications from being created for conversations or actions involving blocked contacts.  
- The exception is the conversation_mention notification type, which will still be created when applicable.
> fix: Exclude notifications for blocked contacts, except mentions

- app/services/messages/new_message_notification_service.rb
- spec/listeners/notification_listener_spec.rb
- spec/services/messages/new_message_notification_service_spec.rb
This PR addresses an issue where mention_notification was being overwritten by assigned_conversation_new_message notifications. Similarly, participating_conversation_new_message was taking priority over assigned_conversation_new_message.
The fix ensures that additional notifications are not created in these scenarios by establishing a priority order for notifications as follows:
1. mention_notification
2. assigned_conversation_new_message
3. participating_conversation_new_message
This change maintains consistency and prevents redundant notifications.
----
Note: In the older implementation of notifications in Chatwoot, notification objects were created only if the user had subscribed to a specific notification type. With the new inbox_view model, we are changing this approach to create …
> fix: Prevent duplicate notifications for mentions

- app/javascript/dashboard/components/widgets/WootWriter/EditorModeToggle.vue
The reply editor toggle was a bit confusing for a few users, where it's not clear that it's clickable. This PR updates it to make it more clear
https://github.com/user-attachments/assets/9e377eda-34d5-4f64-a06a-23ae822da50e
https://github.com/user-attachments/assets/84c6b23c-cd17-4805-8e63-9d7d1cc0d799
> fix: toggle for reply editor

- .devcontainer/docker-compose.yml
- docker-compose.production.yaml
- docker-compose.test.yaml
- docker-compose.yaml
Starting v4.0, pgvector support is mandatory. This PR adds pgvector support for new docker installations.
- Switch to postgres images with pgvector support
- Change the default postgres version from `12` to `16`
- Tested on a new docker installation running on ec2
- Upgrade existing installation
> feat: switch to postgres docker images with pgvector support (v4.0)

- app/javascript/dashboard/routes/dashboard/inbox/InboxList.vue
This PR will fix and issue with Inbox view list has no border left on RTL view
**Before**
**After**
> fix: Inbox view list lacks a border in RTL view.

- deployment/setup_20.04.sh
Multiple versions of postgres were getting installed, conflicting with the `pgvector` extension being installed. This PR sets the version to `16` for all postgres dependencies ensuring a single version is installed.
> fix: set cwctl pg version to 16

- app/javascript/dashboard/helper/actionCable.js
- app/javascript/dashboard/routes/dashboard/settings/reports/LiveReports.vue
Previously, the Reports API fetched data based on event triggers. For example, when an event occurred on an account, the system would automatically retrieve and display updated information. However, this approach was designed under the assumption that reports would be accessed by a small number of users and on an infrequent basis (e.g., once daily or weekly).
In scenarios where large customers have multiple team members actively monitoring reports, this event-driven approach led to an excessive number of requests, significantly straining the system.
This PR introduces a interval-based fetching of reports instead of the event-driven model.
> fix: Remove Report API calls from being called on every event

- app/javascript/dashboard/api/captain/response.js
- app/javascript/dashboard/components-next/captain/assistant/ResponseCard.story.vue
- app/javascript/dashboard/components-next/captain/assistant/ResponseCard.vue
- app/javascript/dashboard/components-next/captain/pageComponents/document/RelatedResponses.vue
- app/javascript/dashboard/i18n/locale/en/integrations.json
- app/javascript/dashboard/routes/dashboard/captain/responses/Index.vue
- db/migrate/20250116000103_add_status_to_captain_assistant_responses.rb
- db/schema.rb
- enterprise/app/controllers/api/v1/accounts/captain/assistant_responses_controller.rb
- enterprise/app/models/captain/assistant_response.rb
- enterprise/app/services/captain/copilot/chat_service.rb
- enterprise/app/services/captain/llm/assistant_chat_service.rb
- enterprise/app/services/captain/llm/conversation_faq_service.rb
- enterprise/app/views/api/v1/models/captain/_assistant_response.json.jbuilder
- spec/enterprise/services/captain/llm/conversation_faq_service_spec.rb
This PR introduces a review step for generated FAQs, allowing a human to validate and approve them before use in customer interactions. While hallucinations are minimal, this step ensures accurate and reliable FAQs for Captain to use during LLM calls when responding to customers.
- Added a status field for the FAQ
- Allow the filter on the UI.
> feat: Add a review step for FAQs generated from conversations before using it

- app/javascript/dashboard/api/captain/document.js
- app/javascript/dashboard/components-next/captain/pageComponents/AssistantSelector.vue
- app/javascript/dashboard/routes/dashboard/captain/documents/Index.vue
- app/javascript/dashboard/routes/dashboard/captain/responses/Index.vue
This PR introduces support for an assistant filter on the documents page.
- Moved the existing assistant filter functionality to a standalone, reusable component.
- Updated the documents page and responses page to use the component
> feat: Add assistant filter support to documents page

- app/javascript/dashboard/components/Modal.vue
Remove backdrop-blur-[100px] from Modal as it was causing issues with old design pages.
> fix: Remove backdrop-blur from Modal

- app/javascript/dashboard/components-next/message/bubbles/Image.vue
- app/javascript/dashboard/components-next/message/chips/Audio.vue
- app/javascript/dashboard/components/widgets/conversation/components/GalleryView.vue
- package.json
- pnpm-lock.yaml
Fixes https://linear.app/chatwoot/issue/CW-3905/fix-download-images-option-to-download-directly-instead-of-opening-url
https://www.npmjs.com/package/@chatwoot/utils/v/0.0.31
https://github.com/chatwoot/utils/pull/37
> fix: Download button opens URL instead of downloading

- app/javascript/dashboard/components-next/captain/pageComponents/DeleteDialog.vue
- app/javascript/dashboard/routes/dashboard/captain/documents/Index.vue
- app/javascript/dashboard/routes/dashboard/captain/responses/Index.vue
This PR fixes an issue where deleting the last item on the last page of responses/documents, would show an empty state instead of loading the previous page.
Fixes
>  If you have pending responses spanning 2 or more pages .. and you delete the last response in the last page.. instead of showing the previous page the system show empty state.
**Loom video**
https://www.loom.com/share/b0e89f774ccd45dab0e8dba2c34bd1ac?sid=d9923bcd-5030-42d9-9b7f-170df5297cfd
> chore: Auto-fetch previous page on last item deletion

- db/migrate/20250116061033_convert_document_to_polymorphic_association.rb
Fixes #10721
This PR addresses an issue where the data migration in the CE edition was failing due to missing models. The change ensures that the migration process runs only when the deployment is using the EE image.
> fix(ce): Check the edition before running the data migration

- app/javascript/dashboard/components-next/HelpCenter/Pages/ArticleEditorPage/ArticleEditor.vue
- app/javascript/dashboard/components-next/HelpCenter/Pages/ArticleEditorPage/ArticleEditorControls.vue
- app/javascript/dashboard/components-next/HelpCenter/Pages/ArticlePage/ArticleHeaderControls.vue
- app/javascript/dashboard/components-next/HelpCenter/Pages/ArticlePage/ArticleList.vue
- app/javascript/dashboard/components-next/HelpCenter/Pages/ArticlePage/ArticlesPage.vue
- app/javascript/dashboard/components-next/HelpCenter/Pages/CategoryPage/CategoryHeaderControls.vue
- app/javascript/dashboard/components-next/HelpCenter/Pages/LocalePage/AddLocaleDialog.vue
- app/javascript/dashboard/components-next/HelpCenter/Pages/LocalePage/LocaleList.vue
- app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
- app/javascript/dashboard/store/modules/helpCenterArticles/mutations.js
- app/javascript/dashboard/store/modules/helpCenterArticles/specs/action.spec.js
- app/javascript/dashboard/store/modules/helpCenterArticles/specs/mutation.spec.js
Fixes https://linear.app/chatwoot/issue/CW-3913/issues-with-help-center
**Fixes included**
1.  >  The default locale that is selected should the portal default locale.
Now, we update the last active locale in UI settings after changing the selected locale from the article page header. This ensures that we see the last active locale-based categories on the category page and remember it when we return. Initially, it’s the default locale.
2. > I cannot switch to a different locale if there are no articles in the portal
Now, the `v-if` condition that checked for the presence of articles in portal has been removed. Additionally, the locale length checks for the showing dropdown have been removed, allows locale switching even if article is not preset.
3. > Create or updating the article is …
> chore: Help center improvements

- enterprise/app/helpers/captain/chat_helper.rb
Fixes https://linear.app/chatwoot/issue/CW-3950/nomethoderror-undefined-method-document-for-an-instance-of
> fix: Use documentable instead of document

- app/javascript/dashboard/components/ui/ContextMenu.vue
- app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue
This PR adds smart positioning to prevent context menu and submenu from overflowing screen boundaries. The context menu and its submenu now dynamically adjust their position when there isn't enough space.
Fixes https://linear.app/chatwoot/issue/CW-3936/assign-to-agent-ui-element-is-drawn-off-canvas
https://github.com/chatwoot/chatwoot/issues/10727
**Loom video**
**Before**
https://www.loom.com/share/6c267dde103c4f2281ed5b4d006a43b1?sid=047966f5-d6d3-4de6-ade8-270141e6e215
**After**
https://www.loom.com/share/5599c6061bb74c3ea527dd06960d3189?sid=ffb01149-bb7a-449e-b0ec-02cc191f472b
> fix: Context menu and its submenu boundary overflow

- app/javascript/dashboard/components-next/sidebar/SidebarAccountSwitcher.vue
- app/javascript/dashboard/i18n/locale/en/settings.json
This PR will disable the account switcher dropdown in the new sidebar for users belonging to only one account.
**Screen recording**
https://github.com/user-attachments/assets/b1402efd-970f-4cf5-9be1-3efa51ad9acc
> chore: Disable account switcher for single-account users

- enterprise/app/jobs/captain/documents/crawl_job.rb
- spec/enterprise/jobs/captain/documents/crawl_job_spec.rb
The available limit for documents is now stored in captain.documents.current_available. This PR fixes the limit sent on crawler job.
> fix: Use `current_available` instead `available` to compute the document limit

- app/javascript/dashboard/routes/dashboard/settings/billing/Index.vue
- app/javascript/dashboard/routes/dashboard/settings/billing/components/BillingCard.vue
- app/javascript/dashboard/routes/dashboard/settings/billing/components/BillingMeter.vue
> fix: captain billing colors

- .github/workflows/publish_foss_docker.yml
Emulated docker arm64 builds are failing for community images. This PR
- Switches gh action to use native arm64 runners
- Merges amd64 and arm64 images to create a multi-arch docker image
Fixes https://github.com/chatwoot/chatwoot/issues/10790
> feat: switch to native arm64 runners for docker ce images

- app/javascript/dashboard/components-next/sidebar/SidebarSubGroup.vue
This PR updates the sidebar to hide empty folders. So, in case the user has not created any folders, or teams, the section in the sidebar will be hidden
> feat: hide empty folders from sidebar

- app/javascript/dashboard/components-next/message/chips/File.vue
- package.json
- pnpm-lock.yaml
The PR includes the usage of `getFileInfo` helper from utils https://github.com/chatwoot/utils/pull/40.
Fixes https://github.com/chatwoot/chatwoot/pull/10806#discussion_r1937797905
**Screenshot**
> chore: Use `getFileInfo` helper from utils

- app/javascript/dashboard/components-next/NewConversation/ComposeConversation.vue
**Issue**
The compose conversation modal was unexpectedly closing when users attempted to add links using the editor. This was happening because the `vOnClickOutside` directive was triggering when users interacted with the link editor popup.
**Solution**
Modified the `vOnClickOutside` directive to ignore clicks within the ProseMirror link editor popup by adding `div.ProseMirror-prompt` to the ignore list. This ensures the modal stays open while users are working with the link editor.
Fixes https://linear.app/chatwoot/issue/CW-3982/clicking-the-create-link-button-when-composing-a-message-on-the
https://github.com/chatwoot/chatwoot/issues/10785
**Loom video**
https://www.loom.com/share/ef7f531d54f44ff083700bca69c08a72?sid=20126754-f8e1-4795-bc52-a989563b818d
> fix: Prevent compose modal from closing when creating a link

- spec/controllers/api/v1/accounts/contacts_controller_spec.rb
We have been encountering errors in the community pipeline for the contacts sort by country spec. Upon investigation, it was discovered that the spec assumes the country code is used for sorting. However, the sorting actually relies on the country attribute.
The payload from a previous spec run indicates that none of the contact objects include the country attribute. This fix addresses the issue by aligning the spec with the actual implementation logic.
Here’s an example payload from the previous spec run for reference:
> chore: Resolve flaky spec for Contact country sorting

- app/services/telegram/update_message_service.rb
- spec/services/telegram/update_message_service_spec.rb
The update ensures proper handling of text updates in photo/video messages by accounting for the caption attribute in addition to the text attribute. This change enables consistent processing across both messages.
Fixes https://github.com/chatwoot/chatwoot/issues/10760
Note: TIL, you can update the video/photo you’ve sent on Telegram, not just the text. Currently, we’re not handling this. To support it, we need to parse the payload and update the attachments accordingly. This could be taken as a followup.
> fix: Update the photo/video caption when an update event is received

- app/javascript/dashboard/i18n/locale/en/search.json
- app/javascript/dashboard/modules/search/components/SearchResultConversationItem.vue
- app/javascript/dashboard/modules/search/components/SearchResultConversationsList.vue
- app/views/api/v1/accounts/search/conversations.json.jbuilder
This addresses #10842. It exposes `additional_attributes` in the conversations search endpoint, uses it in `SearchResultConversationsList` to pass `conversation.additional_attributes?.mail_subject` down to `SearchResultConversationItem`, which in turn displays it.
Fixes #10842
I have tested this locally by searching for conversations. See this screenshot where I searched for "noreply":
I would love to add automated tests but I’m not sure how to do that.
> feat: show email subject in conversation search results

- app/javascript/dashboard/components-next/NewConversation/components/ActionButtons.vue
**Issue:** The message signature wasn't being appended to new email conversations when a target inbox was selected.
**Solution:** To address this, a reusable `handleSignatureSetup` function was created to manage the signature logic. The same logic was applied in both cases, when the inbox selection changed (using `watch`) and during the initial load (using `mounted`).
Fixes https://linear.app/chatwoot/issue/CW-4005/allow-to-activate-the-message-signature-for-new-email-conversations-by
https://github.com/chatwoot/chatwoot/issues/10836
**Steps to reproduce**: https://github.com/chatwoot/chatwoot/issues/10836#issuecomment-2637354304
**Before**
https://www.loom.com/share/ccf597cfa8d94d0eaff1222102901d2c?sid=abfea42b-425e-446e-8e92-99359b786607
**After** …
> fix: Message signature is not appending

- app/presenters/conversations/event_data_presenter.rb
- app/views/api/v1/conversations/partials/_conversation.json.jbuilder
- spec/models/conversation_spec.rb
- spec/presenters/conversations/event_data_presenter_spec.rb
Use to_f instead of to_i to preserve the millisecond precision in the UI.
> chore: Update the precision of the updated_at timestamp in conversation model

- app/jobs/action_cable_broadcast_job.rb
Followup PR for https://github.com/chatwoot/chatwoot/pull/10876. This PR just adds all the events related to conversation update to be reloaded before sending it to the UI.
> chore: Add more conversation events for reload

- app/helpers/portal_helper.rb
- spec/helpers/portal_helper_spec.rb
This PR will remove the hexagon background image from public portal.
Fixes https://linear.app/chatwoot/issue/CW-4013/remove-the-background-from-the-help-center
**Before**
**After**
> chore: Remove the background SVG from the help center

- app/javascript/dashboard/components-next/message/bubbles/BaseAttachment.vue
- app/javascript/dashboard/components-next/message/bubbles/Dyte.vue
The component throws `TypeError: Cannot read properties of null (reading 'name')` when accessing the sender's name in base message attachments.  
1. The `sender` prop in the `Message` component defaults to `null` and is unavailable when the sender is deleted.  
2. When converted to refs using `toRefs(props)` and passed via `provideMessageContext`, the `sender` ref may be `null` or not available.  
3. The code `sender?.value.name` lacks null checks, causing a `TypeError` when `sender` or `sender.value` is `null`.  
Add `null` checks for the `sender` ref and provide a fallback value for `Dyte` integration.
Fixes https://linear.app/chatwoot/issue/CW-4031/typeerror-cannot-read-properties-of-null-reading-name
**Loom Video**
**Before** …
> fix: TypeError - Cannot read properties of null (reading 'name')

- .github/workflows/publish_ee_docker.yml
- Publish arm64 docker images for chatwoot ee edition
- Switch to Github actions for `docker` build/publish from docker hub due to lack of arm64 support
**Note: CE edition arm64 images are already available via https://github.com/chatwoot/chatwoot/pull/10789**
- Tested via github actions
Fixes
https://github.com/chatwoot/chatwoot/issues/9579
https://github.com/chatwoot/chatwoot/issues/7470
https://github.com/chatwoot/chatwoot/issues/5780
https://github.com/chatwoot/chatwoot/issues/5557
https://github.com/chatwoot/chatwoot/issues/2575
https://github.com/chatwoot/chatwoot/issues/6787
> feat: docker arm64 builds for ee edition

- .github/workflows/test_docker_build.yml
- Add GitHub action to test docker builds for internal/external PR's
- This PR builds the image on both amd64 and arm64 runners for every PR
- This also reduces the build time by 70% (50mins to 15mins)
> chore: add gh action to test docker builds against PRs

- app/javascript/dashboard/helper/scriptHelpers.js
Initialize the SDK along with the emitter registration to ensure accurate data reporting for analytics events.
> fix: Initialize SDK along with emitter registration

- app/controllers/dashboard_controller.rb
- spec/controllers/dashboard_controller_spec.rb
This is the error that is triggering a P0 incident in Chatwoot. 
```
DashboardController#index is missing a template for this request format and variant. request.formats: ["application/json"] request.variant: []
```
The user is calling `/app/accounts/api/v1/accounts/<account-id>/inboxes`. The URL is wrong, the requests are routed to dashboard controller as it starts with `/app/accounts`. The dashboard controller is not handling JSON requests and it creates errors. There are 312k errors over the last 2 years. Close to 50k during last 3 days.
This fix would return not_acceptable response to the attempts.
> fix: Handle JSON requests in DashboardController

- app/helpers/super_admin/account_features_helper.rb
- app/javascript/dashboard/components-next/sidebar/SidebarProfileMenu.vue
- app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
- app/javascript/dashboard/featureFlags.js
- app/views/fields/account_features_field/_form.html.erb
- app/views/fields/account_features_field/_show.html.erb
- config/features.yml
This PR introduces internal feature flags for testing purposes. These flags will not be displayed on regular instances to prevent customer confusion.
Additionally, a new feature flag, `contact_chatwoot_support_team`, has been added for Chatwoot Cloud. This flag disables contact support for third-party onboarded accounts, as support will be handled by the original affiliate team.
> chore: Add internal feature flags for Chatwoot Cloud

- app/views/layouts/portal.html.erb
Disable branding on help center as well if the feature is turned on the account.
> fix: Disable branding on help center if the feature is turned on

- app/javascript/dashboard/components-next/message/bubbles/Dyte.vue
The join meeting feature was broken in the dashboard because the message ID was missing in the meeting link. This PR fixes these issues.
> fix: Join Dyte meeting URL in dashboard

- app/javascript/dashboard/components-next/icon/Logo.vue
- app/javascript/dashboard/components-next/sidebar/Sidebar.vue
- public/brand-assets/logo_thumbnail.svg
1. Update `Logo.vue` to fetch the logo from globalConfig and fallback to SVG if required.
2. Update the default `public/brand-assets/logo_thumbnail.svg` to use the new colors.
https://github.com/user-attachments/assets/505a1d05-cd05-4b86-9fe7-c05334f09b25
> fix: logo and custom branding

- enterprise/app/jobs/captain/documents/crawl_job.rb
- handle empty FIRECRAWL_KEY in captain crawl job
> fix: handle empty FIRECRAWL_KEY in captain crawl job

- app/javascript/dashboard/routes/dashboard/settings/reports/ReportContainer.vue
Fixes https://linear.app/chatwoot/issue/CW-4064/convert-average-metric-tooltips-from-seconds-to-readable-time-format
Chart tooltip configuration was using outdated Chart.js structure, causing the time formatting function to not be applied correctly to tooltip values in time-based metrics.
Updated tooltip configuration to use correct Chart.js Vue 3 plugin structure
> fix: Convert seconds based metric tooltips to readable format

- app/javascript/dashboard/routes/dashboard/settings/reports/ReportContainer.vue
This PR fixes showing y-axis numeric labels in reports charts. It occurs after merging this PR. https://github.com/chatwoot/chatwoot/pull/10938
> fix: Reports chart by removing y-axis numeric labels

- config/locales/pt_BR.yml
[fix bug when send tranascription by mail pt_BR](https://github.com/chatwoot/chatwoot/commit/d6c2e5eaadf37c1d6e2d2c705e678e014a23021d) 
when we send a trascription by email has a bug that don't send e-mail
comparing  en.yml x pt_BR.yml I see a diference in  end fix a bug removing + after <reply
Fixes
- [ x ] Bug fix (non-breaking change which fixes an issue)
> fix: transcription email locales for pt_BR

- Gemfile
- Gemfile.lock
Fixes https://linear.app/chatwoot/issue/CW-4082/slackwebapierrorsinvalidarguments-invalid-arguments
Recent Slack file uploads are generating "invalid_arguments" [errors](https://chatwoot-p3.sentry.io/issues/6327909812/?referrer=Linear) in some channels. The issue occurs when using a single files_upload_v2 method with a #channel parameter. Version v2.5.2 fixes these issues The gem has been updated with a new version containing [fixes](https://github.com/slack-ruby/slack-ruby-client/blob/master/CHANGELOG.md#252-20250219).
> chore(deps): Bump slack-ruby-client from 2.5.1 to 2.5.2

- app/services/notification/email_notification_service.rb
- spec/services/notification/email_notification_service_spec.rb
- disable email notifications if the user hasn't confirmed the email yet, as there is potential chance for the emails to bounce
> chore: Disable email notifications for unconfirmed users

- app/javascript/dashboard/components/ChatList.vue
- app/javascript/dashboard/components/ConversationItem.vue
- app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
- app/javascript/dashboard/components/widgets/conversation/contextMenu/Index.vue
- app/javascript/dashboard/i18n/locale/en/conversation.json
The PR includes usability feedback fixes for the conversation card context menu. A "Mark as Read" option has been added after "Mark as Unread" to prevent misclicks due to shifting menu positions. Additionally, a separator line has been introduced for better grouping and clarity
**Fixes** https://linear.app/chatwoot/issue/CW-4088/usability-feedback
https://www.loom.com/share/59f8ad3bf4054b299bfcffc0ba24eca1?sid=98fbb67d-c3e9-4fa4-9b04-2a7cb3bf8568
> fix: Usability issues in conversation card context menu

- app/javascript/dashboard/components-next/Contacts/ContactsForm/ContactMergeForm.vue
- app/javascript/dashboard/components-next/combobox/ComboBox.vue
This PR fixes an issue with the `ComboBox` component, ensuring it correctly handles API search functionality and displays results instantly.
When using the `ComboBox` with API-based search (e.g., contact search), the component applied local filtering on top of the API-filtered results. This caused search results to disappear when they didn't contain the search term in their labels, even though they were correct matches from the API.
- Added a new `useApiResults` prop (default: `false`) to indicate when the ComboBox is being used with API-based search
- When `useApiResults` is `true` and a search is active, the component skips local filtering and shows all options received from the parent
Fixes https://linear.app/chatwoot/issue/CW-4083/contact-merge-search-dropdown-doesnt-display-results-in …
> fix: `ComboBox` filtering delay in contact merge search

- app/views/api/v1/models/_inbox_slim.json.jbuilder
https://github.com/chatwoot/chatwoot/pull/10888 introduced a bug in the conversation editor since we were using the templates , email and phone number payloads in contactable inboxes .  temporary fix for this, we need to rework this fix.
> chore: Fix issue with new conversation editor

- app/javascript/dashboard/components-next/button/Button.vue
Fixed an issue where hover styles were still applied to disabled buttons. Previously, `disabled:pointer-events-none` was used to prevent interactions, ensuring hover styles wouldn’t apply. However, this also removed showing the "not-allowed" cursor. This has been replaced with `hover:enabled` to ensure hover effects only apply when the button is enabled while preserving proper cursor behavior.
**Before**
https://github.com/user-attachments/assets/a5d33869-4d9d-499b-94c8-6371cbb44ecc
**After**
https://github.com/user-attachments/assets/a03d93dc-2374-4c76-8bed-8f1fe79593d2
**Case where `disabled:pointer-events-none` and `hover:enabled` are not added (for context only).**
https://github.com/user-attachments/assets/407320d8-f889-49d2-a78c-a5d24ed745a0
> fix: Show "not-allowed" cursor for disabled buttons

- app/javascript/dashboard/components/ChatList.vue
This PR fixes the issue where the saved `order_by` value for the conversation list is not being applied. The feature was originally added in PR https://github.com/chatwoot/chatwoot/pull/8237 but broke after merging the Vue 3 migration PR https://github.com/chatwoot/chatwoot/pull/10047
Fixes https://linear.app/chatwoot/issue/CW-4110/not-using-the-saved-sort-order-by-option-from-ui-settings
**Cause of the Issue:**  
The previous implementation checked `orderBy` against the keys of the sorting constants instead of their values. Since `orderBy` stores a sorting value, this caused the condition to fail, leading to fallback to the default sorting option.  
**Solution:**  
The fix ensures that `orderBy` is validated against the values of the sorting constants rather than the keys. This correctly …
> fix: Not using saved `order_by` when fetching conversation list

- Gemfile.lock
- app/jobs/inboxes/fetch_imap_email_inboxes_job.rb
- spec/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb
This PR disables the IMAP syncing if the account is suspended.
> fix: Disable syncing IMAP if the account is suspended

- lib/integrations/slack/send_on_slack_service.rb
- spec/lib/integrations/slack/send_on_slack_service_spec.rb
Fixes https://linear.app/chatwoot/issue/CW-4122/slackwebapierrorsmissingscope-missing-scope
This PR adds the ability to handle errors when scopes are missing during link unfurling. Since link unfurling is just a nice-to-have feature that doesn't affect core functionality, we will silently ignore these errors.
> chore: Rescue slack link unfurling errors.

- app/controllers/api/v1/accounts/conversations_controller.rb
- app/views/api/v1/accounts/conversations/attachments.json.jbuilder
There are attachments with over 1000 attachments (unusual) in production, and some of them timeout. This PR would limit the number of attachments to 100 (which is sufficient for viewing the files in the gallery, pagination on the UI can be added later).
> fix: Paginate attachments API

- app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
The Microsoft and Gmail channels don’t function with custom SMTP or IMAP configurations or forwarding option. Displaying the configuration tab creates confusion among users. 
This PR would eliminate the option for these channels.
> fix: Hide Configuration page for Microsoft & Gmail channels

- enterprise/app/services/enterprise/billing/handle_stripe_event_service.rb
Enable inbound_emails in paid accounts automatically
> fix: Add inbound_emails feature to the list of enabled features in paid account

- app/javascript/dashboard/composables/spec/useAgentsList.spec.js
- app/javascript/dashboard/composables/useAgentsList.js
- app/javascript/dashboard/helper/agentHelper.js
- app/javascript/dashboard/helper/specs/agentHelper.spec.js
- app/javascript/dashboard/i18n/locale/en/agentMgmt.json
This PR includes a translation update for the "None" option in the agent assignment multi-select dropdown.
Fixes https://linear.app/chatwoot/issue/CW-4140/none-option-in-assign-agent-multi-select-is-not-translated
**Test cases**
1. Check in conversation sidebar
2. Check in command bar
3. Check in participation dropdown
> fix: Translate "None" option in agent assignment dropdown

- app/javascript/dashboard/components-next/sidebar/Sidebar.vue
The string were not taking the correct locale as there were initialized during the component mount. This change would force the component to re-render the strings.
> fix: Force re-render route i18n string

- lib/custom_markdown_renderer.rb
- spec/lib/custom_markdown_renderer_spec.rb
This pull request includes changes to the `CustomMarkdownRenderer` class and its corresponding tests to support YouTube's "nocookie" [[ref](https://support.google.com/youtube/answer/171780?hl=en#zippy=%2Cturn-on-privacy-enhanced-mode)] URLs and adding the `dnt` param to Vimeo embed [[ref](https://help.vimeo.com/hc/en-us/articles/12426260232977-About-Player-parameters)].
> feat: use nocookie version of youtube & vimeo for help center embeds

- app/javascript/dashboard/components-next/message/bubbles/Email/Index.vue
The PR includes a fix for rendering Google Drive link attachments in email bubbles and update the colors.
**Cause**: The Google Drive attachment displays incorrectly in emails due to inherited `box-sizing: border-box` from parent styles, creating layout issues.
**Solution**: Added targeted CSS for '**gmail_drive_chip**' elements to reset to `box-sizing: initial` and ensure proper image display.
**Before**
**After**
> fix: Email rendering issue with Google Drive link

- app/jobs/webhooks/telegram_events_job.rb
- spec/jobs/webhooks/telegram_events_job_spec.rb
- add a warning logs when Chatwoot receives events for inactive channels
> chore: log events for inactive channels

- app/services/message_templates/hook_execution_service.rb
- spec/services/message_templates/hook_execution_service_spec.rb
At 5 PM, when business hours officially end, an automatic out-of-office message is sent to customers. However, this creates a poor experience if an agent is actively chatting with the customer. This update ensures that the out-of-office message is only sent if no agent message has been sent in the last 5 minutes. If the customer reaches out again after 5 minutes, the out-of-office message will be triggered.
> chore: Disable sending outgoing messages if the conversation is active

- app/controllers/twilio/callback_controller.rb
- app/controllers/twilio/delivery_status_controller.rb
- app/jobs/webhooks/twilio_delivery_status_job.rb
- app/jobs/webhooks/twilio_events_job.rb
- spec/controllers/twilio/callbacks_controller_spec.rb
- spec/controllers/twilio/delivery_status_controller_spec.rb
- spec/jobs/webhooks/twilio_delivery_status_job_spec.rb
- spec/jobs/webhooks/twilio_events_job_spec.rb
- Twilio events were being processed synchronously, leading to slow API responses.
- This change moves Twilio event processing to a background job to improve performance and align with how other events (e.g., WhatsApp) are handled.
> chore: Move Twilio event processing to background job

- app/controllers/public/api/v1/portals/articles_controller.rb
- app/javascript/widget/api/endPoints.js
- app/models/article.rb
- app/views/public/api/v1/portals/articles/index.json.jbuilder
- app/views/widget_tests/index.html.erb
- db/migrate/20250315202035_add_index_to_articles.rb
- db/schema.rb
- spec/controllers/public/api/v1/portals/articles_controller_spec.rb
The UI displays only six articles, and this update introduces a per_page parameter to control the number of articles returned per API call. The value is capped between 1 and 100, with a default fallback if a lower number is set.
This change is necessary due to high website traffic, where excessive payloads are returned without adding value.
**Changes:** 
- Add index to status, account_id, portal_id, views.
- Add per_page param in the API.
- Update the code in the frontend to fetch only 6
> chore: Limit the number of articles retrieved by widget

- app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
This PR fixes the issue where the custom attributes type list dropdown in the conversation sidebar gets hidden under the section.
**Before**
**After**
> fix: Dropdown for custom attributes in conversation sidebar hides under the list

- app/listeners/notification_listener.rb
- spec/listeners/notification_listener_spec.rb
The issue was that when a team change results in an assignee being set to nil, the system was still trying to create a notification about the assignment change, but there was no assignee to notify, causing potential issues in the notification system.
> chore: Ignore notification when assignee is nil

- app/javascript/dashboard/assets/scss/widgets/_base.scss
- app/javascript/dashboard/modules/search/components/SearchHeader.vue
This PR fixes styling inconsistencies by excluding specific more input types (range, color, image, hidden) from receiving the default text input styles.
**Before**
After
> fix: Audio player input styles

- app/javascript/dashboard/store/modules/conversationStats.js
This PR would reduce the API calls if there are more than 100 total conversations, we will throttle requests the number of requests.
Earlier this was 1000 total conversations.
> chore: Reduce meta conversation API calls

- app/builders/contact_inbox_builder.rb
- app/models/inbox.rb
- spec/builders/contact_inbox_builder_spec.rb
This PR addresses a race condition in the contact inbox model caused by duplicate `source_id` values linked to different contacts. 
The issue typically occurs when an agent updates a contact’s email or phone number or when two contacts are merged. In these scenarios, the `source_id`, which is intended to uniquely identify the contact in a session, may still be associated with the old contact inbox.
To solve this, we check if there’s already a ContactInbox with the same source_id but linked to another contact. If we find one, we update that old record by changing its source_id to a random value. This breaks the wrong connection and prevents issues, while still keeping the old data safe.
However, this is only a temporary fix. The main issue is with the way the contact inbox model is …
> fix: Fix duplicate contact inbox race condition

- app/builders/contact_inbox_builder.rb
- app/controllers/api/v1/accounts/contacts/contact_inboxes_controller.rb
- app/javascript/dashboard/components-next/NewConversation/helpers/composeConversationHelper.js
- app/javascript/dashboard/components-next/NewConversation/helpers/specs/composeConversationHelper.spec.js
- app/services/base/send_on_channel_service.rb
- app/services/contact_inbox/source_id_service.rb
- config/locales/en.yml
- spec/builders/contact_inbox_builder_spec.rb
- spec/services/contact_inbox/source_id_service_spec.rb
- spec/services/sms/send_on_sms_service_spec.rb
- spec/services/twilio/send_on_twilio_service_spec.rb
- spec/services/whatsapp/send_on_whatsapp_service_spec.rb
In this PR https://github.com/chatwoot/chatwoot/pull/11139, if there is an attempt to create a duplication session for the contact in the same inbox, we will anonymize the old session. 
This PR would prevent sending messages to the older sessions. The support agents will have to create a new conversation to continue messages with customer.
> fix: Do not allow sending messages if merged contact has a duplicate session

- app/javascript/dashboard/helper/ConversationMetaThrottleManager.js
- app/javascript/dashboard/helper/specs/ConversationMetaThrottleManager.spec.js
- app/javascript/dashboard/store/modules/conversationStats.js
- app/javascript/dashboard/store/modules/specs/conversationStats/helper.spec.js
- app/javascript/widget/assets/scss/woot.scss
This update improves the throttling mechanism for conversation meta requests to optimize server load and enhance performance. The changes implement differentiated thresholds based on account size - a 2-second throttle for small accounts (≤100 conversations) and a 10-second throttle for large accounts (>100 conversations). 
Fixes #11178
> fix: Update throttle for /meta endpoints, will call every 2s for small account, 10s for large accounts

- app/finders/conversation_finder.rb
- spec/finders/conversation_finder_spec.rb
Optimization #11183 missed a condition where the inbox_id filter is manually passed. Due to the previous change, the inbox filter was being discarded for admins, although it continued to work correctly for agents.
This PR includes a fix for that specific case and adds a spec to explicitly test it.
> fix: Apply filter for inbox when the user is an admin

- app/services/contacts/contactable_inboxes_service.rb
- app/services/whatsapp/send_on_whatsapp_service.rb
- spec/factories/channel/channel_whatsapp.rb
- spec/services/whatsapp/send_on_whatsapp_service_spec.rb
The expected payload on WhatsApp Cloud API is the following. 
```json
{ 
"template": {
"name": "TEMPLATE_NAME",
"language": {
"code": "LANGUAGE_AND_LOCALE_CODE"
},
"components": [
"<NAMED_PARAMETER_INPUT>",
"<POSITIONAL_PARAMETER_INPUT>"
]
}
}
```
Named templates expect a `parameter_name`
```json
{
"type": "body",
"parameters": [
{
"type": "text",
"parameter_name": "customer_name",
"text": "John"
},
{
"type": "text",
"parameter_name": "order_id",
"text": "9128312831"
}        
]
}
```
In this PR, we would check if the template is a name template, then we would send the `parameter_name` as well.
Reference: https://github.com/chatwoot/chatwoot/issues/10886
> fix: Add support for named parameter templates in WhatsApp

- app/javascript/dashboard/i18n/locale/en/macros.json
- app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
- app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
- app/models/macro.rb
- app/services/macros/execution_service.rb
- spec/services/macros/execution_service_spec.rb
Fixes https://github.com/chatwoot/chatwoot/issues/5968
We will not support custom payload in V1.
> feat: Add webhook event support for macros

- app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
- app/javascript/dashboard/components/widgets/WootWriter/FullEditor.vue
This PR fixes the button styling issue in the Prose Mirror URL prompt modal and updates the overall modal styles to align with the new design.
This issue occurs after merging this [PR](https://github.com/chatwoot/chatwoot/pull/11159): 
**Before**
**After**
https://www.loom.com/share/f5d59f2df4d94623b7c14336bd2090a9?sid=fb3c24f7-ec0d-4abf-8f4e-1c8baa08130b
> fix: styles in ProseMirror URL prompt modal

- .github/workflows/frontend-fe.yml
- .github/workflows/nightly_installer.yml
- .github/workflows/run_foss_spec.yml
- .github/workflows/size-limit.yml
In my previous PR I got some errors that when checking it is possible to conclude that the version of ubuntu 20.04 in the Github Actions images to run the tests is no longer supported.
Possible to check at this url: https://github.com/actions/runner-images/issues/11101
Changing the Ubuntu version in the image to run the tests.
Old version: 20.04
New version: 22.04
> fix: Updating the Ubuntu version to run the tests

- app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
- app/javascript/dashboard/components/widgets/conversation/TagAgents.vue
**Issue:** When typing "@" in reply mode and then switching to private note mode, the user mentions menu remains visible and cannot be dismissed.
**Cause:** The Prose Mirror suggestion plugin for "@" was active in both reply modes (normal and private). When triggered in normal reply mode and then switching to private note mode, the menu would remain open and couldn't be dismissed.
**Solution**
```
createSuggestionPlugin({
trigger: '@',
showMenu: showUserMentions,
searchTerm: mentionSearchKey,
isAllowed: () => props.isPrivate, // Only allow @ mentions in private note mode
}),
```
1. By setting `isAllowed: () => props.isPrivate`, the @ mention trigger will only activate when in private note mode
2. In normal reply mode, the plugin won't activate at all since `isAllowed` returns false
3. …
> fix: Prevent mentions menu from triggering on reply mode change

- app/javascript/dashboard/composables/useUISettings.js
Users who have not changed the order of the sidebar items were not able to change it as the object returned was created using Object.freeze
To reproduce: 
- Create a new user account, open a conversation, try changing the order of the sidebar items.
> fix: Return new Array instead of freezed object

- app/controllers/devise_overrides/omniauth_callbacks_controller.rb
- spec/controllers/devise/omniauth_callbacks_controller_spec.rb
- use stricter validation to restrict gmail signups
> fix: use stricter validation to restrict gmail signups

- app/views/layouts/portal.html.erb
- spec/controllers/public/api/v1/portals_controller_spec.rb
- Added favicon link to portal layout when logo is present
- Added tests to verify favicon behavior with and without logo
> feat: Use portal logo as favicon in helpcenter pages

- app/javascript/dashboard/components-next/copilot/CopilotAssistantMessage.vue
- app/javascript/dashboard/i18n/locale/en/integrations.json
This PR includes a fix to show an error message when an empty response is received from Captain.
Fixes https://linear.app/chatwoot/issue/CW-4245/empty-responses-from-captain
| Light Mode  | Dark Mode |
| ------------- | ------------- |
| <img width="381" alt="image" src="https://github.com/user-attachments/assets/3aa9ae4a-9253-456f-a28b-d3c35c8e8e81" />  | <img width="381" alt="image" src="https://github.com/user-attachments/assets/8c7e4b87-9f85-43c9-bc5a-4c38e5ae37f7" />  |
> fix: Display error message on empty response from Captain

- app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
This PR resolves a Chrome-specific rendering bug where emojis in the `<textarea>` of the reply box display a shadow or different color tone when placed at the start of the input without a leading space.
**Solution:** Removed the border-radius from the textarea in the Reply box component, which resolves the rendering issue in Chrome
**Cause:** This appears to be a Chrome rendering bug related to how border-radius is handled on form elements, especially with emojis. The exact cause is unclear, but there is some known issue
[Chromium Issue 40333458](https://issues.chromium.org/issues/40333458)
[Related Chromium Duplicates](https://issues.chromium.org/issues/40333458/dupes)
**Before**
https://github.com/user-attachments/assets/618de129-5631-4c7c-ab0b-7188b83c6bf1
**After** …
> fix: Emoji rendering issue with `<textarea/>` in chrome

- app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
- app/javascript/dashboard/store/modules/inboxes.js
- app/javascript/dashboard/store/modules/specs/inboxes/fixtures.js
- app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js
We have added warnings for existing Instagram messenger inboxes via https://github.com/chatwoot/chatwoot/pull/11303. There is an issue with finding the correct Instagram/messenger inbox. This PR will fixes that issue.
> fix:  Old Instagram inbox warnings

- app/javascript/dashboard/components-next/sidebar/Sidebar.vue
- config/features.yml
- deprecated report_v4 feature flag
- remove the gating logic so new reports is available by default
- make search_with_gin an internal feature flag
> chore: deprecate report_v4 feature flag and remove gating logic

- db/migrate/20250416182131_flip_chatwoot_v4_default_feature_flag_installation_config.rb
- db/schema.rb
- Updates ACCOUNT_LEVEL_FEATURE_DEFAULTS installation config to enable chatwoot_v4
- Enables chatwoot_v4 for all existing accounts in batches of 100
- Clears GlobalConfig cache after update
> chore: Enable chatwoot_v4 feature flag by default for accounts

- app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
We have added warnings for existing Instagram messenger inboxes via https://github.com/chatwoot/chatwoot/pull/11303. However, an issue arose where warnings were incorrectly displaying for messenger conversations. This PR resolves that issue.
> chore: Disable warnings old instagram inbox for messenger conversations

- app/javascript/sdk/sdk.js
This PR resolves the issue where the focus outline for the standard bubble type appears as a square in Safari, while it appears circular in Chrome.
Fixes [CW-4252](https://linear.app/chatwoot/issue/CW-4252/v41-circle-around-campaign-pop-up-warped), https://github.com/chatwoot/chatwoot/issues/11327
**Cause**
In Chrome, the focus outline for the standard bubble type is circular, but in Safari, it appears square. This is due to a 20px margin on the SVG inside the bubble.
**Solution**
The `20px` margin was removed from the SVG, fixing the focus outline to appear circular in Safari browser.
https://www.loom.com/share/cc4244f369f84b98afaef539b79abcfe?sid=e957df16-1a53-4349-8bdc-705b2ed82d45
**Before** 
https://www.loom.com/share/e858417722c64df6801ea87e4b89779f?sid=81a0acec-c5f0-4daa-832c-1f2328 …
> fix: Inconsistent widget bubble focus outline shape

- app/javascript/dashboard/helper/portalHelper.js
- app/javascript/dashboard/helper/specs/portalHelper.spec.js
We have added custom domain support to article URLs when a custom domain exists for the portal via https://github.com/chatwoot/chatwoot/pull/11349. However, we missed adding `hc` after the domain. This PR will fix that issue.
> fix: Add missing 'hc' path segment after custom domain in article URLs

- app/javascript/dashboard/components-next/HelpCenter/Pages/PortalSettingsPage/PortalBaseSettings.vue
- app/javascript/dashboard/components-next/HelpCenter/PortalSwitcher/CreatePortalDialog.vue
- app/javascript/dashboard/i18n/locale/en/helpCenter.json
- app/javascript/shared/helpers/Validators.js
- app/javascript/shared/helpers/specs/ValidatorsHelper.spec.js
This PR fixes an issue with slug validation in the Help Center portal settings. Previously, users were able to create or update slugs with invalid characters such as spaces, slashes, and special symbols, which cause help center to crash.
With this update, slug creation and updates are now properly validated. Only slugs that match the allowed pattern will be accepted. No spaces, underscores, slashes, or special characters are allowed.
Examples: **user**, **user-guide**
---
Fixes https://linear.app/chatwoot/issue/CW-4273/add-validation-for-help-centre-slugs
https://www.loom.com/share/a2ca5e2104984f28b29539293ffed33a?sid=e5064cb8-6220-4c43-99da-242c25d32027
> fix: Handle slug validation errors in Help Center

- app/services/crm/leadsquared/setup_service.rb
The response from the LeadSquared API for the activity ID when searching is a number, however, when creating it, it's a string. This was causing the the validations to break
> feat: use numbers when fetching from the API

- app/controllers/api/v1/accounts/conversations/messages_controller.rb
- app/jobs/conversations/update_message_status_job.rb
- app/services/facebook/send_on_facebook_service.rb
- app/services/instagram/base_send_service.rb
- app/services/line/send_on_line_service.rb
- app/services/messages/status_update_service.rb
- app/services/twilio/send_on_twilio_service.rb
- app/views/api/v1/accounts/conversations/messages/update.json.jbuilder
- app/workers/email_reply_worker.rb
- config/routes.rb
- lib/webhooks/trigger.rb
- spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
- spec/services/messages/status_update_service_spec.rb
- Added an api endpoint for update message status ( available only for api inboxes )
- Moved message status management to a service. 
- Handles case where read status arrive before delivered 
fixes: #10314 , #9962
> feat: API Endpoints to update message status

- app/controllers/api/v1/widget/campaigns_controller.rb
- spec/controllers/api/v1/widget/campaigns_controller_spec.rb
If the feature is disabled (manually or due to plan changes), the customer cannot disable the existing campaigns. This PR would fix that. 
Fixes https://linear.app/chatwoot/issue/CW-3691/fix-disable-campaigns-on-plan-downgrade
> fix: Show campaigns only if the feature is enabled

- app/services/instagram/message_text.rb
Fixes https://chatwoot-p3.sentry.io/issues/6557025930?project=6382945
> fix: Undefined local variable or method `error` for an instance of Instagram MessageText 

- app/javascript/entrypoints/sdk.js
- app/javascript/sdk/DOMHelpers.js
- app/javascript/sdk/IFrameHelper.js
- app/javascript/sdk/bubbleHelpers.js
Rails Turbo has two ways of rendering a page, `replace` and `morph`. Navigations typically happen with replace, however refreshes (say after submitting a form) happens with morphs, where Turbo will use a HTML diffing/morphing lib to morph the elements (basically surgically replace what is required, to provide a good UX) 
Since Chatwoot widget is rendered in JS, the morphing function has no context of it's existence. We solve this with two things
1. Add `data-turbo-permanent` to the elements that the widget renders. This will ensure that the element is preserved
2. Break out of the `restoreWidgetInDOM` logic when the rendering method is morphing
3. Remove the `window.Turbo` check, it may or may not always be present correctly.
Fixes: https://github.com/chatwoot/chatwoot/issues/11219
> feat: handle rails turbo morphing

- config/schedule.yml
- config/sidekiq.yml
- move stale contacts job to `housekeeping` queue below `low`
> chore: move stalecontacts job to different sidekiq queue

- app/javascript/dashboard/i18n/locale/en/generalSettings.json
- app/javascript/dashboard/routes/dashboard/settings/account/components/AutoResolve.vue
This PR addresses a few issues with the auto-resolve UX
1. The inputs were disabled unless the user clicked on the toggle. This was not clear to users, this PR enables it by default. Once updated, the toggle automatically switches
2. Update copy for the help text
https://github.com/user-attachments/assets/4916b712-2dd0-4ae5-ba51-5488ba920ba8
> fix(ux): don't disable input for auto resolve

- app/jobs/internal/remove_stale_contact_inboxes_job.rb
- app/jobs/internal/remove_stale_contacts_job.rb
- spec/jobs/internal/process_stale_contacts_job_spec.rb
- spec/jobs/internal/remove_stale_contacts_job_spec.rb
- Use the housekeeping queue for the `remove_stale_contacts` job
- fix specs
> chore: use housekeeping queue for remove_stale_contacts job

- app/controllers/api/v1/accounts_controller.rb
- app/javascript/dashboard/i18n/locale/en/generalSettings.json
- app/javascript/dashboard/routes/dashboard/settings/account/components/AutoResolve.vue
- app/javascript/dashboard/routes/dashboard/settings/account/components/SectionLayout.vue
- app/javascript/v3/components/Form/WithLabel.vue
- app/jobs/conversations/resolution_job.rb
- app/models/account.rb
- app/models/conversation.rb
- spec/controllers/api/v1/accounts_controller_spec.rb
- spec/jobs/conversations/resolution_job_spec.rb
1. Revert to the previous behaviour of auto-resolving all conversations
2. Add an option that allows users to ignore conversations that are waiting for a response. 
3. Fix issue where auto resolve duration input would just enter `10` since that was the lowest value, replaced it with a validation instead
4. Fix copy for the alerts and help texts
> feat: allow auto resolve waiting option

- app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
**Cause:**
The issue was caused by the use of `overflow-auto` on the General Settings section.
**Fix:**
Removed `overflow-auto` from the General Settings section. It was not needed, as it was not applied to the entire page and did not serve a functional purpose in this context.
Fixes https://linear.app/chatwoot/issue/CW-4316/broken-borders-in-dark-mode-new-settings-page
**Before**
https://github.com/user-attachments/assets/1d88aa01-62a4-4e0e-bfd2-33d792c26c0f
**After**
https://github.com/user-attachments/assets/79639828-d830-4662-8d4a-2ce5b99c39b6
> fix: Broken outline in account settings page

- app/javascript/dashboard/i18n/locale/en/integrations.json
- app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookForm.vue
- app/listeners/webhook_listener.rb
- app/models/webhook.rb
- config/initializers/rack_attack.rb
- spec/listeners/webhook_listener_spec.rb
Added support for typing events in webhooks. Two new events are now available: `conversation_typing_on` and `conversation_typing_off`.
> feat: Add support for typing events in webhooks

- app/jobs/internal/process_stale_contacts_job.rb
- spec/jobs/internal/process_stale_contacts_job_spec.rb
- throttle stale contacts job
- process 20% accounts every day
- reduce batch size from 100 to 20
- add delay between jobs
> fix: throttle stalecontacts job

- app/controllers/concerns/access_token_auth_helper.rb
- spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Previously, agent bots weren’t allowed to edit custom attributes in conversations. But with AI, it’s now more feasible to return accurate and useful attributes. Since there’s no strong reason to block this, this PR enables bots to update custom attributes.
Fixes https://github.com/chatwoot/chatwoot/issues/11378
> feat: Allow agent bots to update custom attributes in accessible conversations

- app/controllers/api/v1/accounts/custom_filters_controller.rb
The custom filters API previously required a filter_type attribute, even when accessing a resource by its ID, which isn’t necessary. This PR removes that condition.
Fixes https://github.com/chatwoot/chatwoot/issues/11384
> fix: Allow resource access without filter type in custom_filters API

- docker-compose.production.yaml
https://github.com/chatwoot/chatwoot/issues/11341
This PR updates docker-compose.production.yaml to simplify volume management and eliminate host-path mounts that were causing permission and startup errors. 
1. Removed any preexisting Chatwoot containers and volumes
2. Brought up the development stack
3. Ran database preparation successfully without manual directory creation
> fix: add named volumes for storage, postgres, and redis

- app/javascript/dashboard/components/ChatList.vue
This PR uses `useScrollLock` from `VueUse` to lock scrolling on the chat list panel when the context menu is open.
https://www.loom.com/share/68a25af2c1b149f8bd06bdbaafb4d82d?sid=0984fde6-ade2-405a-afc9-6d8f99480874
> feat: Scroll lock on chat list context menu

- app/javascript/dashboard/store/modules/conversations/index.js
Fixes [CW-4330](https://linear.app/chatwoot/issue/CW-4330/bug-attachments-in-gallery-view-gets-duplicated-when-you-navigate-back)
**Cause**
When navigating back to a previously viewed conversation, attachments were being duplicated in the Gallery View. This occurred because the `SET_ALL_ATTACHMENTS` mutation was appending new attachments to existing ones `(attachments.push(...data))` instead of replacing them. Each time a user returned to a conversation, the attachment list would grow, showing duplicate images.
**Solution**
Updated the `SET_ALL_ATTACHMENTS` mutation to replace the entire attachments array instead of appending to it. This change ensures attachments are cleared before adding new ones when returning to a previously viewed conversation, preventing duplicates. …
> fix: Duplicate attachments when navigating back to a conversation

- app/services/instagram/message_text.rb
**Issue**
When attempting to send a message to Instagram users who have never previously messaged the connected Instagram account, we encounter a "User consent is required to access user profile" error⁠
⁠
**Fix**
This PR implements proper error handling for cases where user consent is required. We can only access a user's profile after they have initiated contact with the Instagram account⁠
> fix: Handle Instagram user consent error for first-time message recipients

- app/models/article.rb
- app/models/concerns/llm_formattable.rb
- app/services/llm_formatter/article_llm_formatter.rb
- app/services/llm_formatter/contact_llm_formatter.rb
- app/services/llm_formatter/conversation_llm_formatter.rb
- app/services/llm_formatter/default_llm_formatter.rb
- app/services/llm_formatter/llm_text_formatter_service.rb
- spec/models/article_spec.rb
- spec/services/llm_formatter/article_llm_formatter_spec.rb
- spec/services/llm_formatter/contact_llm_formatter_spec.rb
- spec/services/llm_formatter/conversation_llm_formatter_spec.rb
This PR introduces support for optionally exposing more data during LLM function calls. This will be useful as we expand Copilot’s capabilities.
Changes included:
- Add support for ArticleLlmFormatter
- Add missing specs for ContactLLMFormatter and ArticleLLMFormatter
- Add additional spec for ConversationLLMFormatter based on config
> chore: Update LLM formatter classes to include additional details

- app/controllers/api/v1/accounts/inboxes_controller.rb
- app/javascript/dashboard/components-next/filter/inputs/FilterSelect.vue
- app/javascript/dashboard/components-next/message/bubbles/CSAT.vue
- app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
- app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/CustomerSatisfactionPage.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/components/CSATDisplayTypeSelector.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/components/CSATEmojiInput.vue
- app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/components/CSATStarInput.vue
- app/javascript/shared/components/CustomerSatisfaction.vue
- app/javascript/shared/components/StarRating.vue
- app/javascript/shared/constants/messages.js
- app/javascript/survey/App.vue
- app/javascript/survey/assets/scss/woot.scss
- app/javascript/survey/components/Banner.vue
- app/javascript/survey/components/Feedback.vue
- app/javascript/survey/views/Response.vue
- app/javascript/widget/components/AgentMessageBubble.vue
- app/models/inbox.rb
- app/services/message_templates/template/csat_survey.rb
- app/views/api/v1/models/_inbox.json.jbuilder
- app/views/public/api/v1/models/_csat_survey.json.jbuilder
- db/migrate/20250514045638_add_csat_config_to_inboxes.rb
- db/schema.rb
- spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
- spec/services/message_templates/template/csat_survey_spec.rb
This PR introduces basic customization options for the CSAT survey:
* **Display Type**: Option to use star ratings instead of emojis.
* **Message Text**: Customize the survey message (up to 200 characters).
* **Survey Rules**: Send surveys based on labels — trigger when a conversation has or doesn't have a specific label.
Fixes https://linear.app/chatwoot/document/improve-csat-responses-a61cf30e054e
**Website Channel (Widget)**
https://www.loom.com/share/7f47836cde7940ae9d17b7997d060a18?sid=aad2ad0a-140a-4a09-8829-e01fa2e102c5
**Email Channel (Survey link)**
https://www.loom.com/share/e92f4c4c0f73417ba300a25885e093ce?sid=4bb006f0-1c2a-4352-a232-8bf684e3d757
> feat: Improve CSAT responses

- app/javascript/dashboard/components-next/dropdown-menu/DropdownMenu.vue
- app/javascript/dashboard/components-next/phonenumberinput/PhoneNumberInput.vue
This PR fixes an issue where toggling the country dropdown unintentionally triggered form submission, resulting in a false contact creation success message.
**Cause:**
The toggle button was missing type="button", so it defaulted to type="submit" inside a form.
**Solution:**
Explicitly set the dropdown toggle button’s type to "button" to prevent accidental form submission.
Fixes https://github.com/orgs/chatwoot/discussions/11326#discussioncomment-12950015
**Before**
https://www.loom.com/share/e554fdd7fa144beda18003ac2ee9dfbb?sid=8e753e2c-10cf-41c6-bac6-a5b65b885db6
**After**
https://www.loom.com/share/16560d22238240fea526cb9c4b14b8b4?sid=fa601780-9b06-4fbb-b1e4-907b7d584328
> fix: Accidental contact creation on country dropdown toggle

- app/javascript/dashboard/components-next/HelpCenter/Pages/CategoryPage/CategoryForm.vue
This PR fixes an issue where updating the icon for a category didn’t work while editing. This happened because the edit dialog is wrapped in a form, and the icon button (missing `type="button"`) triggered a form submission instead of opening the icon picker.
**Solution:**
Set the icon button’s `type` to `"button"` to prevent unintended form submission.
Fixes https://linear.app/chatwoot/issue/CW-4350/updating-an-icon-for-the-category-is-not-working
> fix: Category icon update not working when editing

- app/models/concerns/activity_message_handler.rb
- config/locales/en.yml
- enterprise/app/jobs/captain/inbox_pending_conversations_resolution_job.rb
- spec/enterprise/jobs/captain/inbox_pending_conversations_resolution_job_spec.rb
Currently, when Captain resolves a conversation, the same activity message used for auto-resolution is shown. This has caused confusion for users.
With this change, a distinct activity message will be displayed specifically for resolutions performed by Captain, improving clarity.
Fixes https://linear.app/chatwoot/issue/CW-4289/incorrect-activity-message-for-conversations-resolved-by-captain-auto#comment-d2991763
> chore: Add activity message for conversation resolutions by Captain

- app/javascript/dashboard/components-next/filter/inputs/FilterSelect.vue
This PR fixes a UI bug where the "Select Label" dropdown in the CSAT survey rule overflowed off the screen. The dropdown now stays within the visible bounds.
https://www.loom.com/share/6a26ba5524de4fcdb2f209a6ec215ba6?sid=7cf1c84c-b167-4237-9571-00af56f7da18
> fix: CSAT select label dropdown overflow issue

- app/models/concerns/activity_message_handler.rb
- enterprise/app/models/enterprise/activity_message_handler.rb
- Fix the CE build errors due to captain activity message generation in CE code. hence moving this to EE
> chore: Move Captain activity messages to EE

- app/javascript/dashboard/components/widgets/conversation/ConversationBasicFilter.vue
This PR fixes the translation inconsistency in the `<ConversationBasicFilter />` component, where dropdown options would revert to English after page reload.
**Cause:**
The component used static arrays for chat status and sort options, with translations initialized only once. After a reload, it showed system language (English) until the user's locale was fully loaded.
**Solution:**
Replaced static arrays with computed properties to make translations reactive. This ensures the options automatically update when the locale changes.
**Before**
https://www.loom.com/share/eeac97c59b21480b95ef74813d3d7fa9?sid=0481994a-8d35-4c44-87d0-c6c5a77a54fd
**After**
https://www.loom.com/share/c1bdfbdb19ca4e37bda373f0fe12527a?sid=cb5b1d19-272b-48cb-967c-9a82c2a2b028
> fix: Translation issue in conversation filter on reload

- enterprise/app/helpers/captain/chat_helper.rb
- enterprise/app/services/captain/copilot/chat_service.rb
- enterprise/app/services/captain/llm/assistant_chat_service.rb
- enterprise/app/services/captain/tool_registry_service.rb
- enterprise/app/services/captain/tools/base_service.rb
- enterprise/app/services/captain/tools/search_documentation_service.rb
- spec/enterprise/services/captain/tool_registry_service_spec.rb
- spec/enterprise/services/captain/tools/search_documentation_service_spec.rb
This PR introduces the concept of a tool registry. The implementation is straightforward: you can define a tool by creating a class with a function name. The function name gets registered in the registry and can be referenced during LLM calls. When the LLM invokes a tool using the registered name, the registry locates and executes the appropriate tool. If the LLM calls an unregistered tool, the registry returns an error indicating that the tool is not defined.
> feat: Introduce the concept of tool registry within Captain

- app/controllers/api/v1/accounts/integrations/linear_controller.rb
- lib/linear.rb
- spec/controllers/api/v1/accounts/integrations/linear_controller_spec.rb
- spec/lib/integrations/linear/processor_service_spec.rb
This PR fixes status selection not being applied when creating a Linear ticket from the UI.
Fixes [CW-4376](https://linear.app/chatwoot/issue/CW-4376/linear-integration-when-i-create-a-ticket-with-a-status-the-status-is)
**Cause:**
The `state_id` parameter was not included in the list of permitted parameters in the controller, so the selected status was ignored during issue creation.
**Solution:**
* Added `state_id` to the `permitted_params` in `linear_controller.rb`.
* Mapped `state_id` in the `create_issue` method in `linear.rb`.
https://www.loom.com/share/291077f13a3c4baca78ef53e428d894e?sid=47911490-6156-479d-a96e-336ff9c0e262
> fix: Status not updating when creating a Linear issue

- app/models/message.rb
- spec/models/message_spec.rb
We made so many improvements for CSAT via https://github.com/chatwoot/chatwoot/pull/11485. However, we missed showing message content in the dashboard for CSAT URLs created in non-widget inboxes. This PR fixes the issue by ensuring that CSAT-configured messages are passed along with CSAT responses, otherwise defaulting to the translation.
> fix: Display message content for CSAT messages in non-widget inboxes

- app/javascript/dashboard/components-next/copilot/CopilotHeader.story.vue
- app/javascript/dashboard/components-next/copilot/CopilotHeader.vue
- app/javascript/dashboard/components-next/copilot/CopilotInput.vue
- app/javascript/dashboard/components-next/copilot/CopilotThinkingBlock.vue
- app/javascript/dashboard/components-next/copilot/CopilotThinkingGroup.story.vue
- app/javascript/dashboard/components-next/copilot/CopilotThinkingGroup.vue
- app/javascript/dashboard/i18n/locale/en/integrations.json
This PR adds the components for new Copilot UI
- Added a Header component
- Added a thinking block.
- Update the outline on copilot input
> feat: Add components to show steps in the copilot thinking process

- app/services/twilio/incoming_message_service.rb
This PR addresses an issue where users were unable to view images sent via WhatsApp on Chatwoot due to incorrect Twilio authentication configuration. https://app.chatwoot.com/app/accounts/1/conversations/50824
The problem stemmed from how authentication was being handled for Twilio API requests. The user had configured their inbox using api_key_sid, but the backend logic used only auth_token, leading to failed authentication. Further investigation showed that some customers might input api_secret into the auth_token field unintentionally.
- Tested on console with Client(api_key_sid, auth_token, account_sid) and validated successful authentication for the customer (Twilio channel ID: 2702).
- Simulated toggling the “Use API Key Authentication” checkbox to ensure backend behavior matches UI …
> fix: Twilio authentication handling for WhatsApp attachments 

- app/listeners/action_cable_listener.rb
- config/routes.rb
- db/migrate/20250523024825_remove_uuid_from_copilot_threads.rb
- db/migrate/20250523024826_remove_user_id_from_copilot_messages.rb
- db/migrate/20250523031839_change_message_type_to_integer_in_copilot_messages.rb
- db/schema.rb
- enterprise/app/controllers/api/v1/accounts/captain/copilot_messages_controller.rb
- enterprise/app/controllers/api/v1/accounts/captain/copilot_threads_controller.rb
- enterprise/app/listeners/captain_listener.rb
- enterprise/app/listeners/enterprise/action_cable_listener.rb
- enterprise/app/models/captain/assistant.rb
- enterprise/app/models/copilot_message.rb
- enterprise/app/models/copilot_thread.rb
- enterprise/app/views/api/v1/accounts/captain/copilot_messages/create.json.jbuilder
- enterprise/app/views/api/v1/accounts/captain/copilot_messages/index.json.jbuilder
- enterprise/app/views/api/v1/accounts/captain/copilot_threads/create.json.jbuilder
- enterprise/app/views/api/v1/accounts/captain/copilot_threads/index.json.jbuilder
- enterprise/app/views/api/v1/models/captain/_copilot_message.json.jbuilder
- enterprise/app/views/api/v1/models/captain/_copilot_thread.json.jbuilder
- enterprise/listeners/captain_listener.rb
- lib/events/types.rb
- spec/enterprise/controllers/api/v1/accounts/captain/copilot_messages_controller_spec.rb
- spec/enterprise/controllers/api/v1/accounts/captain/copilot_threads_controller_spec.rb
- spec/enterprise/listeners/action_cable_listener_spec.rb
- spec/enterprise/listeners/captain_listener_spec.rb
- spec/enterprise/models/copilot_message_spec.rb
- spec/enterprise/models/copilot_thread_spec.rb
- spec/factories/captain/copilot_message.rb
- spec/factories/captain/copilot_thread.rb
- spec/listeners/action_cable_listener_spec.rb
- Add API support for creating a thread
- Add API support for creating a message
- Remove uuid from thread (no longer required, we will use existing websocket connection to send messages)
- Update message_type to a column (user, assistant, assistant_thinking)
> feat: Add support for realtime-events in copilot-threads and copilot-messages

- enterprise/app/controllers/api/v1/accounts/captain/copilot_messages_controller.rb
- enterprise/app/controllers/api/v1/accounts/captain/copilot_threads_controller.rb
- enterprise/app/helpers/captain/chat_helper.rb
- enterprise/app/jobs/captain/copilot/response_job.rb
- enterprise/app/models/copilot_message.rb
- enterprise/app/services/captain/copilot/chat_service.rb
- enterprise/app/services/captain/tools/copilot/search_linear_issues_service.rb
- spec/enterprise/controllers/api/v1/accounts/captain/copilot_messages_controller_spec.rb
- spec/enterprise/controllers/api/v1/accounts/captain/copilot_threads_controller_spec.rb
- spec/enterprise/jobs/captain/copilot/response_job_spec.rb
- spec/enterprise/models/copilot_message_spec.rb
- spec/enterprise/services/captain/copilot/chat_service_spec.rb
- spec/enterprise/services/captain/tools/copilot/search_articles_service_spec.rb
- spec/enterprise/services/captain/tools/copilot/search_linear_issues_service_spec.rb
- spec/factories/articles.rb
- spec/factories/categories.rb
- Enable jobs by default when a copilot thread or a message is created.
- Rename thread_id to copilot_thread_id to keep it consistent with the model name
- Add a spec for search_linear_issues service
> fix: Update specs, add background response job implementation for copilot threads

- app/javascript/dashboard/api/captain/copilotMessages.js
- app/javascript/dashboard/api/captain/copilotThreads.js
- app/javascript/dashboard/helper/actionCable.js
- app/javascript/dashboard/helper/specs/actionCable.spec.js
- app/javascript/dashboard/store/captain/copilotMessages.js
- app/javascript/dashboard/store/captain/copilotThreads.js
- app/javascript/dashboard/store/captain/storeFactory.js
- app/javascript/dashboard/store/captain/storeFactory.spec.js
- app/javascript/dashboard/store/captain/storeFactoryHelper.js
- app/javascript/dashboard/store/index.js
- Set up stores for copilotThreads and copilotMessages.
- Add support for upsert messages to the copilotMessages store on receiving ActionCable events.
- Implement support for the upsert option.
> feat: Add stores for copilotMessages and copilotThreads

- app/services/crm/leadsquared/mappers/conversation_mapper.rb
- app/services/crm/leadsquared/processor_service.rb
- app/services/crm/leadsquared/setup_service.rb
- config/integration/apps.yml
- spec/services/crm/leadsquared/mappers/conversation_mapper_spec.rb
- spec/services/crm/leadsquared/processor_service_spec.rb
- spec/services/crm/leadsquared/setup_service_spec.rb
This pull request introduces timezone support for Leadsquared CRM integration, ensuring that all timestamps in conversation and transcript activities are formatted according to the timezone specified in the integration settings. The changes also include updates to the setup process to fetch and store the timezone from the Leadsquared API and corresponding test coverage improvements. The conversation mapper now accepts a hook parameter to access timezone settings, with fallback to system timezone when not configured.
> Note that the UI time is in IST, since I'm viewing this from India
- Add timezone support to LeadSquared CRM integration for accurate time formatting
- Update conversation and transcript activity mappers to use hook-specific timezone settings
- API Integration: Fetch …
> feat: save timezone from leadsquared API

- app/javascript/portal/portalHelpers.js
- app/javascript/portal/specs/portal.spec.js
This PR fixes an issue where external article links in the widget, including those in nested cases, were not opening in a new tab.
Fixes [CW-4409](https://linear.app/chatwoot/issue/CW-4409/links-are-not-working-properly-in-widget)
https://www.loom.com/share/518773f2a8ad42439a99a885249c3575?sid=bd68ee07-36a4-42f8-8cc9-632ff6b1a8f5
> fix: External links in widget not opening in new tab

- app/javascript/dashboard/components/Snackbar.vue
- app/javascript/dashboard/components/SnackbarContainer.vue
Snackbar notifications were not visible when a modal dialog was open. This happened because native `<dialog>` elements rendered with `showModal()` are placed in the browser’s **top layer**, above all normal z-index values, even `z-index: 9999`. As a result, snackbars appeared behind the dialog’s backdrop.
Used the **[Popover API](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/popover#manual)** to render snackbars in the top layer, ensuring they appear above modal dialogs.
* Added `popover="manual"` to the snackbar container.
* Used `showPopover()` to move the element to the top layer.
* Hides and re-shows the popover on new messages.
* Update the component to Composition API
https://www.loom.com/share/9e51d1aa0f4a4739a0585b7a0983077a?sid=eaafb0fa-88c7-45e7-b1 …
> fix: Snackbar notifications hidden behind modal dialogs

- app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue
The CSAT table was retaining links from the previous conversation even after the underlying data changed. This seems to be related to how TanStack Table renders the components. As a temporary fix, I’ve added a key prop to force a re-render.
> fix: Force re-render the CSAT component when data changes

- app/javascript/dashboard/routes/dashboard/settings/reports/components/ConversationCell.vue
- app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue
Follow-up fix to: https://github.com/chatwoot/chatwoot/pull/11643
The issue is the following. 
- Open CSAT reports.
- Click on the conversation links (it works fine)
- Apply a user filter (and probably a rating filter), just make sure that you have a new data than previous, any filter would do
- Click on the link, it would redirect to a different link. (if you observe, it is redirecting to the previous conversation data)
Note that the conversation link shown on the UI is different than the one which it is redirected to.
https://github.com/user-attachments/assets/96ae79f3-fd42-4293-b8d4-f886f48e7868
> fix: route params not reacting to changes

- app/javascript/dashboard/components-next/copilot/CopilotEmptyState.vue
This PR fixes an issue where the copilot displayed irrelevant prompts on the Contacts and Article pages.
Previously, conversation-specific prompts like "Summarize", "Suggest answer", and "Rate the conversation" were shown even outside conversations. With this update, users navigating to the Contacts or Articles routes will now see appropriate dashboard prompts such as "High priority conversation" and "List contacts".
**Contacts Page**
**Articles page**
> fix: Show default dashboard prompt for contact and articles

- app/javascript/dashboard/store/modules/conversations/helpers/filterHelpers.js
- app/javascript/dashboard/store/modules/conversations/helpers/specs/filterHelpers.spec.js
- package.json
- pnpm-lock.yaml
The `matchesFilter` is a utility that checks the incoming payload against a filter and returns `true` or `false`. 
For the `greater_than` and `less_than` filter specifically, the date parsing would fail when the timestamp was a 10 digit number. 
This PR solves this by adding a `coerceToDate` method that tries to parse the given value to a Date object as correctly as possible before comparing. 
Ref: https://github.com/chatwoot/utils/pull/53
> fix: incorrect date parsing in `matchesFilter`

- app/controllers/dashboard_controller.rb
- spec/controllers/dashboard_controller_spec.rb
Users get confused between app routes and API routes. Instead of hitting /api, they append /app in the API call, which ends up calling the dashboard controller and throws an error. To fix this, we added a check to throw a 406 Not Acceptable for non-HTML requests. But Meta requires Accept: \*/\* to return 200 for the integration to be accepted.
This change will only throw an error for JSON requests.
Fixes #11697
Fixes https://github.com/chatwoot/chatwoot/issues/11251
Fixes https://github.com/chatwoot/chatwoot/issues/11205
> fix: Avoid throwing 406 for non-json requests

- app/javascript/dashboard/components/ChatList.vue
This PR fixes an issue where the conversation count in the header for filters and folders flickers when loading more conversations.
**Before**
https://www.loom.com/share/cf6817c4e9604c28a74ebb2ebb631467?sid=2be7d351-32a9-49dc-99d2-b04fbda16cb5
**After**
https://www.loom.com/share/17d853a8a3014be684b796eb0a98558b?sid=ee72eeab-8c68-409f-834f-22850971923d
> fix: Prevent count flicker on loading more conversations

- app/views/public/api/v1/portals/_header.html.erb
- app/views/public/api/v1/portals/_hero.html.erb
- app/views/public/api/v1/portals/_mobile_menu.html.erb
This PR fixes an issue where the divider line was shown even when the locale section was not visible.
**Before**
**After**
> chore: Display divider only when multiple portals are available

- app/javascript/dashboard/components/ChatList.vue
This PR refactors the condition used to determine the initial loading state of the chat list, removing the need for a separate `isInitialLoad` state variable.
The previous approach introduced an additional state to track the initial load, which added unnecessary complexity and potential for state mismatch.
**Changes**
* **Old:**
`:is-list-loading="isInitialLoad"`
* **New:**
`:is-list-loading="chatListLoading && !conversationList.length"`
This new condition simplifies the logic by directly checking two things:
1. The chat list is still loading.
2. There are no conversations yet (indicating the initial state).
https://www.loom.com/share/2e84eab1487d4505ae8d17bfcd903022?sid=79e1b985-34fc-495c-8b83-b76bc7656a40
> chore: Prevent count flicker on loading more conversations

- app/assets/javascripts/secretField.js
- app/assets/stylesheets/administrate/components/_cells.scss
- app/views/fields/secret_field/_index.html.erb
- app/views/fields/secret_field/_show.html.erb
- app/views/super_admin/settings/show.html.erb
- Hides installation identifier by default so that users don't accidentally expose it in screenshots.
> feat: Hide installation identifier

- app/services/llm_formatter/conversation_llm_formatter.rb
- spec/services/llm_formatter/conversation_llm_formatter_spec.rb
https://linear.app/chatwoot/issue/CW-4480/expose-custom-attributes-in-conversation-to-captain-so-that-it-can
Expose custom attributes in conversation to Captain so that it can provide more information
> feat: expose custom attributes in conversation to Captain

- enterprise/app/jobs/captain/conversation/response_builder_job.rb
- enterprise/app/services/messages/audio_transcription_service.rb
- spec/enterprise/services/messages/audio_transcription_service_spec.rb
Update the error to `ActiveStorage::FileNotFoundError`. Fix the condition to enable audio transcription and added a spec for it.
> fix: Update ActiveStorage::FileNotFoundError error and fix the captain condition in audio transcription

- app/javascript/dashboard/components/table/Table.vue
- app/javascript/dashboard/routes/dashboard/settings/reports/components/SummaryReports.vue
This PR fixes the translation inconsistency in the reports pages, where table-column headers reverted to English after a page reload.
**Cause**
The components defined the columns array statically, so header labels were translated only once during component creation. On reload, the table showed the default system language (English) until the user’s locale finished loading.
**Solution**
Replaced the static columns array with a computed property and passed it to `Tanstack useVueTable` via a getter. This makes the headers reactive, ensuring they automatically update whenever the locale changes and remain translated after every reload.
Fixes https://linear.app/chatwoot/issue/CW-4539/translation-issue-in-reports-page-table-header-on-reload
> fix: Translation issue in reports table headers on reload

- db/migrate/20250627195529_add_index_to_messages.rb
All migrations will automatically be wrapped in a transaction. There are queries that you can’t execute inside a transaction. Adding index concurrently is one of them, we have to disable the transaction. I missed this in the earlier PR. #11831
> fix: disable_ddl_transaction! on add_index action

- app/controllers/twilio/callback_controller.rb
- app/jobs/webhooks/twilio_events_job.rb
- app/services/twilio/incoming_message_service.rb
- spec/jobs/webhooks/twilio_events_job_spec.rb
- spec/services/twilio/incoming_message_service_spec.rb
Fixes location messages not appearing in conversations when sent via Twilio. Location messages were being filtered out due to empty body content and missing parameter handling.
> fix: Support location messages in Twilio WhatsApp integration

- app/javascript/dashboard/routes/dashboard/conversation/Macros/List.vue
- app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroItem.vue
This PR updates the macro list behavior to prevent dragging only on the item whose preview is open, allowing users to easily copy content from the macro preview and paste it into the editor or elsewhere.
Since the `showPreview` flag exists within each `MacroItem`, the drag disabling logic is handled locally inside the component, ensuring the rest of the list remains draggable.
Fixes [CW-4548](https://linear.app/chatwoot/issue/CW-4548/conversation-macro-can-no-longer-be-copied), https://github.com/chatwoot/chatwoot/issues/11814
https://www.loom.com/share/53f6d995a8514413b0c99e702aba5b73?sid=f6233dd8-18cb-4f2a-84a6-f72edc36b798
> chore: Disable drag on macro item when preview is open

- .github/workflows/deploy_check.yml
- .github/workflows/logging_percentage_check.yml
- .github/workflows/size-limit.yml
Currently, if a PR is open and a push happens, the Run Size Limit Check workflow will start running. If, shortly after a subsequent push on the same PR happens, the workflow will start running again without cancelling the previous (now obsolete) run. With these changes, the first run would be cancelled, thus saving compute resources (see below for quantity) without sacrificing functionality, since the second run will contain the changes from the first push as well.
Fixes #11839 
No testing has been performed, the three added lines come directly out of the [official documentation](https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-only-cancel-in-progr …
> feat: Cancel redundant ci runs on consecutive pushes on the same PR

- app/helpers/message_format_helper.rb
- app/services/messages/mention_service.rb
- lib/regex_helper.rb
- spec/helpers/message_format_helper_spec.rb
- spec/models/notification_spec.rb
Fixes notification display issues when user or team names contain emojis and special characters. Previously, mention notifications would show URL-encoded characters instead of properly formatted names with emojis.
**Before:**
Notification: "John Doe: Hey @%F0%9F%91%8D%20customer%20support please check this"
**After:**
Notification: "John Doe: Hey @👍 customer support please check this"
> fix: Handle emoji and special characters in mention notifications

- app/javascript/dashboard/components/widgets/conversation/VariableList.vue
- app/javascript/dashboard/helper/commons.js
- app/javascript/dashboard/helper/specs/commons.spec.js
This PR fixes an issue where typing variables, like `{{contact.name}}`, caused the variable list to miss showing `contact.name`. The search key in this case became `contact.name}},` which didn't match any available options. The logic in `VariableList.vue` only checked the part after the last comma and didn’t fully sanitize the input.
**Solution**
Updated `searchKey` to remove all {} and commas for accurate matching.
Fixes [CW-4574](https://linear.app/chatwoot/issue/CW-4574/i-dont-see-an-option-for-contactname-it-shows-initially-but-it-doesnt)
https://www.loom.com/share/fc86e53853ad49e6acf6de57ebbd8fcb?sid=6702f896-d1a3-4c5a-9eb7-b96b5ed91531
> fix: Variable search item not showing after braces/commas

- lib/regex_helper.rb
**Summary**
- Fixed Ruby warning about unescaped closing bracket in character class within `MENTION_REGEX`
- Properly escaped the `]` character in the regex pattern to follow Ruby regex syntax standards
**Changes**
- Updated `MENTION_REGEX` in `lib/regex_helper.rb` to escape the closing bracket in character class `[^]]+` → `[^\\]]+`
> fix: Escape closing bracket in mention regex

- app/models/inbox.rb
- spec/models/inbox_spec.rb
Ref: https://app.chatwoot.com/app/accounts/1/conversations/53511
> feat: remove colon and semicolons when sanitizing inbox name

- app/javascript/dashboard/components-next/Contacts/ContactsForm/ContactsForm.vue
This PR fixes an issue where editing a contact name from the “Contacts” tab would not allow spaces in the First or Last Name fields — the space would disappear immediately after typing.
This issue did not occur in the sidebar editor or when adding a new contact.
**Cause:** The form had a deep watcher on `contactData`, which triggered `prepareStateBasedOnProps()` on every nested change. This caused the form state to reset.
**Solution:** Replaced the deep watcher with a shallow watcher that only watches `contactData.id`.
This fires once on mount and whenever a new contact is selected, avoiding unnecessary re-hydration while the user is typing.
Fixes https://github.com/chatwoot/chatwoot/issues/11922 , CW-[4623](https://linear.app/chatwoot/issue/CW-4623/inconsistent-name-field-validation-when- …
> fix: Contact name editing did not allow spaces

- app/controllers/api/v1/accounts/callbacks_controller.rb
- fetch all Facebook pages during setup instead of only the first 25
fixes:  #3082
> fix: Fetch all Facebook pages during setup

- app/jobs/inboxes/fetch_imap_email_inboxes_job.rb
- spec/enterprise/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb
- spec/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb
This PR disables queueing IMAP sync jobs for emails channels that 
- are in free plan if on Chatwoot cloud.
- requires authorization
> fix: Disable IMAP inboxes that requires authorization

- app/javascript/dashboard/components/widgets/InboxName.vue
- app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
This PR fixes a minor UI overflow issue in the conversation card, where the assignee name overflows when the inbox name is too long.
**Before**
**After**
> fix: Overflow issue with conversation card

- app/listeners/automation_rule_listener.rb
- app/mailboxes/imap/imap_mailbox.rb
- app/mailboxes/incoming_email_validity_helper.rb
- app/mailboxes/support_mailbox.rb
- app/models/message.rb
- app/presenters/mail_presenter.rb
- app/services/message_templates/hook_execution_service.rb
- spec/listeners/automation_rule_listener_spec.rb
- spec/mailboxes/imap/imap_mailbox_spec.rb
- spec/mailboxes/reply_mailbox_spec.rb
- spec/mailboxes/support_mailbox_spec.rb
- spec/models/message_spec.rb
- spec/presenters/mail_presenter_spec.rb
- spec/services/message_templates/hook_execution_service_spec.rb
The term "sorcerer’s apprentice mode" is defined as a bug in a protocol where, under some circumstances, the receipt of a message causes multiple messages to be sent, each of which, when received, triggers the same bug. -  RFC3834
Reference: https://github.com/chatwoot/chatwoot/pull/9606
This PR:
- Adds an auto_reply attribute to message.
- Adds an auto_reply attribute to conversation. 
- Disable conversation_created / conversation_opened event if auto_reply is set.
- Disable message_created event if auto_reply is set.
> fix: Disable automations on auto-reply emails

- app/javascript/dashboard/components/ChatListHeader.vue
This PR increase z-index of filter dropdown to prevent overlap with other elements.
Fixes https://linear.app/chatwoot/issue/CW-5394/update-z-index-for-filters
> fix: Overlap issue with filter dropdown

- app/javascript/dashboard/components-next/HelpCenter/Pages/PortalSettingsPage/PortalBaseSettings.vue
- app/services/whatsapp/oneoff_campaign_service.rb
- app/services/whatsapp/providers/base_service.rb
- app/services/whatsapp/providers/whatsapp_360_dialog_service.rb
- app/services/whatsapp/providers/whatsapp_cloud_service.rb
- app/services/whatsapp/send_on_whatsapp_service.rb
- spec/services/whatsapp/oneoff_campaign_service_spec.rb
- spec/services/whatsapp/providers/whatsapp_cloud_service_spec.rb
WhatsApp template message errors were not being properly handled because the `@message instance` variable was only set in the `send_message` method but not in `send_template`. When template sending failed, the `handle_error` method couldn't update the message status due to the missing @message reference, resulting in silent failures with no user feedback.
> fix: Improve WhatsApp template message error handling
