app/uploaders/attachment_uploader.rb

Guess the code for `store_dir` was copied + pasted from `app/uploaders/avatar_uploader.rb` but the location for test environment wasn't updated.

Update location where attachment uploads are stored in test environment

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/dispatchers/dispatcher.rb
app/models/account.rb
app/models/conversation.rb
app/models/message.rb
app/models/subscription.rb
app/models/user.rb
app/presenters/conversations/event_data_presenter.rb
config/initializers/event_handlers.rb
config/initializers/redis.rb
config/locales/en.yml
lib/current.rb
spec/factories/accounts.rb
spec/factories/channel_widget.rb
spec/factories/contacts.rb
spec/factories/conversations.rb
spec/factories/inboxes.rb
spec/factories/messages.rb
spec/factories/users.rb
spec/models/conversation_spec.rb
spec/presenters/conversations/event_data_presenter_spec.rb
spec/rails_helper.rb

Fixes #46 #54 #60 #62 #128 
- Added tests for public methods and callbacks 
- Created Message#unread_since scope
- Introduced `Conversations::EventDataPresenter`
- Got rid of global `$dispatcher` variable
- Use the new syntax for rails dirty-checking
- Added pry-rails

Refactor Conversation model

---

app/javascript/src/assets/scss/_foundation-custom.scss
app/javascript/src/assets/scss/_foundation-settings.scss

Solves https://github.com/chatwoot/chatwoot/issues/114
Buttons had light green (#13ce66) & light yellow (#ffc82c) backgrounds with white text, leading to these warning messages:
```
20:03:22 frontend.1 | WARNING: Contrast ratio of #fff on #13ce66 is pretty bad, just 2
20:03:22 frontend.1 |          on line 75 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
20:03:22 frontend.1 |          from line 121 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
20:03:22 frontend.1 |          from line 203 of node_modules/foundation-sites/scss/components/_button-group.scss, in mixin `foundation-button-group`
20:03:22 frontend.1 |          from line 86 of node_modules/foundation-sites/scss/foundation.scss, in mixin …
```

Fix #114: Address color contrast warning messages

---

app/models/plan.rb

+ Enumerable#detect will stop iteration when the first match is found, hence it may give us performance benefit.

Prefer Enumerable#detect over Enumerable#select.first

---

app/javascript/dashboard/assets/scss/widgets/_modal.scss

+ Use middle instead of centre in flex-align

Fixes #115: Use middle instead of centre in flex-align

---

.gitignore

A folder `buildreports` is created after running `yarn test` 
I added that to the `.gitginore` file and also `coverage` for the future when you implement coverage for the backend.

Ignore coverage reports

---

shared/config/application.yml

add the default redis url and frontend url to avoid extra hassles when setting up the repo

Less configuration when setting up the repo

---

package.json

Add rubocop on commit hook

---

docker/Dockerfile

I tried to build the docker image and was greeted with this error:
```
Step 6/13 : RUN bundle
---> Running in 84545de0d54b
/usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.2) required by your /app/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.2`
from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
from /usr/local/bin/bundle:23:in `<main>'
ERROR: Service 'server' failed to build: The command '/bin/sh -c bundle' returned a non-zero code: 1
```
This pr fixes that by installing bundler in the image.

Fix docker image by installing bundler

---

app/javascript/widget/components/ChatHeader.vue
app/javascript/widget/store/modules/conversation.js
app/javascript/widget/views/Home.vue

Collapsed header will look like:

Makes widget header expand and collapse by messages size

---

db/migrate/20190819010457_create_channels.rb
db/migrate/20191014051743_add_invited_by_to_user.rb
db/migrate/20191016211109_rename_channel_attribute_name_in_models.rb
db/migrate/20191020085608_rename_old_tables.rb
db/migrate/20191020173522_rename_sender_id_to_contact_in_conversation.rb
db/migrate/20191024062958_add_website_token_to_web_widget.rb
db/migrate/20191027054756_create_contact_inboxes.rb
db/migrate/20191116073924_add_additional_attributes_to_conversation.rb
db/migrate/20191124091232_add_widget_color_to_web_widget.rb

We were using rails from source, later moved to rails to the stable version. Due to this a couple of migrations are breaking
Fixes #313

[Bug] Fix breaking migrations, revert migrations to 6.0

---

README.md

Fixes #311 .
* Added link to env variables documentation right below the Heroku one click deploy button so that people dont get confused with broken app on deploying without the env variables set correctly
This is a documentation update.

[#311] Added link to env variables documentation

---

.env.example

The ENABLE_BILLING env var is not used in the chatwoot code base. Instead, the BILLING_ENABLED is used to enable billing.
I searched for instances of "BILLING" in the codebase.

Fix BILLING_ENABLED in example .env file

---

config/webpacker.yml
docker-compose.yaml
docker/Dockerfile
docker/Procfile.docker.dev
docker/entrypoint.sh
docs/development/project-setup/quick-setup.md

Reduce time to build docker development environment, after first build
Fix warning Integrity check: System parameters don't match.
Reduce commands required to use docker-compose and update quick-setup doc.
Moved webpacker-dev-server to its own service.
Do not install development and test gems in production.
Do not precompile assets in development.
Fixes # #321 
Manually (only tested in development environment using docker-compose)
- Clear docker environment
- Build and Run environment
- Validate running state
- Stop environment and re-build, ensure cache is used
- Stop environment make change to Package.json, ensure yarn is automatically run
- Stop environment make change to Gemfile, ensure bundle install is run 
Prior to caching all builds ran for ~6 minutes, now between 1-5 minutes …

Improve docker compose performance

---

docs/README.md
docs/channels/website-channel.md
docs/development/environment-setup/docker.md

[Docs] Fix formatting in docs

---

Procfile
Procfile.dev
app/models/conversation.rb
app/models/user.rb
config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb
config/environments/test.rb
config/routes.rb
config/sidekiq.yml
docs/development/environment-setup/docker.md
spec/mailers/confirmation_instructions_spec.rb
spec/models/conversation_spec.rb

use ActiveJob Queue Adapter as Sidekiq to send emails via sidekiq. This feature allows sending devise and mailer emails to be enqueued in sidekiq before it is actually sent. 
In addition to the rails service, we also need to run `sidekiq` service to send an email out to the SMTP server. This can be done locally by running `docker-compose run rails bundle exec sidekiq` in one of the terminal. You can also see the enqueued mailers in the sidekiq web console by visiting http://0.0.0.0:3000/sidekiq (you need to login to the application with an administrator account to access web console)

Send emails via sidekiq

---

docker-compose.production.yaml
docker-compose.yaml

We use Postgres 11.6 in Heroku. Bumping the docker-compose files to use 11.6

Upgrade: Use postgres 11.6 in docker-compose

---

app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue

Bug: Force fetch inbox settings on route change

---

.circleci/config.yml
.env.example
.rubocop.yml
app/mailers/application_mailer.rb
app/mailers/assignment_mailer.rb
app/mailers/conversation_mailer.rb
app/models/message.rb
app/views/conversation_mailer/new_message.html.erb
app/workers/conversation_email_worker.rb
config/environments/development.rb
config/environments/production.rb
config/initializers/redis.rb
config/sidekiq.yml
lib/redis/alfred.rb
spec/mailers/conversation_mailer_spec.rb
spec/models/message_spec.rb
spec/rails_helper.rb
spec/workers/conversation_email_worker_spec.rb

This close #139 .
* Added the `setex` and `get` methods to Redis wrapper
* Set the priorities for the Sidekiq queues
* Was not able to use Mailhog for a testing email in local, switched back to letter opener and added comments on using the SMTP settings
* Added after create hood in messages to queue the sending of mail after 2 minutes using Sidekiq worker and also set the Redis key for the conversation to avoid the email sending for every message
* Added the Sidekiq worker to send the email and delete the conversation Redis key
* Added the mailer and mail template
* Mailer sends the last 10 messages along with the new messages from the time it was queuedFixes # (issue)
* Send email only in development or if SMTP config is set
* Set the SMTP_PORT in production variable
* Added specs for …

[#139] Send conversation emails

---

app/mailers/conversation_mailer.rb
spec/mailers/conversation_mailer_spec.rb

* Changed `from` email to be that set in the ENV variable `MAILER_SENDER_EMAIL` and `reply_to` email to be of the agent's email for conversation emails.
* Made necessary spec changes

[Chore] Changed from email and reply to email for conversation email

---

app/views/conversation_mailer/new_message.html.erb

The conversation email had a link to the app dashboard to that particular conversation thread. This was accessible only to the agent and not to the customer. Removed this link from the email sent to the customer.

[Chore] Removed agent dashboard link in conversation mail to user

---

Procfile.dev
config/initializers/sidekiq.rb
config/sidekiq.yml
db/schema.rb
docker-compose.yaml
docker/entrypoints/rails.sh

* Add Sidekiq as part of the composer stack (reduce confusion during development)
* Minor improvements over Gem update without building Dockerfile each time
* Reduce default redis concurrency to 3

Add sidekiq docker

---

spec/controllers/api/v1/inbox_members_controller_spec.rb

This PR adds tests for the inbox_members_controller.rb
I wasn't able to cover line 16 in inbox_members_controller.rb probably because Rails now automatically throws a 404 if an Entity couldn't be found in a before_action. So we can probably remove that line. @pranavrajs thoughts?
Improves #37 

Chore: Added tests for inbox_members

---

config/cable.yml
config/initializers/redis.rb
config/initializers/sidekiq.rb

This closes #491 .
* When the the .env file has line with REDIS_PASSWORD set as empty, the value for this in the initializers comes as an empty string "".
* Fixed this in a way that, if it's empty string, then it's taken as `nil` value so that password is skipped
Fixes #491 
Tested in local with redis password set and without this.

[491] Bug fix - Sidekiq Redis Auth issue

---

app/javascript/widget/components/UserMessageBubble.vue

This fixes the color of an agents link in the chat widget being invisible due to having the same color as the background of the chat bubble.
Fixes #519

Fix: Fixed color of agent link in chat widget being white

---

app/javascript/dashboard/assets/scss/_layout.scss

This fixes a misalignment of the back button between the text and the icon. After noticing it multiple times I decided to fix it.
Before:
After:
It may look like a small difference on the screenshots but it fixed a noticeable issue me and a buddy of mine noticed 😅

Fix: Fixed misalignment of back button

---

app/javascript/dashboard/assets/scss/_foundation-custom.scss

The default Chatwoot font for the code tag called "Monaco" is not supported by windows, which results in it falling back to "Times New Roman". I added "Verdana" as fallback font which I found suiting for code tags.
Before:
After:

Fix: Fixed code font not being displayed on windows

---

app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue

This fixes an issue with description after inbox creation now showing.
Fixes #499

Fix: Finish setup now shows description for code

---

swagger/definitions/index.yml
swagger/definitions/request/conversation/create_message.yml
swagger/definitions/resource/conversation.yml
swagger/definitions/resource/extension/contact/conversation.yml
swagger/definitions/resource/extension/contact/list.yml
swagger/definitions/resource/extension/conversation/labels.yml
swagger/definitions/resource/extension/conversation/list.yml
swagger/definitions/resource/extension/conversation/show.yml
swagger/definitions/resource/extension/conversation/status_toggle.yml
swagger/definitions/resource/extension/conversation/with_display_id.yml
swagger/definitions/resource/extension/message/with_source_sender.yml
swagger/definitions/resource/message.yml
swagger/definitions/resource/user.yml
swagger/paths/contact/crud.yml
swagger/paths/contact/list_create.yml
swagger/paths/conversation/assignments.yml
swagger/paths/conversation/crud.yml
swagger/paths/conversation/labels.yml
swagger/paths/conversation/list.yml
swagger/paths/conversation/messages.yml
swagger/paths/conversation/toggle_status.yml
swagger/paths/conversation/update_last_seen.yml
swagger/paths/index.yml
swagger/swagger.json

This closes #549 
* Added the documentation for the conversation APIs - 8 endpoints
* Added descriptions for the existing endpoints
* Added new resource models and updated some parts of the contact API
After making the changes, ran the task `rake swagger:build`, and went to `http://localhost:3000/swagger` and verified the documentation has been updated with my changes.

Chore: Document Conversation APIs in swagger

---

Gemfile
Gemfile.lock

This closes #565 
At the time of using, `json_refs` gem did not have the ability to recursively resolve the references. So we had to fork this into one of our own and make the required changes. So this fork was used as the source for the gem.
Along with this, we had raised a PR in the original repo so as to push the recursive dereferencing changes upstream. This was merged in the gem's parent repo. So updated the source of this gem to the original parent repo source.

Chore: Update the source of `json_refs` gem (#565)

---

swagger/paths/contact/conversations.yml
swagger/paths/contact/crud.yml
swagger/paths/contact/list_create.yml
swagger/paths/conversation/assignments.yml
swagger/paths/conversation/crud.yml
swagger/paths/conversation/labels.yml
swagger/paths/conversation/list.yml
swagger/paths/conversation/messages.yml
swagger/paths/conversation/toggle_status.yml
swagger/paths/conversation/update_last_seen.yml
swagger/swagger.json

This closes #589 
Currently with swagger documentation, when you click on a particular request on the left navigation bar, the URL of the page changes to something that is constructed from the request params and is highly unreadable and very long. This makes it very difficult to understand the URL and also to share it. Made this short and readable.

Chore: User Friendly URLs on the swagger docs

---

app/controllers/twitter/callbacks_controller.rb
app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
app/javascript/dashboard/i18n/locale/en/conversation.json
app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
app/presenters/conversations/event_data_presenter.rb
app/services/twitter/direct_message_parser_service.rb
app/services/twitter/send_reply_service.rb
app/services/twitter/tweet_parser_service.rb
app/views/api/v1/contacts/conversations/index.json.jbuilder
app/views/api/v1/conversations/index.json.jbuilder
app/views/api/v1/conversations/partials/_conversation.json.jbuilder
spec/models/conversation_spec.rb
spec/presenters/conversations/event_data_presenter_spec.rb
spec/services/twitter/send_reply_service_spec.rb

Bug: Fix duplicate messages from Twitter DM and tweets

---

app/models/conversation.rb
app/models/message.rb

Fixes #639 
* Update conversation's updated_at when a message is created/saved
* Changed the ordering of conversation to be based on `updated_at` rather than `created_at`
Amidst Corona, in a home quarantined lockdown situation in local.

[Feature] Conversation ordering changes (#639)

---

app/mailers/conversation_reply_mailer.rb
app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb

This fixes #650 
* When an attachment was sent in the reply mailer it was breaking due to the truncating function applied on the last message content. Here the content was empty and so it broke. Fixed this breakage.
* Also addressed the issue that if the attachment was there the content was coming empty. With these changes, made the content to have a link to the attachment.
Under the duress of a declining economy with multiple governments enforcing stricter lockdown around the world and Covid-19 viruses mutating fast as they could, in a tropical climate, racing the clock in a mac machine in the local environment using Mailhog.
A screenshot after the fix:

Bug: Fixed conversation reply mail issue when an attachment is sent (#650)

---

spec/mailers/confirmation_instructions_spec.rb

Fixes #534 
* Fixed confirmation email flaky tests due to unescaped HTML
Tested in local by running RSpec multiple times.

Bugfix: Fixed confirmation email flaky tests (#534)

---

app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue

On June 30, 2020, Facebook API will deprecate the `read_page_mailboxes` scope.
Fixes #760 
No tests, looks like this particular scope is not needed anymore. Someone with more knowledge of this part of the codebase should test more thoroughly 🙏

Remove deprecated scope from FB Channel

---

.codeclimate.yml
app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
app/models/account.rb
app/models/concerns/features.rb
app/views/api/v1/accounts/show.json.jbuilder
app/views/api/v1/accounts/update.json.jbuilder
config/features.yml
db/migrate/20200503151130_add_account_feature_flag.rb
db/schema.rb

Fixes #814 
* Added the new column on account model for managing feature flags
* Encapsulated the feature flagging as a concern. With this, we can re-use the same concern if we introduce this in other models like user or inbox or so.
* Added the inbound email flag
* Locked the fields of this feature in account settings based on this
* Added the features in the account API responses
Self-testing has been performed. [Self-attestation stamp]

Feature: Feature flags on account (#814)

---

app/views/widgets/show.html.erb

Bug: Fix inbox.agent_bot nil case

---

.rubocop.yml
lib/global_config.rb
spec/lib/global_config_spec.rb

This closes #844 .
* Added a global config helper to easily access installation/global configs
* This will fetch the keys from cache with fallback to DB on a cache miss
* Ability to query multiple keys simultaneously
* Interface to delete the existing global config cache
* Added tests for this new helper module
Tested locally from the console. 
From the screenshot, a couple of things to note,
1. The first call came from cache as there were no queries being fired
2. After clearing the global config cache, the DB queries appeared in the next call
3. But thereafter how many ever times you called config, there were no DB queries as it was already cached
Usage :
```
GlobalConfig.get('SHOW_WIDGET_HEADER', 'ACCOUNT_LEVEL_FEATURE_DEFAULTS')
GlobalConfig.clear_cache
```

Feature: Global Config helper (#844)

---

spec/controllers/super_admin/users_controller_spec.rb

Fixes #887 
* Fixed the flaky failure in rspec for super admin user controller due to unescaped user name check
Purely locally. 💯

Fixed rspec due to unescaped html check for user name (#887)

---

app/mailboxes/conversation_mailbox.rb
app/presenters/mail_presenter.rb
spec/mailboxes/conversation_mailbox_spec.rb
spec/presenters/mail_presenter_spec.rb

Fixes #883 
* Parsed the quoted text and replies in incoming emails and store them separately
* Did this parsing for plain text and HTML part of emails
* In the chat window, we will only show the parsed reply alone
Tested in the local environment with an actual email reply with quoted text from Gmail under hot and humid weather before the onset of rain.

Chore: Parse quoted text in incoming emails (#883)

---

app/mailers/conversation_reply_mailer.rb
config/installation_config.yml
config/locales/en.yml
db/migrate/20200522115645_reload_config.rb
db/schema.rb
spec/mailers/conversation_reply_mailer_spec.rb

Fixes #885 
* Added custom Message-ID and In-Reply-To headers for conversation reply emails
* Added new global config for the default domain (This is used in the above headers)
* Added migration to run the config loader to load the new global config value
* The subject of the conversation reply mailer was made static (This is required for threaded emails)
* Added required tests
Tested with Gmail client by sending out multiple replies and confirming that it comes to be threaded as expected while having black tea with extra sugar and oreo cookies on the side.

Chore: Threaded email replies for a conversation (#885)

---

app/javascript/widget/store/modules/specs/conversation/mutations.spec.js

The test was providing a false positive as the state of `isAgentTyping` was not changed
I just changed the initial state of isAgentTyping from `false` to `true`
expected)

fix bug within #toggleAgentTypingStatus test

---

Procfile

Add release migration to Heroku release so that the migration scripts are automatically run when a new version is deployed.

Chore: Add rake db:migrate to Heroku release phase

---

app/javascript/sdk/IFrameHelper.js
app/javascript/sdk/bubbleHelpers.js

This PR fixes #954 
- Add listener to widget holder to disable scrolling on parent
- Doesn't hide scrollbar for parent hence avoiding the jump when hovered

Enhancement: Improve scrolling on widget #954

---

app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss

**Update .conversation--message text color in the Conversations List for better hierarchy**
This is a minor change in the CSS of the Conversations List which changes the message text (.conversation--message) to a lighter gray color for better hierarchy.

Update .conversation--message text color

---

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss

This proposes a new look for the chat bubbles in the Dashboard area, by introducing light shadow and removing borders from chat bubbles. Also, updates the border color for the private note message using an already defined variable in the app's SCSS files ($warning-color).
**Before:**
**After:**

Proposed Enhancements for Chat Bubble Looks in the Dashboard

---

db/migrate/20170525104650_create_round_robin.rb

Because RoundRobin had defined in file, so when db:create and db:migrate will raise error.
so change the migration file name

fixed db:migrate RoundRobin dup

---

app/mailers/conversation_reply_mailer.rb
app/views/mailers/conversation_reply_mailer/reply_without_summary.html.erb
app/workers/conversation_reply_email_worker.rb
spec/factories/messages.rb
spec/mailers/conversation_reply_mailer_spec.rb
spec/workers/conversation_reply_email_worker_spec.rb

Fixes #1048 
Right now as part of conversation continuity we are using the
ConversationReplyMailer which sends a summary of messages including
the incoming messages when an agent replies. Ideally, we want
to send only the reply of that agent and not a summary when
Conversation continuity is enabled. Added the functionality
to send the reply email without summary. Added required unit
tests to cover the changes.
Locally, with an underperforming `mailhog` competing for resources with the OS habitants (especially Chrome and Docker).

Enhancement: Ability to send out an email without summary (#1048)

---

app/mailboxes/application_mailbox.rb
app/mailboxes/conversation_mailbox.rb
app/mailers/conversation_reply_mailer.rb
spec/fixtures/files/reply.eml
spec/mailers/conversation_reply_mailer_spec.rb

In conversation continuity, the reply to email was looking like
`reply+to+{some_random_hex_id}@reply.chatwoot.com`
Changed the prefix to just `reply` instead of `reply+to`.
Now it looks like: 
`reply+{some_random_hex_id}@reply.chatwoot.com`
By running all the unit tests related to the parts where the reply email is set in email outbound parts and the parts where the email reply is received and parsed.

Chore: Change the prefix in reply emails

---

.env.example
app/mailers/conversation_reply_mailer.rb
config/installation_config.yml
spec/mailers/conversation_reply_mailer_spec.rb

For the outgoing emails which have a dependency on the incoming
part as well like the conversation continuity part, some of the
config variables used were entirely based on the account attributes.
But this is not true in case of self-hosted situations where you have
multiple accounts and have a common config for incoming emails.
So moved out some of the attributes entirely dependent on the account
to ENV with a fallback to the Global config.
Also, with these changes, the name of the agent will be shown in the
email client within the conversation rather than just the support
email address. This has a huge UX impact on the customer.
Modified all the necessary unit tests to reflect these changes.
Updated the .env.example file for the new ENV variable.
Fixes #1061 
“Quality is never an …

Chore: Move email configs to ENV variables

---

app/mailers/conversation_reply_mailer.rb
app/models/concerns/featurable.rb
app/models/message.rb
spec/mailers/conversation_reply_mailer_spec.rb

Private notes were sent in the emails as part of
conversation continuity. Fixed this issue.
Also made the changes to not even queue the mails
if the message is a private note.
Fixed broken signups in develop branch due to changes
in `featurable` module.
Fixes #1069 
Pakka local.

Bugfix: Private notes in emails & broken Signup

---

app/presenters/mail_presenter.rb

Fixes #1062 
We had changed the support email from an account based
only value to account based with fallback on global config
and environment variable.
Incoming email quoted text parsing was still based on
account based support email. Changed this to utilize
the newly introduced fallback values from global config
and environment for parsing quoted text.
With intuition. 😸  😝

Bug: Fixed quoted text parsing in incoming email

---

app/controllers/api/v1/profiles_controller.rb
app/javascript/dashboard/api/auth.js
app/javascript/dashboard/components/layout/Sidebar.vue
app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/i18n/locale/en/settings.json
app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
app/javascript/dashboard/store/modules/conversations/getters.js
app/mailers/conversation_reply_mailer.rb
app/models/conversation.rb
app/models/user.rb
app/presenters/conversations/event_data_presenter.rb
app/views/api/v1/accounts/inbox_members/show.json.jbuilder
app/views/api/v1/conversations/partials/_conversation.json.jbuilder
app/views/api/v1/models/_agent.json.jbuilder
app/views/api/v1/models/_user.json.jbuilder
app/views/api/v1/widget/inbox_members/index.json.jbuilder
app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
spec/mailers/conversation_reply_mailer_spec.rb
spec/models/conversation_spec.rb

- Add a field on Profile Settings page to update display_name
- Add a virtual attribute on the user to return display_name if available
- Use available_name instead of name everywhere except agent list dashboard for admin
Fixes #972

feat: Use display_name instead of name of the agent

---

app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/widget/components/AgentMessage.vue
app/mailers/agent_notifications/conversation_notifications_mailer.rb
app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.html.erb
app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.html.erb
app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb

- Use available_name in message sender details
- Use available_name in the emails.

chore: Update the usage of available_name instead of name

---

config/storage.yml

minio doesn't work without `force_path_style: true`
more info here: https://kevinjalbert.com/rails-activestorage-configuration-for-minio/
Fixes #893
On my instance, without `force_path_style: true`, saving images causes `500` errors.
With this change it works fine.

Bugfix: add missing option to s3_compatible to support minio

---

config/environments/production.rb
config/environments/staging.rb
config/environments/test.rb
config/initializers/assets.rb

When we changed the assets serving to CDN, everything seems to be working fine except the fonts. For the requests for fonts, we were seeing CORS issue. Fixed this issue.
Tested in the staging environment with CloudFront.

Fix: fonts cors issue with cdn

---

app/services/round_robin/manage_service.rb

The `validate_queue` method of `RoundRobin::ManageService` will always return `false` for `inbox.inbox_members.map(&:user_id).sort == queue.map(&:to_i).sort` when the number of agents in the queue are >10.
**Reason**: 
Incorrect syntax: `queue.sort.map(&:to_i)`
The queue contains the string integers ("1", "2", "3" etc.), and here we are sorting the queue before mapping it to the integer. 
So, for the queue: `["4", "2", "1", "11", "12"]`
result:  `[1, 11, 12, 2, 4]`
expected result:  `[1, 2, 4, 11, 12]`
As a result, the method always returns false
The correct order should be: **map then sort**
Correct syntax: `queue.map(&:to_i).sort`
Functional test

bug fix: validate_queue method - map then sort, instead of sort then map

---

app/models/channel/twilio_sms.rb
spec/models/channel/twilio_sms_spec.rb

- Remove 24-hour window message for Twilio SMS

fix: Check medium to decide 24 hour window

---

app/controllers/api/v1/accounts/contacts/conversations_controller.rb
app/controllers/api/v1/accounts/contacts_controller.rb
app/finders/conversation_finder.rb
app/finders/message_finder.rb
app/views/api/v1/conversations/partials/_conversation.json.jbuilder

There were a couple of N+1 queries fired on the dashboard side of
the app. Fixed this to improve performance.
Tested in local by monitoring the server logs with an eye for bullet gem's warnings in N+1 queries.

Chore: Fix N+1 queries in dashboard side

---

app/presenters/mail_presenter.rb

There were issues in parsing Arabic or UTF characters (emojis) correctly for the incoming emails.
All these characters were converted to question marks which is the fallback character when an encoding is enforced and there is a missing matching character.
Fixes #1081 
In local

Bugfix: Email encoding issue for utf8 characters (#1081)

---

app/models/conversation.rb
config/locales/en.yml
spec/models/conversation_spec.rb

Fixes #1077 
- Added one test case in rspec to check correct activity message is generated
- Manual testing on local build

add: self-assign conversation activity message

---

app/javascript/packs/sdk.js

Passes the user argument to `hasUserKeys()` in the `setUser()` function. This was a bug introduced in https://github.com/chatwoot/chatwoot/commit/dbd1720aeb99e75a1fe5a171895576af22eda9f9.
Fixes: #1296
attn: @pranavrajs
**Reproduction steps:**
* Load current version of SDK
* Call `setUser` with valid properties
**Verification steps:**
* Build the javascript
* Pointed my SDK initialization at the local copy
* Call `setUser` and see a success

fix(1296): Call hasUserKeys() with user argument

---

app/models/conversation.rb
config/locales/en.yml
spec/models/conversation_spec.rb

Feature to create an activity message of label addition/deletion.
Fixes #1022 
I have added RSpec tests to check both cases to add and remove labels creates activity messages in DB
- spec/models/conversation_spec.rb

feat: Activity message for label addition/deletion

---

spec/models/conversation_spec.rb
spec/presenters/conversations/event_data_presenter_spec.rb

While working on #418, realised the metric that we need to calculate inactivity of converstions has been already introduced in #1281. I can build my changes for #418 on top of work done in #1281, but that PR is still not merged due to a couple of test cases failing in #1281. 
Fixed failing tests post introduction of last_activity_at in conversations
Verified that the test cases that were failing in the original PR are not failing here.

fix: Fixing failing tests post introduction of last_activity_at in conversations

---

app/javascript/dashboard/components/widgets/ChannelItem.vue

`===` comparison of array and number types always returns false. Compare length of the array instead.
I have not done any testing yet.

fix: array length check

---

app/models/user.rb

Currently, the app shows the initials of the user if no avatar image is set. To add a personal touch in the app, we will pull the Gravatar profile image if no image avatar image is found.
Fixes #1240 
I created different accounts and added avatar image for a few accounts.
After implementing the feature, the accounts which do not have the avatar image started to show the Gravatar images and the one which had one remained the same.

feat: use gravatar if no avatar image

---

app/models/user.rb

Add `d=404` to gravatar request to fallback to letter avatar

fix: Add default 404 param on gravatar

---

app/javascript/dashboard/assets/scss/views/settings/integrations.scss

Description
height property for .integration--image class was not defined which was causing this issue. I have added the height now it is working fine.
Fixes #1196 
I have checked on the safari attaching screenshot here.

Bug: Fix 1196 Integrations page is broken on safari

---

app/views/api/v1/conversations/partials/_conversation.json.jbuilder

- Remove unnecessary information in conversation APIs.

chore: Use agent partial instead of user in conversation API

---

app/javascript/dashboard/assets/scss/widgets/_login.scss
app/javascript/dashboard/routes/auth/Signup.vue

This just improves the styling of the registration page on mobile a bit as it provides an immediately negative impression as it is.
Before:
After:
Minor styling improvement.
I tested with Chrome, Firefox, and Safari.
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] Any dependent changes have been merged and published in downstream modules

Improve mobile styling of registration view a bit

---

app/controllers/api/base_controller.rb
app/controllers/api/v1/accounts/agents_controller.rb
app/controllers/api/v1/accounts/contacts_controller.rb
app/controllers/api/v1/accounts/inboxes_controller.rb
app/controllers/api/v1/accounts/labels_controller.rb
app/controllers/api/v1/accounts/webhooks_controller.rb
app/controllers/api/v1/accounts_controller.rb

While adding more model authorization policies to my fork, I noticed the `check_authorization` method was not DRY. So this is my attempt to clean up. 
I replaced the six `check_authorization` methods with one method inside of the `base controller`. 
One edge case that is accounted for is when the model you want to authroize is not the same as the controller name. For example, for `AgentsController` we want to check authorization for the `User` model. In this case, we just pass in the correct model to `super`.

DRY up check_authorization method

---

app/models/conversation.rb
config/locales/en.yml
spec/models/conversation_spec.rb

Added message when user performs mute / unmute conversations actions
https://github.com/chatwoot/chatwoot/issues/1330
Added tests in "spec/models/conversation_spec.rb"

Add messages on mute / unmute actions

---

package.json
yarn.lock

- Remove warning purgeLayersByDefault

chore: Upgrade tailwindcss to 1.9.x

---

docker-compose.yaml
docker/entrypoints/helpers/pg_database_url.sh
docker/entrypoints/rails.sh
yarn.lock

* The `POSTGRES_PASSWORD` variable setting inside the entry point script of the Rails docker container was printed in the logs when the container was run using `docker-compose`. Fixed this by removing this password being set in this script.
* Added env file from the root directory to the container
* Updated the tailwind version in yarn lock
Fixes #1371
Tested in a local environment by following the `docker-compose` logs when the chatwoot boots up. Without the changes, the password was being printed in the logs. When the changes are applied, the pg password is no longer printed in the logs.

fix: pg pass printed by docker container (#1371)

---

app/javascript/dashboard/store/modules/labels.js

Sorted labels returning from `getLabelsOnSidebar` by alphabetical order.
Fixes #1386

Fix: Sort label links on sidebar for homepage #1386 

---

lib/integrations/slack/incoming_message_builder.rb
spec/lib/integrations/slack/incoming_message_builder_spec.rb
spec/support/slack_stubs.rb

- If no thread timestamp is available, ignore the message
- Add specs to cover the case

fix: Add a check for thread_ts

---

Gemfile.lock
app/javascript/sdk/IFrameHelper.js
app/javascript/sdk/sdk.js
app/javascript/widget/assets/scss/woot.scss
app/javascript/widget/views/Router.vue

Fixes #1434 
- Add missing close button
- Fix the position of the widget holder if there is no bubble present

fix: Add missing close button if bubble is hidden

---

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
app/javascript/dashboard/components/ChatList.vue

I have added the "text-truncate" class to the page title to truncate overflow text of the label title, now user can use open/resolved/bot dropdown even with long label title.
Fixes #1447 
I am attaching a screenshot to test.

Label Overflow text-truncate fix 1447

---

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
app/javascript/shared/components/ResizableTextArea.vue
app/javascript/widget/components/ChatInputWrap.vue

Fixes #940 
- Create events for typing on and off on resizable text area
- Send typing events on these events instead of focus

chore: Send typing events on keyup, not on focus

---

config/storage.yml

Hey folks, a tiny change here to fix an issue using Chatwoot with Google Cloud Storage that i came across: Essentially, following the [instructions](https://www.chatwoot.com/docs/configuring-cloud-storage) as provided for GCS currently leads to a misconfigured ActiveStorage (any file uploads fail): the issue is that ActiveStorage expects `google.credentials` in `storage.yml` to be _either_ a path to a local json file containing the credentials, _or_ a JSON string of the credentials themselves, but _not_ a Ruby hash parsed from that JSON. A one line change fixes it.
I've tested manually, but not entirely sure how best to include unit tests to cover it seeing as it's a config change? happy to do so though if you have any pointers.
Thanks!
Tim
- …

GCS credentials dont need to be parsed as JSON

---

app.json

The Heroku deploys were having workers turned off by default. This was because the `worker` process was not available in `formation`.

fix: Add worker to the formation to avoid default turned off state

---

app/controllers/api/v1/accounts/contacts_controller.rb
spec/controllers/api/v1/accounts/contacts_controller_spec.rb
spec/factories/contacts.rb

- Ignore case for name, email search in contacts, use ILIKE instead of LIKE

chore: Ignore case while searching contact name, email

---

app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue

- Old contact doesnot have additional attribute, it will be null. Use empty object if it is not available.

fix: Use empty object if additional_attribute is null

---

app/builders/account_builder.rb
app/listeners/installation_webhook_listener.rb
app/models/account.rb
lib/events/types.rb
spec/listeners/installation_webhook_listener_spec.rb

- Remove `account.destroy` listener.
- Add `users` to `account.created` listener.
- Remove unnecessary `@account.destroy` method.

chore: Remove account.destroy listener

---

app/controllers/api/v1/accounts/contacts/labels_controller.rb
app/controllers/api/v1/accounts/conversations/labels_controller.rb
spec/controllers/api/v1/accounts/contacts/labels_controller_spec.rb
spec/controllers/api/v1/accounts/conversations/labels_controller_spec.rb

Labels were sent as an array rather than a string, so specs didn't cover this part. We were not able to add the labels to a conversation. 
This PR fixes the controller and the associated specs.

fix: Labels cannot be added to conversations

---

app/models/conversation.rb
spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb

- Un-assignment was broken because the assignee name was not resolved during the activity message creation. This PR fixes that issue.

fix: Resolve name only if assignee exists during unassignment

---

.gitignore
app/controllers/super_admin/installation_configs_controller.rb
app/dashboards/installation_config_dashboard.rb
app/fields/serialized_field.rb
app/models/installation_config.rb
app/views/fields/serialized_field/_form.html.erb
app/views/fields/serialized_field/_index.html.erb
app/views/fields/serialized_field/_show.html.erb
app/views/super_admin/application/_navigation.html.erb
config/installation_config.yml
config/routes.rb
db/migrate/20210113045116_add_locked_attribute_to_installation_config.rb
db/schema.rb
lib/config_loader.rb
spec/controllers/super_admin/installation_configs_controller_spec.rb
spec/factories/installation_config.rb

* Added the ability for super admins to view, edit and update installation config values. Also, they can add new installation config values. The impact of editing and adding depends on which all installation config values are being used in the code.
* Known limitation now: Ability to edit hash values (for eg: feature flags) are disabled. This requires more work and will be taken up in a secondary set of changes.
* Minor UX improvement. Clicking on the Sidekiq option in the super admin sidebar will now open the Sidekiq dashboard in a new tab rather than in the same tab that you were using super admin.
* Added the scoping ability for installation configs to be selectively shown in the super admin console as some of them need not be exposed to the super admin and will be part of the Ops. …

feat: installation config in super admin console

---

.rubocop.yml
app/mailboxes/support_mailbox.rb
app/mailers/conversation_reply_mailer.rb
app/models/channel/email.rb
app/models/message.rb
app/workers/conversation_reply_email_worker.rb

The intention is to allow public to beta test email channel
- Fixed thread issues with outgoing email, now it would select the last incoming email message_id
- Fixed outgoing message subject name, set it to `re: original message name`
- Send email in email channel without 2 minute delay
- Display generated email address in the UI

fix: Add correct thread message_id to the email message

---

app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
app/javascript/dashboard/components/widgets/conversation/CannedResponse.vue
app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
app/javascript/dashboard/i18n/locale/en/conversation.json

- Add an option to toggle enter to send 
- Save enter to send in uiSettings
- Fix key down scroll height in canned responses.
- Allow canned responses on private notes.

feat: Add "Enter to send" option on format mode

---

app/javascript/dashboard/routes/dashboard/settings/agents/AddAgent.vue
app/javascript/dashboard/routes/dashboard/settings/agents/EditAgent.vue
app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
app/models/user.rb
spec/models/user_spec.rb

Add name error validation for account settings Profile name. Have set minimum string length for the name as 4.
Fixes #1714
Bugfix (a non-breaking change that fixes an issue)
Setting the profile name in the account settings with a string value less than 4 throws an error as shown in the above image.
`bundle exec rspec spec/models/user_spec.rb`

Add name error validation for account setting Profile name #1714

---

package.json
yarn.lock

Upgrade @chatwoot/prosemirror-schema to use `encodeURIComponent` in generating mention url

fix: Use encodeURIComponent in generating mention url

---

app/helpers/file_type_helper.rb
app/javascript/dashboard/components/widgets/conversation/Message.vue

Looks a little bit ugly. Since this would get the product to be useful, I'm inclined to this approach.
@sojan-official @nithindavid Any thoughts?
Fixes #1458

feat: Use audio tag instead of download file button

---

app/views/api/v1/models/_inbox.json.jbuilder

Many self-hosted instances require this key as a part of QA & maintenance. Since this key is not sensitive its better to send it as a part of the JSON response instead of having to use a regex to get it from the widget_script_tag
Many self-hosted instances require this key as a part of QA & maintenance. Since this key is not sensitive its better to send it as a part of the JSON response instead of having to use a regex to get it from the widget_script_tag
Fixes #1764
https://github.com/chatwoot/chatwoot/issues/1764
Ran the relevant tests.

Include website_token key in the inboxes response

---

app/javascript/dashboard/components/widgets/conversation/Message.vue

Fixes #1770 
**Fix**
Added CSS to Message.vue to fix the color issue. Changed to blue.

Fix: Links inside private note is not visible

---

app/javascript/dashboard/components/widgets/conversation/Message.vue

Fixes #1567 
**Describe the FIx**
Fixes color for file name, file icon for attachments in private note.

Fix colors for attachments in private note

---

app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue

- The key in `v-for` expects a string but mistakenly we are using an object there

Fix warning on new inbox page

---

Gemfile.lock

Push settings were missing in Opera. `browser` gem wrongly identified Opera as safari. 
More context: https://github.com/fnando/browser/pull/483

fix: Upgrade browser gem to fix missing push config in Opera

---

app/listeners/notification_listener.rb
spec/listeners/notification_listener_spec.rb

Fix attachment rendering if the message content is empty in private note

---

app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
app/javascript/dashboard/components/ChatList.vue
app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
app/javascript/dashboard/components/widgets/conversation/EmptyState.vue
app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue

- Keeps conversation header width constant irrespective of the contact panel status
- Layout & css cleanup

chore: Move conversation header above sidebar

---

app/javascript/shared/helpers/AudioNotificationHelper.js
app/javascript/shared/helpers/specs/AudioNotificationHelper.spec.js

**Why**
- Notifications were playing while I was away from chatwoot tab, irrespective of the condition.
- Play for private notes from others

Fix: apply alert conditions while document is hidden

---

app/javascript/dashboard/assets/scss/_foundation-settings.scss
app/javascript/dashboard/components/ChatList.vue
app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue

Fixes congestion because #1835 
Here's how it'll look on different screen sizes (title as pixels)
**1040**
**1280**
**1368**
**1440**
**1740**

Chore: Responsive fixes for common screen widths

---

app/javascript/dashboard/assets/scss/widgets/_buttons.scss
app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue

Why?
The height of the buttons were not same as width, which is expected to be of square shape.

Chore: Reply panel emoji button size fixes

---

app/javascript/widget/components/PreChat/Form.vue

**Why**
Having the prechat form with minimum length set to 10 makes it difficult to start conversations for users.

Chore: Make prechat message minimum length to 1

---

app/javascript/dashboard/helper/actionCable.js

**Why**
When a new conversation is created, sometimes action cable event for `conversation.update` arrives before `created`. In this case the data in updated might be missing `id` attribute.

Fix: Add check for id on update conversation

---

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue

The name of the inbox needs to be shown in the conversation list only if there are more than 1 inbox present otherwise it is unnecessary repetition.

fix: Show inbox name only if more > 1 inbox present

---

app/mailers/application_mailer.rb
lib/exception_list.rb

- If a contact contains an invalid email address, the sidekiq jobs for conversation continuity would error out. handling this exception gracefully.

chore: Handle Sentry Errors

---

app/javascript/sdk/IFrameHelper.js

On SDK reset, we were recreating the bubble/iframe nodes. It leads to multiple content nodes. This PR checks if a node is already initialized before recreating one.
Fixes #2023

fix: Use exisiting bubble nodes if available

---

app/javascript/dashboard/api/auth.js

**Why?**
Fixes the page freeze issue #2042
**What went wrong?**
The user cookie might get invalidated before auth cookie. But we are determining whether a user session only based on validity of auth cookie.
**Fix**
Added check for user cookie on login check

fix: Invalidate session if user cookie is absent

---

app/models/message.rb

We have issues reported on installations where attachment messages for WhatsApp weren't working at times. So here is a fix for the same.
1) Create a Twilio Inbox
2) Ensure attachments can be sent

Fix: Twilio whatsapp attachment messages not working

---

app/javascript/dashboard/routes/dashboard/settings/teams/Create/AddAgents.vue
app/javascript/dashboard/routes/dashboard/settings/teams/Edit/EditAgents.vue

fix: Refresh user teams after creating a new team

---

app/javascript/dashboard/routes/dashboard/conversation/contact/NewConversation.vue

**Why**
New conversation inboxes are not fetched for contacts.

Fix: Fetch contactable inboxes on new conversion 

---

app/javascript/dashboard/components/widgets/conversation/AvailabilityStatusBadge.vue
app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue

**Describe the issue**
Fixes status badge width issue by new pull requests #2047 and #2122 .
**After**
**Before**

Chore: fixes issue with status badge.

---

app/builders/contact_builder.rb
spec/builders/contact_builder_spec.rb

- Contact builder should identify existing contacts based on phone number
QA
---
1) Create Twilio Inbox A in chatwoot and create a conversation through SMS/Whatsapp
2) Create Twilio account B in the same account and create a conversation with the same phone numbers
3) Conversations should be successfully created and grouped under same contact

chore: Contact builder should Identify contacts based on phone number

---

app/javascript/shared/assets/stylesheets/ionicons.scss

Lighthouse audit "Ensure text remains visible during webfont load"
#2111

chore: Add font-display: swap to Ionicons

---

Gemfile.lock

chore: Upgrade rexml to 3.2.5 to fix CVE-2021-28965

---

db/migrate/20210428135041_add_campaigns.rb

Rename the migration to fix `previous definition of Campaigns was here`

fix: Rename migration for Campaigns

---

app/javascript/dashboard/components/layout/specs/AvailabilityStatus.spec.js
app/javascript/dashboard/components/specs/SidemenuIcon.spec.js
app/javascript/shared/components/specs/DateSeparator.spec.js
app/javascript/shared/components/specs/Spinner.spec.js

- Removes `to be deprecated` methods
- Adds context for woot-buttonin jest files

chore: Fixes warnings in jest

---

app/javascript/dashboard/components/widgets/chart/BarChart.js
app/javascript/dashboard/i18n/locale/en/report.json
app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
package.json
yarn.lock

- Upgrade chart.js to 2.9.4 to fix CVE-2020-7746
- Add more options to the report selector
- Set drawOnChartArea to false, instead of display: false.

fix: Upgrade chart.js to 2.9.4, fix grid-line option

---

app/views/api/v1/models/_app.json.jbuilder
spec/controllers/api/v1/accounts/integrations/apps_controller_spec.rb

fix: Slack integration redirect url missing client ID

---

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue

**Why**
Conversations with emails would push the right sidebar. Thereby cutting a part of the info on the sidebar.

fix: Fixes email overflow issue in conversation.

---

lib/woot_message_seeder.rb

- add an example for select inputs in chat bot form message
fixes: #2076

chore: Add select field example to woot seeder

---

.env.example
Gemfile
Gemfile.lock
config/environments/development.rb
config/environments/production.rb
config/routes.rb
spec/controllers/dashboard_controller_spec.rb
spec/rails_helper.rb

- ability to run Chatwoot as an API only server
- removes action cable testing gem since it is merged to rails 6

chore: ability to run Chatwoot as API only server

---

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue

This makes it easy to insert a canned response everywhere in the rich text editor.
Note: The simple text editor doesn't get this functionality. I'm creating a new pr for default to use rich-text-editor.
Fixes: #1542

enhancement: Adds support for canned command key everywhere on rich text editor

---

app/javascript/widget/views/Router.vue

fix: Disallow unread/campaign view if widget is active

---

app/actions/contact_merge_action.rb
spec/actions/contact_merge_action_spec.rb

When an agent updates a contact email in the dashboard, while the contact also update his email via the email collect box,
Merge action receives the same base and mergee contacts which could cause data corruption.

fix: Adds condition to handle base and mergee contact being same

---

app/controllers/api/v1/widget/messages_controller.rb
app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/components/widgets/conversation/helpers/botMessageContentHelper.js
app/javascript/dashboard/components/widgets/conversation/helpers/specs/botMessageContentHelper.spec.js
app/javascript/dashboard/i18n/locale/en/conversation.json
app/javascript/widget/components/AgentMessageBubble.vue

- Change the response content attribute from `feedback_text` to `feedback`.
- Render the response on the agent dashboard
Fixes #2471

feat: Show the CSAT response to the agent

---

deployment/setup_18.04.sh
deployment/setup_20.04.sh

Context:
`sks-keyserver.net` `gpg` pool is now deprecated due to GDPR issues and is no longer reliable. Switching to use ubuntu keyserver for the time being as this is the only server returning `rvm` maintainers `gpg` keys at the moment.
Quoting [sks-keyserver.net](https://sks-keyservers.net/status/) domain,
```
This service is deprecated. This means it is no longer maintained, and
new HKPS certificates will not be issued. Service reliability should not
be expected.
Update 2021-06-21: Due to even more GDPR takedown requests, the DNS
records for the pool will no longer be provided at all.
```
Change(s)
- Switch gpg keyserver being used to fetch rvm keys
Fixes #2508 
Tested on a fresh Ubuntu 20.04 instance. The script completes fully and Chatwoot …

fix: rvm gpg key issue

---

config/environments/production.rb

- Add missing cache-headers on the production config.

fix: Add missing Cache-Control headers in the production config

---

app/javascript/widget/components/AgentTypingBubble.vue

Fixes #914 
**Preview**
https://user-images.githubusercontent.com/64252451/124226532-e6a8e280-db26-11eb-8f7b-c27ac0694b3c.mov

bug: fixes typing indicator out of position in widget

---

app/models/contact.rb

Expose contact custom attributes in events so the external system can behave accordingly without triggering an  additional API call

chore: Expose contact custom attributes in events

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/scripts/setup.sh

Reduce the steps to spin up Codespaces
- use chatwoot base image
- script to set up the required .env file
- run `rake db:chatwoot_prepare` on init
updated instructions 
https://github.com/chatwoot/chatwoot/wiki/Using-chatwoot-codespace

chore: Reduce steps to spin up Codespaces

---

lib/integrations/dialogflow/processor_service.rb
spec/lib/integrations/dialogflow/processor_service_spec.rb

- Process every fulfilment message instead of the first one.
- Create multiple messages/actions based on the response
Fixes #2570

feat: Support messages along with the actions in Dialogflow response

---

lib/integrations/slack/incoming_message_builder.rb
spec/lib/integrations/slack/incoming_message_builder_spec.rb
spec/support/slack_stubs.rb

Use unescape while saving the response on Chatwoot.
**Before**
**After**
Fixes #2603 
Note: This PR is created and tested from Codespaces 👍

fix: Unescape Slack incoming messages

---

app/controllers/installation/onboarding_controller.rb
lib/chatwoot_hub.rb
spec/lib/chatwoot_hub_spec.rb

Chatwoot tracks usage of its products which helps the team to improve and deliver better software. You can opt-out of this telemetry at any time.
None of your customer data is ever transmitted by Chatwoot installation. The telemetry data collected by our products are purely usage statics of various software features. 
Our software onboarding screens may contain optional forms to subscribe to our product newsletters or a callback request. These inputs are completely optional and the user preferences updated in these onboarding steps are completely adhered to.
Chatwoot sends anonymised metadata to our telemetry instance at a defined interval. The following list contains the various attributes in this metadata. 
- Aggregated number various data models like users, accounts, labels, canned …

chore: Add Telemetry

---

app/javascript/dashboard/mixins/agentMixin.js
app/javascript/dashboard/mixins/specs/agentMixin.spec.js

fix: Disable "none" option from agent dropdown If agent is not selected

---

app/controllers/api/v1/accounts/conversations_controller.rb
app/javascript/dashboard/api/inbox/conversation.js
app/javascript/dashboard/api/specs/inbox/conversation.spec.js
app/javascript/dashboard/components/buttons/ResolveAction.vue
app/javascript/dashboard/constants.js
app/javascript/dashboard/i18n/locale/en/chatlist.json
app/javascript/dashboard/i18n/locale/en/conversation.json
app/javascript/dashboard/store/modules/conversations/actions.js
app/javascript/shared/components/ui/dropdown/DropdownSubMenu.vue
app/jobs/conversations/reopen_snoozed_conversations_job.rb
app/jobs/trigger_scheduled_items_job.rb
app/models/conversation.rb
app/models/message.rb
config/locales/en.yml
db/migrate/20210721182458_add_snoozed_until_to_conversations.rb
db/schema.rb
spec/controllers/api/v1/accounts/conversations_controller_spec.rb
spec/jobs/conversations/reopen_snoozed_conversations_job_spec.rb
spec/jobs/trigger_scheduled_items_job_spec.rb
spec/models/conversation_spec.rb
spec/models/message_spec.rb

`snoozed` conversation status will give the user the ability to remove inactive conversations from the primary open view. 
- Introduces a new conversation status snoozed
- Filter for accessing snoozed conversations
- Snoozed conversations are reopened when snooze_until time is reached
- Snoozed conversations are reopened when there is a new customer reply
fixes: #1582
https://user-images.githubusercontent.com/73185/126552245-e12302df-fb07-486e-959a-60dd4e16d2ce.mov

feat: Ability to snooze conversations

---

app/controllers/api/v1/accounts/custom_attribute_definitions_controller.rb
app/models/account.rb
app/models/custom_attribute_definition.rb
app/views/api/v1/accounts/custom_attribute_definitions/create.json.jbuilder
app/views/api/v1/accounts/custom_attribute_definitions/index.json.jbuilder
app/views/api/v1/accounts/custom_attribute_definitions/show.json.jbuilder
app/views/api/v1/accounts/custom_attribute_definitions/update.json.jbuilder
app/views/api/v1/models/_custom_attribute_definition.json.jbuilder
config/routes.rb
db/migrate/20210722095814_add_custom_attribute_definition.rb
db/schema.rb
spec/controllers/api/v1/accounts/custom_attribute_definitions_controller_spec.rb
spec/factories/custom_attribute_definitions.rb

- Add schema to store custom attribute definition
- Add APIs for CRUD operations on Custom Attribute Definitions
Fixes #2655

feat: Add APIs for custom attribute definitions

---

app/models/account.rb
app/models/channel/web_widget.rb
app/models/concerns/featurable.rb
app/models/notification_setting.rb
config/database.yml
docker/entrypoints/helpers/pg_database_url.sh

POSTGRES_PORT was not taking effect if provided separately
instead of using DATABASE_URL. This adds support for using
databases running on non-standard ports.
- Fix docker entry point for rails to respect `POSTGRES_PORT` setting
- Fix database.yml to respect `POSTGRES_PORT` setting
- Toggle flag_shitzu gem `check_for_column` to false
- Tested across a new Chatwoot Kubernetes deployment using Chatwoot helm package

fix: external db with non-standard port

---

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue

**Why**
- This pr will stop escaping markdown when passed down as props into editor component.
- Will fix issue blocked in #2577

fix:  Appending markdown as HTML into editor

---

app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/components/widgets/conversation/bubble/MailHead.vue
app/javascript/shared/helpers/MessageFormatter.js
app/javascript/shared/mixins/messageFormatterMixin.js
app/javascript/widget/components/UserMessage.vue

- Use `gfm:true, breaks: true` for marked rendering
- Add margin-bottom for `<p>` in widget messages
- Render text-only messages on email channel with markdown
Fixes #1730

fix: Render line-breaks properly in messages

---

app/javascript/dashboard/store/modules/conversations/actions.js
app/javascript/dashboard/store/modules/conversations/getters.js
app/javascript/dashboard/store/modules/conversations/index.js
app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js

While reviewing #2672, resolve and move next shortcut had troubles because the action was resolving the current conversation.

fix: Resolve conversation with id instead of current conversation

---

app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue

Updates icons on chatlist to show whether last message is 
- Reply
- Private note
- Activity

feat: Updates icons to show last message type

---

docker/entrypoints/helpers/pg_database_url.rb
docker/entrypoints/rails.sh

The `pg_database_url.sh` helper script (used in Docker entrypoint) wasn't working anymore because of a small syntax error.
This PR fixes this and also renames the file to have an appropiate extension (`.rb`).
Tested locally with own Docker image build.

fix: Fix and rename pg_database_url.sh helper script

---

app/javascript/dashboard/components/widgets/conversation/Message.vue
app/mailboxes/mailbox_helper.rb
app/presenters/mail_presenter.rb
spec/mailboxes/reply_mailbox_spec.rb
spec/mailboxes/support_mailbox_spec.rb
spec/presenters/mail_presenter_spec.rb

- Add a multipart flag to the email message model.
- Save content type to email message model
- Render line break if text/plain email.

fix: Save content_type, multipart information to email message model

---

app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue

-  Removes the multi-select agent dropdown from the conversation header.
-  By default changed the contact side panel from close to open.
**Before**
**After**

chore: Removes the multi-select dropdown from the conversation header

---

app/javascript/dashboard/components/widgets/conversation/bubble/File.vue

fix: Checks window object for null before focusing

---

app/javascript/sdk/sdk.js

fix: Fixes external css interference for widget bubble

---

app/drops/message_drop.rb
app/mailers/agent_notifications/conversation_notifications_mailer.rb
app/models/application_record.rb
app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb

Updated a template for the conversation_mention email. We have introduced in MessageDrop to get the message sender and message content in the template. This is not impacting other ConversationNotificationsMailer templates.
Fixes #2825 
1. Mention agent in the conversation, checked updated mail body. 
2. Assign agent and checked the relevant template if it's not impacted.

feat: Add message content to mention email template

---

.env.example
Gemfile
Gemfile.lock
config/initializers/datadog.rb
config/initializers/sentry.rb
config/newrelic.yml

Add the support for Newrelic and Datadog.
ref: https://www.chatwoot.com/docs/self-hosted/monitoring/apm-and-error-monitoring
fixes: #2861

chore: support for APMs

---

docker/Dockerfile

Chatwoot `webpack` docker for local setup was failing due to missing git binary.
- add git binary in chatwoot base image
- Tested on 20.04 Ubuntu instance

fix: chatwoot_webpack failure due to missing git

---

app/listeners/event_listener.rb
spec/builders/v2/report_builder_spec.rb

This change adds the missing conversation id for the first response event.
Fixes #2746
Verified conversation id in the first response event record created in DB using rails console.

Add missing conversation id for first response event

---

app/models/attachment.rb

- Attachment validation was supposed to affect the web widget channel only. But it was validating for all channels as well

chore: Attachment validation fix

---

app/mailboxes/application_mailbox.rb
app/mailboxes/support_mailbox.rb
spec/fixtures/files/support_without_sender_name.eml
spec/mailboxes/support_mailbox_spec.rb

Check the email channel case insensitive.
Fixes #2504 
Send an email to email channel and receive the message in email channel inbox

fix: Emails not delivered when case does not match

---

app/models/attachment.rb
lib/integrations/slack/incoming_message_builder.rb
lib/integrations/slack/send_on_slack_service.rb
spec/lib/integrations/slack/incoming_message_builder_spec.rb
spec/lib/integrations/slack/send_on_slack_service_spec.rb
spec/support/slack_stubs.rb

Slack was not able to process attachments, we chatwoot should be able to receive and send files.
Fixes https://github.com/chatwoot/product/issues/4
- Send an attachment through the slack channel check if we are able to see it in the chatwoot conversation
- Send an attachment to the slack channel check from chatwoot conversation.

feat: Support sending and receiving attachments in Slack Integration

---

app/javascript/shared/components/ChatOption.vue

Add CSS rules to ChatOption to make long options wrap instead of going outside of the chat bubble.
As requested by @pranavrajs I have raised a pull request regarding the option buttons in the chat widget going out of the chat bubble when they are long:
Old version:
New version:
**! As I don't know the code base very well, please verify if I didn't break something somewhere else !**
I have only tested this by editing the HTML source of my chat widget in the browser (via dev tools). **No rebuild of the source has been performed.**

Add option button CSS rules

---

app/javascript/dashboard/routes/dashboard/contacts/components/ContactLabels.vue
app/jobs/labels/update_job.rb
app/models/label.rb
app/services/labels/update_service.rb
spec/jobs/labels/update_job_spec.rb
spec/models/label_spec.rb
spec/services/labels/update_service_spec.rb

When a label is updated from the admin panel, it doesn't update the associated conversations and contacts. With this change, when a label title is changed, it would update the label list of conversation and contact.

fix: Update associations when a label is updated

---

app/controllers/api/v1/accounts/contacts_controller.rb
config/locales/en.yml
spec/controllers/api/v1/accounts/contacts_controller_spec.rb

Fix for Contact Imports API, it returns 200 success even if there is no file attached in the request
Fixes #3031 
- Bug fix (non-breaking change which fixes an issue).
Tried passing `import_file` param as `nil` in request payload and verified it.

fix: Add blank check for file param in Import API

---

app/views/api/v1/widget/configs/create.json.jbuilder
app/views/widgets/show.html.erb

At widget the timezone offset is sent but it doesn't take dst in mind. The problem is that at widget settings the offset is taken from the timezone itself and it has no context of the current date. Solution is to get the offset from a current date instance.
Fixes #2882

fix: Fixes offset issue for Business hours on timezones with DST

---

app/javascript/packs/sdk.js
app/javascript/sdk/IFrameHelper.js

The `window.$chatwoot.toggle();` provided in the SDK can be inadequate in some cases because there is no way to know the current status of the chatWindow whether it toggled close or open. 
So this change allows the user to explicitly pass the state to `window.$chatwoot.toggle();` function. which helps to open or close the chat window.
Fixes #3040
1. Create a new chat window using inbox Messenger Script.
2. window.$chatwoot.toggle(); should retains current behaviour
3. window.$chatwoot.toggle('close'); should close the window if open
4. window.$chatwoot.toggle('open;); should open window if closed

feat: Ability to close and reopen the chat window via SDK

---

app/javascript/dashboard/routes/dashboard/Dashboard.vue
app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue
app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js

As part of #3084, a key was added to router-view which forced re-render every time a URL is changed. This was done to force re-render report views.
To fix that:

fix: Update Re-rendering behaviour for lists in conversation view

---

app/javascript/dashboard/components/widgets/forms/Input.vue

Add a read-only attribute to woot-input component.
Fixes https://github.com/chatwoot/chatwoot/issues/3120
UI 
- [] I have added tests that prove my fix is effective or that my feature works

chore: Add readonly attribute to woot-input component

---

app/views/api/v1/models/_agent.json.jbuilder
spec/controllers/api/v1/accounts/csat_survey_responses_controller_spec.rb

CSAT reports page was failing to load when there is an assigned agent who got deleted.

fix: CSAT reports page failing to load

---

app/services/notification/push_notification_service.rb

By this time, push notifications won't awake the device if it is in sleeping mode. So if a customer sends a message and the agent's device is sleeping, no notificatión was show until device awakes.
In order to get a fast notification when a new conversation/message was created even if the device is sleeping, priority must be set as high. This behaviour will perform a better service as agent can get fastly notificated about new messages and conversations.

Chore: Fcm notification priority

---

app/javascript/shared/helpers/MessageTypeHelper.js

Twilio recommends 320 characters as an upper limit for SMS to ensure delivery. 
This changes the hardcoded message length limit for Twilio SMS messages from 160 to 320 in Chatwoot UI. 320 was chosen since it's the upper limit for SMS suggested by Twilio to ensure the best deliverability and user experience.
[Maximum Message Length with Twilio Programmable Messaging](https://support.twilio.com/hc/en-us/articles/360033806753-Maximum-Message-Length-with-Twilio-Programmable-Messaging)
The only downside is when messages are greater than 160 characters, concatenation  which is handled by Twilio automatic is necessary. This takes up 7 characters per segment  so only a  maximum of 153 characters using GSM encoding can be contained in each segment. This means a message of 320 characters with GSM …

Update Twilio SMS MSG Limit to 320 characters

---

app/builders/messages/instagram/message_builder.rb
app/services/instagram/send_on_instagram_service.rb
spec/services/instagram/send_on_instagram_service_spec.rb

When we send a welcome message to the Instagram user that message comes back again to save it in the Chatwoot inbox, we should consider a template message as a repeated message and neglect that.
Fixes #3196 
Tested on staging

Bug: Instagram render template message twice

---

app/jobs/conversations/activity_message_job.rb
app/listeners/action_cable_listener.rb
app/models/concerns/activity_message_handler.rb
app/models/concerns/assignment_handler.rb
app/models/conversation.rb
app/models/message.rb
spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
spec/models/concerns/assignment_handler_shared.rb
spec/models/conversation_spec.rb
spec/services/message_templates/hook_execution_service_spec.rb
swagger/paths/application/agents/create.yml
swagger/paths/application/agents/update.yml
swagger/swagger.json

- fix the wrong conversation status being sent in webhooks
- additional information in websocket events
- refactor activity messaging code 
- move activity message generation to background job to stop the callback loop

chore: Fix conversation status in webhooks

---

app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue
app/javascript/dashboard/i18n/locale/en/chatlist.json

The previous structure would let accidental translation of value for the chat status filter which causes unintentional breakages. 
fixes: #2552

chore: Fix translations breaking the chat filter

---

app/javascript/dashboard/api/inbox/message.js
app/javascript/dashboard/api/specs/inbox/message.spec.js

The payload was generating 'undefined' value in cc/bcc emails. As it is a string backend was not able to recognize whether it was a wrong string or not. 
Followup actions: @tejaswinichile Please add email validation on cc_emails, bcc_emails on the backend.

fix: Set cc, bcc default to empty string if unavailable

---

.env.example

Added `SMTP_TLS` and `SMTP_SSL` in .env.example
Fixes #3396

Fix 3396: Mention the env variables SMTP_TLS and SMTP_SSL in .env.example

---

app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue

- Use label title instead of id in the Filter API as per the changes made in #3418

fix: Pass label title instead of id to filter API

---

app/javascript/dashboard/components/CustomAttribute.vue

Before adding rich types in custom attributes, all the boolean values are stored in string format ("true"/"false"). This fix will render all these values in boolean format.
1. Create a new contact attribute with type **checkbox**
2. Set attribute via SDK method
Ex: 
```
window.$chatwoot.setCustomAttributes({
cloudCustomer: "false" // "true"
});
```
3. Check this attribute is rendering properly in the contact sidebar

fix: Render checkbox if string value passed 

---

config/schedule.yml
spec/configs/schedule_spec.rb

we had instances where after copy-pasting the schedule block, the dev forgets to change the schedule key,
This would break some of the scheduled jobs without explicit errors
this PR add a spec that will prevent

chore: validation spec for schedules

---

app/javascript/dashboard/components/SnackbarContainer.vue

A bug was introduced as a part of #3425, which blocked new alert messages.

fix: Update missing method onNewToastMessage

---

app/controllers/api/v1/accounts/contacts_controller.rb
app/controllers/concerns/request_exception_handler.rb
app/javascript/dashboard/i18n/locale/en/contact.json
app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
app/javascript/dashboard/store/modules/contacts/actions.js
app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js
app/javascript/shared/helpers/specs/CustomErrors.spec.js
spec/controllers/api/v1/accounts/contacts_controller_spec.rb

Fixed contact update alert message. Contact update API returns full original contact object without details about validation errors. For validation errors, I updated the error message with the field names which has errors.
Fixes #3476  (issue)
I tested with front-end app creating duplicated contact with phone number and emails and it shows correct error messages on both cases. I didn't touch other languages since I am able to handle only English.

Fix: Update contact validation messages

---

db/migrate/20211208085931_update_contact_inbox_foreign_key.rb
db/schema.rb

refer: https://www.bigbinary.com/blog/rails-6-1-allows-associations-to-support-destroy_async-option-with-dependent-key
`destroy_async option should not be used when the association is backed by foreign key constraints in the database`
So to resolve this I have added foreign key with `cascade: delete`

Fix: Add foreign key with delete cascade for destroy_async

---

app/controllers/api/v1/widget/contacts_controller.rb
app/drops/conversation_drop.rb
app/drops/message_drop.rb
app/helpers/message_format_helper.rb
app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
app/javascript/sdk/IFrameHelper.js
app/views/api/v1/widget/contacts/update.json.jbuilder
app/views/layouts/mailer/base.liquid
app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
spec/controllers/api/v1/widget/contacts_controller_spec.rb
spec/helpers/message_format_helper_spec.rb

- Fix handleNotificationDot throwing error if hideMessageBubble is true.
- Fix missing hideConversationActions
- Process hmac only for update calls and ignore if custom_attributes are present
- Send only valid attributes in the update call instead of the whole contact object
- Update the email design to match the 2.0 designs
- Add a text "Previous messages"

fix: Add fixes for sentry errors

---

app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
app/javascript/dashboard/assets/scss/widgets/_reports.scss
app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue

bug: Fixes irregular padding on agent selector in report page

---

app/models/notification.rb
spec/models/notification_spec.rb

- Added conversation display id in push payload for the notifications `conversation_creation` and `conversation_assignment`

chore: Add display id in conversation related push payload

---

app/mailboxes/reply_mailbox.rb
spec/fixtures/files/forwarder_email.eml
spec/fixtures/files/reply.eml
spec/fixtures/files/reply_mail_without_uuid.eml
spec/mailboxes/reply_mailbox_spec.rb

Instead of string, we consider array for in_reply_to mail header.
Fixes #3615
Change the string type to array for in reply to.

bug: NoMethodError: undefined method `match' for in_reply_to 

---

app/javascript/shared/components/FluentIcon/DashboardIcon.vue
app/javascript/shared/components/FluentIcon/Icon.vue
app/javascript/shared/components/FluentIcon/Index.vue

**Why**
Currently the component we use to render fluent icons does not support icon sources with multiple SVG paths.

feat: Adds multiple path support for icons

---

app/controllers/api/v1/notification_subscriptions_controller.rb
config/routes.rb
spec/controllers/api/v1/notification_subscriptions_controller_spec.rb

- Added delete notification subscription API for clearing all the push tokens when logged out from the mobile app (https://github.com/chatwoot/chatwoot-mobile-app/issues/430)

chore: Notification subscription delete API

---

app/javascript/dashboard/i18n/locale/en/conversation.json

Updated "email address" to "email addresses" in the Invite your team members guide.
Fixes #3671 
Grammatical error

Fix: Error with plurals in Invite members onboarding guide.

---

app/javascript/dashboard/i18n/locale/en/cannedMgmt.json

Removed extra space before "." as mentioned in the issue: https://github.com/chatwoot/chatwoot/issues/3669
Fixes # (3669)
Fixed a typo
Replication steps:
1. Open "Add Canned Responses" modal.
2. Refer to the description of modal under the title.
3. There is an extra space before "." in the description.

Fixed spacing issue as per - Issue 3669

---

app/javascript/packs/sdk.js

fix: Return if window.$chatwoot is already defined

---

app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue

The secondary sidebar does not show an active page for the inbox, teams, integrations, applications settings page.
**Fixes** https://github.com/chatwoot/chatwoot/issues/3842
**Screen recording** 
https://user-images.githubusercontent.com/64252451/151338402-3775480b-760b-4061-a5de-8c1950727e4d.mov

bug: Fixes sidebar does not show an active page for settings page

---

app/controllers/platform/api/v1/users_controller.rb
app/javascript/dashboard/routes/login/Login.vue
spec/controllers/platform/api/v1/users_controller_spec.rb

- Add URL encoding for the params in platform API calls.
Fixes [product#307](https://github.com/chatwoot/product/issues/307)
Fixes: #2186

fix: URL encode params on Platform API call

---

app/javascript/dashboard/components/ChatList.vue
app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue

Fixes filter API calls failing issue after merging this PR https://github.com/chatwoot/chatwoot/pull/3926, when we open a newly saved folder. And will break the existing saved filter.

Fixes API call failing after opening the saved filter

---

docker/Dockerfile

Docker builds was failing as `nokogiri` gem failed to compile.
Nokogiri gem depends on `libxml2` and `libxslt` which is now compressed with `xz`. Previous releases of these libraries were gzipped. As we are compiling gems natively, `xz` needs to be installed.
Fixes #4045
- 20.04 instance
- dockerhub CI

fix: nokogiri gem build failure in docker

---

app/javascript/packs/sdk.js
app/javascript/sdk/IFrameHelper.js

- Added a resetTriggered flag to check if the loaded event was triggered by a reset method. 
- If resetTriggered, the ready event will not be fired again.
Fixes #3963, #3918

fix: Add resetTriggered flag to fix reset loop

---

app/controllers/api/v1/accounts/conversations/messages_controller.rb
spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb

Delete the contents of content attributes while deleting a message.
#4151

fix: Delete content_attributes in message destroy API

---

app/javascript/sdk/sdk.js

Reduce the campaign height in case of smaller text messages.

fix: Reduce the height of the unread container while campaign is active

---

app/javascript/dashboard/assets/scss/_foundation-custom.scss

Adds monospace fonts for Linux systems.

System default monospace fonts for code elem

---

app/models/concerns/activity_message_handler.rb
spec/controllers/api/v1/widget/messages_controller_spec.rb

Fixes the bug which triggered "Contact resolved conversation" activity messages when snoozed conversations were reopened

chore: Disable invalid contact resolved activity messages

---

app/controllers/platform/api/v1/users_controller.rb

I just happened to notice this. Was it intentional that this could fail silently?  I don't think there's a probable scenario right now where it actually would fail, but seems like it might be good to use the bang version by default if we're not checking the return value?

chore: Use bang version of "find_or_create_by!" in Plaform UsersController

---

config/initializers/mailer.rb

Fixes https://github.com/chatwoot/chatwoot/issues/4247.
This line in `config/initializers/mailer.rb`:
https://github.com/chatwoot/chatwoot/blob/86b4183bdedb363b5b4a8020be40cda93cdd6498/config/initializers/mailer.rb#L31-L32
was overriding this setting from `config/environments/test.rb`:
https://github.com/chatwoot/chatwoot/blob/86b4183bdedb363b5b4a8020be40cda93cdd6498/config/environments/test.rb#L45
but we want to keep `delivery_method = :test` in the test env.

Don't override "action_mailer.delivery_method" in the test env

---

app/javascript/widget/assets/scss/views/_conversation.scss
app/javascript/widget/components/AgentMessage.vue

Adds visualization in the form of an audio player inside the Widget.
Fixes #3603
https://github.com/chatwoot/chatwoot/issues/3603
Sent an audio type attachment.
Audio recorded.
Attached photo type.
Sent PDF attachment

feat: support audio player on widget

---

app/controllers/api/v1/accounts/agent_bots_controller.rb
app/controllers/api/v1/accounts/agents_controller.rb
app/controllers/api/v1/accounts/campaigns_controller.rb
app/controllers/api/v1/accounts/canned_responses_controller.rb
app/controllers/api/v1/accounts/contacts/notes_controller.rb
app/controllers/api/v1/accounts/custom_attribute_definitions_controller.rb
app/controllers/api/v1/accounts/custom_filters_controller.rb
app/controllers/api/v1/accounts/inboxes_controller.rb
app/controllers/api/v1/accounts/integrations/hooks_controller.rb
app/controllers/api/v1/accounts/integrations/slack_controller.rb
app/controllers/api/v1/accounts/kbase/categories_controller.rb
app/controllers/api/v1/accounts/kbase/portals_controller.rb
app/controllers/api/v1/accounts/labels_controller.rb
app/controllers/api/v1/accounts/teams_controller.rb
app/controllers/api/v1/accounts/webhooks_controller.rb
app/controllers/api/v1/notification_subscriptions_controller.rb
app/controllers/platform/api/v1/account_users_controller.rb
app/models/team.rb
spec/controllers/api/v1/widget/messages_controller_spec.rb
spec/models/conversation_spec.rb

There are not many ways for `destroy` to fail, but it seems best to use the bang version by default when not checking the return value.

Use "destroy!" instead of "destroy" when not checking the return value

---

spec/controllers/super_admin/app_config_controller_spec.rb

This was generating a warning:
Using `should` from rspec-expectations' old `:should` syntax without
explicitly enabling the syntax is deprecated. Use the new `:expect` syntax
or explicitly enable `:should` with `config.expect_with(:rspec) { |c|
c.syntax = :should }` instead.

Eliminate deprecation warning in "app_config_controller_spec.rb"

---

app/models/account.rb
spec/models/account_spec.rb

Conversation and campaign sequences persist in the database even after the related account is deleted. This PR adds an `after_desttory` callback on the account model that will delete the associated sequences.
Fixes #4252 

fix: drop conv and campaign seq on account delete

---

app/controllers/platform/api/v1/users_controller.rb
spec/controllers/platform/api/v1/users_controller_spec.rb

Call `skip_confirmation!` before saving the user (instead of `confirm` after
saving the user) so that the user is marked as confirmed already and the
confirmation email isn't sent.
The platform api automatically confirms users so we don't need to send this
email.

Don't send confirmation email when creating User via platform api

---

app/builders/v2/report_builder.rb
spec/controllers/api/v2/accounts/report_controller_spec.rb

I noticed this because I was getting test failures in `spec/controllers/api/v2/accounts/report_controller_spec.rb` running the tests locally on my laptop.
- ReportBuilder wasn't using the specified time zone for the timestamp in the
"build" method
- The ReportController spec was calling `Time.zone.today.to_time`, but
that sequence loses time zone information because `today` is a Date and
Dates don't have time zones in Ruby, so the time ended up in the system
time start-of-date instead of the `Time.zone` start-of-date.

Timezone fixes for ReportBuilder and for ReportController spec

---

app/models/account.rb

Account support_email should give priority to environment variables over installation config
Fixes: #3304

chore: Support Email should give priority to environment variable

---

app/builders/v2/report_builder.rb
app/javascript/dashboard/assets/scss/widgets/_report.scss
app/javascript/dashboard/components/widgets/ReportStatsCard.vue
app/javascript/dashboard/components/widgets/chart/BarChart.js
app/javascript/dashboard/i18n/locale/en/report.json
app/javascript/dashboard/mixins/reportMixin.js
app/javascript/dashboard/mixins/specs/reportMixin.spec.js
app/javascript/dashboard/mixins/specs/reportMixinFixtures.js
app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
app/javascript/dashboard/routes/dashboard/settings/reports/constants.js
spec/builders/v2/report_builder_spec.rb

This change allows the user to understand how many conversations are used for the calculation of the below metrics in reports.
1. First Response Time
2. Resolution Time
Fixes #4041
https://user-images.githubusercontent.com/5848740/159978918-6d802dd5-3f4c-4285-874c-6f59c568fd5d.mp4

feat: Display how many conversations are considered for the metric calculation

---

app/javascript/dashboard/i18n/locale/en/contact.json
app/javascript/dashboard/modules/notes/components/ContactNote.vue

Add a confirmation note before deleting a note about a contact #4124
- Login to to any user (e.g john@acme.inc)
- Go to contact menu, then choose on of the contact to see contact detail panel
- Add notes to the contact
- Click trash button on the right top corner of the note, the pop up confirmation should appear
- Click button with label "Yes, Delete", the note must be deleted
- Click button with label "No, keep:, the note must be keep

feat: Add a confirmation note before deleting a note about a contact

---

.circleci/config.yml
app/models/concerns/assignment_handler.rb
app/services/round_robin/assignment_service.rb
app/services/round_robin/manage_service.rb
spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
spec/services/round_robin/manage_service_spec.rb

Before this change, auto-assignment in teams wasn't using round-robin service.
Hence the agent's online, offline status wasn't respected by auto-assignment.
This change will make teams give priority to online agents for assignments.
fixes: https://github.com/chatwoot/product/issues/356

chore: Use Round Robin service for team assignment

---

.circleci/config.yml

CircleCI has deprecated old docker images in favour of their next-gen images published under a new registry. This PR switches the docker images used by Chatwoot to next-gen images from CircleCI.
ref: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
Fixes https://github.com/chatwoot/product/issues/353 

chore: Upgrade to next gen docker convenience image

---

deployment/setup_20.04.sh

- Modify Linux installation to be non-interactive (can be run unattended after initial selection)
This PR changes the LetsEncrypt behaviour to be non-interactive. Earlier, the installation flow was waiting for user input at the SSL cert generation stage. With this change, once the user confirms completes the initial selection, the installation can be completed unattended.

feat: make linux  installation non-interactive

---

spec/listeners/action_cable_listener_spec.rb

I noticed this failure while running tests:
```
1) ActionCableListener#message_created sends message to all hmac verified contact inboxes
Failure/Error: ::ActionCableBroadcastJob.perform_later(tokens.uniq, event_name, payload)
#<ActionCableBroadcastJob (class)> received :perform_later with unexpected arguments
expected: (["YToPaCn8hv2nDGAJTaswm1QS", "jnMSLHxjzw2kZfiLNM3c5ZPS", "SijhChPd2yAef4BbecVVXYm9", "4A4XR7TeDf6rRSSz6CAzLKrx"], "message.created", {"account_id"=>914, :account_id=>914, "content"=>"Incoming Message", "content_attributes"=>{}, "conte...ype"=>"User", "source_id"=>nil, "status"=>"sent", "updated_at"=>2022-04-02 12:19:45.276596000 +0000})
got: (["YToPaCn8hv2nDGAJTaswm1QS", "jnMSLHxjzw2kZfiLNM3c5ZPS", "4A4XR7TeDf6rRSSz6CAzLKrx", "SijhChPd2yAef4BbecVVXYm9"], …
```

Fix test failure in action_cable_listener_spec.rb due to ordering

---

app/views/api/v1/widget/messages/index.json.jbuilder
spec/controllers/api/v1/widget/messages_controller_spec.rb

fix: Skip `contact_last_seen_at` in empty conversation payload

---

.github/workflows/run-foss-spec.yml
app/presenters/mail_presenter.rb
spec/fixtures/files/non_utf_encoded_mail.eml
spec/presenters/mail_presenter_spec.rb

> The Action mailbox presenter was deciding mail.body without considering the mail content type.
> If mail encoding in base64 and non-UTF-8 charset, `mail.body.decoded` decodes the entire mail without knowing the mail body encoding type, and then when we encode it to UTF-8 it encodes it to invalid characters.
> mail.decoded actually works on mail decoding by checking the mail content type, so it decoded the mail body properly from the US-ASCII and then encode it to UTF-8
Fixes #4381 
Test Cases

Fix: handling UTF encoded mail

---

app/helpers/api/v1/inboxes_helper.rb
app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
app/javascript/dashboard/routes/dashboard/settings/inbox/ImapSettings.vue
app/javascript/dashboard/routes/dashboard/settings/inbox/SmtpSettings.vue
app/jobs/inboxes/fetch_imap_emails_job.rb
app/mailers/conversation_reply_mailer.rb
app/mailers/conversation_reply_mailer_helper.rb
app/models/channel/email.rb
app/views/api/v1/models/_inbox.json.jbuilder
config/schedule.yml
db/migrate/20220409044943_rename_imap_email_and_smtp_email_columns.rb
db/schema.rb
spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
spec/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb
spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
spec/mailboxes/imap/imap_mailbox_spec.rb
spec/mailers/conversation_reply_mailer_spec.rb

This change allows the user to use email, username, and API key for configuring IMAP and SMTP.
Also, users can send emails using the inbox mail address with SMTP.
Fixes #3544
1. Verified conversation continuity using IMAP & SMTP.
2. Added spec to validate the change.

fix: Remove IMAP and SMTP email validation

---

app/javascript/dashboard/i18n/locale/en/signup.json
app/javascript/dashboard/routes/auth/Signup.vue
app/javascript/shared/helpers/Validators.js
app/javascript/shared/helpers/specs/ValidatorsHelper.spec.js

Fixes #4209 & https://github.com/chatwoot/product/issues/398
**Validation**
`Before`
1. Minimum length for a password is 6.
`After`
1. Minimum length for a password is 6.
2. Must include one capital letter.
3. Must include one small letter.
4. Should include one numerical value between `0-9`.
5. Must include one special character like `[!@#$%^&*()_+\-=[\]{}|'"/\\.,``<>:;?~]`

feat: Adds the ability to validate password at signup

---

app/jobs/data_import_job.rb
app/listeners/action_cable_listener.rb
app/models/contact.rb
db/migrate/20220418094715_remove_contact_pubsub_token.rb
db/schema.rb
spec/jobs/data_import_job_spec.rb
spec/listeners/action_cable_listener_spec.rb

When we migrated the pubsub tokens from contact to contact inboxes, we missed out on doing this update for the typing indicator events. Hence the agent typing events weren't visible on the widget side. This change fixes that as well as removes the necessary column contact pubsub token from the model.
fixes: #4476

fix: Agent typing indicator for website widget

---

app/builders/messages/message_builder.rb
app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
app/listeners/automation_rule_listener.rb
app/models/automation_rule.rb
app/services/automation_rules/action_service.rb
app/services/automation_rules/conditions_filter_service.rb
spec/listeners/automation_rule_listener_spec.rb

Conversation contact-based conditions should work on the message event, and contact conditions should work on the conversation event.
Right now we consider the respective model to apply the conditions on the automation rule.
Fixes #4459 
Tested locally and through test cases.

feat: Add support for conversation attribute automation conditions in message event

---

app/builders/v2/report_builder.rb
app/javascript/dashboard/i18n/locale/en/report.json
app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
app/javascript/dashboard/routes/dashboard/settings/reports/constants.js
spec/controllers/api/v2/accounts/report_controller_spec.rb

This change restricts the agent conversations metrics query to show data from the current account.
Fixes #4556
https://user-images.githubusercontent.com/5848740/165285615-0c419e44-9279-4b0e-b9bb-80da8522cad4.mp4

fix: Update agent metrics query to show data from current account

---

.env.example
Gemfile.lock
config/newrelic.yml

Newrelic gem 8.7 has application log forwarding support and
this is enabled by default. Update the gem to make use of this
feature. Chatwoot has turned this off by default though.
Set `NEW_RELIC_APPLICATION_LOGGING_ENABLED` to enable 
this feature. Make sure to disable any other log forwarding services
you have to prevent duplicated logs.
ref: https://docs.newrelic.com/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-870
Fixes #4625 
- Using this config in Chatwoot hub.

chore: update newrelic gem to support log forwarding

---

app/javascript/dashboard/components/layout/Sidebar.vue
app/javascript/dashboard/components/layout/sidebarComponents/AccountContext.vue
app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
app/javascript/dashboard/i18n/locale/en/settings.json
app/javascript/shared/assets/stylesheets/shadows.scss

When multiple accounts are present and the "Currently viewing" div is viewable, my assumption was that I could click on that div to change which account I was viewing. Instead I found that the account switcher was somewhat hidden under the "Profile Settings" menu.
This PR makes the "Currently viewing" div also clickable for switching accounts
**Note:**
- I'm a complete newbie to Vue and I focus more on backend code in general. I may be doing things incorrectly.
- I don't know if making the whole thing a blue link is the ideal styling we'd want?
I'm happy to make changes if this looks OK in general, just lmk (or feel free to just add changes).
Fixes #4632
I tried it out locally.

Open "Switch Account" modal when clicking account name on dashboard

---

lib/integrations/slack/incoming_message_builder.rb
spec/lib/integrations/slack/incoming_message_builder_spec.rb

Interpreter error for `nil.any?` added `nil.present?`
Fixes https://sentry.io/share/issue/48c10d26490f4bdaab78c82244fcea98/
Tested with a test case: slack message without supported message and without event[:files]

Fix: sentry issue for slack incoming files check

---

app/controllers/platform/api/v1/users_controller.rb
spec/controllers/platform/api/v1/users_controller_spec.rb

When the platform update API is called with a new user email, Chatwoot will still follow the same behaviour as in the dashboard where the user will have to confirm the new email activation link until the email gets updated on the user record.
In the case of platform APIs, this might not be the ideal behaviour since the original app will already have a flow to update the user emails. Hence we need to confirm the emails without the extra step in this case
fixes: #4510

chore: Ability to update user email via Platform APIs

---

app/controllers/api/v1/widget/base_controller.rb
app/controllers/api/v1/widget/conversations_controller.rb
spec/controllers/api/v1/widget/conversations_controller_spec.rb

fix: Revert changes to fix name updation from pre-chat form

---

Gemfile
Gemfile.lock

`flay` and `rspec` are development dependencies of the `devise-secure_password` gem. It shouldn't generate an error message ideally if we have not installed it. So, I made a change [here](https://github.com/chatwoot/devise-secure_password/commit/d777b04f12652d576b1272b8f39857e3e0b3fc26) to avoid that. 
These 2 gems create a lot of warnings on the M1 mac. This PR removes these gems.

chore: Remove flay, rspec from development/test group

---

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
app/javascript/dashboard/store/modules/inboxes.js
app/models/channel/api.rb
app/models/message.rb
app/views/api/v1/models/_inbox.json.jbuilder
db/migrate/20220610091206_add_additional_attributes_to_api_channel.rb
db/schema.rb

- Save message templates in the additional attributes in the API inbox
- Render template selector if message templates are present

chore: Add support for message_templates in API inbox

---

app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
app/javascript/shared/helpers/Validators.js
app/models/inbox.rb
db/migrate/20220616154502_remove_special_characters_from_inbox_name.rb

Revert #4883
PR #4883 tried to remove special characters from the inbox name. It broke in the Chatwoot Cloud as there were inboxes with valid special characters. We had to push a temporary fix to continue the deployment by removing the logic from the migration. This PR reverts the changes done in #4883

chore: Revert the migration for inbox name changes

---

app/models/concerns/sort_handler.rb
app/models/conversation.rb
app/models/mention.rb
spec/models/conversation_spec.rb
spec/models/mention_spec.rb

I have faced the issue where I have no conversations with the last message as an incoming message, all were either activity messages or template messages, because of the previous change it sent an empty conversation list which is the wrong result. So to fix this
1.  I have removed the filer i.e `where clause` from the sort query.
2. Added sort based on message_type and message created_at on the conversation table. 

fix: last incoming message sort

---

app/javascript/dashboard/routes/auth/Signup.vue

To reduce the effort to signup, we would try to keep the fields to a minimum in the signup form. As a first step, I'm removing the confirm password option. It seems redundant. Even if the user forgets the password, they can reset it easily.
@iamsivin / @muhsin-k / @fayazara I did a quick test on the local machine, it seems to be working fine without issues.

chore: Remove confirm password in the account signup step

---

app/builders/messages/messenger/message_builder.rb

1. when Instagram story is deleted
2. We try to fetch the attachment and story link for the same from the background job
3. FB raises the `Koala::Facebook::ClientError` error and then the story mention_id is empty.
Which causes https://sentry.io/organizations/chatwoot-p3/issues/3253162714/?project=6382945&query=is%3Aunresolved#context-sidekiq

fix: Fixing message create issue for deleted instagram story

---

app/builders/messages/instagram/message_builder.rb
app/builders/messages/messenger/message_builder.rb
config/locales/en.yml
spec/builders/messages/instagram/message_builder_spec.rb
spec/factories/instagram/instagram_message_create_event.rb
spec/jobs/webhooks/instagram_events_job_spec.rb

Fixing: https://sentry.io/share/issue/930fed19b99d4f45a95c13c1f2e60652/
This known exception that Facebook throws when we are fetching the deleted story data. So instead of logging this to sentry, we are logging it to rails logger as we can not handle or resolve this issue from our end.
```
type: OAuthException, code: 9000001, message: (#9000001) This Message has been deleted by the user or the business., x-fb-trace-id: AH8KdfvtSee [HTTP 400]
```

fix: Handling facebook client error for deleted story

---

app/javascript/dashboard/i18n/locale/en/contactFilters.json

Adds missing i18n key for referrer link attribute in filters.

Fix: Add missing referrer-link key for i18n

---

config/puma.rb

fixes the console warning 
```
backend  | [29359] ! WARNING: Detected running cluster mode with 1 worker.
backend  | [29359] ! Running Puma in cluster mode with a single worker is often a misconfiguration.
backend  | [29359] ! Consider running Puma in single-mode (workers = 0) in order to reduce memory overhead.
backend  | [29359] ! Set the `silence_single_worker_warning` option to silence this warning message.
backend  | [29359] - Worker 0 (PID: 29412) booted in 0.04s, phase: 0
```

chore: Fix puma configuration

---

app/services/filter_service.rb
spec/services/conversations/filter_service_spec.rb

We are getting custom_attribute_type as an empty string so the filter was failing.
1. less_than and greater_than were not working because the OR operator wasn't working on an empty string
2. added presence check for custom_attribte_type
Fixes: 
https://sentry.io/organizations/chatwoot-p3/issues/3252991467/?project=6382945&query=StatementInvalid&statsPeriod=14d
https://sentry.io/organizations/chatwoot-p3/issues/3381238789/?project=6382945

fix: Conversation filter on dates

---

app/controllers/api/v1/accounts/channels/twilio_channels_controller.rb
app/models/channel/twilio_sms.rb
spec/controllers/api/v1/accounts/channels/twilio_channels_controller_spec.rb
spec/models/channel/twilio_sms_spec.rb

According to this: https://github.com/chatwoot/chatwoot/blob/develop/app/models/channel/twilio_sms.rb#L31 messaging_service_id should work if phone number is nil.
But we are getting the ""/empty/non_null value from the UI that's why this validation is not working.
Made the changes to receive nil value while creating the twilio inbox.

fix: Twilio validation over blank messaging_service_sid

---

enterprise/app/controllers/enterprise/api/v1/accounts_controller.rb
spec/enterprise/controllers/enterprise/api/v1/accounts_controller_spec.rb

- Do not enqueue job to create a customer if it is already enqueued

fix: Do not enqueue job if it is already enqueued

---

app/controllers/api/v1/widget/base_controller.rb
app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/languages.js
app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/specs/advancedFilterItems.spec.js
app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/specs/languages.spec.js
app/javascript/dashboard/i18n/locale/en/contact.json
app/javascript/dashboard/routes/dashboard/conversation/ConversationInfo.vue

- Add missing attribute in additional_attributes
- Display browser_language in the sidebar.
- Update the language list to use everything.

fix: Update browser_language logic to include all languages

---

config/routes.rb
enterprise/app/controllers/enterprise/webhooks/stripe_controller.rb
spec/enterprise/controllers/enterprise/webooks/stripe_controller_spec.rb
spec/enterprise/services/enterprise/billing/handle_stripe_event_service_spec.rb

note: 
This will require a slight change in the webhook URL of stripe right after deploy
( to confirm with the URL schema of other webhooks which we use )

chore: Add specs for stripe Webhooks endpoint

---

app/builders/account_builder.rb
app/controllers/api/v1/accounts_controller.rb
app/controllers/platform/api/v1/accounts_controller.rb
app/views/api/v1/accounts/create.json.jbuilder
db/migrate/20220720123615_set_default_locale_at_accounts.rb
db/schema.rb
spec/controllers/api/v1/accounts_controller_spec.rb
spec/controllers/platform/api/v1/accounts_controller_spec.rb
spec/models/account_spec.rb

Setting Account default language in the account created via API.
Fixes #4855 
Tested with the test cases

fix: Set account default language in account API

---

lib/online_status_tracker.rb
spec/lib/online_status_tracker_spec.rb

Previously round-robin conversation assignment logic wasn't considering the case where the Agent who had auto-offline config set as false.
fixes: #4780

chore: Round-robin should consider auto-offline false config

---

app/controllers/concerns/ensure_current_account_helper.rb
app/controllers/concerns/website_token_helper.rb
app/controllers/widgets_controller.rb
app/dashboards/account_dashboard.rb
app/javascript/dashboard/helper/routeHelpers.js
app/javascript/dashboard/helper/specs/routeHelpers.spec.js
app/javascript/dashboard/i18n/locale/en/settings.json
app/javascript/dashboard/routes/dashboard/dashboard.routes.js
app/javascript/dashboard/routes/dashboard/suspended/Index.vue
app/javascript/dashboard/routes/index.js
app/javascript/dashboard/routes/index.spec.js
app/models/account.rb
app/views/api/v1/models/_account.json.jbuilder
app/views/api/v1/models/_user.json.jbuilder
db/migrate/20220802133722_add_status_to_accounts.rb
db/schema.rb
spec/controllers/api/base_controller_spec.rb
spec/controllers/api/v1/widget/configs_controller_spec.rb
spec/controllers/widgets_controller_spec.rb
spec/factories/accounts.rb

Fixes #5173 
- Added a new field status (default: active, supports :suspended)
- Added a check in the controllers to see if the account is active.
- Added a check in the UI to see if the account is active.
Loom: https://www.loom.com/share/aba2f49fdc6d497c87db776b0d67ce4f

chore: Allow super admin to suspend an account

---

app/javascript/dashboard/components/widgets/Thumbnail.vue
app/javascript/shared/helpers/emoji.js
app/javascript/shared/helpers/specs/Emoji.spec.js

Fixes https://github.com/chatwoot/chatwoot/issues/5176
**Screenshot**
| **Before**                                                                                                                                     | **After**                                                                                                                                      |
| ------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------ |
| ![SCR-20220803-cz5](https://user-images.githubusercontent.com/64252451/182520978-df1fb517-3b0c-43e7-a693-841457da65ae.png) | …

fix: Avatar renders an incorrect symbol if it has emoji

---

enterprise/app/services/enterprise/billing/handle_stripe_event_service.rb

- Stop returning 500 to stripe so that invalid events are not reprocessed.

chore: Skip reprocessing invalid stripe events

---

.github/workflows/lock.yml

We often have cases where users would comment over stale closed Github Issues.
This creates unnecessary noise for the original reporter and makes it harder for triaging.
This action locks the closed threads once it is inactive for over a month.
fixes: https://github.com/chatwoot/product/issues/421

chore: Lock closed threads automatically

---

app/builders/notification_builder.rb
spec/builders/notification_builder_spec.rb

This issue occurs when the conversation assignee is removed from an account, but the assignment persists. This leads to an error when we try to fetch the user's notification settings associated with that account.
fixes: #5223

fix: assigned_conversation_new_message? NoMethod error

---

app/services/notification/push_notification_service.rb

Right now, if 2 messages are sent in an assigned conversation, we will only see one browser push notification. This is happening because the tag generated is not unique and is the same for both notifications. `new_message_{conversation_id}`
This PR updates the logic to generate a unique tag.
Fixes https://github.com/chatwoot/satisfilabs/issues/19

chore: Add notification ID to tag to make it unique

---

app/models/team.rb
app/presenters/conversations/event_data_presenter.rb
spec/models/conversation_spec.rb
spec/presenters/conversations/event_data_presenter_spec.rb

When we assign a team via API, it was not auto-populating on UI.
The issue was, that our broadcast push_event_data wasn't containing the team information.
Fixes https://github.com/chatwoot/satisfilabs/issues/29
Tested on local and via test cases.

fix: Auto populate team after assigned via API

---

app/jobs/migration/remove_stale_notifications_job.rb

The job which we introduced recently for removing the stale migrations
would time out in instances with a large amount of deleted data.
So improving it for better memory utilization.

chore: Improve memory usage in RemoveStaleNotificationsJob

---

.env.example

The Linux installer is failing at the database migration stage for fresh `v2.8.0` installations. This is due to the empty `POSTGRES_DATABASE` variable from the `.env` file.
This does not affect docker and kubernetes installations.
Fixes #5281 
ref: https://github.com/chatwoot/chatwoot/runs/7869274506?check_suite_focus=true#step:6:31
- Tested on a fresh instance

hotfix: linux installation failure due to empty database name

---

app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue

Allow dashboard app frames to query information after the load event. Following [this tweet](https://twitter.com/ericmigi/status/1560321001405050880), the Tooljet team and I did a sync-up to figure out why the events are not working.
- Dashboard Apps expected the message event to be registered on the load event.
- The Tooljet Apps had delayed loading. Their main page would fire the load event even before the event listeners were registered.
- There needed a way to query the information after the page was loaded.
With this change, the child iframe pages can send an event `chatwoot-dashboard-app:fetch-info` using postMessage. Then Chatwoot would respond with the appContext payload.

feat: Allow Dashboard App Frames to query the information 

---

app.json
db/schema.rb

fix: heorku deploy failure

---

app/javascript/dashboard/routes/dashboard/helpcenter/components/AddCategory.vue
app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalCustomization.vue
app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
app/javascript/dashboard/store/modules/helpCenterPortals/index.js
app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
app/javascript/dashboard/store/modules/helpCenterPortals/specs/actions.spec.js
app/javascript/dashboard/store/modules/helpCenterPortals/specs/fixtures.js
app/javascript/dashboard/store/modules/helpCenterPortals/specs/getters.spec.js
app/javascript/dashboard/store/modules/helpCenterPortals/specs/mutations.spec.js

1. Our store was designed in a way that 'id' will be the key to query from store but our routes have only `portalSlug`. To solve this there was an additional code `selectedPortalId`. I have remove this and now this uses portal slug instead of id to query.
2. Cleans route files and renamed params `portal_slug`

chore: Moves portal slug as ID to query resources in vue store

---

app/models/account_user.rb
app/services/agents/destroy_service.rb
spec/services/agents/destroy_service_spec.rb

Unassign agents from the conversation when they are removed from the account.
Fixes #4555
Tested manually

fix: un-assign agent from conversation after removal

---

app/services/instagram/message_text.rb
spec/factories/instagram/instagram_message_create_event.rb
spec/jobs/webhooks/instagram_events_job_spec.rb

Fixes: #5508 
We can not read contact information, because of this error, as the messages are echo messages when the sender sends the message to contacts and we don't have the consent of the user until and unless they send messages to us.
So after this result to get information about the contact is empty and we are trying to create a contact inbox for the same and the error appears.
type: OAuthException, code: 230, message: (#230) User consent is required to access user profile, x-fb-trace-id: AaitxF/whwY [HTTP 403] (Koala::Facebook::ClientError)

fix: contact is not available for inaccessible sender

---

.github/workflows/publish_foss_docker.yml

`arm64` build is failing at the asset:pre-compile stage. This usually happens due to instance mem/CPU requirements not being met. Reverting this change for now.
- gh action

chore: revert arm64 docker build in gh action

---

app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
app/javascript/shared/components/ui/dropdown/DropdownItem.vue

**Changes**
- Uses woot-button for message context menu dropdown 
- Changes minimum bubble width

chore: Add woot button to message context menu

---

app/javascript/widget/components/PreChat/Form.vue

Now it will show the validation error message for the checkbox if the required field is enabled.
Fixes https://github.com/chatwoot/chatwoot/issues/5576
**Screenshot**

fix: Added validation for checkbox

---

app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue

**Why**
We recently made the category name in the article table clickable. This introduced an overflow issue for long category names.

Fix: Fixes overflow issue for category name in article list

---

app/controllers/api/v1/widget/conversations_controller.rb
spec/controllers/api/v1/widget/conversations_controller_spec.rb

Fixes https://github.com/chatwoot/product/issues/601

fix: Discard invalid contact attributes in widget conversation end point

---

app/javascript/shared/helpers/AudioNotificationHelper.js

See #4942. We've also had a number of crash reports show up in our logs related to this. Typically we see "undefined is not a constrcutor" because `window.AudioContext || window.webkitAudioContext` returns `undefined`.
Fixes #4942.

Avoid crashing when `AudioContext` is not available.

---

app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue

**Why**
When the switch account item from the profile menu is clicked, it was not showing up.

fix: Show account switch modal from portal dashboard

---

app/models/conversation.rb

- remove extra dispatch for label updates

chore: Stop duplicate socket updates for conversation update

---

app/javascript/widget/components/ChatInputWrap.vue

Fixes #5722 
**Before**
**After**

bug: Fixes width overflow issue with emoji selector in widget

---

app/services/macros/execution_service.rb
spec/controllers/api/v1/accounts/macros_controller_spec.rb

- For event send_message and send_attachment set message sender to the macro executer
Fixes #5731 
- Added test cases for the same

fix: Set message sender to macros excution

---

db/seeds.rb

run: `docker-compose run --rm rails bundle exec rails db:chatwoot_prepare` error: field contact_inbox is undefine

fix: db/seeds.rb field contact_inbox is undefined

---

config/initializers/01_redis.rb

The initializer set up a connection pool, but both pools actually created namespace wrappers around a single global connection.
I am developing a feature where I tried using a blocking redis command.  Using this froze all of redis for the whole application since there was no connection pooling.  This change allowed me to continue.

chore: Use multiple connections in Redis connection pool

---

lib/regex_helper.rb
spec/models/contact_inbox_spec.rb

Fix flaky test : flaky /spec/services/whatsapp/providers/whatsapp_cloud_service_spec.rb:17
example build : https://app.circleci.com/pipelines/github/chatwoot/chatwoot/48955/workflows/a2959d25-19ea-4812-ba15-5aac69c43265/jobs/49523
cause : factory bot can create phone numbers of length 15 digits,  which is valid e164, while our regex only handled uptill 14 digits

fix: flaky test whatsapp_cloud_service_spec.rb:17

---

app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
app/models/macro.rb
app/services/macros/execution_service.rb
spec/controllers/api/v1/accounts/macros_controller_spec.rb

Fixes #5733 
Tested on local, can save the macros with private note and when we execute the macros able to see private note in the conversation

Feat/5733 Add private note action in macros

---

app/controllers/public/api/v1/inboxes/contacts_controller.rb
spec/controllers/public/api/v1/inbox/contacts_controller_spec.rb

This seems to be a bigger issue than initially anticipated in the issue that this PR fixes. Because the identifier is never used to identify the contact, this results in having a new contact created every time if the email or phone is not supplied.
Fixes #5704 
Automated test has been added.

fix: Identifier not persisted on customer created via Inbox API Channel

---

.gitignore
app/javascript/dashboard/routes/dashboard/settings/macros/MacroEditor.vue
app/javascript/dashboard/routes/dashboard/settings/macros/constants.js

Single select dropdown instead of multiple for Agents and teams in Macros dropdowns
https://user-images.githubusercontent.com/15716057/201093177-0bcb1987-ca9f-4153-bac9-21581bd70759.mp4
Fixes #5836

fix: Single select for agents and teams in Macros actions

---

app/presenters/conversations/event_data_presenter.rb
spec/listeners/action_cable_listener_spec.rb

Fixes https://github.com/chatwoot/product/issues/659
It was added for dispatching an event when the label is changing through macros or API.
- Test macros add_label for the impact.

fix: send label list not object in event data presenter

---

app/finders/message_finder.rb
spec/finders/message_finder_spec.rb

To support https://github.com/chatwoot/chatwoot/issues/3320

feat: Add support for `after` param in messages API

---

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue

This ensures `posthog` replaces the corresponding elements with an empty block in recordings.
ref: https://posthog.com/manual/recordings#ignoring-sensitive-elements
Fixes https://github.com/chatwoot/product/issues/676

chore: add ph-no-capture css class to messages

---

app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
app/javascript/dashboard/i18n/locale/en/chatlist.json
app/javascript/shared/constants/messages.js
app/models/message.rb
app/services/whatsapp/incoming_message_base_service.rb
app/views/api/v1/models/_message.json.jbuilder
spec/services/whatsapp/incoming_message_service_spec.rb

ref: #1021
Process field statuses receives in webhook whatsapp cloud api
Creating a spec

feat: Read/Delivery status for Whatsapp Cloud API

---

app/javascript/dashboard/components/ChatList.vue
app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
app/javascript/dashboard/helper/URLHelper.js
app/javascript/dashboard/routes/dashboard/commands/conversationHotKeys.js

Fixes https://github.com/chatwoot/product/issues/696
1. Adds missing in the following URL for Conversation actions in the Command bar.
2. Fixes Mark as unread from unattended view redirects to the all-conversation screen.
3. Fixes Sidebar mention is not highlighted when the unattended view, mentions view, and the all conversation view is active.
https://www.loom.com/share/0740a494a62c4cf5bf5534fcc6dbc923

fix: Conversation View bugs

---

app/javascript/dashboard/routes/dashboard/conversation/search/SearchMessageItem.vue

When doing a conversation search, if the search term includes any regular
expression characters and the search returns results, then this function would
interpret the regex characters and possibly throw an exception.
For example, if a conversation includes the text "+15555550111" and you search
for "+15555550111" then you get an exception like:
> Invalid regular expression: /(+15555550111)/: Nothing to repeat
Because the "+" is not escaped.
**NOTE:** I haven't added any tests b/c I'm not familiar w/ how to write tests for
frontend changes like this in chatwoot.
I've only tested by running the code locally and testing in a browser.

Escape search term before building regular expression

---

app/views/devise/mailer/confirmation_instructions.html.erb
spec/mailers/confirmation_instructions_spec.rb

Fix the confirmation mail template when the user updates his email 
before this fix, if the user is confirmed and tries to update his email, he will receive an email with a login URL instead of a confirmation link for the new email.
after this fix, if the user is confirmed and tries to update his email, he will receive an email with a confirmation link for the new email and will be able to update his email.
- Try to log in with your confirmed email and update your email.
- Chatwoot will log you out and send you a confirmation email.
- The Confirmation email will contain a login link instead of a confirmation link.
- In this scenario, you will not be able to update your email.

fix: Confirmation mail template on email update

---

app/javascript/dashboard/assets/scss/widgets/_buttons.scss
app/javascript/dashboard/components/ui/Label.vue
app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue

- This will hide the expand labels button when there are not enough labels
- Increases font size for small-sized labels
Loom - https://www.loom.com/share/0f1f06b2d4ec4a3c802024eb272fea84

fix: Hide show more labels button when there's no overflow

---

app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue

If you only have one inbox, the inbox name in the chat header will be hidden.
Fixes https://github.com/chatwoot/chatwoot/issues/5843

chore: Hide inbox name only has one inbox

---

app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue

By this PR the canned response menu in the rich editor is showing from the editor component before its showing from the imported component.
Fixes https://github.com/chatwoot/product/issues/724
https://www.loom.com/share/2c937f19af7c42b7b10f12fa733bbc54

fix: Use canned response menu from the editor in contact messages

---

app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
app/javascript/dashboard/mixins/conversations.js

With https://github.com/chatwoot/chatwoot/pull/5157, the read status in the website channel went missing. I have refactored the code to ensure the status works on both the website and WhatsApp channels.

fix: Update the logic to show read status for web

---

app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue
app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
config/webpack/environment.js

The props were configured:
maxLength: Maximum length of the recorded clip. Default was 10s, set to 900 (15 minutes) 
timeSlice: Required parameter to use size (maxFileSize) management.
maxFileSize: Maximum file size of a recorded clip (in bytes). Recording will stop when the limit is reached. Can only be used when timeSlice option is also enabled.
Based on configured props videojs will cut the recording as soon as the first condition is met, size or time.
```
maxLength: 900,
timeSlice: 1000,
maxFileSize: 15 * 1024 * 1024,
```
I made an adjustment in passing the **audio-record-format** format.
When assembling the AudioRecorder component the inbox was undefined. I delegated to the parent component (RaplyBox) to send as a prop.
Fixes #6054  …

feat: Send audio longer than 10 seconds

---

config/initializers/01_redis.rb

Due to https://github.com/chatwoot/chatwoot/commit/86ca7f4a8d5e2b7d45033e85d5e100870ed0bfa0 the Redis configuration in some Heroku deployments was breaking, temporarily reverting the part until we identify a fix.
fixes: #5938

Fix: Errors in Heroku deployments

---

app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue

This PR fixes incorrect form labels on the team reports page
The fix is to handle the last `v-else` block to handle the `inbox` and `team` type separately, which earlier handled only the `inbox`.  Ideal solution to this would be to have a generic filter component that is used separately instead of handling multiple cases in the same component. But this fix should work for now
- Navigate to the `/app/accounts/<account_id>/reports/teams` page on any instance to find the incorrect label,
- The component is shared across other pages, navigating to other reports can verify that this fix does not break any of the existing pages
- [ x I have added tests that prove my fix is effective or that my feature works

fix: incorrect label for team members

---

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
app/javascript/dashboard/constants.js
app/javascript/dashboard/routes/dashboard/Dashboard.vue

1. This PR will fix the issue that if the desktop view is false, the conversation display layout is not updated on the first load. It is working fine when we resize the screen.
2. Handle the secondary sidebar on the small screen. If the inner width of the window is less than 1024, then the secondary sidebar will be closed else it will retain the previous state.
3. Fix the scrolling issue in the chat list for touchscreen devices.
Fixes https://github.com/chatwoot/product/issues/745
**Before**
https://www.loom.com/share/2278cfdcac1a4c93bc785e80fae460f9
**After**
https://www.loom.com/share/b7be2ac0e39544e294ff507acf04861d

fix: If desktop view is false then the view not getting updated

---

app/javascript/dashboard/components/widgets/AutomationActionInput.vue

Uses rich message editor instead of native textarea for message actions in automations and macros editors

feat: Use rich text editor for automation and macros message action

---

app/javascript/shared/helpers/Validators.js

This PR will fix an issue which is occurred by domain validation PR, that we cannot create a portal if the custom domain field is empty.
**Before**
**After**
https://www.loom.com/share/5a807911eda64337a3c5af39da1fe803

fix: Not able to create a portal if the custom domain is empty

---

app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue

This PR will fix the space issue with the timestamp in every bubble. It's showing an extra margin, which looks inconsistent.
**Before**
**After**

fix: Fixes inconsistent spacing in message bubble

---

app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue

Truncates all table cells to a fixed width layout
Before
After
Fixes https://github.com/chatwoot/product/issues/747

fix: Handle overflowing content in custom attrs table

---

app/models/concerns/liquidable.rb
spec/models/concerns/liquidable_shared.rb

It will not throw an error if messages have invalid liquid syntax.

fix: Stop processing broken liquid tags

---

app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplatesPicker.vue

Filters and removes all templates from whatsapp template picker, where the status is not equal to `approved`
Fixes [# (issue)](https://github.com/chatwoot/product/issues/779)
Tested locally

fix: Show only approved whatsapp templates

---

app/services/whatsapp/incoming_message_base_service.rb
app/services/whatsapp/incoming_message_service_helpers.rb
spec/services/whatsapp/incoming_message_service_spec.rb

Whatsapp now sends a `deleted` status message which throws an error in sidekiq. Temporarily handling that until we implement delete for the WhatsApp channel.

fix: Error when unsupported Whatsapp message status

---

.github/workflows/stale.yml

Adds stale bot to Chatwoot/chatwoot. This will add the stale label and a comment to any PR that has been idle for over 30 days. For now the PR is not closed.
P.S. This does not work on issues, only PRs for now

chore: add stale PR bot

---

app/views/public/api/v1/portals/articles/show.html.erb

Prevents this
https://user-images.githubusercontent.com/15716057/213369910-324484c9-a992-40a2-8467-bd20dd420c59.mp4
Adds bread-word class to article prose content

fix: Prevent overflowing content in articles in phones

---

app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplatesPicker.vue

Filters out all the templates where formats are either of these `['DOCUMENT', 'IMAGE', 'VIDEO']`

fix: Remove whatsapp formats which are currently not supported

---

app/presenters/conversations/event_data_presenter.rb
spec/models/conversation_spec.rb
spec/presenters/conversations/event_data_presenter_spec.rb

Fix the issue introduced in #6267

fix: Add missing timestamp in the real-time event

---

.husky/pre-commit
package.json

This PR speeds up the pre-commit hook to lint only the staged files, instead of running it across all files like it does right now.
This change affects developer workflow. **Note that it removes the `git add` at the end, not sure if that was intenional.** We can add that back and use `git ls-files -m` to show all modified files
Tested locally on my iTerm, with vanilla Git setup

chore: run linting on staged files only

---

app/controllers/super_admin/instance_statuses_controller.rb

- Fix Redis status when Redis is online in the super-admin Instance health page

fix: redis health status in superadmin panel

---

app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue

1. Show the delete button in the context menu for messages and attachments.
2. Removed add canned response button in the context menu for attachments.
Fixes https://github.com/chatwoot/product/issues/789
https://www.loom.com/share/f3ed0ede5c8e46058fa3f8ccc992a189

fix: Cannot delete message with attachments without content

---

Gemfile
Gemfile.lock
app/services/notification/push_notification_service.rb
lib/vapid_service.rb
spec/services/notification/push_notification_service_spec.rb

The previous gem `webpush` hasn't been updated in a while. Also with the recent ruby upgrade, we needed a fix for https://github.com/zaru/webpush/pull/106. Hence switching to the `web-push` gem where the issues are fixed.

chore: Switch to web-push gem

---

app/javascript/dashboard/store/modules/auth.js
app/javascript/dashboard/store/modules/specs/auth/mutations.spec.js

Fixes https://github.com/chatwoot/chatwoot/issues/6374
**How to do QA?**
1. Login to the chatwoot app.
2. Login into the same account using the mobile app (or incognito window)
3. Change the availability status from the mobile app or incognito window.
4. Check user availability status updates in real time.

fix: Update user availability status in real-time when change from the mobile app 

---

app/controllers/api/v1/accounts/canned_responses_controller.rb
app/models/canned_response.rb
spec/controllers/api/v1/accounts/canned_responses_controller_spec.rb

This PR updates the canned response search query to order by short_code matches first
Fixes: https://github.com/chatwoot/product/issues/788
Tested locally
https://www.loom.com/share/7d5df79f7f8646a7bb0c8a6fa236f84b

fix: order for canned response

---

app/javascript/dashboard/helper/automationHelper.js
app/javascript/dashboard/mixins/automations/methodsMixin.js
app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
app/listeners/automation_rule_listener.rb
spec/listeners/automation_rule_listener_spec.rb

https://www.loom.com/share/46959eb3074549eb8694fc10daa42b47
@nithindavid Conversation opened working on this PR; please let me know your thoughts.
We used the conversation_opened event name instead of conversation_reopened because we use a similar event_name in agent_bot_listener to maintain consistency using the same event.  We can change the front_end display event though.

Added event for conversation opened

---

app/helpers/message_format_helper.rb

1. Profile Settings -> open Email Notifications
2. send attachment message without content
3. trigger email notification
4. email can not show messages
1. Profile Settings -> open Email Notifications
2. send attachment message without content
3. trigger email notification
4. email content was correct
```ruby
ActionView::Template::Error: undefined method `gsub' for nil:NilClass
/app/app/helpers/message_format_helper.rb:5:in `transform_user_mention_content'
/app/app/drops/conversation_drop.rb:38:in `block in recent_messages'
/app/app/drops/conversation_drop.rb:35:in `map'
/app/app/drops/conversation_drop.rb:35:in `recent_messages'
/gems/ruby/3.0.0/gems/liquid-5.3.0/lib/liquid/drop.rb:37:in `invoke_drop'
```

fixBug: email notification error, Attachment Message without content

---

app/javascript/widget/components/AgentMessage.vue
app/javascript/widget/components/FileBubble.vue
app/javascript/widget/components/UserMessage.vue

The text color in the widget was using a contrast helper on the bubbles for messages coming from agent to the user, where the bubbles are always white color, so inverting the color did not make sense, I have removed these styles from the bubble. 
Now it will use the default colors and fixed the same for dark mode.
Before 
Now
Fixes #6352 

fix: Text color bug on attachment bubble

---

app/javascript/sdk/IFrameHelper.js
app/javascript/widget/constants/sdkEvents.js
app/javascript/widget/helpers/actionCable.js
app/views/widget_tests/index.html.erb

Added chatwoot:on-message event. Fixes https://github.com/chatwoot/chatwoot/issues/2995
The website owners can implement the following method to listen to the messages sent in the conversation. This callback would be triggered for both the incoming and outgoing messages.
```js
window.addEventListener('chatwoot:on-message', function(e) {
console.log('chatwoot:on-message', e.detail)
})
```

chore: Add chatwoot:on-message event

---

app/jobs/conversations/resolution_job.rb
app/models/conversation.rb
lib/limits.rb
spec/jobs/conversations/resolution_job_spec.rb

We will be adding a limit to the resolution job so that it is performed at a spaced interval. This will ensure there won't be a sudden spike in resource usage
fixes: https://github.com/chatwoot/product/issues/707
ref customer report 
> An account had -20k unresolved conversations. Those conversations got resolved at once due to inactivity. This event triggered around 400k jobs in Sidekiq, eventually leading to increased memory and CPU usage. The number of jobs is common (not unusual), considering each resolution event can lead to 8-20 smaller jobs performing several activities like webhook notifications, email alerts, or realtime messages to agents.

chore: Limit conversation resolution Job

---

app/controllers/api/v1/accounts/articles_controller.rb
app/controllers/public/api/v1/portals/articles_controller.rb
app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleItem.stories.js

Fixes https://github.com/chatwoot/chatwoot/issues/5756
Article views is not incremented when the article is access in portal. This PR implements the increasing the views count when article is access in portal
- Create an article in help center
- Initially the views count is 0
- When that article is access on portal, the views count increases
https://www.loom.com/share/938f88e5d349455481168072c87f29ac

fix : Help Center article view count

---

app/javascript/widget/store/modules/message.js
app/javascript/widget/store/modules/specs/message/actions.spec.js

- Fixes https://github.com/chatwoot/chatwoot/issues/5957
This resolves an issue that occurs when a user double-clicks an interactive message resulting in a multi trigger of the handler function.
- Created an interactive message using API
- Perform a double click on the `input-select`  options.
- The actions was being ran once, since other actions are bounced back if the message is already being updated
https://user-images.githubusercontent.com/45232708/217775924-6b0b4f16-90a8-443e-bac3-e0c1562bff49.mov
https://user-images.githubusercontent.com/45232708/217776437-206eafce-21cd-4ba4-88a4-0d68da44a18a.mov

fix: interactive messages - button should not respond to double click 

---

app/controllers/api/v1/accounts/inboxes_controller.rb
app/listeners/notification_listener.rb
app/models/concerns/message_filter_helpers.rb
app/models/inbox.rb
app/services/messages/mention_service.rb
app/services/messages/new_message_notification_service.rb
spec/services/messages/mention_service_spec.rb
spec/services/messages/new_message_notification_service_spec.rb

**Change:** New message notification would now be triggered if there is another agent replying to a conversation assigned to me.
Part of #4145

chore: Refactor the notification service for participants

---

app/javascript/dashboard/i18n/locale/en/settings.json
app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue

The settings for a portal is very difficult to find. Adding this to the portal sidebar will improve the usability.

fix: Add a settings link for portals in sidebar

---

app/controllers/api/v1/accounts/conversations_controller.rb
spec/controllers/api/v1/accounts/conversations_controller_spec.rb

- Capture `ActiveRecord::RecordNotUnique` and return 422
Fixes #6457 
- Added spec

fix: sentry CHATWOOT-37A ActiveRecord::RecordNotUnique

---

app/javascript/dashboard/i18n/index.js
app/javascript/dashboard/i18n/locale/is/index.js

Closes https://github.com/chatwoot/chatwoot/issues/6484
Fixes issue with displaying Icelandic language translations
1. Go to 'settings'
2. Click on 'account settings'
3. Scroll down to 'site language'
4. change it to icelandic
5. click update settings button in top right corner
6. Verify that the language has been updated
https://user-images.githubusercontent.com/45232708/220324564-ff1c5205-86e8-4cbe-8b06-3129a6d483af.mov

fix: Icelandic locale shows only english

---

app/controllers/api/v1/widget/messages_controller.rb
spec/controllers/api/v1/widget/messages_controller_spec.rb

The name is not updated when the email is updated via the email collect message. This PR fixes that.

fix: Name missing when email is collected via email hook

---

.husky/pre-commit

The pre-commit hook would format event those files excluded in the config. This is because the files were passed as args instead of the linter running on the entire project. When this happens, the exclude is not respect. 
The `--force-exclusion` flag instructs our machine overlords to force exlucde files specified in the configuration `Exclude` even if they are explicitly passed as arguments.

chore: add `--force-exclusion` option to rubocop pre-commit hook

---

app/models/automation_rule.rb
spec/models/automation_rule_spec.rb

Fix: https://github.com/chatwoot/product/issues/809
Adding condition-based validation for automation rule to prevent it from creating invalid records such as with no `query_operator`

fix: Condition based backend validation

---

app/controllers/public/api/v1/portals/articles_controller.rb
spec/controllers/public/api/v1/portals/articles_controller_spec.rb

If there are categories with same slug in 2 different locales, then the API fails to find the article.

fix: Fetch categories by locale

---

app/controllers/microsoft/callbacks_controller.rb

Fixes #6353, by using the email address (part before the "@") as a fallback name.
I made this change, then managed to have the inbox successfully create in my own deploy.
As it is such a small change, no formal tests have been written.

fix: Setting a fallback name from the email address for MS email channel

---

app/controllers/api/v1/accounts/integrations/apps_controller.rb
app/views/api/v1/models/_app.json.jbuilder
app/views/api/v1/models/_hook.json.jbuilder
spec/controllers/api/v1/accounts/integrations/apps_controller_spec.rb

Fixes https://github.com/chatwoot/chatwoot/issues/6570
- Allow listing the connected apps without exposing credentials

fix: Allow integration apps to be listed by an agent

---

app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue

Clicking the contact name in conversation has no effect. This PR implements opening contact details panel when contact name in conversation is clicked
- Go to a conversation
- Click on contact name
- Contact details panel is opened
https://www.loom.com/share/729ad136af754685b46fd796408056a0

fix: Clicking contact name in conversation should open contact details panel

---

config/initializers/datadog.rb
config/initializers/sentry.rb

- handle the case where the system fails to start when empty APM environment variables are present

chore: Handle APM variables being empty

---

app/models/message.rb

Document: 
For conversations: 4029, 4041, and 4038:
`dispatch_create_events[message_created]: first_human_response? && outgoing?` was always true in the `model/message.rb`
It needs one more check; if the message is not being sent by 'Automation'.
When we trigger FIRST_REPLY_CREATED, we have one more action to update the conversation with `message.created_at.`
And that was again triggering:-
`conversation_updated` -> which has `send_message` automation which will again trigger `message_created` -> `FIRST_REPLY_CREATED`
And this was going in a loop.
So this condition is valid for all the affected messages: 
```
----------
For Account 58:  
conversations: 1483, 1482
automation: 521
---- - ----
- ----- ----
For Account 61: 
conversations: 4041, 4038, 4029
automation: 476
------------
```

fix: Add a check for automation_created message in FIRST_REPLY_CREATED

---

app/javascript/dashboard/api/reports.js
app/javascript/dashboard/api/specs/reports.spec.js

The reports timings we're not being passed correctly to the `ReportsAPI`, this PR fixes it

fix: timing in the API

---

lib/integrations/bot_processor_service.rb

Sentry Issue: [EXTERNAL-SOCIALBOT-5R](https://chatwoot-p3.sentry.io/issues/3990919574/?referrer=github_integration)

fix: hook exception for empty hook

---

lib/webhooks/trigger.rb

- There is little value in throwing the third-party webhook-related exceptions to sentry. Let's rather write it to logs instead.

chore: Disable throwing Webhook exceptions to Sentry

---

.env.example
Procfile
app/controllers/widgets_controller.rb
app/jobs/contact_ip_lookup_job.rb
app/services/ip_lookup_service.rb
config/initializers/geocoder.rb
enterprise/app/controllers/enterprise/widgets_controller.rb
lib/tasks/ip_lookup.rake

- Disable widget based on country code from IP address
https://www.loom.com/share/f2363462485b4aa8a6826f77a8964bf7
The database download has been moved to a rake task and will be downloaded during boot up. Dynamically fetching (async fetches via Sidekiq) the database does not work well with synchronous calls since each server requires a copy of the file.
I updated the Procfile to download the DB initially and then run the service afterwards. This change may increase the bootup time by 3-4 seconds, depending on network latency.
I removed the IP_LOOKUP_SERVICE variable because none of the other services will work without the lookup parameter. Therefore, managing this variable is pointless.

feat(poc): Disable widget based on country

---

app/javascript/dashboard/modules/search/components/SearchHeader.vue
app/javascript/dashboard/modules/search/components/SearchTabs.vue
app/javascript/dashboard/modules/search/components/SearchView.vue

Reverts search page design to get rid of the popover feel.
Fixes: https://linear.app/chatwoot/issue/CW-5/followup-from-search-improvements

fix: Reverts popover styling for search page

---

app/javascript/dashboard/App.vue

The notification subscription is called after every presence update due to it being implemented in the currentUser watcher. I move it current account watcher.

fix: Move subscription calls to after initialize

---

app/javascript/dashboard/components/Modal.vue
app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/components/widgets/conversation/bubble/Image.vue
app/javascript/dashboard/components/widgets/conversation/bubble/Video.vue
app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue

- Add an option to skip custom context menu 
- Disable translate if there is no text in the message
- Fix the width of video + text messages.
- Disable context menu on modals
Fix https://linear.app/chatwoot/issue/CW-1414/feedback-on-context-menu

fix: Display native context menu on image, video preview modals

---

app/javascript/dashboard/components/CustomAttribute.vue

Hello, your CustomAttribute component is never cleared, which leads to memory leaks of several GB over time. All events must be turned off when the component destroyed.

fix memory leek

---

db/migrate/20230202132107_install_audited.rb
db/migrate/20230328131926_drop_extra_audit_integer_column.rb
db/schema.rb

When I run the migration from **[this PR](https://github.com/chatwoot/chatwoot/pull/6434/files#diff-4e30cbc2669e4b0f6e1fc0526be0c6141082a5c1dc88aaddc8c0fbc1d742f0ddR16)**:
https://github.com/chatwoot/chatwoot/blob/3e6d23e0715a0a700404c02e5a7a32b4fa079187/db/migrate/20230202132107_install_audited.rb#L16
it adds an extra integer column named "integer" to my DB.
Diff in `db/schema.rb`:
```diff
create_table "audits", force: :cascade do |t|
t.bigint "auditable_id"
t.string "auditable_type"
t.bigint "associated_id"
t.string "associated_type"
t.bigint "user_id"
t.string "user_type"
t.string "username"
t.string "action"
t.jsonb "audited_changes"
t.integer "version", default: 0
+    t.integer "integer", default: 0
t.string "comment"
t.string "remote_address"
t.string "request_uuid"
t.datetime …
```

chore: Remove extra audit column

---

db/schema.rb

When I run `rails db:schema:dump` this is what is generated for me. It was previously in the chatwoot codebase _with_ the prefix, but was removed **[in this PR](https://github.com/chatwoot/chatwoot/pull/5338#discussion_r957645071)** without explanation as to why.
Should `public.` be in schema.rb or not? What was the reason for its removal? Do I have something unique about my setup that's causing it to be added?

chore: Re-add "public" prefix to "public.gen_random_uuid()" in schema.rb

---

app/javascript/dashboard/components/widgets/conversation/Message.vue
app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue

Show attribute external error when exist.
Simulate error message and print

feat: show external error in message

---

app/jobs/webhooks/telegram_events_job.rb
app/services/telegram/update_message_service.rb
spec/jobs/webhooks/telegram_events_job_spec.rb
spec/services/telegram/incoming_message_service_spec.rb
spec/services/telegram/update_message_service_spec.rb

- Add support for telegram `edited_message` events : Update the user message back in Chatwoot dashboard when updated by the contact
https://user-images.githubusercontent.com/73185/228543477-f976ae75-27c9-4044-a3db-bcc38f4019cf.mov

chore: Support telegram `edited_message` events

---

lib/integrations/slack/send_on_slack_service.rb
spec/lib/integrations/slack/send_on_slack_service_spec.rb

Fixes: https://linear.app/chatwoot/issue/CW-1336/add-conversation-link-at-the-start-of-the-thread-in-slack
https://www.loom.com/share/8f21c9e97e804613a15833587dc3c86a

fix: Add link to conversation in slack message

---

app/listeners/automation_rule_listener.rb
app/services/automation_rules/action_service.rb
spec/factories/automation_rules.rb
spec/listeners/automation_rule_listener_old_spec.rb
spec/listeners/automation_rule_listener_spec.rb
spec/services/action_service_spec.rb
spec/services/automation_rules/action_service_spec.rb
spec/services/automation_rules/conditions_filter_service_spec.rb

The current way of writing specs for automation in one single file automation_listener isn't effective. Hence we are breaking down the specs for each class into separate spec files.
fixes: CW-1447

chore: Refactor Automation Specs [CW-1447]

---

app/controllers/api/v1/accounts/contacts_controller.rb

Update contacts API query to be faster
Here's a very naive benchmarking, done manually.  Used [this query](https://gist.github.com/scmmishra/8c3a10f58d23f49e9bc3cb798d5f3712) to find the accounts with these combinations. Ran the query with limit `2000` and offset `15` on a sizable test database
| Contacts Count | Conversations Count | New Query    | Old Query     | Notes                                 |
|----------------|---------------------|--------------|---------------|---------------------------------------|
| 51809          | 165927              | 92.051 ms    | 2485.252 ms   | Most active account                   |
| 13             | 126340              | 121.225 ms   | 876.705 ms    | Most conversations per contact        |
| 2980474        | 69 (nice)           | 12478.887 ms | …

feat(perf): update contacts filter query

---

app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue

This PR will enable the import option form the role admin accounts.
Fixes https://linear.app/chatwoot/issue/CW-1396/import-option-is-shown-to-agents
https://www.loom.com/share/32683696380041e4a2dafc18a911da0b

fix: Disable import option in agent account

---

app/javascript/dashboard/api/reports.js
app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
app/javascript/dashboard/store/modules/reports.js

The `groupBy` and `businessHours` filter were not being applied, this PR fixes that

fix: inconsistent usage of snake_case and camelCase

---

app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
app/models/account.rb
app/views/api/v1/models/_account.json.jbuilder
config/features.yml
db/migrate/20230404030719_remove_settings_flags_from_account.rb
db/schema.rb
spec/factories/accounts.rb

The custom domain feature uses the settings_flag attribute (an old implementation), which was not used anywhere else. I have migrated the flag to the feature_flags attribute so that it can be updated via the UI.
This PR:
- Migrates custom_reply_domain and custom_reply_email to feature_flags.
- Remove the settings_flags attribute from the account model.

chore: Use feature_flags attribute instead of settings_flags

---

app/javascript/shared/helpers/MessageTypeHelper.js

Message length on Facebook and Instagram are currently limited to 640 characters but
the Facebook doc says the limit 2000 characters.
reference -> https://developers.facebook.com/docs/messenger-platform/reference/send-api#request
the Instagram doc says the limit is 1000 characters
This pull request extend the message length to 1000 characters to meet the facebook and instagram limit.
-  [x] New feature (non-breaking change which adds functionality)

feature: Extend the message limit for the Facebook Channels

---

app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue

Fixes https://linear.app/chatwoot/issue/CW-1392/canned-responses-are-not-sent-in-the-new-message-editor
https://www.loom.com/share/fc179cc38be9420db2ce9425097d5bb7

fix: Canned Responses are not sent in the new message editor

---

app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
app/javascript/dashboard/mixins/specs/time.spec.js
app/javascript/dashboard/mixins/time.js

This PR allows one to see the year in the conversation message timestamp if the message is not from the current year.
Fixes https://linear.app/chatwoot/issue/CW-1423/show-year-if-the-date-is-not-from-the-current-year
https://www.loom.com/share/1aa01938420d4405b238df6b444fb04b

feat: Show year in message timestamp if the message is not from the current year

---

app/finders/message_finder.rb
spec/finders/message_finder_spec.rb

Fixes https://linear.app/chatwoot/issue/CW-1475/support-after-param-in-messages-end-point

feat: Support `after` param in messages end point

---

app/jobs/webhooks/whatsapp_events_job.rb
spec/jobs/webhooks/whatsapp_events_job_spec.rb

- Disable processing events if an account is suspended.
- Move the processing to low, as this job affects all other real-time actions.

fix: Disable processing events if account is suspended

---

.env.example
app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
app/javascript/widget/components/AgentMessage.vue
app/javascript/widget/components/UnreadMessage.vue
app/javascript/widget/mixins/configMixin.js
app/javascript/widget/mixins/specs/configMixin.spec.js
app/models/channel/web_widget.rb
app/views/api/v1/widget/configs/create.json.jbuilder
app/views/widgets/show.html.erb
db/migrate/20230407191457_migrate_env_var_to_channel_feature.rb
db/schema.rb

This PR is done to allow users to customize their bot image and name on their live-chat widget. As the first step, we will allow them to use their inbox name and avatar for the bot and later add an option to customize it.
- Remove USE_INBOX_AVATAR_FOR_BOT env variable
- Add a feature_flag for use_inbox_avatar_for_bot
- Add a migration based on the feature flag

feat: Use inbox image as avatar for the bot 

---

app/javascript/dashboard/components/Code.vue
app/javascript/dashboard/i18n/locale/en/settings.json
app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue

This PR allows creating a code-pen with the widget for testing in one-click. 
1. Allow codepen in then `Code.vue` component
2. Update the style for `Copy` button in `Code.vue`
3. Enable codepen for config

feat: one-click codepen for widget configuration

---

app/models/concerns/account_cache_revalidator.rb
app/models/concerns/channelable.rb
spec/models/inbox_spec.rb

The changes in channel object (for eg: whatsapp templates or config in the website live chat) doesn't trigger an cache invalidation right now. The user has to logout and log back in to get the changes. 
To avoid this, we have to invalidate the inbox cache if there is any change in the associated channel object.
To reproduce the issue. 
Open rails console, get the first web widget and update any attribute in the channel object. Check if the inbox cache invalidation event is triggered.

fix: Invalidate cache if any of the related objects change

---

app/models/concerns/activity_message_handler.rb
app/models/message.rb
config/locales/en.yml
spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb

Fixes: https://linear.app/chatwoot/issue/CW-1359/activity-message-generation-error-using-an-api
1. Create Conversation In any way
2. Resolve the conversation
3. Send Message via API with the api_access_token: See the activity message
4. Again, resolve the conversation
5. Send a message using a public API endpoint: See the activity message
https://www.loom.com/share/aaccdb8bb31146d88637feffba147ca9

Add status reopen activity message for api channel

---

swagger/paths/index.yml
swagger/swagger.json

Change /profile to /api/v1/profile
Reported by: [#22988](https://app.chatwoot.com/app/accounts/1/conversations/22988)

fix: Update the profile API URL in the documentation

---

app/finders/email_channel_finder.rb
spec/finders/email_channel_finder_spec.rb

Fixes: #6608  
ref: https://linear.app/chatwoot/issue/CW-30/emails-not-routed-based-on-x-original-to

fix: Find email channel with bcc and x-original-to

---

app/controllers/twitter/callbacks_controller.rb

The `twitter_client.user_show(screen_name: inbox.name)` returns a 403 from Twitter API with the following error
```json
{
"errors": [
{
"message": "You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve",
"code": 453
}
]
}
```
The next statement was `return unless response.success?` but the `success` property does not exist on the Twitty Response class, so it breaks the creation of twitter inbox. This PR fixes that

fix: use response.status instead of success

---

app/javascript/shared/components/CustomerSatisfaction.vue
app/javascript/widget/components/template/EmailInput.vue

1. FIx border color for CSAT
2. Fix the border color in the email input
Fixes https://linear.app/chatwoot/issue/CW-38/bug-fix-border-color-for-csat-component-in-widget
**Screenshot**

fix: Border color for CSAT component in widget

---

app/models/conversation.rb
db/migrate/20230418100944_add_priority_to_conversation.rb
db/schema.rb

Seems like this can be done with minimal impact, tried it on staging instance with 2M rows, happened within 200ms
- [StackOverflow](https://stackoverflow.com/a/19527223 )
- [PostgreSQL Docs](https://www.postgresql.org/docs/current/sql-altertable.html#:~:text=When%20a%20column,the%20table%20required.)
> When a column is added with ADD COLUMN and a non-volatile DEFAULT is specified, the default is evaluated at the time of the statement and the result stored in the table's metadata. That value will be used for the column for all existing rows. If no DEFAULT is specified, NULL is used. In neither case is a rewrite of the table required.

feat: add priority field to conversation

---

spec/listeners/reporting_event_listener_spec.rb

The spec from time to time returns 43 seconds when `from_now` time is close to a second boundary. Making now time the same for both `conversation_updated_at` and `human_message_created_at` should make the spec more deterministic.
```
ReportingEventListener#first_reply_created when last handoff event exists creates first_response event with handoff value
Failure/Error: expect(account.reporting_events.where(name: 'first_response')[0]['value']).to be 42.0
expected #<Float:155374187144282114> => 42.0
got #<Float:156500087051124738> => 43.0
Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.
```
The issue can be reproduced by running …

fix: Fixes flaky reporting_event_listener spec

---

.rubocop.yml
app/jobs/account/conversations_resolution_scheduler_job.rb
app/jobs/conversations/reopen_snoozed_conversations_job.rb
app/jobs/inboxes/fetch_imap_email_inboxes_job.rb
app/jobs/migration/update_first_response_time_in_reporting_events_job.rb
app/jobs/trigger_scheduled_items_job.rb
spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
spec/jobs/bulk_actions_job_spec.rb
spec/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb

- Enable the rubocop Rails/FindEach
- Replace the .all.each with .find_each
This should let us avoid potential high memory usage.
Motivation from the latest Speedshop newsletter by Nate Berkopec
ref: https://www.rubyinrails.com/2017/11/16/use-find-each-instead-of-all-each-in-rails/

chore: Use find_each instead of .all.each

---

swagger/paths/index.yml
swagger/swagger.json

Fixes a mistake in the URL for team_members.

fix: Add `/api/v1` to the team_members API documentation

---

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue

fix: spacing for priority mark in inbox page

---

lib/integrations/openai/processor_service.rb
spec/lib/integrations/openai/processor_service_spec.rb

Adds additional endpoints for OpenAI integration which will allow 
- Reply Suggestions
- Summarization
ref: #6436 
fixes: https://linear.app/chatwoot/issue/CW-1596/backend-for-generating-conversation-summary
----- 
Payload formats
```
{
"event": {
"name": "summarize",
"data": {
"conversation_display_id": 12
}
}
}
```
```
{
"event": {
"name": "reply_suggestion",
"data": {
"conversation_display_id": 12
}
}
}
```

chore: GPT Reply suggestion & summarize endpoints

---

Gemfile

- Reorder gems in the development section

fix: Re-order gem list to fix rubocop errors

---

app/models/message.rb
db/migrate/20230509101256_add_index_to_messages_created_at.rb
db/schema.rb

This PR adds index on message `created_at` field, this PR speeds up the labels reports that counts messages.
Before: https://explain.dalibo.com/plan/33521ebf4f883cd6
After: https://explain.dalibo.com/plan/33521ebf4f883cd6
The improvements are marginal for most use-cases but for larger tables this should speed things up significantly
Here's a query you can try to test
```sql
EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) SELECT 
COUNT(*) AS count_all, 
DATE_TRUNC('day', "messages"."created_at" :: timestamptz AT TIME ZONE 'Asia/Kolkata'):: date AS date_trunc_day_messages_created_at_timestamptz_at_time_zone_eur 
FROM 
messages 
WHERE 
messages.account_id = 1 
AND messages.conversation_id IN (
9856, 9857, 9858, 9859, 9860, 9861, 9862, 
9863, 9864, 9865, 9866, 9867, 9868, 
9869, 9870, …
```

feat(perf): add index to messages created at

---

app/models/message.rb
db/migrate/20230510060828_add_index_to_messages_for_reportings.rb
db/schema.rb

Extension to the following PR: https://github.com/chatwoot/chatwoot/pull/7044
---
An index on `conversation_id`, `account_id`, `message_type` and `created_at` does speed things up for the query
Before: https://explain.dalibo.com/plan/da7c4h9e9161ba64
After: https://explain.dalibo.com/plan/b2c9ece7247120c8

feat(perf): add additional indexes for messages

---

app/javascript/dashboard/components/widgets/conversation/Message.vue

Fixes https://linear.app/chatwoot/issue/CW-1728/wrong-cache-information-for-gcs-storage
Fixes https://github.com/chatwoot/chatwoot/issues/7000
- Force reload audio on each re-render.
@scmmishra Do you have any other ideas here? The issue here is that the redirect gets cached on the frontend, which eventually expires and the audio becomes in-accessible

fix: Avoid audio URLs getting cached at the frontend

---

app/controllers/api/v1/accounts/conversations_controller.rb
app/models/conversation.rb
app/views/api/v1/accounts/conversations/attachments.json.jbuilder
config/routes.rb
spec/controllers/api/v1/accounts/conversations_controller_spec.rb
spec/factories/messages.rb

Fixes https://linear.app/chatwoot/issue/CW-1678/api-to-list-all-attachments-for-a-conversation

feat: API to list all attachments for a conversation

---

package.json
yarn.lock

**Description**
This was because of an error in the code. the nodes object was coming with different keys.
**Loom**
https://www.loom.com/share/82d8beba08de49f5b2405783ce2d3d0b
**Pr on schema side** 
https://github.com/chatwoot/prosemirror-schema/pull/11
https://linear.app/chatwoot/issue/CW-1505/editor-adds-a-stray-/-in-a-conversation

fixes: Editor adding slash char while creating block quotes [cw-1505]

---

app/models/account.rb
app/models/application_record.rb
app/models/contact.rb
spec/models/account_spec.rb
spec/models/article_spec.rb
spec/models/message_spec.rb

Introduces a default max length validation for all string and text fields to prevent processing large payloads.

chore: Add max length validation to text fields

---

app/javascript/dashboard/i18n/index.js
config/initializers/languages.rb

This PR will enable Hebrew support in the dashboard.
https://linear.app/chatwoot/issue/CW-1736/chore-enable-hebrew-in-chatwoot

chore: Enable support for Hebrew in dashboard [CW-1736]

---

app/builders/messages/instagram/message_builder.rb
app/jobs/webhooks/instagram_events_job.rb
spec/builders/messages/instagram/message_builder_spec.rb
spec/factories/instagram/instagram_message_create_event.rb
spec/jobs/webhooks/instagram_events_job_spec.rb

Fixes: https://linear.app/chatwoot/issue/CW-1694/ig-sent-messages-are-returned-as-new-message-from-the-customer

fix: Duplicate instagram conversations for echo messages

---

app/models/attachment.rb
spec/models/attachment_spec.rb

fixes: https://linear.app/chatwoot/issue/CW-1746/activerecordrecordinvalid-validation-failed-external-url-is-too-long

fix: External url validation in attachment

---

app/jobs/inboxes/fetch_imap_emails_job.rb

Limiting the query to 2 days to ensure that it runs timebound. 
fixes: https://linear.app/chatwoot/issue/CW-1747/activerecordquerycanceled-pgquerycanceled-error-canceling-statement

chore: Fix Activerecord query cancelled when fetching email

---

app/javascript/portal/application.scss
app/javascript/portal/portalHelpers.js

Our tailwind configuration purges the styles that don't appear in a Vue file. Fixes the invisible styles getting removed as it is generated using javascript.
I will find a proper fix for this later.

fix: Avoid styles getting purged on prod build

---

app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue

- Add the option to open the conversation in a new tab by using cmd/ctrl with the click. 
https://linear.app/chatwoot/issue/CW-1754/allow-cmd-click-on-the-conversation-cards

feat: Add cmd/ctrl click open on the conversation cards

---

app/views/api/v1/accounts/articles/_article.json.jbuilder
spec/controllers/api/v1/accounts/articles_controller_spec.rb

When on a new help-center, I tried to create an article, but the action would fail with an internal server error, see screenshot below
This is the error on [sentry](https://chatwoot-p3.sentry.io/share/issue/d5abdec089304223830fee829c6eb705/). This is happening becuase the **help center does not have any existing categories.**  This PR is a temporary fix for this issue, ideally we should have better onboarding and ask users to create a few categories first.
Tested locally, updated unit tests

refactor: make category non-mandatory

---

app/views/public/api/v1/models/_conversation.json.jbuilder
spec/controllers/public/api/v1/inbox/conversations_controller_spec.rb

Remove private notes from conversation list public API
Fixes: https://github.com/chatwoot/chatwoot/issues/7075
Tested locally and added relevant unit tests

fix: exclude private and activity messages from public API

---

app/controllers/api/v1/accounts/inboxes_controller.rb
spec/controllers/api/v1/accounts/inboxes_controller_spec.rb

Fixes: https://linear.app/chatwoot/issue/CW-1803/bug-inbox-doesnt-update-reauthorisation-required-automattically

fix: Reauthorize when channel settings updated

---

app/javascript/sdk/constants.js
app/javascript/widget/App.vue
app/javascript/widget/components/ConversationWrap.vue
app/javascript/widget/mixins/darkModeMixin.js
tailwind.config.js

- Added an option to use dark Mode only in the widget. 
- Accept `dark` in the sdk options.
- Change the Tailwind Dark Mode style strategy to `class` to override color changes based on the OS preference.
https://www.loom.com/share/dc16ac938c6f454e882e32b2c07b30f1

feat: Add an option to use darkMode only in the widget

---

app/javascript/dashboard/components/widgets/chart/HorizontalBarChart.js
app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetrics.vue

This PR fixes the following issues
1. CSAT chart showing an incorrect graph
2. CSAT chart is not responding to data change
Tested locally

fix: CSAT chart showing incorrect data

---

app/jobs/inboxes/fetch_imap_emails_job.rb
lib/exception_list.rb

Reference: https://app.chatwoot.com/app/accounts/1/conversations/23909
We discovered that Google throws this error while fetching the email as a warning that you are giving access to the app[chatwoot], which does not implement the 2-factor authentication.
This seems to be issue with Gmail server: [https://answers.microsoft.com/en-us/outlook_com/forum/all/imap-too-many-simultaneous-connections/9e0c2393-d7a8-4433-adb2-4a72ff80ed66\](https://answers.microsoft.com/en-us/outlook_com/forum/all/imap-too-many-simultaneous-connections/9e0c2393-d7a8-4433-adb2-4a72ff80ed66%5C)
We will be removing this warning from our side, for now.

Fix: prevent IMAPBadResponse exception from sending the authorization mail

---

app/services/conversations/filter_service.rb
app/views/api/v1/conversations/partials/_conversation.json.jbuilder

This PR fixes some N+1 queries for the conversation filter service. This caches the labels and precomputes the total message count. 
Total Queries: 251
Total Queries: 213

feat(perf): improve performance of conversation filter API [CW-1605]

---

app/models/contact.rb
db/migrate/20230523104139_add_partial_index_for_resolved_contacts.rb
db/schema.rb

This PR adds a [partial index](https://www.postgresql.org/docs/current/indexes-partial.html) to the `contacts` table, based on conditions for `resolved_contacts`, i.e. It should have one value, either phone number, email or identifier.  The partial index shaves off about 90% of the execution time, this should speed up other queries as well
This is tested on ChatwootQA instance, it has enough contacts that the count query hangs up the database. 
|               | Execution Time | Explain                                          | Notes                                                           |
|---------------|----------------|--------------------------------------------------|-----------------------------------------------------------------|
| Baseline      | 16.4s          | …

feat(perf): contacts query performance

---

app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue

Fixes https://github.com/chatwoot/chatwoot/issues/7048 and https://linear.app/chatwoot/issue/CW-1837/problems-sending-audios-by-whatsapp

fix: Enable `ogg` audio format for API channel

---

app/views/public/api/v1/portals/articles/show.html.erb

By applying pr-1 on a container div instead of directly on the image (which distorts it), it creates the intended padding without any image distortion.
Fixes #7202
Bug fix (non-breaking change which fixes an issue)

fix: profile picture distortion (#7202)

---

app/models/agent_bot.rb
app/models/attachment.rb
app/models/channel/api.rb
lib/limits.rb
spec/models/agent_bot_spec.rb
spec/models/attachment_spec.rb
spec/models/channel/api_spec.rb

- Increase the external URL field validation to 2048 characters
fixes: https://github.com/chatwoot/chatwoot/issues/7098

chore: Increase character limit for external url fields

---

app/finders/conversation_finder.rb
app/views/api/v1/conversations/partials/_conversation.json.jbuilder
spec/controllers/api/v1/accounts/conversations_controller_spec.rb

This PR reduces the impact on N+1 queries in the conversation list view. Reduces the number of queries while rendering the template by about 15%

feat(perf): update query to reduce N+1 impact [CW-1926]

---

app/mailboxes/imap/imap_mailbox.rb
spec/mailboxes/imap/imap_mailbox_spec.rb

Fixes: https://linear.app/chatwoot/issue/CW-1996/nomethoderror-undefined-method-each-for

fix: Wrap references string into array

---

config/database.yml

Database credentials, passwords in particular, can easily contain characters that are reserved in YAML and must be quoted. In our case a password started with ']'.
The CI build on GitHub passes.

fix: Quote database env variables

---

app/controllers/super_admin/instance_statuses_controller.rb

To check the edition anytime in admin dashboard, Showing as below:

chore: Show chatwoot_edition in Instance details

---

app/controllers/public/api/v1/portals/base_controller.rb

Fix missing yield. The redirect to the default locale page was not working.

fix: around_action not yielding if params are absent

---

app/models/channel/whatsapp.rb
app/services/whatsapp/providers/whatsapp_360_dialog_service.rb
app/services/whatsapp/providers/whatsapp_cloud_service.rb

Fix for the cases where there are multiple channels with invalid provider config, which results in templates sync scheduler failing to schedule jobs for valid channels.
fixes: https://linear.app/chatwoot/issue/CW-2032/bug-whatsapp-template-sync-failing-in-cloud

chore: Ensure updating message_templates_last_updated column

---

app/builders/v2/report_builder.rb
app/finders/conversation_finder.rb
app/models/conversation.rb

The unattended count in the chat list and the report won't match, this PR fixes the logic of counting the unattended conversations from the current logic to the one used in `conversation_finder.rb`

fix: unattended count mismatch in report and list

---

app/javascript/dashboard/store/modules/conversations/index.js
app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js

Fix retry messages popping if there were no attachments previously.
Fixes https://linear.app/chatwoot/issue/CW-2041/typeerror-cannot-read-properties-of-undefined-reading-some
Fixes https://linear.app/chatwoot/issue/CW-2042/typeerror-cannot-read-properties-of-undefined-reading-filter

fix: Cannot read properties of undefined (reading 'some')

---

app/javascript/dashboard/i18n/locale/en/auditLogs.json
app/javascript/dashboard/routes/dashboard/settings/auditlogs/Index.vue
app/models/team.rb
enterprise/app/models/enterprise/audit/team.rb
spec/enterprise/models/team_spec.rb

- Adds audit trail for team events 
Fixes https://linear.app/chatwoot/issue/CW-1771/team-changes-as-events-for-audit-logs
- Tested locally.
- Added specs

feat:  audit trail for team events

---

app/models/contact.rb
app/models/reporting_event.rb
db/migrate/20230612103936_add_index_to_reporting_events.rb
db/schema.rb

This PR adds better indexes `reporting_events (account_id, name, created_at)`
Before fix: https://explain.dalibo.com/plan/3437h21f244defae
After-fix: https://explain.dalibo.com/plan/427cdd84gdc86g7d
Notice that the number of rows planned in the `Bitmap index scan` block is around 7K, which reduced from 26K, drastically reducing the cost of the subsequent heap scan. The query time reduced to 8ms from 34ms.

feat: add index to reporting events [CW-1960]

---

app/controllers/api/v1/accounts_controller.rb
spec/controllers/api/v1/accounts_controller_spec.rb

Update the cache headers for `cache_keys` to `max-age=10, private, stale-while-revalidate=300`
1. The cache will be fresh for 10 seconds (max-age=10). During this time, the browser will use the cached version without checking with the server.
1. After the initial 10 seconds, the browser can continue to serve the stale cache for up to 5 minutes (stale-while-revalidate=300). During this period, it will also try to revalidate and update the cache in the background.
1. After 310 seconds in total (10 seconds fresh, 300 seconds stale), if the browser has not been able to revalidate the cache, it will attempt to fetch the fresh resource directly from the server for subsequent requests, causing potential latency equivalent to a network request.
This means that the data will directly be …

feat: update cache headers for cache_keys

---

app/helpers/report_helper.rb
spec/builders/v2/report_builder_spec.rb

The current method that gets the resolved conversation count is the following, along with it's SQL query
```rb
def resolutions_count
(get_grouped_values scope.conversations.where(account_id: account.id).resolved).count
end
```
<details>
<summary>Resultant Query</summary>
```sql
SELECT 
COUNT(*) AS "count_all", 
DATE_TRUNC(
'day', "conversations"."created_at" :: timestamptz AT TIME ZONE 'Asia/Kolkata'
):: date AS "date_trunc_day_conversations_created_at_timestamptz_at_time_zon" 
FROM 
"conversations" 
WHERE 
"conversations"."account_id" = $1 
AND "conversations"."account_id" = $2 
AND "conversations"."status" = $3 
AND (
"conversations"."created_at" >= '2023-06-05 18:30:00' 
AND "conversations"."created_at" < '2023-06-12 18:29:59'
) 
GROUP BY 
DATE_TRUNC(
'day', …
```

fix: calculation for resolution count

---

app/mailers/conversation_reply_mailer.rb
spec/mailers/conversation_reply_mailer_spec.rb

We have display_name and the actual name for an agent. display_name is used in all public facing parts. The https://github.com/chatwoot/chatwoot/pull/7232/files PR missed this and used actual name instead.
This PR fixes it.

fix: Use available_name instead of actual name in the sender name

---

app/javascript/shared/helpers/localStorage.js

Fixes https://linear.app/chatwoot/issue/CW-2075/ns-error-storage-busy-no-error-message

fix: `NS_ERROR_STORAGE_BUSY` warnings in firefox

---

app/services/conversations/filter_service.rb
spec/services/conversations/filter_service_spec.rb

Fixes: https://linear.app/chatwoot/issue/CW-2083/nomethoderror-undefined-method-custom-attribute-definitions-for

fix: empty account variable for custom_attrbute_definition running in background job

---

app/controllers/api/v1/accounts/inboxes_controller.rb
app/javascript/dashboard/components/SettingsSection.vue
app/javascript/dashboard/components/ui/PreviewCard.vue
app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
app/javascript/dashboard/mixins/uiSettings.js
app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
app/javascript/dashboard/routes/dashboard/settings/inbox/components/SenderNameExamplePreview.vue
app/views/api/v1/models/_inbox.json.jbuilder

Fixes https://linear.app/chatwoot/issue/CW-2098/frontend-getter-for-friendly-and-business-name
**Screenshot**

feat: Frontend to customize the email sender name

---

app/javascript/dashboard/i18n/locale/en/generalSettings.json

This PR included a fix for dismiss button text missing in the i18n file for the update banner. Issue occurred from this [PR](https://github.com/chatwoot/chatwoot/pull/7296/files#diff-1b188675b65350cc8e8e40c86be834a1471d3d8ad6dcaf800eafe51c117de215R34) 
**Before**
**After**

fix: Issue with i18n in update banner

---

app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue

Fix [!7197](https://github.com/chatwoot/chatwoot/issues/7197) [CW-1900]
From
To

fix: Remove overflow string in label delete confirm button

---

app/jobs/inboxes/fetch_imap_emails_job.rb

Fixes: https://linear.app/chatwoot/issue/CW-1781/netimapbadresponseerror-user-is-authenticated-but-not-connected

fix: log User is authenticated but not connected

---

Gemfile.lock
app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
app/javascript/dashboard/routes/dashboard/settings/inbox/components/SenderNameExamplePreview.vue

This PR adds the ability to update the business name.
Fixes https://linear.app/chatwoot/issue/CW-2124/add-business-name-field-for-professional-sender-name

feat: Adds business name field for sender name

---

app/javascript/dashboard/helper/snoozeHelpers.js
app/javascript/dashboard/helper/specs/snoozeHelpers.spec.js

We are using the `setHoursToNine` method to set the time to 9:00 for the provided date. The method `setHoursToNine` uses the `setHours` function from the `date-fns` library.
However, the `setHours` function from `date-fns` only sets the hours of the given date object, and does not provide a way to directly set the minutes and seconds.
To set the minutes and seconds using `date-fns`, we need to use `setMinutes` and `setSeconds` in combination with `setHours`. This PR will address this issue.

fix: Set date hours to 9 in snooze time

---

app/javascript/dashboard/components/buttons/ResolveAction.vue

**Why**
Snooze is frequently used than pending from the menu. Changing the order would make the snooze button more easy to find 

chore: Change order of resolve action dropdown buttons

---

app/javascript/widget/helpers/IframeEventHelper.js
app/javascript/widget/helpers/actionCable.js
app/listeners/action_cable_listener.rb
app/models/message.rb
spec/lib/integrations/dyte/processor_service_spec.rb
spec/models/message_spec.rb

Fixes https://linear.app/chatwoot/issue/CW-2202/the-onmessage-events-are-not-triggered-properly-in-widget
- Trigger onMessage event if the message is updated with responses (input_select or form saves the message response in the same message)
- Include conversation id and source_id in the push event data

chore: Update onMessage event to include conversation id

---

app/javascript/dashboard/components/widgets/WootWriter/Editor.vue

Adds a space after inserting the mention node, so user could continue composing the note. 

fix: Adds a space after mention to improve UX

---

app/javascript/v3/components/Form/Input.vue

Before | After
-- | -- 
Ref: https://github.com/tailwindlabs/tailwindcss.com/issues/1135

fix: Add appearance-none to input field for ring to work

---

enterprise/app/jobs/enterprise/sentiment_analysis_job.rb

Fix https://linear.app/chatwoot/issue/CW-2214/nomethoderror-undefined-method-predict-for-nilnilclass-nomethoderror

fix: Disable predictions if model is absent

---

app/javascript/dashboard/store/modules/conversations/getters.js

Fix https://linear.app/chatwoot/issue/CW-2216/typeerror-cannot-read-properties-of-undefined-reading-filter

fix: Cannot read properties of undefined (reading 'filter')

---

app/javascript/dashboard/api/CacheEnabledApiClient.js

This PR resolves the issue where the cache enabled API would fail to fetch when IDB was not available

fix: idb is not available in firefox private mode [CW-2217]

---

app/controllers/api/v1/accounts/channels/twilio_channels_controller.rb
app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Twilio.vue
app/models/channel/twilio_sms.rb
db/migrate/20230714054138_add_api_key_sid_to_twilio_sms.rb
db/schema.rb

We use Account SID and Account Auth token for Twilio SMS authentication. One user had their Account Auth token leaked (conversation [here](https://app.chatwoot.com/app/accounts/1/conversations/26054)), which prompted them to switch to API Key authentication. API Key authentication is a better option as it reduces the privileges of the key and enables revocation whenever needed.
The changes are straightforward.
- Added a migration to include api_key_sid 
- Use auth_token for storing both api_key_secret and account_auth_token
- Update the UI to include the API Key SID changes.
I've tested this locally. It seems to be working without issues.

feat: Add support for API key authentication in Twilio

---

app/javascript/dashboard/components/widgets/conversation/conversation/LabelSuggestion.vue

1. Highlight the dismiss button when the area is hovered
2. Highlight the add labels button when one of the labels are selected
https://github.com/chatwoot/chatwoot/assets/18097732/4b4c89c9-173d-4628-a082-6af03b8399ae

feat: update the UX around label suggestions

---

app/listeners/reporting_event_listener.rb
app/models/message.rb
lib/events/types.rb
spec/listeners/reporting_event_listener_spec.rb

Calculate the average response time of replies. 
**Conditions:** 
- Added a `reply_time` event.
- Added a reporting event listener to compute time based on the REPLY_CREATED event.

feat: Compute average response time of replies

---

lib/chatwoot_exception_tracker.rb

Right now, if sentry is configured exception won't be logged. This results in the log management tool missing every error captured with ChatwootExceptionTracker. This change logs the exception, even if Sentry is configured or not.
Fixes https://linear.app/chatwoot/issue/CW-2145/improve-logging-info-debug-trace

fix: modify exception tracker to log even if sentry configured

---

config/app.yml
package.json

Bump the Chatwoot version to `3.0.0`
ref: https://github.com/orgs/chatwoot/discussions/7570

chore: bump up version

---

app/controllers/public/api/v1/portals/base_controller.rb
app/javascript/portal/portalHelpers.js
app/views/layouts/portal.html.erb
app/views/public/api/v1/portals/_category-block.html.erb
app/views/public/api/v1/portals/_hero.html.erb
app/views/public/api/v1/portals/articles/_article_header.html.erb
app/views/public/api/v1/portals/articles/show.html.erb
app/views/public/api/v1/portals/categories/_category-hero.html.erb
app/views/public/api/v1/portals/categories/show.html.erb

Add support for a plain layout in the help center.
**Edits:** 
- Add a param `show_plain_layout`
- Add a helper to add this param on all help center URLs.
- Render content based on the param.
Fixes https://linear.app/chatwoot/issue/CW-2289/update-the-portal-design-to-support-plain-articles
| Plain | With Design |
| -- | -- |
| <img width="500" alt="Screenshot 2023-07-24 at 4 24 08 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/9289931c-1f51-40b1-8601-cd20f46a7f82"> | <img width="495" alt="Screenshot 2023-07-24 at 4 24 00 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/f8e2b57f-adab-49f7-85a6-3a8d85994502"> |

feat: Add support for plain design help center layout

---

app/controllers/public/api/v1/portals/articles_controller.rb
app/models/article.rb
app/views/public/api/v1/models/hc/_associated_article.json.jbuilder
app/views/public/api/v1/portals/index.json.jbuilder
app/views/public/api/v1/portals/show.json.jbuilder
spec/controllers/public/api/v1/portals/articles_controller_spec.rb

Fix https://linear.app/chatwoot/issue/CW-2283/api-to-list-top-articles-from-the-connected-help-center
Additions: 
- Added param for sort. Default sort = sort_by_position
- Added page param.
- Fix issues with the partials rendering

feat: Sort articles based on views

---

app/controllers/api/v1/accounts/contacts_controller.rb
app/models/contact.rb

Fixes the contacts page sort by `created_at`.
fixes: https://github.com/chatwoot/chatwoot/issues/7577
By sorting.

fix: Contacts page sort by created_at [CW-2262]

---

app/services/facebook/send_on_facebook_service.rb
app/services/instagram/send_on_instagram_service.rb
app/services/message_templates/hook_execution_service.rb
spec/services/message_templates/hook_execution_service_spec.rb

> Customer  is facing some issues with the welcome and out of office messages
> 
> Based on the investigation,  we believe the problem is the flow of how messages are created when using the API 
> 
> - The way Chatwoot creates conversations using the widget API is along with a first message. 
> 
> - But in this case of creating a conversation using the Application API, mostly the conversation and messages are created in subsequent requests, which messes up the logic for welcome messages / other automated messages. 
> 
>    ie 
> 
>     - The conversation is created, and this triggers automation which creates the assignment message. 
> 
>     - which in turn triggers the welcome message and subsequent automated messages
> 
> We will add a fix for the same where we will skip triggering …

chore: Disable message hooks for conversations without incoming message

---

app/controllers/public/api/v1/inboxes/conversations_controller.rb
app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
config/routes.rb
spec/controllers/public/api/v1/inbox/conversations_controller_spec.rb

- Add toggle_typing endpoint for client APIs : 
```
curl --location 'http://localhost:3000/public/api/v1/inboxes/7mXPYawhiZPG2ooE5ZkC4vaJ/contacts/9b9d46b9-8542-43f5-8077-082d54682581/conversations/21/toggle_typing' \
--header 'Content-Type: application/json' \
--data '{ "typing_status": "on" }'
```
- Add update_contact_last_seen endpoint for client APIs: 
```
curl --location 'http://localhost:3000/public/api/v1/inboxes/7mXPYawhiZPG2ooE5ZkC4vaJ/contacts/9b9d46b9-8542-43f5-8077-082d54682581/conversations/21/update_last_seen' \
--header 'Content-Type: application/json' 
```
Fixes: https://github.com/chatwoot/chatwoot/issues/7581

feat: toggle typing and update last seen endpoints for client apis

---

app/javascript/dashboard/modules/search/components/MessageContent.vue
app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue

Fixes the following issues
[[Sentry Link](https://chatwoot-p3.sentry.io/issues/4285192034/)]
Couldn't find the root cause of this, but seems like the component handles empty data as well, so added null checks in the `Array.find`. The cause of this mostly the contact list not having the inbox property set. The fix should be good enough for now
[[Sentry Link](https://chatwoot-p3.sentry.io/issues/4283480477/)]
The problem here is in the vue rendering lifecycle, it's a bit tricky to solve this, since `$refs` are not reactive in nature. But then, this can work. [stackoverflow](https://stackoverflow.com/questions/39035498/vuejs-watch-refs)
```js
this.$watch(() => {
return this.$refs.messageContainer;
}, this.setOverflow);
```

fix: sentry issues [CW-2222][CW-2232]

---

app/models/contact.rb
db/migrate/20230727065605_add_partial_index_contact_account_id.rb
db/schema.rb

This PR adds a [partial index](https://www.postgresql.org/docs/current/indexes-partial.html) to the `contacts` very similar to the one added here: https://github.com/chatwoot/chatwoot/pull/7175
The main difference is the fields on which this index operates, in this case we only index the account_id field, this drastically helps in building the contact list query when loading the contact page
```sql
EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON)
SELECT
contacts.*,
(
SELECT
COUNT(*)
FROM
"conversations"
WHERE
"conversations"."contact_id" = "contacts"."id"
) as conversations_count
FROM
"contacts"
WHERE
"contacts"."account_id" = 1
AND (
contacts.email <> ''
OR contacts.phone_number <> ''
OR contacts.identifier <> ''
)
GROUP BY
"contacts"."id"
ORDER BY
"contacts"."last_activity_at" …
```

feat(perf): contact page loading speed

---

app/dashboards/account_dashboard.rb

This fixes an issue where `permitted_attributes` throws an error of `ArgumentError (wrong number of arguments (given 1, expected 0)):`
This is because we now bring in the latest version of `administrate` and `administrate` changes the way `permitted_attributes` works, it now passes a action parameter to `permitted_attributes`. Which means we need to update `permitted_attributes` to accept that new parameter.
I talk about this more in the issue.
Fixes #7592 
By updating the account through super admin portal.

fix: Update `permitted_attributes` to support the latest version of administrate 

---

app/models/integrations/hook.rb
db/migrate/20230801180936_update_default_status_in_hooks.rb
db/schema.rb

In the recent Slack integration update, we made changes to how hooks are handled. Now, hooks require an additional check to be enabled. By default, new hooks are created in a disabled state, which might lead to issues with the hooks not being executed as expected. 
This migration updates the status attribute of hooks to have 'enabled' as the default value, ensuring that new hooks are enabled by default and can function properly.

fix: Update the default status of the hooks to enabled

---

app/javascript/dashboard/routes/dashboard/commands/conversationHotKeys.js

This pull request resolves the issue of being unable to access conversation actions via the command bar in certain conversation URLs.

fix: Enable cmd bar actions for all conversation routes

---

app/javascript/dashboard/components/widgets/conversation/Message.vue

This PR fixes issues with links that are not readable in private notes dark mode
Fixes https://linear.app/chatwoot/issue/CW-2347/links-are-not-readable-in-private-notes-dark-mode
**Screenshot**
| Before   | After   |
|------------|------------|
| <img width="763" alt="image" src="https://github.com/chatwoot/chatwoot/assets/64252451/b621981b-1642-4d19-af27-9a72359b8b7e">  | <img width="763" alt="image" src="https://github.com/chatwoot/chatwoot/assets/64252451/cf9162fe-23f0-4c7b-beb0-227c8f854f12">  |

fix: Links are not readable in private notes dark mode

---

app/javascript/dashboard/components/layout/config/sidebarItems/settings.js

- Remove the **beta** label from automation, bots and macros
Fixes https://linear.app/chatwoot/issue/CW-2334/remove-beta-label-from-everything

refactor: remove beta label from automation, bots and macros

---

app/models/conversation.rb
spec/models/conversation_spec.rb

Fixes https://linear.app/chatwoot/issue/CW-2360/new-conversations-are-created-with-unread-count-=-0
This PR https://github.com/chatwoot/chatwoot/pull/7267 introduced a bug. When a conversation is created, the agent_last_seen_at would not be available. Querying created_at > nil returned empty results. A case where agent_last_seen_at being empty should have been added. The spec was also missing to validate this case.
This PR would check for the existence of agent_last_seen_at attribute. If present, it would return all the message since the time, otherwise it would return all the messages.

fix: Update unread_count being 0 if agent has not seen the conversation

---

app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
app/javascript/dashboard/modules/search/components/MessageContent.vue
app/javascript/dashboard/modules/search/components/ReadMore.vue
app/javascript/dashboard/routes/dashboard/conversation/contact/SocialIcons.vue

This PR includes following fixes,
1. Blockquote text is not visible in private notes.
2. Social profile icon is not visible in dark mode and added hover.
3. Search shrink container color issue.
Fixes 
https://linear.app/chatwoot/issue/CW-2354/dark-mode-fixes , 
https://linear.app/chatwoot/issue/CW-2359/breakage-in-search-page
**Light mode**
| Blockquote   | Social profile icon  |  Search shrink container |
|------------|------------|------------|
| <img width="220" alt="Screenshot 2023-08-08 at 1 29 58 PM" src="https://github.com/chatwoot/chatwoot/assets/64252451/fa064bb5-4c8b-4e19-a6da-332bb45c0bac">  | <img width="220" alt="Screenshot 2023-08-08 at 1 22 54 PM" src="https://github.com/chatwoot/chatwoot/assets/64252451/e1da8a84-38ea-4a05-931e-87e88f62d217">  |  <img width="752" …

fix: Dark mode color fixes

---

app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue

This pull request addresses an issue where the default timezone was not working properly in the business hour section upon initial save.
Fixes https://linear.app/chatwoot/issue/CW-2357/default-timezone-in-the-business-hour-section-is-not-working
**Screencast**
https://www.loom.com/share/29d4be82033c4379bd750f28a9c99225?sid=055131d6-57fd-4787-b478-0659b196a656

fix: Default timezone is not working

---

lib/integrations/slack/channel_builder.rb

Fixes https://linear.app/chatwoot/issue/CW-2381/typeerror-no-implicit-conversion-of-nil-into-array-typeerror

fix: Rename channel_list to channels to avoid "no implicit conversion of nil" exception
